"""Handler registration for the workflows.* read wrappers."""

from __future__ import annotations

from yoke_core.domain.handlers import workflows_definition as _wd
from yoke_core.domain.handlers import workflows_version_list as _wvl
from yoke_core.domain.handlers import workflows_versioning as _wv
from yoke_core.domain.handlers import (
    workflows_canon_follow as _wcf,
    workflows_canon_update as _wcu,
)
from yoke_core.domain.handlers import workflows_item_posture as _wip


def register(registry) -> None:
    registry.register(
        "workflows.definition.get",
        _wd.handle_workflows_definition_get,
        _wd.WorkflowsDefinitionGetRequest,
        _wd.WorkflowsDefinitionGetResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_definition",
        target_kinds=["global"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=[],
        adapter_status="live",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.item.get",
        _wv.handle_workflows_item_get,
        _wv.WorkflowItemGetRequest,
        _wv.WorkflowItemPinResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["item"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_read"],
        adapter_status="live",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.version.get",
        _wv.handle_workflows_version_get,
        _wv.WorkflowVersionGetRequest,
        _wv.WorkflowVersionGetResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["global"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_read"],
        adapter_status="live",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.version.list",
        _wvl.handle_workflows_version_list,
        _wvl.WorkflowVersionListRequest,
        _wvl.WorkflowVersionListResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_version_list",
        target_kinds=["global"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_read"],
        adapter_status="live",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.canon.get",
        _wv.handle_workflows_canon_get,
        _wv.WorkflowCanonGetRequest,
        _wv.WorkflowCanonGetResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["global"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_read"],
        adapter_status="internal",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.canon_update.preview",
        _wcu.handle_workflows_canon_update_preview,
        _wcu.WorkflowCanonUpdatePreviewRequest,
        _wcu.WorkflowCanonUpdatePreviewResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_canon_update",
        target_kinds=["global"],
        side_effects=[],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_read"],
        adapter_status="internal",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.canon_update.apply",
        _wcu.handle_workflows_canon_update_apply,
        _wcu.WorkflowCanonUpdateApplyRequest,
        _wcu.WorkflowCanonUpdateApplyResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_canon_update",
        target_kinds=["global"],
        side_effects=["workflow_version_published"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_append"],
        adapter_status="internal",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.canon_update.apply_all",
        _wcu.handle_workflows_canon_update_apply_all,
        _wcu.WorkflowCanonUpdateApplyAllRequest,
        _wcu.WorkflowCanonUpdateApplyAllResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_canon_update",
        target_kinds=["global"],
        side_effects=["workflow_version_published"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=["immutable_version_append"],
        adapter_status="internal",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.canon_follow.set",
        _wcf.handle_workflows_canon_follow_set,
        _wcf.WorkflowCanonFollowSetRequest,
        _wcf.WorkflowCanonFollowSetResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_canon_follow",
        target_kinds=["global"],
        side_effects=["workflows_canon_follow_update"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=[],
        adapter_status="internal",
        claim_required_kind=None,
    )
    registry.register(
        "workflows.current.set",
        _wv.handle_workflows_current_set,
        _wv.WorkflowCurrentSetRequest,
        _wv.WorkflowCurrentSetResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["global"],
        side_effects=["workflows_current_version_update"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=[
            "published_version_only",
            "new_items_only",
            "expected_current_version",
        ],
        adapter_status="live",
        claim_required_kind=None,
        ambient_session_required=False,
    )
    registry.register(
        "workflows.policy_defaults.publish",
        _wv.handle_workflows_policy_defaults_publish,
        _wv.WorkflowPolicyDefaultsPublishRequest,
        _wv.WorkflowPolicyDefaultsPublishResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["global"],
        side_effects=["workflows_version_publish"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=[
            "bounded_policy_defaults_only",
            "immutable_version_publish",
            "expected_current_version",
            "new_items_only",
        ],
        adapter_status="live",
        claim_required_kind=None,
        ambient_session_required=False,
    )
    registry.register(
        "workflows.item.migrate",
        _wv.handle_workflows_item_migrate,
        _wv.WorkflowItemMigrateRequest,
        _wv.WorkflowItemMigrateResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_versioning",
        target_kinds=["item"],
        side_effects=["items_workflow_version_update"],
        emitted_event_names=["YokeFunctionCalled"],
        guardrails=[
            "same_workflow_only",
            "stage_mapping_required",
            "posture_compatibility",
            "lane_policy_compatibility",
            "live_binding_compatibility",
        ],
        adapter_status="live",
        claim_required_kind="operator_override",
    )
    registry.register(
        "workflows.item_posture.amend",
        _wip.handle_item_posture_amend,
        _wip.ItemPostureAmendRequest,
        _wip.ItemPostureAmendResponse,
        stability="stable",
        owner_module="yoke_core.domain.handlers.workflows_item_posture",
        target_kinds=["item"],
        side_effects=[
            "items_workflow_posture_update",
            "qa_requirements_waive",
            "qa_plan_item_attachments_delete",
            "qa_plan_item_attachments_insert",
        ],
        emitted_event_names=[
            "YokeFunctionCalled",
            "ItemWorkflowPostureAmended",
        ],
        guardrails=[
            "definition_posture_allowlist",
            "declared_amendment_guard",
            "non_terminal_stage_only",
            "recorded_evidence_preserved",
        ],
        adapter_status="live",
        claim_required_kind="item",
    )


__all__ = ["register"]
