"""Governed purge tests for retired project GitHub credentials."""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from runtime.api.domain.migrations import (
    retired_github_capability_secrets as migration,
)
from runtime.api.fixtures import pg_testdb
from yoke_core.domain import bootstrap_project_helpers
from yoke_core.domain import json_helper
from yoke_core.domain import project_model
from yoke_core.domain import validate_webapp_pipeline_helpers
from yoke_core.domain.db_compatibility_attestation import (
    validate as validate_attestation,
)
from yoke_core.domain.db_mutation_profile import validate as validate_profile


_SCHEMA = """
CREATE TABLE capability_secrets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    type TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'literal',
    UNIQUE(project_id, type, key)
)
"""


def test_ticketless_manifest_is_valid() -> None:
    payload = json_helper.load_path(
        Path(__file__).with_name(
            "retired_github_capability_secrets.migration.json"
        )
    )

    validate_profile(payload["profile"])
    validate_attestation(payload["attestation"])


@pytest.mark.parametrize(
    "reader",
    (
        bootstrap_project_helpers._capability_secret,
        validate_webapp_pipeline_helpers._capability_secret,
    ),
)
def test_private_capability_readers_refuse_retired_github_secrets(reader) -> None:
    with pytest.raises(ValueError, match="retired and cannot be read"):
        reader(object(), "yoke", " GitHub ", "token")


def test_project_model_hides_retired_github_secret_metadata(conn: Any) -> None:
    assert project_model._secrets_metadata(conn, 1) == [
        {"type": "docker", "key": "registry", "source": "literal"},
        {
            "type": "github-actions-runner-fleet",
            "key": "hook",
            "source": "literal",
        },
    ]


@pytest.fixture
def conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    connection = pg_testdb.connect_test_database(name)
    try:
        connection.execute(_SCHEMA)
        connection.execute(
            "INSERT INTO capability_secrets "
            "(project_id, type, key, value, source) VALUES "
            "(1, 'github', 'token', 'retired-one', 'literal'), "
            "(2, ' GitHub ', 'token', 'retired-two', 'literal'), "
            "(3, 'GITHUB', 'token', 'retired-three', 'literal'), "
            "(1, 'docker', 'registry', 'keep-docker', 'literal'), "
            "(1, 'github-actions-runner-fleet', 'hook', 'keep-hook', 'literal')"
        )
        connection.commit()
        yield connection
    finally:
        connection.close()
        pg_testdb.drop_test_database(name)


def test_apply_removes_only_normalized_github_rows(conn: Any) -> None:
    unrelated_before = [
        dict(row) for row in conn.execute(
            "SELECT project_id, type, key, value, source "
            "FROM capability_secrets "
            "WHERE LOWER(TRIM(type)) <> 'github' ORDER BY id"
        ).fetchall()
    ]

    migration.apply(conn)
    conn.commit()
    migration.invariants(conn)

    assert conn.execute(
        "SELECT COUNT(*) FROM capability_secrets "
        "WHERE LOWER(TRIM(type)) = 'github'"
    ).fetchone()[0] == 0
    unrelated_after = [
        dict(row) for row in conn.execute(
            "SELECT project_id, type, key, value, source "
            "FROM capability_secrets ORDER BY id"
        ).fetchall()
    ]
    assert unrelated_after == unrelated_before


def test_apply_is_idempotent(conn: Any) -> None:
    migration.apply(conn)
    migration.apply(conn)
    conn.commit()

    migration.invariants(conn)


def test_invariants_detect_retired_rows(conn: Any) -> None:
    with pytest.raises(AssertionError, match="3 retired"):
        migration.invariants(conn)


def test_apply_requires_capability_secrets_table() -> None:
    name = pg_testdb.create_test_database()
    connection = pg_testdb.connect_test_database(name)
    try:
        with pytest.raises(AssertionError, match="table is required"):
            migration.apply(connection)
    finally:
        connection.close()
        pg_testdb.drop_test_database(name)
