"""Governed migration tests for canonical item design documents."""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from runtime.api.domain.migrations import design_documents_to_item_field as migration
from runtime.api.fixtures import pg_testdb
from yoke_core.domain.environment_bootstrap import run_init_chain_at_dsn
from yoke_core.domain.portable_migration import (
    apply_manifest,
    load_packaged_modules,
    parse_manifest_text,
)
from yoke_core.domain.schema_common import _table_exists


ROOT = Path(__file__).resolve().parents[4]
MANIFEST = (
    ROOT
    / "runtime/api/domain/migrations/design_documents_to_item_field.migration.json"
)


@pytest.fixture
def legacy_conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    dsn = pg_testdb.dsn_for_test_database(name)
    run_init_chain_at_dsn(dsn, emit=lambda _line: None)
    conn = pg_testdb.connect_test_database(name)
    try:
        conn.execute(
            "CREATE TABLE designs ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "item_id BIGINT NOT NULL UNIQUE, slug TEXT NOT NULL, body TEXT NOT NULL, "
            "created_at TEXT NOT NULL, updated_at TEXT NOT NULL)"
        )
        conn.execute("CREATE INDEX idx_designs_item ON designs(item_id)")
        conn.execute("CREATE INDEX idx_designs_slug ON designs(slug)")
        conn.execute(
            "INSERT INTO projects (id, slug, name, public_item_prefix, created_at) "
            "VALUES (901, 'migration-test', 'Migration Test', 'MIG', now())"
        )
        conn.execute(
            "INSERT INTO items "
            "(id, title, type, status, priority, created_at, updated_at, "
            "project_id, project_sequence) VALUES "
            "(902, 'First', 'issue', 'planned', 'medium', now(), now(), 901, 1), "
            "(903, 'Second', 'issue', 'planned', 'medium', now(), now(), 901, 2)"
        )
        conn.execute(
            "INSERT INTO designs (item_id, slug, body, created_at, updated_at) "
            "VALUES (902, 'first', 'first design', now(), now()), "
            "(903, 'second', 'second design', now(), now())"
        )
        conn.commit()
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_apply_preserves_documents_in_item_field_and_drops_table(
    legacy_conn: Any,
) -> None:
    migration.apply(legacy_conn)
    legacy_conn.commit()
    migration.invariants(legacy_conn)

    assert legacy_conn.execute(
        "SELECT id, design_spec FROM items WHERE id IN (902, 903) ORDER BY id"
    ).fetchall() == [(902, "first design"), (903, "second design")]
    assert not _table_exists(legacy_conn, migration.SOURCE_TABLE)
    assert legacy_conn.execute(
        "SELECT to_regclass('public.designs_id_seq')"
    ).fetchone() == (None,)


def test_apply_accepts_identical_existing_content(legacy_conn: Any) -> None:
    legacy_conn.execute(
        "UPDATE items SET design_spec = 'first design' WHERE id = 902"
    )

    migration.apply(legacy_conn)
    legacy_conn.commit()

    migration.invariants(legacy_conn)


def test_apply_refuses_different_existing_content(legacy_conn: Any) -> None:
    legacy_conn.execute(
        "UPDATE items SET design_spec = 'newer design' WHERE id = 902"
    )

    with pytest.raises(AssertionError, match="already have different"):
        migration.apply(legacy_conn)
    legacy_conn.rollback()

    assert _table_exists(legacy_conn, migration.SOURCE_TABLE)
    assert legacy_conn.execute(
        "SELECT design_spec FROM items WHERE id = 902"
    ).fetchone() == (None,)


def test_apply_refuses_orphaned_document(legacy_conn: Any) -> None:
    legacy_conn.execute(
        "INSERT INTO designs (item_id, slug, body, created_at, updated_at) "
        "VALUES (9999, 'orphaned', 'orphaned design', now(), now())"
    )

    with pytest.raises(AssertionError, match="without a matching item"):
        migration.apply(legacy_conn)
    legacy_conn.rollback()

    assert _table_exists(legacy_conn, migration.SOURCE_TABLE)


def test_apply_is_idempotent(legacy_conn: Any) -> None:
    migration.apply(legacy_conn)
    migration.apply(legacy_conn)
    legacy_conn.commit()

    migration.invariants(legacy_conn)


def test_public_manifest_loads_exact_module_and_applies(legacy_conn: Any) -> None:
    manifest = parse_manifest_text(MANIFEST.read_text(encoding="utf-8"))

    assert manifest.module_identifiers == ("design_documents_to_item_field",)
    assert manifest.affected_tables == ("designs", "items")
    assert load_packaged_modules(manifest)[0].__name__ == (
        "yoke_core.domain.migrations.design_documents_to_item_field"
    )

    result = apply_manifest(legacy_conn, manifest)

    assert result.modules == ("design_documents_to_item_field",)
    assert result.pre_row_counts == {"designs": 2, "items": 2}
    assert result.post_row_counts == {"designs": -1, "items": 2}
    migration.invariants(legacy_conn)
