"""Governed migration tests for actor-only event identity."""

from __future__ import annotations

from collections.abc import Iterator
import json
from typing import Any

import pytest

from runtime.api.domain.migrations import events_actor_identity as migration
from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_core.domain.schema_common import _column_exists, _get_indexes


_OLD_EVENTS_SCHEMA = f"""
    CREATE TABLE {migration.EVENTS_TABLE} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id TEXT UNIQUE NOT NULL,
        {migration.RETIRED_COLUMN} TEXT,
        actor_id INTEGER,
        envelope TEXT,
        created_at TEXT NOT NULL
    );
    CREATE INDEX {migration.RETIRED_INDEX}
        ON {migration.EVENTS_TABLE}({migration.RETIRED_COLUMN});
"""


@pytest.fixture
def old_events_conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        apply_sql_script(conn, _OLD_EVENTS_SCHEMA)
        conn.execute(
            f"INSERT INTO {migration.EVENTS_TABLE} "
            f"(event_id, {migration.RETIRED_COLUMN}, actor_id, envelope, created_at) VALUES "
            "(%s, %s, %s, %s, %s), (%s, %s, %s, %s, %s)",
            (
                "event-null",
                None,
                7,
                '{"user_id":null,"event_name":"NullIdentity"}',
                "2026-07-11T12:00:00Z",
                "event-empty",
                "",
                8,
                '{"user_id":null,"event_name":"EmptyIdentity"}',
                "2026-07-11T12:00:01Z",
            ),
        )
        conn.commit()
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_apply_preserves_rows_and_historical_null_envelopes(
    old_events_conn: Any,
) -> None:
    before = old_events_conn.execute(
        f"SELECT COUNT(*) FROM {migration.EVENTS_TABLE}"
    ).fetchone()[0]

    migration.apply(old_events_conn)
    old_events_conn.commit()
    migration.invariants(old_events_conn)

    after = old_events_conn.execute(
        f"SELECT COUNT(*) FROM {migration.EVENTS_TABLE}"
    ).fetchone()[0]
    envelopes = old_events_conn.execute(
        f"SELECT envelope FROM {migration.EVENTS_TABLE} ORDER BY event_id"
    ).fetchall()
    assert after == before == 2
    assert all('"user_id":null' in row[0] for row in envelopes)
    assert not _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )
    assert migration.RETIRED_INDEX not in set(
        _get_indexes(old_events_conn, migration.EVENTS_TABLE)
    )


def test_apply_preserves_envelopes_with_escaped_nul_payloads(
    old_events_conn: Any,
) -> None:
    envelope = json.dumps(
        {
            "user_id": None,
            "event_name": "BinaryToolOutput",
            "context": {"output": "prefix" + chr(0) + "suffix"},
        },
        separators=(",", ":"),
    )
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        (envelope, "event-null"),
    )

    migration.apply(old_events_conn)
    old_events_conn.commit()
    migration.invariants(old_events_conn)

    preserved = old_events_conn.execute(
        f"SELECT envelope FROM {migration.EVENTS_TABLE} WHERE event_id = %s",
        ("event-null",),
    ).fetchone()[0]
    assert preserved == envelope


def test_apply_still_refuses_envelope_identity_alongside_escaped_nul(
    old_events_conn: Any,
) -> None:
    envelope = json.dumps(
        {
            "user_id": "platform-user-1",
            "context": {"output": "prefix" + chr(0) + "suffix"},
        },
        separators=(",", ":"),
    )
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        (envelope, "event-null"),
    )

    with pytest.raises(AssertionError, match="envelope has 1 non-null"):
        migration.apply(old_events_conn)

    assert _column_exists(old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN)


def test_apply_refuses_escaped_top_level_identity_key_with_escaped_nul(
    old_events_conn: Any,
) -> None:
    envelope = json.dumps(
        {
            "user_id": "platform-user-1",
            "context": {"output": "prefix" + chr(0) + "suffix"},
        },
        separators=(",", ":"),
    ).replace('"user_id"', '"' + chr(92) + 'u0075ser_id"')
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        (envelope, "event-null"),
    )

    with pytest.raises(AssertionError, match="envelope has 1 non-null"):
        migration.apply(old_events_conn)

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )


def test_apply_refuses_malformed_envelope_with_escaped_nul(
    old_events_conn: Any,
) -> None:
    import psycopg

    envelope = json.dumps(
        {"context": {"output": "prefix" + chr(0) + "suffix"}},
        separators=(",", ":"),
    )
    malformed = envelope[:-1] + ",}"
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        (malformed, "event-null"),
    )

    with pytest.raises(psycopg.errors.InvalidTextRepresentation):
        migration.apply(old_events_conn)
    old_events_conn.rollback()

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )


def test_apply_is_idempotent(old_events_conn: Any) -> None:
    migration.apply(old_events_conn)
    migration.apply(old_events_conn)
    old_events_conn.commit()

    migration.invariants(old_events_conn)


def test_idempotent_apply_still_rejects_envelope_identity(
    old_events_conn: Any,
) -> None:
    migration.apply(old_events_conn)
    old_events_conn.commit()
    migration.invariants(old_events_conn)
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        ('{"user_id":"platform-user-1"}', "event-null"),
    )
    old_events_conn.commit()

    with pytest.raises(AssertionError, match="envelope has 1 non-null"):
        migration.apply(old_events_conn)


def test_idempotent_apply_refuses_malformed_envelope(old_events_conn: Any) -> None:
    import psycopg

    migration.apply(old_events_conn)
    old_events_conn.commit()
    migration.invariants(old_events_conn)
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        ("not-json", "event-null"),
    )
    old_events_conn.commit()

    with pytest.raises(psycopg.errors.InvalidTextRepresentation):
        migration.apply(old_events_conn)
    old_events_conn.rollback()


def test_apply_refuses_nonempty_user_identity(old_events_conn: Any) -> None:
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} "
        f"SET {migration.RETIRED_COLUMN} = %s WHERE event_id = %s",
        ("platform-user-1", "event-null"),
    )

    with pytest.raises(AssertionError, match="has 1 non-empty values"):
        migration.apply(old_events_conn)

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )
    assert migration.RETIRED_INDEX in set(
        _get_indexes(old_events_conn, migration.EVENTS_TABLE)
    )


def test_apply_refuses_nonnull_envelope_user_identity(old_events_conn: Any) -> None:
    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        ('{"user_id":"platform-user-1"}', "event-null"),
    )

    with pytest.raises(AssertionError, match="envelope has 1 non-null"):
        migration.apply(old_events_conn)

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )


def test_apply_refuses_malformed_historical_envelope(old_events_conn: Any) -> None:
    import psycopg

    old_events_conn.execute(
        f"UPDATE {migration.EVENTS_TABLE} SET envelope = %s WHERE event_id = %s",
        ("not-json", "event-null"),
    )
    old_events_conn.commit()

    with pytest.raises(psycopg.errors.InvalidTextRepresentation):
        migration.apply(old_events_conn)
    old_events_conn.rollback()

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )


def test_apply_refuses_unrecognized_missing_index(old_events_conn: Any) -> None:
    old_events_conn.execute(f"DROP INDEX {migration.RETIRED_INDEX}")

    with pytest.raises(AssertionError, match="unrecognized pre-migration shape"):
        migration.apply(old_events_conn)

    assert _column_exists(
        old_events_conn, migration.EVENTS_TABLE, migration.RETIRED_COLUMN
    )


def test_apply_locks_append_writers_before_count(old_events_conn: Any) -> None:
    statements: list[str] = []

    class RecordingConnection:
        def __init__(self, inner: Any) -> None:
            self._inner = inner

        def execute(self, query: str, *args: Any, **kwargs: Any) -> Any:
            statements.append(" ".join(query.split()))
            return self._inner.execute(query, *args, **kwargs)

        def __getattr__(self, name: str) -> Any:
            return getattr(self._inner, name)

    recorded = RecordingConnection(old_events_conn)
    migration.apply(recorded)
    migration.invariants(recorded)

    lock_index = statements.index("LOCK TABLE events IN ACCESS EXCLUSIVE MODE")
    count_index = statements.index("SELECT COUNT(*) FROM events")
    assert lock_index < count_index


def test_apply_detects_row_loss_before_releasing_lock(old_events_conn: Any) -> None:
    class RowLossConnection:
        def __init__(self, inner: Any) -> None:
            self._inner = inner

        def execute(self, query: str, *args: Any, **kwargs: Any) -> Any:
            result = self._inner.execute(query, *args, **kwargs)
            if query == f"ALTER TABLE {migration.EVENTS_TABLE} DROP COLUMN {migration.RETIRED_COLUMN}":
                self._inner.execute(
                    f"DELETE FROM {migration.EVENTS_TABLE} WHERE event_id = %s",
                    ("event-null",),
                )
            return result

        def __getattr__(self, name: str) -> Any:
            return getattr(self._inner, name)

    with pytest.raises(AssertionError, match="row count changed from 2 to 1"):
        migration.apply(RowLossConnection(old_events_conn))
    old_events_conn.rollback()


def test_invariants_allow_post_commit_append(old_events_conn: Any) -> None:
    migration.apply(old_events_conn)
    old_events_conn.commit()
    old_events_conn.execute(
        f"INSERT INTO {migration.EVENTS_TABLE} "
        "(event_id, actor_id, envelope, created_at) VALUES (%s, %s, %s, %s)",
        (
            "event-after-cutover",
            9,
            '{"event_name":"AfterCutover"}',
            "2026-07-11T12:00:02Z",
        ),
    )
    old_events_conn.commit()

    migration.invariants(old_events_conn)
    count = old_events_conn.execute(
        f"SELECT COUNT(*) FROM {migration.EVENTS_TABLE}"
    ).fetchone()[0]
    assert count == 3
