"""Architecture read handlers and the snapshot-sync label refresh.

`project_structure.architecture_health.get` and
`project_structure.architecture_draft.get` serve the dashboard, board,
and CLI from the shared computers; `project.snapshot.sync` refreshes
map-derived classifications whenever a HEAD snapshot lands for a
project that declares a map.
"""

from __future__ import annotations

import json

from yoke_contracts.api.function_call import (
    ActorContext,
    FunctionCallRequest,
    TargetRef,
)
from yoke_core.domain._path_snapshots_test_helpers import path_snapshot_db
from yoke_core.domain.db_helpers import iso8601_now
from yoke_core.domain.handlers import project_snapshot_sync as sync_handler
from yoke_core.domain.handlers import project_structure as ps_handler


def _repo(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir(exist_ok=True)
    return repo


def _request(function: str, payload: dict) -> FunctionCallRequest:
    return FunctionCallRequest(
        function=function,
        actor=ActorContext(session_id="test-session"),
        target=TargetRef(kind="global", project_id="demo"),
        payload=payload,
    )


def _sync_head(files: list[dict]) -> None:
    outcome = sync_handler.handle_project_snapshot_sync(
        _request("project.snapshot.sync", {
            "project_id": "demo",
            "snapshots": [{
                "ref": "HEAD",
                "commit_sha": "a" * 40,
                "files": files,
            }],
        })
    )
    assert outcome.primary_success is True, outcome.error
    return outcome


def _ensure_project_structure_table(conn) -> None:
    conn.execute(
        "CREATE TABLE IF NOT EXISTS project_structure ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "project_id INTEGER NOT NULL, family TEXT NOT NULL, "
        "attachment_kind TEXT NOT NULL DEFAULT '', "
        "attachment_value TEXT NOT NULL DEFAULT '', "
        "entry_key TEXT NOT NULL DEFAULT '', payload TEXT, "
        "created_at TEXT NOT NULL, updated_at TEXT NOT NULL)"
    )


def _declare_model(conn) -> None:
    _ensure_project_structure_table(conn)
    payload = {
        "layers": [
            {"id": "storage", "may_depend_on": [], "forbidden_edges": []},
            {
                "id": "service",
                "may_depend_on": ["storage"],
                "forbidden_edges": [],
            },
        ],
        "domains": [
            {
                "id": "app",
                "path_roots": [{"glob": "src/**", "layer": "service"}],
            },
        ],
    }
    conn.execute(
        "INSERT INTO project_structure "
        "(project_id, family, attachment_kind, attachment_value, "
        "entry_key, payload, created_at, updated_at) "
        "VALUES (3, 'architecture_model', '', 'project', '', %s, %s, %s)",
        (json.dumps(payload), iso8601_now(), iso8601_now()),
    )
    conn.commit()


def test_health_reports_undeclared_map(tmp_path) -> None:
    with path_snapshot_db(tmp_path, _repo(tmp_path)):
        outcome = ps_handler.handle_architecture_health_get(
            _request("project_structure.architecture_health.get", {})
        )
        assert outcome.primary_success is True
        assert outcome.result_payload["health"] == {"declared": False}


def test_sync_skips_refresh_without_a_map(tmp_path) -> None:
    with path_snapshot_db(tmp_path, _repo(tmp_path)):
        outcome = _sync_head(
            [{"path": "src/app.py", "line_count": 3, "language": "python",
              "module_name": "src.app"}],
        )
        assert outcome.result_payload["architecture_refresh"] is None


def test_sync_refreshes_labels_and_health_reflects_them(tmp_path) -> None:
    with path_snapshot_db(tmp_path, _repo(tmp_path)) as conn:
        _declare_model(conn)
        outcome = _sync_head([
            {"path": "src/app.py", "line_count": 3, "language": "python",
             "module_name": "src.app"},
            {"path": "scripts/loose.py", "line_count": 3,
             "language": "python", "module_name": "scripts.loose"},
        ])
        refresh = outcome.result_payload["architecture_refresh"]
        assert refresh == {
            "layer_rows": 1,
            "domain_rows": 1,
            "exemption_rows": 0,
            "unclassified": 1,
            "removed_rows": 0,
            "operator_rows_kept": 0,
        }
        health_outcome = ps_handler.handle_architecture_health_get(
            _request("project_structure.architecture_health.get", {})
        )
        health = health_outcome.result_payload["health"]
        assert health["declared"] is True
        assert health["classified"] == 1
        assert health["unclassified"] == 1
        assert health["coverage_pct"] == 50.0


def test_draft_proposes_from_the_synced_tree(tmp_path) -> None:
    with path_snapshot_db(tmp_path, _repo(tmp_path)):
        _sync_head(
            [{"path": "src/app/api_routes.py", "line_count": 3,
              "language": "python", "module_name": "src.app.api_routes"}],
        )
        outcome = ps_handler.handle_architecture_draft_get(
            _request("project_structure.architecture_draft.get", {})
        )
        assert outcome.primary_success is True
        draft = outcome.result_payload
        assert draft["payload"]["domains"][0]["id"] == "app"
        assert any(
            root["layer"] == "interface"
            for root in draft["payload"]["domains"][0]["path_roots"]
        )
        assert draft["notes"]


def test_missing_project_rejects(tmp_path) -> None:
    with path_snapshot_db(tmp_path, _repo(tmp_path)):
        request = FunctionCallRequest(
            function="project_structure.architecture_health.get",
            actor=ActorContext(session_id="test-session"),
            target=TargetRef(kind="global"),
            payload={},
        )
        outcome = ps_handler.handle_architecture_health_get(request)
        assert outcome.primary_success is False
        assert outcome.error.code == "payload_invalid"
