"""Shared native database and request fixtures for focused command tests."""

from __future__ import annotations

from pydantic import BaseModel
from yoke_core.domain.auth_schema import create_auth_tables
from yoke_core.domain.actor_permissions import seed_roles_and_permissions
from yoke_core.domain.project_seed_test_helpers import seed_project_identities
from yoke_core.domain.schema_init_actor_path_claim_tables import (
    create_actor_path_claim_tables,
)
from yoke_core.domain.schema_init_path_tables import create_path_registry_tables
from yoke_core.domain.schema_init_tables import create_core_tables
from yoke_contracts.api.function_call import (
    ActorContext,
    FunctionCallRequest,
    TargetRef,
)
from yoke_core.domain.yoke_function_registry import RegistryEntry


class EmptyModel(BaseModel):
    pass


def _conn():
    from runtime.api.fixtures import pg_testdb

    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(pg_testdb.connect_test_database(name), name)
    create_core_tables(conn)
    seed_project_identities(conn)
    create_path_registry_tables(conn)
    create_actor_path_claim_tables(conn)
    create_auth_tables(conn)
    seed_roles_and_permissions(conn)
    return conn


def _create_ephemeral_env_table(conn) -> None:
    conn.execute(
        """
        CREATE TABLE ephemeral_environments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id INTEGER NOT NULL,
            branch TEXT,
            status TEXT,
            created_at TIMESTAMPTZ
        )
        """
    )


def _entry(function_id: str) -> RegistryEntry:
    return RegistryEntry(
        function_id=function_id,
        handler=lambda _request: None,
        request_model=EmptyModel,
        response_model=EmptyModel,
        stability="stable",
        owner_module=__name__,
        target_kinds=("item",),
        side_effects=("render_body",),
        emitted_event_names=(),
        guardrails=(),
        adapter_status="live",
    )


def _read_entry(function_id: str) -> RegistryEntry:
    entry = _entry(function_id)
    return RegistryEntry(
        function_id=entry.function_id,
        handler=entry.handler,
        request_model=entry.request_model,
        response_model=entry.response_model,
        stability=entry.stability,
        owner_module=entry.owner_module,
        target_kinds=entry.target_kinds,
        side_effects=(),
        emitted_event_names=entry.emitted_event_names,
        guardrails=entry.guardrails,
        adapter_status=entry.adapter_status,
    )


def _request(actor_id: int, project: str) -> FunctionCallRequest:
    return FunctionCallRequest(
        function="items.structured_field.replace",
        actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
        target=TargetRef(kind="item", project_id=project),
        payload={},
    )


def _process_acquire_request(
    actor_id: int, *, project: str | None
) -> FunctionCallRequest:
    """Build a ``claims.work.acquire --process`` request as the CLI adapter does.

    The adapter sends a ``kind='global'`` envelope target and nests the project
    inside ``payload['target']['project']`` (the shape the acquire handler
    consumes); it never sets a top-level ``project`` / ``project_id``.
    """
    target_spec: dict = {"kind": "process", "process_key": "STRATEGIZE"}
    if project is not None:
        target_spec["project"] = project
    return FunctionCallRequest(
        function="claims.work.acquire",
        actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
        target=TargetRef(kind="global"),
        payload={"target": target_spec},
    )


def _seed_session(conn, *, session_id: str, project_id: int) -> None:
    conn.execute(
        "INSERT INTO harness_sessions (session_id, executor, provider, model, workspace, project_id, offered_at, last_heartbeat) VALUES (%s, 'codex', 'openai', 'gpt', '/tmp/work', %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
        (session_id, project_id),
    )
