"""Shared fixtures for project capability tests."""

from __future__ import annotations

from pathlib import Path
from typing import Iterator

import pytest

from yoke_core.domain import db_backend
from runtime.api.fixtures.file_test_db import init_test_db


def _apply_capability_schema() -> None:
    """Create the ``project_capabilities`` + ``capability_secrets`` tables."""
    conn = db_backend.connect()
    try:
        conn.execute(
            """
            CREATE TABLE projects (
                id BIGINT PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                public_item_prefix TEXT NOT NULL DEFAULT 'YOK'
            )
            """
        )
        conn.execute(
            """
            INSERT INTO projects (id, slug, name, public_item_prefix)
            VALUES (1, 'yoke', 'Yoke', 'YOK'), (2, 'buzz', 'Buzz', 'BUZ')
            """
        )
        conn.execute(
            """
            CREATE TABLE project_capabilities (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id BIGINT NOT NULL REFERENCES projects(id),
                type TEXT NOT NULL,
                settings TEXT DEFAULT '{}',
                verified_at TEXT,
                created_at TEXT NOT NULL,
                UNIQUE(project_id, type)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE capability_secrets (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id BIGINT NOT NULL REFERENCES projects(id),
                type TEXT NOT NULL,
                key TEXT NOT NULL,
                value TEXT NOT NULL DEFAULT '',
                source TEXT NOT NULL DEFAULT 'literal'
                    CHECK(source = 'literal'),
                created_at TEXT NOT NULL,
                UNIQUE(project_id, type, key)
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture
def cap_db(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[str]:
    """Per-test Postgres DB with the capability + secret tables applied."""
    monkeypatch.setenv("YOKE_MACHINE_HOME", str(tmp_path / "machine-home"))
    with init_test_db(tmp_path, apply_schema=_apply_capability_schema) as db_path:
        yield db_path
