"""Focused tests for project-role function-call authorization."""

from __future__ import annotations

import pytest
from pydantic import BaseModel

from yoke_core.domain.actor_permissions import (
    PERM_CLAIMS_ACQUIRE,
    PERM_DB_READ_RAW,
    PERM_EVENTS_READ,
    PERM_EVENTS_WRITE,
    PERM_ITEMS_READ,
    PERM_ITEMS_WRITE,
    ROLE_OPERATOR,
    ROLE_OWNER,
    ROLE_VIEWER,
    PermissionDenied,
    grant_actor_project_role,
    require_permission,
)
from yoke_core.domain.actors import seed_human_actor
from yoke_core.domain.auth_schema import create_auth_tables
from yoke_core.domain.actor_permissions import seed_roles_and_permissions
from yoke_core.domain.project_identity import resolve_project_id
from yoke_core.domain.project_seed_test_helpers import seed_project_identities
from yoke_core.domain.schema_init_actor_path_claim_tables import (
    create_actor_path_claim_tables,
)
from yoke_core.domain.schema_init_path_tables import create_path_registry_tables
from yoke_core.domain.schema_init_tables import create_core_tables
from yoke_contracts.api.function_call import (
    ActorContext,
    FunctionCallRequest,
    TargetRef,
)
from yoke_core.domain.yoke_function_permissions import (
    check_dispatch_permission,
    permission_key_for,
)
from yoke_core.domain.yoke_function_registry import RegistryEntry


class EmptyModel(BaseModel):
    pass


def _conn():
    from runtime.api.fixtures import pg_testdb

    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name), name
    )
    create_core_tables(conn)
    seed_project_identities(conn)
    create_path_registry_tables(conn)
    create_actor_path_claim_tables(conn)
    create_auth_tables(conn)
    seed_roles_and_permissions(conn)
    return conn


def _create_ephemeral_env_table(conn) -> None:
    conn.execute(
        """
        CREATE TABLE ephemeral_environments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id INTEGER NOT NULL,
            branch TEXT,
            status TEXT,
            created_at TEXT
        )
        """,
    )


def _entry(function_id: str) -> RegistryEntry:
    return RegistryEntry(
        function_id=function_id,
        handler=lambda _request: None,
        request_model=EmptyModel,
        response_model=EmptyModel,
        stability="stable",
        owner_module=__name__,
        target_kinds=("item",),
        side_effects=("render_body",),
        emitted_event_names=(),
        guardrails=(),
        adapter_status="live",
    )


def _read_entry(function_id: str) -> RegistryEntry:
    entry = _entry(function_id)
    return RegistryEntry(
        function_id=entry.function_id,
        handler=entry.handler,
        request_model=entry.request_model,
        response_model=entry.response_model,
        stability=entry.stability,
        owner_module=entry.owner_module,
        target_kinds=entry.target_kinds,
        side_effects=(),
        emitted_event_names=entry.emitted_event_names,
        guardrails=entry.guardrails,
        adapter_status=entry.adapter_status,
    )


def _request(actor_id: int, project: str) -> FunctionCallRequest:
    return FunctionCallRequest(
        function="items.structured_field.replace",
        actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
        target=TargetRef(kind="item", project_id=project),
        payload={},
    )


def test_dispatch_permission_allows_role_project_and_denies_missing_project_role():
    conn = _conn()
    try:
        actor_id = seed_human_actor(conn)
        yoke_id = resolve_project_id(conn, "yoke")
        grant_actor_project_role(
            conn,
            actor_id=actor_id,
            project_id=yoke_id,
            role_name=ROLE_OWNER,
            granted_by_actor_id=actor_id,
        )
        entry = _entry("items.structured_field.replace")

        allowed = check_dispatch_permission(conn, entry, _request(actor_id, "yoke"))
        assert allowed.error is None
        assert allowed.permission_key == "items.write"
        assert allowed.project_slug == "yoke"

        denied = check_dispatch_permission(conn, entry, _request(actor_id, "buzz"))
        assert denied.error is not None
        assert denied.error.error is not None
        assert denied.error.error.code == "permission_denied"
        assert denied.project_slug == "buzz"
    finally:
        conn.close()


def test_project_scoped_github_write_denies_omitted_project_context():
    conn = _conn()
    try:
        actor_id = seed_human_actor(conn)
        buzz_id = resolve_project_id(conn, "buzz")
        grant_actor_project_role(
            conn,
            actor_id=actor_id,
            project_id=buzz_id,
            role_name=ROLE_OWNER,
            granted_by_actor_id=actor_id,
        )
        entry = _entry("github_actions.secret.set")
        request = FunctionCallRequest(
            function=entry.function_id,
            actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
            target=TargetRef(kind="global"),
            payload={"repo": "upyoke/yoke", "name": "CI", "value": "secret"},
        )

        denied = check_dispatch_permission(conn, entry, request)

        assert denied.error is not None
        assert denied.error.error is not None
        assert denied.error.error.code == "permission_denied"
        assert denied.project_id is None
    finally:
        conn.close()


def test_shepherd_dependency_writes_require_item_write_permission():
    assert permission_key_for(
        _read_entry("shepherd.dependency_list.run")
    ) == "items.read"
    assert permission_key_for(
        _entry("shepherd.dependency_add.run")
    ) == "items.write"
    assert permission_key_for(
        _entry("shepherd.dependency_update.run")
    ) == "items.write"
    assert permission_key_for(
        _entry("shepherd.dependency_remove.run")
    ) == "items.write"
    assert permission_key_for(
        _entry("shepherd.verdict.run")
    ) == "items.write"
    assert permission_key_for(
        _entry("shepherd.caveat_disposition.run")
    ) == "items.write"


def test_qa_writes_require_item_write_permission():
    assert permission_key_for(
        _entry("qa.requirement.waive")
    ) == "items.write"
    assert permission_key_for(
        _read_entry("qa.requirement.get")
    ) == "items.read"


def test_ephemeral_env_update_requires_item_write_on_env_project():
    conn = _conn()
    try:
        _create_ephemeral_env_table(conn)
        actor_id = seed_human_actor(conn)
        buzz_id = resolve_project_id(conn, "buzz")
        yoke_id = resolve_project_id(conn, "yoke")
        grant_actor_project_role(
            conn,
            actor_id=actor_id,
            project_id=buzz_id,
            role_name=ROLE_OWNER,
            granted_by_actor_id=actor_id,
        )
        cursor = conn.execute(
            "INSERT INTO ephemeral_environments "
            "(project_id, branch, status, created_at) "
            "VALUES (%s, 'YOK-10', 'pending', 'now') RETURNING id",
            (buzz_id,),
        )
        env_id = int(cursor.fetchone()[0])
        request = FunctionCallRequest(
            function="ephemeral_env.update",
            actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
            target=TargetRef(kind="global"),
            payload={"env_id": env_id, "field": "status", "value": "healthy"},
        )
        entry = _entry("ephemeral_env.update")

        allowed = check_dispatch_permission(conn, entry, request)
        assert permission_key_for(entry) == PERM_ITEMS_WRITE
        assert allowed.error is None
        assert allowed.project_slug == "buzz"

        conn.execute(
            "UPDATE ephemeral_environments SET project_id = %s WHERE id = %s",
            (yoke_id, env_id),
        )
        denied = check_dispatch_permission(conn, entry, request)
        assert denied.error is not None
        assert denied.project_slug == "yoke"
    finally:
        conn.close()


def test_db_read_run_uses_raw_permission_and_role_boundary():
    from yoke_core.domain.db_read_constants import DB_READ_FUNCTION_ID

    assert permission_key_for(_read_entry(DB_READ_FUNCTION_ID)) == PERM_DB_READ_RAW

    conn = _conn()
    try:
        yoke_id = resolve_project_id(conn, "yoke")
        owner_id = seed_human_actor(conn)
        operator_id = seed_human_actor(conn)
        viewer_id = seed_human_actor(conn)
        for actor_id, role_name in (
            (owner_id, ROLE_OWNER),
            (operator_id, ROLE_OPERATOR),
            (viewer_id, ROLE_VIEWER),
        ):
            grant_actor_project_role(
                conn,
                actor_id=actor_id,
                project_id=yoke_id,
                role_name=role_name,
                granted_by_actor_id=actor_id,
            )

        assert require_permission(
            conn,
            actor_id=owner_id,
            project_id=yoke_id,
            permission_key=PERM_DB_READ_RAW,
        ).allowed
        for actor_id in (operator_id, viewer_id):
            with pytest.raises(PermissionDenied):
                require_permission(
                    conn,
                    actor_id=actor_id,
                    project_id=yoke_id,
                    permission_key=PERM_DB_READ_RAW,
                )
    finally:
        conn.close()


def test_events_and_ouroboros_permissions_split_reads_and_writes():
    assert permission_key_for(_entry("events.emit")) == PERM_EVENTS_WRITE
    assert permission_key_for(_read_entry("events.query.run")) == PERM_EVENTS_READ
    assert (
        permission_key_for(_entry("ouroboros.entry.insert"))
        == PERM_EVENTS_WRITE
    )
    assert (
        permission_key_for(_entry("ouroboros.entry.mark_reviewed"))
        == PERM_EVENTS_WRITE
    )
    assert (
        permission_key_for(_entry("ouroboros.entry.mark_archived"))
        == PERM_EVENTS_WRITE
    )
    assert (
        permission_key_for(_read_entry("ouroboros.entry.list"))
        == PERM_EVENTS_READ
    )
    assert (
        permission_key_for(_read_entry("ouroboros.wrapup.list"))
        == PERM_EVENTS_READ
    )
    assert permission_key_for(_entry("ouroboros.field_note.append")) is None


def _process_acquire_request(
    actor_id: int, *, project: str | None,
) -> FunctionCallRequest:
    """Build a ``claims.work.acquire --process`` request as the CLI adapter does.

    The adapter sends a ``kind='global'`` envelope target and nests the project
    inside ``payload['target']['project']`` (the shape the acquire handler
    consumes); it never sets a top-level ``project`` / ``project_id``.
    """
    target_spec: dict = {"kind": "process", "process_key": "STRATEGIZE"}
    if project is not None:
        target_spec["project"] = project
    return FunctionCallRequest(
        function="claims.work.acquire",
        actor=ActorContext(actor_id=str(actor_id), session_id="s-1"),
        target=TargetRef(kind="global"),
        payload={"target": target_spec},
    )


def test_process_work_claim_resolves_project_from_payload_target():
    conn = _conn()
    try:
        actor_id = seed_human_actor(conn)
        yoke_id = resolve_project_id(conn, "yoke")
        grant_actor_project_role(
            conn,
            actor_id=actor_id,
            project_id=yoke_id,
            role_name=ROLE_OWNER,
            granted_by_actor_id=actor_id,
        )
        entry = _entry("claims.work.acquire")
        assert permission_key_for(entry) == PERM_CLAIMS_ACQUIRE

        # The per-project process authority is read from the nested target
        # spec; before this branch existed the resolver saw no project hint
        # and denied with "could not resolve a target project".
        allowed = check_dispatch_permission(
            conn, entry, _process_acquire_request(actor_id, project="yoke"),
        )
        assert allowed.error is None
        assert allowed.permission_key == PERM_CLAIMS_ACQUIRE
        assert allowed.project_slug == "yoke"

        # A process target that names no project still cannot resolve one —
        # the no-fallback contract holds (matches the handler's own guard).
        unresolvable = check_dispatch_permission(
            conn, entry, _process_acquire_request(actor_id, project=None),
        )
        assert unresolvable.error is not None
        assert unresolvable.error.error is not None
        assert unresolvable.error.error.code == "permission_denied"
        assert unresolvable.project_id is None
    finally:
        conn.close()


def test_strategy_carry_summary_stays_read_only_by_contract():
    from yoke_core.domain.handlers import strategy_operations

    by_id = {
        row["function_id"]: row
        for row in strategy_operations.REGISTRATIONS
    }

    assert by_id["strategy.carry.summary"]["side_effects"] == []
    assert (
        by_id["strategy.carry.register_new"]["side_effects"]
        == ["db_write"]
    )
    assert (
        permission_key_for(_read_entry("strategy.carry.summary"))
        == PERM_ITEMS_READ
    )
    assert (
        permission_key_for(_entry("strategy.carry.register_new"))
        == PERM_ITEMS_WRITE
    )
