"""Status sync + parent-epic checkbox update without host ``gh``.

Verifies update_status side effects route through the bearer-token REST
transport and never spawn ``gh``:

- ``_run_gh`` symbol is no longer present on the front-door module.
- ``shutil.which('gh')`` is not on the gate path; the GitHub-side-effect
  fan-out gate is now ``if not github_issue: return``.
- ``_github_label_sync`` / ``_github_comment_post`` /
  ``_github_close_on_terminal`` dispatch REST requests.
- ``_update_epic_checkbox`` GETs the parent-issue body via REST and
  PATCHes the flipped body back.

All tests masking ``gh`` from PATH still succeed because the engine
never reaches a host-``gh`` subprocess.
"""

from __future__ import annotations

from io import StringIO
from typing import Any
from unittest import mock

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import update_status as us
from yoke_core.domain.gh_rest_transport import (
    RestResponse,
)
from yoke_core.domain.project_github_auth import (
    ProjectGithubAuth,
)


def _mask_path(monkeypatch):
    monkeypatch.setenv("PATH", "/nonexistent")


_ITEMS_DDL = (
    "CREATE TABLE items (id INTEGER PRIMARY KEY, github_issue TEXT, "
    "project_id INTEGER, project_sequence INTEGER, "
    "title TEXT, status TEXT, type TEXT)"
)
_EPIC_TASKS_DDL = (
    "CREATE TABLE epic_tasks ("
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    "epic_id TEXT, task_num TEXT, title TEXT, worktree TEXT, "
    "context_estimate TEXT, dependencies TEXT, status TEXT, "
    "dispatch_attempts INTEGER DEFAULT 0, github_issue TEXT, "
    "last_heartbeat TEXT)"
)
# The repo-resolution join reads projects; without the table the swallowed
# lookup failure would poison the Postgres transaction for later statements.
_PROJECTS_DDL = (
    "CREATE TABLE projects (id INTEGER PRIMARY KEY, slug TEXT, "
    "github_repo TEXT)"
)


def _disposable_conn(*ddl: str) -> Any:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name), name,
    )
    for statement in ddl:
        conn.execute(statement)
    return conn


def _auth(project: str = "yoke", repo: str = "org/yoke") -> ProjectGithubAuth:
    return ProjectGithubAuth(
        project=project, repo=repo, token="t",
    )


def _ok_response(body=None) -> RestResponse:
    return RestResponse(status=200, headers={}, body=body if body is not None else {})


class TestRunGhSymbolRetired:
    """AC-2: ``_run_gh`` is no longer exported from update_status."""

    def test_run_gh_not_present(self):
        assert not hasattr(us, "_run_gh"), (
            "_run_gh should be retired from update_status front door"
        )

    def test_update_status_helpers_drops_run_gh(self):
        from yoke_core.domain import update_status_helpers as ush
        assert not hasattr(ush, "_run_gh"), (
            "_run_gh should be retired from update_status_helpers"
        )


class TestGithubLabelSyncRest:
    def test_label_sync_dispatches_rest_with_no_host_gh(self, monkeypatch):
        _mask_path(monkeypatch)
        calls = []

        def fake_req(req, *, token, **kwargs):
            calls.append((req.method, req.path))
            if req.method == "GET":
                return _ok_response([{"name": "status:plan drafted"}])
            return _ok_response()

        with mock.patch(
            "yoke_core.domain.update_status_github_sync.resolve_project_github_auth",
            return_value=_auth(),
        ), mock.patch(
            "yoke_core.domain.update_status_github_sync.request_with_retry",
            side_effect=fake_req,
        ):
            us._github_label_sync(
                "100", "implementing", [], "yoke", stderr=StringIO(),
            )
        # Should have POSTed the label-create + retrieved + deleted old + added new.
        methods = [c[0] for c in calls]
        assert "GET" in methods
        assert "POST" in methods
        assert any(
            c[0] == "DELETE"
            and c[1].endswith("labels/status%3Aplan%20drafted")
            for c in calls
        )


class TestGithubCommentPostRest:
    def test_comment_post_dispatches_rest(self, monkeypatch):
        _mask_path(monkeypatch)
        calls = []

        def fake_req(req, *, token, **kwargs):
            calls.append((req.method, req.path, req.body))
            return _ok_response()

        with mock.patch(
            "yoke_core.domain.update_status_github_sync.resolve_project_github_auth",
            return_value=_auth(),
        ), mock.patch(
            "yoke_core.domain.update_status_github_sync.request_with_retry",
            side_effect=fake_req,
        ):
            us._github_comment_post(
                "42", "idea", "implementing", "note text",
                [], "yoke", stderr=StringIO(),
            )
        # Comment POST should fire on the /comments endpoint.
        assert any(c[0] == "POST" and c[1].endswith("/issues/42/comments")
                   for c in calls)


class TestGithubCloseOnTerminalRest:
    def test_close_on_terminal_patches_issue_state(self, monkeypatch):
        _mask_path(monkeypatch)
        calls = []

        def fake_req(req, *, token, **kwargs):
            calls.append((req.method, req.path, dict(req.body or {})))
            if req.method == "GET":
                return _ok_response({"state": "closed"})
            return _ok_response()

        with mock.patch(
            "yoke_core.domain.update_status_github_sync.resolve_project_github_auth",
            return_value=_auth(),
        ), mock.patch(
            "yoke_core.domain.update_status_github_sync.request_with_retry",
            side_effect=fake_req,
        ):
            us._github_close_on_terminal(
                "42", "done", "1", "1", [], "yoke", stderr=StringIO(),
            )
        # PATCH /issues/42 with state=closed
        patches = [c for c in calls if c[0] == "PATCH"]
        assert patches
        assert patches[0][2].get("state") == "closed"


class TestEpicCheckboxRest:
    def _make_conn(self) -> Any:
        conn = _disposable_conn(_ITEMS_DDL)
        conn.execute(
            "INSERT INTO items (id, github_issue, project_id, project_sequence, "
            "title, status, type) "
            "VALUES (42, '#1234', 1, 42, 'Parent', 'implementing', 'epic')"
        )
        conn.commit()
        return conn

    def test_checkbox_flip_uses_rest(self, monkeypatch):
        _mask_path(monkeypatch)
        conn = self._make_conn()
        calls = []

        body_before = "- [ ] #100 First task\n- [ ] #101 Second task\n"

        def fake_req(req, *, token, **kwargs):
            calls.append((req.method, req.path, req.body))
            if req.method == "GET":
                return _ok_response({"body": body_before, "number": 1234})
            return _ok_response()

        with mock.patch(
            "yoke_core.domain.update_status_epic_checkbox.resolve_project_github_auth",
            return_value=_auth(),
        ), mock.patch(
            "yoke_core.domain.update_status_epic_checkbox.request_with_retry",
            side_effect=fake_req,
        ):
            us._update_epic_checkbox(
                conn, "42", "1", "done", "#100", [], "yoke",
                stdout=StringIO(), stderr=StringIO(),
            )

        # GET parent body, PATCH with flipped checkbox.
        gets = [c for c in calls if c[0] == "GET"]
        patches = [c for c in calls if c[0] == "PATCH"]
        assert gets and patches
        patch_body = patches[0][2] or {}
        assert "[x] #100" in str(patch_body.get("body") or "")


class TestNoGithubIssueShortCircuit:
    """AC-14: gate is ``if not github_issue: return``; no shutil.which gate."""

    def test_skips_when_no_github_issue(self, monkeypatch):
        _mask_path(monkeypatch)
        conn = _disposable_conn(_EPIC_TASKS_DDL, _ITEMS_DDL, _PROJECTS_DDL)
        conn.execute(
            "INSERT INTO items (id, project_id, project_sequence, title, "
            "status, github_issue, type) "
            "VALUES (50, 1, 50, 'p', 'implementing', '', 'epic')"
        )
        conn.execute(
            "INSERT INTO epic_tasks (epic_id, task_num, title, status, github_issue) "
            "VALUES ('50', '1', 't', 'idea', '')"
        )
        conn.commit()
        # With no github_issue + no claim bypass, the status update path
        # would attempt to acquire a claim; bypass that via env.
        monkeypatch.setenv("YOKE_CLAIM_BYPASS", "test-bypass")
        # Avoid board rebuild + auto_derive side effects.
        with mock.patch("yoke_core.domain.update_status._rebuild_board"), \
             mock.patch("yoke_core.domain.update_status.auto_unblock"), \
             mock.patch("yoke_core.domain.update_status.auto_derive_epic_status"), \
             mock.patch(
                 "yoke_core.domain.update_status._github_label_sync"
             ) as label, \
             mock.patch(
                 "yoke_core.domain.update_status._github_comment_post"
             ) as comment, \
             mock.patch(
                 "yoke_core.domain.update_status._github_close_on_terminal"
             ) as close:
            rc = us.update_task_status(
                conn, "50", "1", "implementing",
                no_rebuild=True, no_derive=True,
                stdout=StringIO(), stderr=StringIO(),
            )
        assert rc == 0
        # Without github_issue, the GitHub side effects do NOT fire.
        label.assert_not_called()
        comment.assert_not_called()
        close.assert_not_called()

    def test_skips_when_github_issue_is_sentinel_zero(self, monkeypatch):
        """Regression: a prior sync that hit a REST 422 (e.g. label too long)
        used to stamp ``github_issue='#0'`` into epic_tasks. Lifecycle
        transitions then tried to POST to ``/issues/0/comments`` because the
        legacy guard only checked for empty / "null". The new guard rejects
        the ``#0`` sentinel the same way it rejects empty.
        """
        _mask_path(monkeypatch)
        conn = _disposable_conn(_EPIC_TASKS_DDL, _ITEMS_DDL, _PROJECTS_DDL)
        conn.execute(
            "INSERT INTO items (id, project_id, project_sequence, title, "
            "status, github_issue, type) "
            "VALUES (50, 1, 50, 'p', 'implementing', '#4556', 'epic')"
        )
        conn.execute(
            "INSERT INTO epic_tasks (epic_id, task_num, title, status, github_issue) "
            "VALUES ('50', '1', 't', 'idea', '#0')"
        )
        conn.commit()
        monkeypatch.setenv("YOKE_CLAIM_BYPASS", "test-bypass")
        err = StringIO()
        with mock.patch("yoke_core.domain.update_status._rebuild_board"), \
             mock.patch("yoke_core.domain.update_status.auto_unblock"), \
             mock.patch("yoke_core.domain.update_status.auto_derive_epic_status"), \
             mock.patch(
                 "yoke_core.domain.update_status._github_label_sync"
             ) as label, \
             mock.patch(
                 "yoke_core.domain.update_status._github_comment_post"
             ) as comment, \
             mock.patch(
                 "yoke_core.domain.update_status._github_close_on_terminal"
             ) as close:
            rc = us.update_task_status(
                conn, "50", "1", "implementing",
                no_rebuild=True, no_derive=True,
                stdout=StringIO(), stderr=err,
            )
        assert rc == 0
        label.assert_not_called()
        comment.assert_not_called()
        close.assert_not_called()
        assert "sentinel" in err.getvalue()
