"""Tests for the GitHub body-size budget guard + compact-mirror renderer."""

from __future__ import annotations

from typing import Any, Iterator, Optional

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import backlog_github_body_budget as bb


# ---------------------------------------------------------------------------
# Pure predicate
# ---------------------------------------------------------------------------


class TestBodyExceedsBudget:
    def test_under_budget_returns_false(self):
        assert bb.body_exceeds_budget("a" * 1000) is False

    def test_exactly_at_budget_returns_false(self):
        body = "a" * bb.GITHUB_BODY_BUDGET_BYTES
        assert bb.body_exceeds_budget(body) is False

    def test_one_byte_over_budget_returns_true(self):
        body = "a" * (bb.GITHUB_BODY_BUDGET_BYTES + 1)
        assert bb.body_exceeds_budget(body) is True

    def test_byte_length_vs_char_length(self):
        """AC-2: predicate is byte-length, not char-length.

        A 31k-char emoji body is ~124k bytes because each emoji code point
        encodes as four UTF-8 bytes.  Char-length-based logic would falsely
        accept it; the byte-length predicate must reject.
        """
        # Each "🚀" is 4 bytes in UTF-8.  31 000 chars → 124 000 bytes.
        body = "🚀" * 31000
        assert len(body) == 31000  # char-length passes
        assert len(body.encode("utf-8")) == 124000  # byte-length exceeds
        assert bb.body_exceeds_budget(body) is True


# ---------------------------------------------------------------------------
# Compact mirror
# ---------------------------------------------------------------------------


_TRANSITIONS_DDL = """
CREATE TABLE item_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    task_num INTEGER,
    from_status TEXT,
    to_status TEXT NOT NULL,
    source TEXT,
    session_id TEXT,
    actor_id INTEGER,
    project_id INTEGER,
    created_at TEXT NOT NULL
)
"""


def _disposable_conn(ddl: Optional[str] = None) -> Any:
    """Disposable Postgres DB connection, optionally seeded with *ddl*.

    Autocommit: the renderer's best-effort reads (item ref, evidence)
    swallow failures on this minimal schema; autocommit keeps one failed
    probe from poisoning the statements that follow it.
    """
    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name), name,
    )
    conn.autocommit = True
    if ddl:
        conn.execute(ddl)
    return conn


@pytest.fixture
def evidence_conn() -> Iterator[Any]:
    """Disposable Postgres DB seeded with a minimal transition row."""
    conn = _disposable_conn(_TRANSITIONS_DDL)
    conn.execute(
        "INSERT INTO item_status_transitions "
        "(item_id, from_status, to_status, created_at) VALUES (%s, %s, %s, %s)",
        (42, "refined-idea", "implementing", "2026-05-13T20:00:00Z"),
    )
    yield conn
    conn.close()


class TestRenderCompactMirror:
    def test_contains_required_fields(self, evidence_conn: Any):
        """AC-3: compact mirror names title, YOK-N, project, status, lifecycle,
        DB pointer, lifecycle commands, and evidence summary."""
        fields = {
            "title": "My Title",
            "project": "yoke",
            "status": "implementing",
            "type": "issue",
        }
        out = bb.render_compact_mirror(fields, conn=evidence_conn, item_id=42)
        assert "[YOK-42] My Title" in out
        assert "YOK-42" in out
        assert "yoke" in out
        assert "implementing" in out
        assert (
            "python3 -m yoke_core.cli.db_router items get YOK-42 body"
            in out
        )
        # Lifecycle commands include the implementing-phase entry.
        assert "/yoke advance YOK-42 reviewing-implementation" in out
        # Evidence summary present.
        assert "latest transition: refined-idea -> implementing" in out

    def test_unknown_status_falls_back_to_do(
        self, evidence_conn: Any,
    ):
        fields = {"title": "x", "status": "unknown-status", "type": "issue"}
        out = bb.render_compact_mirror(fields, conn=evidence_conn, item_id=1)
        assert "/yoke do YOK-1" in out

    def test_missing_evidence_falls_back_to_no_recent_evidence(self):
        empty = _disposable_conn(_TRANSITIONS_DDL)
        out = bb.render_compact_mirror(
            {"title": "x", "status": "idea"}, conn=empty, item_id=1,
        )
        assert "no recent evidence" in out

    def test_evidence_read_failure_falls_back_quietly(self):
        """Evidence read failures must not crash the whole sync."""
        broken = _disposable_conn()
        # No item_status_transitions table → execute() raises.
        out = bb.render_compact_mirror(
            {"title": "x", "status": "idea"}, conn=broken, item_id=1,
        )
        assert "no recent evidence" in out

    def test_long_title_truncated(self, evidence_conn: Any):
        """AC `Watch Out For`: cap title length to keep mirror under budget."""
        long_title = "x" * 5000
        out = bb.render_compact_mirror(
            {"title": long_title, "status": "idea"},
            conn=evidence_conn,
            item_id=1,
        )
        # Truncated title ends with the ellipsis sentinel.
        assert "…" in out
        # The mirror line for the title is shorter than the raw title.
        assert long_title not in out

    def test_compact_mirror_fits_under_budget(
        self, evidence_conn: Any,
    ):
        """The compact mirror itself MUST fit under the budget."""
        long_title = "x" * 5000  # title truncates to ~500 chars
        out = bb.render_compact_mirror(
            {
                "title": long_title,
                "project": "yoke",
                "status": "implementing",
                "type": "issue",
            },
            conn=evidence_conn,
            item_id=42,
        )
        assert bb.body_exceeds_budget(out) is False


# ---------------------------------------------------------------------------
# Selector
# ---------------------------------------------------------------------------


class TestSelectBodyForGithub:
    def test_under_budget_returns_full(self, evidence_conn: Any):
        full_body = "small body"
        chosen, mode = bb.select_body_for_github(
            full_body,
            item_fields={"title": "t", "status": "idea"},
            conn=evidence_conn,
            item_id=1,
        )
        assert chosen == full_body
        assert mode == "full"

    def test_over_budget_returns_compact(
        self, evidence_conn: Any,
    ):
        big_body = "a" * (bb.GITHUB_BODY_BUDGET_BYTES + 100)
        chosen, mode = bb.select_body_for_github(
            big_body,
            item_fields={
                "title": "t",
                "project": "yoke",
                "status": "implementing",
                "type": "issue",
            },
            conn=evidence_conn,
            item_id=42,
        )
        assert mode == "compact"
        assert bb.body_exceeds_budget(chosen) is False
        assert "YOK-42" in chosen


class TestSelectAndWriteBodyFile:
    def test_writes_full_body_to_temp_file_when_under_budget(
        self, evidence_conn: Any, tmp_path,
    ):
        full_body = "tiny body content"
        path, mode = bb.select_and_write_body_file(
            full_body,
            item_fields={"title": "t", "status": "idea"},
            conn=evidence_conn,
            item_id=1,
            prefix="yoke-test-",
        )
        try:
            assert mode == "full"
            with open(path, "r", encoding="utf-8") as f:
                assert f.read() == full_body
        finally:
            bb.unlink_quiet(path)

    def test_writes_compact_mirror_when_over_budget(
        self, evidence_conn: Any,
    ):
        big_body = "a" * (bb.GITHUB_BODY_BUDGET_BYTES + 100)
        path, mode = bb.select_and_write_body_file(
            big_body,
            item_fields={"title": "t", "status": "idea"},
            conn=evidence_conn,
            item_id=42,
            prefix="yoke-test-",
        )
        try:
            assert mode == "compact"
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            assert "YOK-42" in content
            assert "DB" in content
            assert bb.body_exceeds_budget(content) is False
        finally:
            bb.unlink_quiet(path)


class TestEmitCompactNotice:
    def test_emits_only_on_compact_mode(self, capsys):
        import sys
        bb.emit_compact_notice("full", 42, sys.stderr)
        captured = capsys.readouterr()
        assert captured.err == ""

        bb.emit_compact_notice("compact", 42, sys.stderr)
        captured = capsys.readouterr()
        assert "YOK-42" in captured.err
        assert "compact mirror" in captured.err
