"""Hard-cutover migration coverage for steering-scope work claims."""

from __future__ import annotations

import psycopg
import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import migrations as migration_history_package
from yoke_core.domain.migration_history import (
    history_dir,
    load_migration_module,
    ordered_entries,
)
from yoke_core.domain.migration_serving_version import declared_minimum
from yoke_core.domain.schema_common import _get_check_constraint_defs

ENTRY_NAME = "0020_steering_scope_claims"


def _entry():
    directory = history_dir(migration_history_package)
    record = next(
        candidate
        for candidate in ordered_entries(directory)
        if candidate.name == ENTRY_NAME
    )
    return load_migration_module(directory / f"{record.name}.py", record.name)


entry = _entry()


@pytest.fixture
def retired_db():
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    conn.execute(
        """
        CREATE TABLE work_claims (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            target_kind TEXT NOT NULL
              CHECK(target_kind IN ('item','epic_task','process')),
            item_id INTEGER,
            epic_id INTEGER,
            task_num INTEGER,
            process_key TEXT,
            conflict_group TEXT,
            claim_type TEXT NOT NULL DEFAULT 'exclusive'
              CHECK(claim_type='exclusive'),
            claimed_at TEXT NOT NULL,
            last_heartbeat TEXT NOT NULL,
            released_at TEXT,
            release_reason TEXT,
            reason TEXT,
            reason_intent TEXT,
            release_reason_intent TEXT,
            CHECK (
              (target_kind='item' AND item_id IS NOT NULL
                AND epic_id IS NULL AND task_num IS NULL
                AND process_key IS NULL AND conflict_group IS NULL) OR
              (target_kind='epic_task' AND item_id IS NULL
                AND epic_id IS NOT NULL AND task_num IS NOT NULL
                AND process_key IS NULL AND conflict_group IS NULL) OR
              (target_kind='process' AND item_id IS NULL
                AND epic_id IS NULL AND task_num IS NULL
                AND process_key IS NOT NULL AND conflict_group IS NOT NULL)
            )
        )
        """
    )
    conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, item_id, claimed_at, last_heartbeat) "
        "VALUES ('item-session', 'item', 10, 't1', 't1')"
    )
    conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, process_key, conflict_group, claimed_at, "
        "last_heartbeat) VALUES "
        "('process-session', 'process', 'DOCTOR', 'doctor:yoke', 't2', 't2')"
    )
    conn.commit()
    try:
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def _insert_steering(conn, *, session_id: str = "steering-session"):
    return conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, steering_project_id, "
        "steering_strategy_doc_slugs, owner_kind, owner_session_id, "
        "registered_by_actor_id, registered_by_session_id, claimed_at, "
        "last_heartbeat) VALUES "
        "(%s, 'steering_scope', 7, '[\"MISSION\"]', 'session', %s, 2, %s, "
        "'t3', 't3') RETURNING id",
        (session_id, session_id, session_id),
    ).fetchone()[0]


def test_cutover_preserves_rows_and_accepts_typed_steering_scope(retired_db) -> None:
    entry.apply(retired_db)
    entry.invariants(retired_db)

    assert retired_db.execute("SELECT COUNT(*) FROM work_claims").fetchone()[0] == 2
    legacy = retired_db.execute(
        "SELECT target_kind, steering_project_id, owner_kind "
        "FROM work_claims ORDER BY id"
    ).fetchall()
    assert [(row[0], row[1], row[2]) for row in legacy] == [
        ("item", None, None),
        ("process", None, None),
    ]
    claim_id = _insert_steering(retired_db)
    assert int(claim_id) > 0
    retired_db.commit()
    entry.invariants(retired_db)


def test_cutover_checks_owner_shape_and_exact_active_identity(retired_db) -> None:
    entry.apply(retired_db)
    _insert_steering(retired_db)
    retired_db.commit()

    with pytest.raises(psycopg.errors.CheckViolation):
        retired_db.execute(
            "INSERT INTO work_claims "
            "(session_id, target_kind, steering_project_id, "
            "steering_strategy_doc_slugs, owner_kind, owner_session_id, "
            "registered_by_actor_id, registered_by_session_id, claimed_at, "
            "last_heartbeat) VALUES "
            "('wrong-owner', 'steering_scope', 8, '[]', 'session', "
            "'somebody-else', 2, 'wrong-owner', 't4', 't4')"
        )
    retired_db.rollback()

    with pytest.raises(psycopg.errors.UniqueViolation):
        _insert_steering(retired_db, session_id="another-session")
    retired_db.rollback()


def test_cutover_is_idempotent_and_declares_the_serving_floor(retired_db) -> None:
    entry.apply(retired_db)
    entry.apply(retired_db)
    entry.invariants(retired_db)

    checks = " ".join(_get_check_constraint_defs(retired_db, "work_claims"))
    assert "steering_scope" in checks
    assert "owner_session_id" in checks
    assert declared_minimum(entry) == entry.MINIMUM_SERVING_VERSION
