"""Regression tests for ``_run_module_invariants`` validation-surface guard.

Migration #48 (``refresh_item_progress_view_pipeline_blocked_reason``)
test-verify failed when the validation surface lacked
``deployment_flows`` and the module's ``invariants(conn)`` queried
it directly. The fix classifies the resulting missing-relation error
with an explicit hint pointing the operator at a module-side guard
instead of asking every validation surface to bootstrap the table.
"""

from __future__ import annotations

from collections.abc import Iterator
from types import SimpleNamespace
from typing import Any

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain.migration_apply_verify import _run_module_invariants


@pytest.fixture
def conn_with_only_items() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        conn.execute(
            "CREATE TABLE items "
            "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"
        )
        conn.commit()
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_no_invariants_returns_none(conn_with_only_items):
    """A module with no ``invariants`` attribute is a no-op."""
    module = SimpleNamespace()
    assert _run_module_invariants(module, conn_with_only_items) is None


def test_invariants_passes_returns_none(conn_with_only_items):
    """A successful invariant returns None (the all-clear signal)."""

    def invariants(conn: Any) -> None:
        conn.execute("SELECT COUNT(*) FROM items").fetchone()

    module = SimpleNamespace(invariants=invariants)
    assert _run_module_invariants(module, conn_with_only_items) is None


def test_missing_relation_carries_validation_surface_hint(conn_with_only_items):
    """A missing-relation failure surfaces the canonical hint so the
    operator knows to guard the invariant module-side rather than
    bootstrap the missing table on every validation surface."""

    def invariants(conn: Any) -> None:
        conn.execute("SELECT 1 FROM deployment_flows").fetchone()

    module = SimpleNamespace(invariants=invariants)
    err = _run_module_invariants(module, conn_with_only_items)
    assert err is not None
    assert "deployment_flows" in err
    assert "validation surface lacks this table" in err


def test_non_table_operational_error_keeps_plain_format(conn_with_only_items):
    """Operational errors that are NOT missing-relation failures keep the
    plain ``invariants raised <Class>: ...`` format so they remain comparable
    across the verify and live-apply paths."""

    def invariants(conn: Any) -> None:
        conn.execute(
            "SELECT * FROM items WHERE missing_col = %s", (1,)
        ).fetchone()

    module = SimpleNamespace(invariants=invariants)
    err = _run_module_invariants(module, conn_with_only_items)
    assert err is not None
    assert "invariants raised" in err
    assert "validation surface" not in err


def test_other_exception_keeps_class_name_prefix(conn_with_only_items):
    """Non-Operational exceptions keep the legacy ``invariants raised
    <Class>: <msg>`` shape so downstream callers can pattern-match."""

    def invariants(conn: Any) -> None:
        raise ValueError("custom failure")

    module = SimpleNamespace(invariants=invariants)
    err = _run_module_invariants(module, conn_with_only_items)
    assert err is not None
    assert err.startswith("invariants raised ValueError: custom failure")
