"""Tests for the install bundle's managed-markdown + permissions layer."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_contracts.project_contract.managed_block import MANAGED_BLOCK_END
from yoke_core.domain import (
    install_bundle,
    install_bundle_managed,
    install_bundle_tree_sync,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGED_ROOT = REPO_ROOT / install_bundle_tree_sync.PACKAGED_TREE_REL
PYPROJECT = REPO_ROOT / "packages/yoke-core/pyproject.toml"
INSTALLED_RULES_BUDGET_BYTES = 135_000
REPRESENTATIVE_PROJECT_RULES = "# Project rules\n" + "- project-specific rule\n" * 350


@pytest.fixture()
def conn():
    name = pg_testdb.create_test_database()
    db = pg_testdb.connect_test_database(name)
    try:
        db.execute(
            "CREATE TABLE projects ("
            "id INTEGER PRIMARY KEY, slug TEXT, name TEXT, "
            "default_branch TEXT DEFAULT 'main')"
        )
        db.execute("INSERT INTO projects (id, slug, name) VALUES (1, 'yoke', 'Yoke')")
        db.execute(
            "CREATE TABLE strategy_docs ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, slug TEXT NOT NULL, "
            "content TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, "
            "updated_by_actor_id INTEGER, archived_at TEXT, "
            "UNIQUE(project_id, slug))"
        )
        db.execute(
            "CREATE TABLE project_capabilities ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, type TEXT NOT NULL, "
            "settings TEXT DEFAULT '{}', created_at TEXT NOT NULL, "
            "UNIQUE(project_id, type))"
        )
        db.commit()
        yield db
    finally:
        db.close()
        pg_testdb.drop_test_database(name)


def test_packaged_snapshot_carries_root_source_files() -> None:
    # The doctrine files are FILES, not dirs, so the per-dir byte test in the
    # sibling suite never sees them; guard them explicitly so the product wheel
    # carries only the project-agnostic prefix build_bundle extracts blocks from.
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        source = REPO_ROOT / rel
        packaged = PACKAGED_ROOT / rel
        source_bytes = source.read_bytes()
        marker = MANAGED_BLOCK_END.encode("utf-8")
        boundary = source_bytes.index(marker) + len(marker)
        expected = source_bytes[:boundary] + b"\n"
        assert packaged.is_file(), f"packaged snapshot missing root file {rel}"
        assert packaged.read_bytes() == expected, (
            f"snapshot drift for {rel}: "
            f"source_sha256={hashlib.sha256(expected).hexdigest()} "
            f"packaged_sha256={hashlib.sha256(packaged.read_bytes()).hexdigest()}"
        )


def test_packaged_snapshot_excludes_repo_internal_teaching() -> None:
    markers = (
        "# Yoke Repo Internals",
        "origin/cla-signatures",
        "yoke-hosted-stage-typed-target",
    )
    offenders = []
    for path in PACKAGED_ROOT.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        found = [marker for marker in markers if marker in text]
        if found:
            offenders.append((path.relative_to(PACKAGED_ROOT).as_posix(), found))
    assert offenders == [], (
        f"repo-internal teaching reached install bundle: {offenders}"
    )


def test_pyproject_package_data_covers_root_source_files() -> None:
    # A root file added to INSTALL_BUNDLE_SOURCE_FILES but not globbed here would
    # be materialized into the snapshot yet omitted from the wheel.
    text = PYPROJECT.read_text("utf-8")
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        assert f'"{rel}"' in text, (
            f"pyproject package-data is missing a glob for root file {rel!r}"
        )


def test_bundle_ships_managed_markdown_and_permissions(conn) -> None:
    # A managed project needs the agnostic doctrine (AGENTS.md/CLAUDE.md) and the
    # Codex shell (CODEX.md) as marker-delimited blocks, plus the Claude tool
    # permissions — a fresh install otherwise has no rules files and prompts on
    # every Bash/Write/Edit/Monitor call. The block bodies are extracted from
    # this repo's OWN doctrine files (dogfooding), so what ships is what yoke runs.
    from yoke_contracts.project_contract.managed_block import (
        MANAGED_BLOCK_BEGIN,
        extract_block_body,
        render_block,
    )
    from yoke_core.domain.agents_render_claude import CLAUDE_PERMISSIONS

    bundle = install_bundle.build_bundle(1, conn)

    mm = bundle["managed_markdown"]
    assert set(mm["blocks"]) == {"doctrine", "codex_shell", "cursor_shell"}
    assert mm["targets"] == [
        {"path": "AGENTS.md", "block": "doctrine"},
        {"path": "CLAUDE.md", "block": "doctrine"},
        {"path": "CODEX.md", "block": "codex_shell"},
        {"path": "CURSOR.md", "block": "cursor_shell"},
    ]
    for body in mm["blocks"].values():
        # Bodies are block *bodies*, not blocks — non-empty and marker-free.
        assert body and MANAGED_BLOCK_BEGIN not in body
    root = install_bundle.server_tree_root()
    agents_text = (root / "AGENTS.md").read_text("utf-8")
    authored = extract_block_body(agents_text)
    # The doctrine block leads with this repo's own authored block body...
    assert mm["blocks"]["doctrine"].startswith(authored)
    # ...and re-rendering that authored region reproduces the source file's block.
    assert render_block(authored) in agents_text
    codex_text = (root / "CODEX.md").read_text("utf-8")
    assert mm["blocks"]["codex_shell"] == extract_block_body(codex_text)

    perms = bundle["claude_settings_permissions"]
    assert perms["allow"] == list(CLAUDE_PERMISSIONS["allow"])
    assert perms["auto_memory_enabled"] is False


def test_composed_external_rules_keep_harness_context_headroom(
    conn,
    tmp_path,
) -> None:
    from yoke_cli.project_install.managed_markdown import apply_managed_markdown

    for name in ("AGENTS.md", "CLAUDE.md"):
        (tmp_path / name).write_text(REPRESENTATIVE_PROJECT_RULES, encoding="utf-8")
    bundle = install_bundle.build_bundle(1, conn)

    apply_managed_markdown(tmp_path, bundle["managed_markdown"], None)

    sizes = {
        name: (tmp_path / name).stat().st_size for name in ("AGENTS.md", "CLAUDE.md")
    }
    assert max(sizes.values()) <= INSTALLED_RULES_BUDGET_BYTES, sizes


def test_doctrine_block_leaves_generated_packet_to_session_orientation(conn) -> None:
    doctrine = install_bundle.build_bundle(1, conn)["managed_markdown"]["blocks"][
        "doctrine"
    ]

    assert doctrine
    assert "Main-session DB/API packet (main_agent)" not in doctrine


def test_bundle_files_stay_out_of_yoke_dir_except_docs(conn) -> None:
    bundle = install_bundle.build_bundle(1, conn)
    for entry in bundle["files"]:
        p = entry["path"]
        # Docs are the one yoke-authoritative .yoke/ subtree; all else stays out.
        assert p.startswith(".yoke/docs/") or not p.startswith(".yoke/")
        assert not p.startswith("/")
        assert ".." not in p.split("/")


def test_bundle_ships_universal_docs(conn) -> None:
    from yoke_core.domain.install_bundle import DOCS_DEST, DOCS_SOURCE

    bundle = install_bundle.build_bundle(1, conn)
    by_path = {e["path"]: e["content"] for e in bundle["files"]}
    # Authored under docs/public; installed projects receive .yoke/docs/.
    for rel in (
        "index.md",
        "nav.yaml",
        "reference/commands.md",
        "reference/lifecycle.md",
        "reference/db-reference.md",
        "reference/db-reference/functions.md",
        "reference/qa-platform/success-policy-schema.md",
    ):
        path = f"{DOCS_DEST}/{rel}"
        assert path in by_path, f"bundle missing shipped doc {path}"
        assert by_path[path].strip()
    # Every shipped doc byte-matches the server tree's docs/public source.
    root = install_bundle.server_tree_root()
    for path, content in by_path.items():
        if path.startswith(f"{DOCS_DEST}/"):
            rel = path[len(DOCS_DEST) + 1 :]
            assert content == (root / DOCS_SOURCE / rel).read_text("utf-8")
