"""Unit tests for ``yoke_core.domain.epic_amend``.

Each test runs against a disposable Postgres database seeded with the
``epic_tasks`` schema. Single-transaction behavior is verified by the
sibling-dependency cascade tests on ``task_remove`` and ``task_split``.
"""

from __future__ import annotations

import unittest
from typing import Any

import pytest

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_core.domain import epic_amend


_TASKS_SCHEMA = """
CREATE TABLE epic_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    title TEXT,
    worktree TEXT,
    context_estimate TEXT,
    dependencies TEXT,
    status TEXT DEFAULT 'planning',
    dispatch_attempts INTEGER DEFAULT 0,
    body TEXT,
    github_issue TEXT,
    branch TEXT,
    worktree_path TEXT,
    blocked_by TEXT,
    max_attempts INTEGER DEFAULT 5,
    agent_id TEXT,
    last_heartbeat TEXT,
    UNIQUE(epic_id, task_num)
);
"""


def _seed_conn() -> Any:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name), name,
    )
    apply_sql_script(conn, _TASKS_SCHEMA)
    conn.commit()
    return conn


def _add_row(conn, epic_id, task_num, title, **kwargs):
    conn.execute(
        "INSERT INTO epic_tasks (epic_id, task_num, title, worktree, "
        "context_estimate, dependencies, status, body) VALUES "
        "(%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            str(epic_id), task_num, title,
            kwargs.get("worktree", ""), kwargs.get("context_estimate", ""),
            kwargs.get("dependencies", ""), kwargs.get("status", "planning"),
            kwargs.get("body", ""),
        ),
    )
    conn.commit()


class TestTaskAdd(unittest.TestCase):
    def test_appends_at_next_task_num(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        result = epic_amend.task_add(
            conn, 100, title="second", body="body-text",
        )
        assert result.task_num == 2
        row = conn.execute(
            "SELECT title, body FROM epic_tasks WHERE epic_id='100' "
            "AND task_num=2"
        ).fetchone()
        assert row["title"] == "second"
        assert row["body"] == "body-text"

    def test_first_task_starts_at_one(self):
        conn = _seed_conn()
        result = epic_amend.task_add(conn, 200, title="first")
        assert result.task_num == 1

    def test_rejects_empty_title(self):
        conn = _seed_conn()
        with pytest.raises(ValueError, match="title"):
            epic_amend.task_add(conn, 100, title="")


class TestTaskReassign(unittest.TestCase):
    def test_updates_worktree_column(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first", worktree="old-wt")
        result = epic_amend.task_reassign(conn, 100, 1, "new-wt")
        assert result.old_worktree == "old-wt"
        assert result.new_worktree == "new-wt"
        row = conn.execute(
            "SELECT worktree FROM epic_tasks WHERE epic_id='100' AND task_num=1"
        ).fetchone()
        assert row["worktree"] == "new-wt"

    def test_rejects_empty_worktree(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        with pytest.raises(ValueError, match="new_worktree"):
            epic_amend.task_reassign(conn, 100, 1, "")

    def test_raises_when_task_missing(self):
        conn = _seed_conn()
        with pytest.raises(LookupError):
            epic_amend.task_reassign(conn, 100, 99, "any")


class TestTaskRemove(unittest.TestCase):
    def test_removes_row(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        _add_row(conn, 100, 2, "second")
        epic_amend.task_remove(conn, 100, 1)
        rows = conn.execute(
            "SELECT task_num FROM epic_tasks WHERE epic_id='100'"
        ).fetchall()
        assert [r["task_num"] for r in rows] == [2]

    def test_cascade_removes_dependency_token(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        _add_row(conn, 100, 2, "second", dependencies="1")
        _add_row(conn, 100, 3, "third", dependencies="1,2")
        result = epic_amend.task_remove(conn, 100, 1)
        assert 2 in result.cascade_updated
        assert 3 in result.cascade_updated
        rows = conn.execute(
            "SELECT task_num, dependencies FROM epic_tasks WHERE epic_id='100' "
            "ORDER BY task_num"
        ).fetchall()
        deps = {r["task_num"]: r["dependencies"] for r in rows}
        assert deps[2] == ""
        assert deps[3] == "2"

    def test_raises_when_task_missing(self):
        conn = _seed_conn()
        with pytest.raises(LookupError):
            epic_amend.task_remove(conn, 100, 99)


class TestTaskMetadataUpdate(unittest.TestCase):
    def test_updates_whitelisted_fields(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first", context_estimate="2k")
        result = epic_amend.task_metadata_update(
            conn, 100, 1,
            {"title": "renamed", "context_estimate": "4k",
             "github_issue": "#42"},
        )
        assert result.updated_fields["title"] == "renamed"
        assert result.updated_fields["context_estimate"] == "4k"
        row = conn.execute(
            "SELECT title, context_estimate, github_issue FROM epic_tasks "
            "WHERE epic_id='100' AND task_num=1"
        ).fetchone()
        assert row["title"] == "renamed"
        assert row["context_estimate"] == "4k"
        assert row["github_issue"] == "#42"

    def test_rejects_unknown_field(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        with pytest.raises(ValueError, match="unknown metadata"):
            epic_amend.task_metadata_update(
                conn, 100, 1, {"status": "planned"},
            )

    def test_rejects_empty_fields(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "first")
        with pytest.raises(ValueError, match="empty"):
            epic_amend.task_metadata_update(conn, 100, 1, {})

    def test_raises_when_task_missing(self):
        conn = _seed_conn()
        with pytest.raises(LookupError):
            epic_amend.task_metadata_update(conn, 100, 99, {"title": "x"})


class TestTaskSplit(unittest.TestCase):
    def test_creates_children_at_max_plus_one(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "parent")
        _add_row(conn, 100, 2, "sibling")
        result = epic_amend.task_split(
            conn, 100, 1,
            [{"title": "child-A", "body": "A-body"},
             {"title": "child-B"}],
        )
        assert result.parent_task_num == 1
        assert result.new_task_nums == [3, 4]
        rows = conn.execute(
            "SELECT task_num, title, body FROM epic_tasks "
            "WHERE epic_id='100' ORDER BY task_num"
        ).fetchall()
        title_map = {r["task_num"]: r["title"] for r in rows}
        body_map = {r["task_num"]: r["body"] for r in rows}
        # Parent row removed; siblings + 2 children present.
        assert 1 not in title_map
        assert title_map[2] == "sibling"
        assert title_map[3] == "child-A"
        assert title_map[4] == "child-B"
        assert body_map[3] == "A-body"

    def test_redirects_sibling_dependencies_to_first_child(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "parent")
        _add_row(conn, 100, 2, "sibling", dependencies="1")
        _add_row(conn, 100, 3, "other", dependencies="1,2")
        result = epic_amend.task_split(
            conn, 100, 1,
            [{"title": "child-A"}, {"title": "child-B"}],
        )
        assert result.new_task_nums == [4, 5]
        # First child is 4 — sibling deps that referenced 1 now reference 4.
        rows = conn.execute(
            "SELECT task_num, dependencies FROM epic_tasks "
            "WHERE epic_id='100' AND task_num IN (2, 3) ORDER BY task_num"
        ).fetchall()
        deps = {r["task_num"]: r["dependencies"] for r in rows}
        assert deps[2] == "4"
        assert deps[3] == "4,2"

    def test_rejects_empty_children(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "parent")
        with pytest.raises(ValueError, match="children"):
            epic_amend.task_split(conn, 100, 1, [])

    def test_rejects_child_missing_title(self):
        conn = _seed_conn()
        _add_row(conn, 100, 1, "parent")
        with pytest.raises(ValueError, match="title"):
            epic_amend.task_split(
                conn, 100, 1, [{"body": "no title"}],
            )

    def test_raises_when_parent_missing(self):
        conn = _seed_conn()
        with pytest.raises(LookupError):
            epic_amend.task_split(
                conn, 100, 99, [{"title": "x"}],
            )


if __name__ == "__main__":
    unittest.main()
