"""Tests for DB-backed project policy capability defaults."""

from __future__ import annotations

import json
from collections.abc import Iterator
from typing import Any

import pytest

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_contracts.title_policy import DEFAULT_TITLE_MAX_LENGTH
from yoke_core.domain.project_policy_capabilities import (
    PROJECT_POLICY_CAPABILITY,
    SESSION_ROUTING_CAPABILITY,
    ensure_default_policy_capabilities,
    set_project_policy_value,
)
from yoke_core.domain.project_title_policy import resolve_title_max_length


_SCHEMA = """
CREATE TABLE projects (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    default_branch TEXT DEFAULT 'main',
    public_item_prefix TEXT DEFAULT 'YOK',
    created_at TEXT NOT NULL DEFAULT '2026-06-30T00:00:00Z'
);
CREATE TABLE project_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id),
    type TEXT NOT NULL,
    settings TEXT DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE(project_id, type)
);
"""


@pytest.fixture
def policy_conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        apply_sql_script(conn, _SCHEMA)
        conn.execute(
            "INSERT INTO projects "
            "(id, slug, name, default_branch) "
            "VALUES (%s, %s, %s, %s)",
            (1, "yoke", "Yoke", "stage"),
        )
        conn.execute(
            "INSERT INTO projects "
            "(id, slug, name, default_branch) "
            "VALUES (%s, %s, %s, %s)",
            (2, "externalwebapp", "ExternalWebapp", "main"),
        )
        conn.commit()
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def _settings(conn: Any, project_id: int, cap_type: str) -> dict[str, Any]:
    row = conn.execute(
        "SELECT settings FROM project_capabilities WHERE project_id=%s AND type=%s",
        (project_id, cap_type),
    ).fetchone()
    assert row is not None
    return json.loads(row["settings"])


def test_ensure_creates_default_capabilities(policy_conn: Any) -> None:
    report = ensure_default_policy_capabilities(policy_conn, 1)
    policy_conn.commit()

    assert report["1"][PROJECT_POLICY_CAPABILITY]["created"] is True
    policy = _settings(policy_conn, 1, PROJECT_POLICY_CAPABILITY)
    assert policy["base_branch"] == "stage"
    assert policy["wip_cap"] == 30
    assert policy["disposable_generated_paths"] == []
    routing = _settings(policy_conn, 1, SESSION_ROUTING_CAPABILITY)
    assert routing["executor_default_lanes"]["claude*"] == "DARIUS"
    assert routing["executor_default_lanes"]["DARIUS"] == "DARIUS"
    assert "conduct" in routing["lane_paths"]["DARIUS"]
    assert "feed" in routing["lane_paths"]["DARIUS"]
    assert routing["process_offers"]["default"] is False
    assert routing["lane_metadata"] == {
        "DARIUS": {"label": "DARIUS", "glyph": "🐎"},
        "ALTMAN": {"label": "ALTMAN", "glyph": "👓"},
    }


def test_default_lane_paths_allow_dash_on_every_lane(policy_conn: Any) -> None:
    ensure_default_policy_capabilities(policy_conn, 1)
    policy_conn.commit()

    routing = _settings(policy_conn, 1, SESSION_ROUTING_CAPABILITY)
    for lane, paths in routing["lane_paths"].items():
        assert "dash" in paths, f"lane {lane} cannot run dash"


def test_ensure_repairs_missing_keys_without_overwriting(policy_conn: Any) -> None:
    policy_conn.execute(
        "INSERT INTO project_capabilities "
        "(project_id, type, settings, created_at) "
        "VALUES (%s, %s, %s, %s)",
        (
            2,
            PROJECT_POLICY_CAPABILITY,
            '{"base_branch":"release","wip_cap":9}',
            "2026-06-30T00:00:00Z",
        ),
    )
    policy_conn.commit()

    report = ensure_default_policy_capabilities(policy_conn, 2)
    policy_conn.commit()

    repaired = report["2"][PROJECT_POLICY_CAPABILITY]["repaired_keys"]
    assert "default_priority" in repaired
    assert "disposable_generated_paths" in repaired
    policy = _settings(policy_conn, 2, PROJECT_POLICY_CAPABILITY)
    assert policy["base_branch"] == "release"
    assert policy["wip_cap"] == 9
    assert policy["default_priority"] == "medium"
    assert policy["disposable_generated_paths"] == []


class TestResolveTitleMaxLength:
    def test_defaults_when_unset(self, policy_conn: Any) -> None:
        assert resolve_title_max_length(policy_conn, 1) == DEFAULT_TITLE_MAX_LENGTH

    def test_reads_a_stored_override(self, policy_conn: Any) -> None:
        set_project_policy_value(policy_conn, 1, "title_max_length", 42)
        policy_conn.commit()

        assert resolve_title_max_length(policy_conn, 1) == 42

    def test_projects_are_independent(self, policy_conn: Any) -> None:
        set_project_policy_value(policy_conn, 1, "title_max_length", 42)
        policy_conn.commit()

        assert resolve_title_max_length(policy_conn, 2) == DEFAULT_TITLE_MAX_LENGTH

    def test_resolves_by_slug_or_id_alike(self, policy_conn: Any) -> None:
        set_project_policy_value(policy_conn, 1, "title_max_length", 42)
        policy_conn.commit()

        assert resolve_title_max_length(policy_conn, "yoke") == 42
        assert resolve_title_max_length(policy_conn, 1) == 42

    def test_missing_project_falls_back_to_the_default(self, policy_conn: Any) -> None:
        assert resolve_title_max_length(policy_conn, 999999) == DEFAULT_TITLE_MAX_LENGTH
        assert resolve_title_max_length(policy_conn, None) == DEFAULT_TITLE_MAX_LENGTH
