"""Tests for the install bundle's managed-markdown + permissions layer."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import (
    install_bundle,
    install_bundle_managed,
    install_bundle_tree_sync,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGED_ROOT = REPO_ROOT / install_bundle_tree_sync.PACKAGED_TREE_REL
PYPROJECT = REPO_ROOT / "packages/yoke-core/pyproject.toml"


@pytest.fixture()
def conn():
    name = pg_testdb.create_test_database()
    db = pg_testdb.connect_test_database(name)
    try:
        db.execute(
            "CREATE TABLE projects ("
            "id INTEGER PRIMARY KEY, slug TEXT, name TEXT, "
            "default_branch TEXT DEFAULT 'main')"
        )
        db.execute("INSERT INTO projects (id, slug, name) VALUES (1, 'yoke', 'Yoke')")
        db.execute(
            "CREATE TABLE strategy_docs ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, slug TEXT NOT NULL, "
            "content TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, "
            "updated_by_actor_id INTEGER, archived_at TEXT, "
            "UNIQUE(project_id, slug))"
        )
        db.execute(
            "CREATE TABLE project_capabilities ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, type TEXT NOT NULL, "
            "settings TEXT DEFAULT '{}', created_at TEXT NOT NULL, "
            "UNIQUE(project_id, type))"
        )
        db.commit()
        yield db
    finally:
        db.close()
        pg_testdb.drop_test_database(name)


def test_packaged_snapshot_carries_root_source_files() -> None:
    # The doctrine files are FILES, not dirs, so the per-dir byte test in the
    # sibling suite never sees them; guard them explicitly so the product wheel
    # carries the same AGENTS.md/CODEX.md build_bundle extracts blocks from.
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        source = REPO_ROOT / rel
        packaged = PACKAGED_ROOT / rel
        assert packaged.is_file(), f"packaged snapshot missing root file {rel}"
        assert packaged.read_bytes() == source.read_bytes(), (
            f"snapshot drift for {rel}: "
            f"source_sha256={hashlib.sha256(source.read_bytes()).hexdigest()} "
            f"packaged_sha256={hashlib.sha256(packaged.read_bytes()).hexdigest()}"
        )


def test_pyproject_package_data_covers_root_source_files() -> None:
    # A root file added to INSTALL_BUNDLE_SOURCE_FILES but not globbed here would
    # be materialized into the snapshot yet omitted from the wheel.
    text = PYPROJECT.read_text("utf-8")
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        assert f'"{rel}"' in text, (
            f"pyproject package-data is missing a glob for root file {rel!r}"
        )


def test_bundle_ships_managed_markdown_and_permissions(conn) -> None:
    # A managed project needs the agnostic doctrine (AGENTS.md/CLAUDE.md) and the
    # Codex shell (CODEX.md) as marker-delimited blocks, plus the Claude tool
    # permissions — a fresh install otherwise has no rules files and prompts on
    # every Bash/Write/Edit/Monitor call. The block bodies are extracted from
    # this repo's OWN doctrine files (dogfooding), so what ships is what yoke runs.
    from yoke_contracts.project_contract.managed_block import (
        MANAGED_BLOCK_BEGIN,
        extract_block_body,
        render_block,
    )
    from yoke_core.domain.agents_render_claude import CLAUDE_PERMISSIONS

    bundle = install_bundle.build_bundle(1, conn)

    mm = bundle["managed_markdown"]
    assert set(mm["blocks"]) == {"doctrine", "codex_shell"}
    assert mm["targets"] == [
        {"path": "AGENTS.md", "block": "doctrine"},
        {"path": "CLAUDE.md", "block": "doctrine"},
        {"path": "CODEX.md", "block": "codex_shell"},
    ]
    for body in mm["blocks"].values():
        # Bodies are block *bodies*, not blocks — non-empty and marker-free.
        assert body and MANAGED_BLOCK_BEGIN not in body
    root = install_bundle.server_tree_root()
    agents_text = (root / "AGENTS.md").read_text("utf-8")
    authored = extract_block_body(agents_text)
    # The doctrine block leads with this repo's own authored block body...
    assert mm["blocks"]["doctrine"].startswith(authored)
    # ...and re-rendering that authored region reproduces the source file's block.
    assert render_block(authored) in agents_text
    codex_text = (root / "CODEX.md").read_text("utf-8")
    assert mm["blocks"]["codex_shell"] == extract_block_body(codex_text)

    perms = bundle["claude_settings_permissions"]
    assert perms["allow"] == list(CLAUDE_PERMISSIONS["allow"])
    assert perms["auto_memory_enabled"] is False


def test_doctrine_block_carries_the_generated_main_agent_packet(conn) -> None:
    # A managed project auto-loads its rules files and nothing else Yoke owns,
    # so the doctrine block is the only place a static packet reaches that
    # project's top-level session. Without it the session has no schema/API
    # truth and confabulates table and column names.
    from yoke_contracts.project_contract.managed_block import (
        MAIN_AGENT_PACKET_MARKER,
        carries_main_agent_packet,
    )
    from yoke_core.domain.schema_api_context import render_role_packet

    doctrine = install_bundle.build_bundle(1, conn)["managed_markdown"]["blocks"][
        "doctrine"
    ]

    assert carries_main_agent_packet(doctrine)
    packet_region = doctrine.split(MAIN_AGENT_PACKET_MARKER, 1)[1]
    assert render_role_packet("main_agent").rstrip() in packet_region
    # The packet is generated on the server, so machine-local advisories about
    # the server's own PATH and interpreter must not ride along to the client.
    assert "Yoke CLI not on PATH" not in doctrine


def test_doctrine_block_omits_the_packet_when_the_render_degrades(
    conn, monkeypatch,
) -> None:
    # A degraded render must leave the block packet-free rather than ship a
    # failure banner into a project's rules file: absent marker means the
    # project's own hooks deliver the packet, on the machine that can act on it.
    from yoke_contracts.project_contract.managed_block import (
        carries_main_agent_packet,
    )

    monkeypatch.setattr(
        install_bundle_managed, "render_main_agent_section", lambda: "",
    )
    doctrine = install_bundle.build_bundle(1, conn)["managed_markdown"]["blocks"][
        "doctrine"
    ]

    assert doctrine
    assert not carries_main_agent_packet(doctrine)


def test_bundle_files_stay_out_of_yoke_dir_except_docs(conn) -> None:
    bundle = install_bundle.build_bundle(1, conn)
    for entry in bundle["files"]:
        p = entry["path"]
        # Docs are the one yoke-authoritative .yoke/ subtree; all else stays out.
        assert p.startswith(".yoke/docs/") or not p.startswith(".yoke/")
        assert not p.startswith("/")
        assert ".." not in p.split("/")


def test_bundle_ships_universal_docs(conn) -> None:
    from yoke_core.domain.install_bundle_managed import DOCS_SOURCE

    bundle = install_bundle.build_bundle(1, conn)
    by_path = {e["path"]: e["content"] for e in bundle["files"]}
    # The relocated universal docs ship at .yoke/docs/ so installed skills and
    # agents resolve their references; a sampling must be present, non-empty.
    for rel in (
        "commands.md", "lifecycle.md", "db-reference.md",
        "db-reference/functions.md", "qa-platform/success-policy-schema.md",
    ):
        path = f"{DOCS_SOURCE}/{rel}"
        assert path in by_path, f"bundle missing shipped doc {path}"
        assert by_path[path].strip()
    # Every shipped doc byte-matches the server tree's .yoke/docs/ source.
    root = install_bundle.server_tree_root()
    for path, content in by_path.items():
        if path.startswith(f"{DOCS_SOURCE}/"):
            assert content == (root / path).read_text("utf-8")
