"""Portable governed-migration contract for hosted engine databases."""

from __future__ import annotations

import hashlib
from pathlib import Path
from types import SimpleNamespace

import pytest

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_core.domain.portable_migration import (
    PortableMigrationError,
    apply_manifest,
    load_packaged_modules,
    parse_manifest_text,
    row_counts,
)


ROOT = Path(__file__).resolve().parents[3]
MANIFEST = ROOT / "runtime/api/domain/migrations/events_actor_identity.migration.json"


def _old_events_schema(conn) -> None:
    apply_sql_script(
        conn,
        """
        CREATE TABLE events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id TEXT UNIQUE NOT NULL,
            user_id TEXT,
            actor_id INTEGER,
            envelope TEXT,
            created_at TEXT NOT NULL
        );
        CREATE INDEX idx_events_user_id ON events(user_id);
        INSERT INTO events
            (event_id, user_id, actor_id, envelope, created_at)
        VALUES
            ('portable-null', NULL, 7, '{"user_id":null}', '2026-07-11T12:00:00Z'),
            ('portable-empty', '', 8, NULL, '2026-07-11T12:00:01Z');
        """,
    )
    conn.commit()


def test_manifest_text_keeps_exact_digest_and_loads_packaged_module() -> None:
    raw = MANIFEST.read_text(encoding="utf-8")
    manifest = parse_manifest_text(raw)

    assert manifest.project == "yoke"
    assert manifest.module_identifiers == ("events_actor_identity",)
    assert manifest.affected_tables == ("events",)
    assert manifest.sha256 == hashlib.sha256(raw.encode("utf-8")).hexdigest()
    modules = load_packaged_modules(manifest)
    assert modules[0].__name__ == ("yoke_core.domain.migrations.events_actor_identity")


def test_portable_apply_uses_packaged_module_and_returns_secret_free_counts() -> None:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        _old_events_schema(conn)
        manifest = parse_manifest_text(MANIFEST.read_text(encoding="utf-8"))

        result = apply_manifest(conn, manifest)

        assert result.modules == ("events_actor_identity",)
        assert result.pre_row_counts == {"events": 2}
        assert result.post_row_counts == {"events": 2}
        assert result.baseline_verification == {
            "integrity_check": "ok",
            "fk_violations": 0,
            "post_row_counts": {"events": 2},
            "pre_row_counts": {"events": 2},
            "count_preserving": False,
            "failures": [],
        }
        assert row_counts(conn, ("events",)) == {"events": 2}
        columns = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = 'events'"
        ).fetchall()
        assert "user_id" not in {row[0] for row in columns}
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_portable_apply_refuses_identity_without_dropping_schema() -> None:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        _old_events_schema(conn)
        conn.execute(
            "UPDATE events SET user_id = %s WHERE event_id = %s",
            ("platform-user-1", "portable-null"),
        )
        conn.commit()
        manifest = parse_manifest_text(MANIFEST.read_text(encoding="utf-8"))

        with pytest.raises(AssertionError, match="has 1 non-empty values"):
            apply_manifest(conn, manifest)

        columns = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = 'events'"
        ).fetchall()
        assert "user_id" in {row[0] for row in columns}
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_portable_manifest_refuses_untracked_theorem_shape() -> None:
    with pytest.raises(PortableMigrationError, match="keys invalid"):
        parse_manifest_text('{"version":1,"project":"yoke","extra":true}')


def test_row_counts_refuses_non_identifier_table() -> None:
    class NeverExecutes:
        def execute(self, _query):
            raise AssertionError("unsafe table reached SQL execution")

    with pytest.raises(PortableMigrationError, match="bare SQL identifier"):
        row_counts(NeverExecutes(), ("events; DROP TABLE events",))


def test_packaged_module_invariants_hook_is_optional(monkeypatch) -> None:
    manifest = parse_manifest_text(MANIFEST.read_text(encoding="utf-8"))
    module = SimpleNamespace(__name__="package.optional", apply=lambda _conn: None)
    monkeypatch.setattr(
        "yoke_core.domain.portable_migration.importlib.import_module",
        lambda _name: module,
    )

    assert load_packaged_modules(manifest) == (module,)


def test_verification_failure_carries_secret_free_baseline_evidence(
    monkeypatch,
) -> None:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        _old_events_schema(conn)
        manifest = parse_manifest_text(MANIFEST.read_text(encoding="utf-8"))

        def invariant(_conn):
            raise AssertionError("synthetic invariant refusal")

        module = SimpleNamespace(
            __name__="package.refusing",
            apply=lambda _conn: None,
            invariants=invariant,
        )
        monkeypatch.setattr(
            "yoke_core.domain.portable_migration.load_packaged_modules",
            lambda _manifest: (module,),
        )

        with pytest.raises(
            PortableMigrationError, match="synthetic invariant refusal"
        ) as excinfo:
            apply_manifest(conn, manifest)

        assert excinfo.value.baseline_verification == {
            "integrity_check": "ok",
            "fk_violations": 0,
            "post_row_counts": {"events": 2},
            "pre_row_counts": {"events": 2},
            "count_preserving": False,
            "failures": [],
        }
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)
