"""Hard-cutover migration coverage for canonical work-claim scope."""

from __future__ import annotations

import psycopg
import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import migrations as migration_history_package
from yoke_core.domain.migration_history import (
    history_dir,
    load_migration_module,
    ordered_entries,
)
from yoke_core.domain.migration_serving_version import declared_minimum
from yoke_core.domain.schema_common import _get_columns
from yoke_core.domain.schema_init_columns import apply_work_claim_scope_column

ENTRY_NAME = "0020_work_claim_scope"
FINAL_COLUMNS = {
    "id",
    "session_id",
    "target_kind",
    "scope",
    "claim_type",
    "claimed_at",
    "last_heartbeat",
    "released_at",
    "release_reason",
    "reason",
    "reason_intent",
    "release_reason_intent",
}


def _entry():
    directory = history_dir(migration_history_package)
    record = next(
        candidate for candidate in ordered_entries(directory)
        if candidate.name == ENTRY_NAME
    )
    return load_migration_module(directory / f"{record.name}.py", record.name)


entry = _entry()


@pytest.fixture
def specialized_db():
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    conn.execute(
        """
        CREATE TABLE work_claims (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            target_kind TEXT NOT NULL,
            item_id INTEGER,
            epic_id INTEGER,
            task_num INTEGER,
            process_key TEXT,
            conflict_group TEXT,
            steering_project_id INTEGER,
            steering_strategy_doc_slugs TEXT,
            owner_kind TEXT,
            owner_item_id INTEGER,
            owner_session_id TEXT,
            owner_work_claim_id INTEGER,
            registered_by_actor_id INTEGER,
            registered_by_session_id TEXT,
            claim_type TEXT NOT NULL DEFAULT 'exclusive',
            claimed_at TEXT NOT NULL,
            last_heartbeat TEXT NOT NULL,
            released_at TEXT,
            release_reason TEXT,
            reason TEXT,
            reason_intent TEXT,
            release_reason_intent TEXT
        )
        """
    )
    conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, item_id, claimed_at, last_heartbeat) "
        "VALUES ('item-session', 'item', 10, 't1', 't1')"
    )
    conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, process_key, conflict_group, claimed_at, "
        "last_heartbeat) VALUES "
        "('process-session', 'process', 'DOCTOR', 'doctor:yoke', 't2', 't2')"
    )
    conn.execute(
        "INSERT INTO work_claims "
        "(session_id, target_kind, steering_project_id, owner_kind, "
        "owner_session_id, registered_by_actor_id, registered_by_session_id, "
        "claimed_at, last_heartbeat) VALUES "
        "('steering-session', 'steering', 7, 'session', 'steering-session', "
        "2, 'steering-session', 't3', 't3')"
    )
    conn.commit()
    apply_work_claim_scope_column(conn)
    try:
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_cutover_backfills_every_kind_and_drops_specialized_columns(
    specialized_db,
) -> None:
    entry.apply(specialized_db)
    entry.invariants(specialized_db)

    assert set(_get_columns(specialized_db, "work_claims")) == FINAL_COLUMNS
    rows = specialized_db.execute(
        "SELECT target_kind, scope FROM work_claims ORDER BY id"
    ).fetchall()
    assert [(row[0], row[1]) for row in rows] == [
        ("item", '{"item_id":10}'),
        ("process", '{"conflict_group":"doctor:yoke","process_key":"DOCTOR"}'),
        ("steering", '{"project_id":7}'),
    ]


def test_cutover_enforces_active_scope_and_process_conflict_uniqueness(
    specialized_db,
) -> None:
    entry.apply(specialized_db)
    specialized_db.commit()
    with pytest.raises(psycopg.errors.UniqueViolation):
        specialized_db.execute(
            "INSERT INTO work_claims "
            "(session_id, target_kind, scope, claimed_at, last_heartbeat) "
            "VALUES ('other', 'item', '{\"item_id\":10}', 't4', 't4')"
        )
    specialized_db.rollback()

    with pytest.raises(psycopg.errors.UniqueViolation):
        specialized_db.execute(
            "INSERT INTO work_claims "
            "(session_id, target_kind, scope, claimed_at, last_heartbeat) "
            "VALUES ('other', 'process', "
            "'{\"conflict_group\":\"doctor:yoke\",\"process_key\":\"DOCTOR-ALT\"}', "
            "'t4', 't4')"
        )
    specialized_db.rollback()


def test_cutover_is_idempotent_and_declares_serving_floor(specialized_db) -> None:
    entry.apply(specialized_db)
    entry.apply(specialized_db)
    entry.invariants(specialized_db)
    assert declared_minimum(entry) == entry.MINIMUM_SERVING_VERSION
