"""Unit tests for the ``workflow_item.epic_task.*`` and
``workflow_item.epic_progress_note.append`` handlers.

Each test constructs a synthetic :class:`FunctionCallRequest`, patches
:func:`yoke_core.domain.handlers.workflow_item_epic_task._open_connection`
(and the progress-note module sibling) to return a disposable
Postgres test-database connection, and asserts the returned
:class:`HandlerOutcome` shape.
"""

from __future__ import annotations

import unittest
from contextlib import contextmanager
from typing import Any
from unittest.mock import patch

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_core.domain.handlers import (
    workflow_item_epic_progress_note as progress_handler,
    workflow_item_epic_task as task_handler,
)
from yoke_contracts.api.function_call import (
    ActorContext,
    FunctionCallRequest,
    TargetRef,
)


_TASKS_SCHEMA = """
CREATE TABLE epic_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    title TEXT,
    worktree TEXT,
    context_estimate TEXT,
    dependencies TEXT,
    status TEXT DEFAULT 'planning',
    dispatch_attempts INTEGER DEFAULT 0,
    body TEXT,
    github_issue TEXT,
    branch TEXT,
    worktree_path TEXT,
    blocked_by TEXT,
    max_attempts INTEGER DEFAULT 5,
    agent_id TEXT,
    last_heartbeat TEXT,
    UNIQUE(epic_id, task_num)
);
CREATE TABLE epic_progress_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    note_num INTEGER NOT NULL,
    body TEXT,
    commit_hash TEXT,
    synced_to_github INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    UNIQUE(epic_id, task_num, note_num)
);
"""


def _seed_conn() -> Any:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name), name,
    )
    apply_sql_script(conn, _TASKS_SCHEMA)
    conn.commit()
    return conn


def _add_task(conn, epic_id, task_num, title, **kwargs):
    conn.execute(
        "INSERT INTO epic_tasks (epic_id, task_num, title, worktree, "
        "context_estimate, dependencies, status, body) VALUES "
        "(%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            str(epic_id), task_num, title,
            kwargs.get("worktree", ""), kwargs.get("context_estimate", ""),
            kwargs.get("dependencies", ""), kwargs.get("status", "planning"),
            kwargs.get("body", ""),
        ),
    )
    conn.commit()


@contextmanager
def _conn_cm(conn):
    """Wrap a connection so the handler's ``with`` block does not close it."""
    try:
        yield conn
    finally:
        # Tests own the connection lifecycle.
        pass


def _build_request(function: str, *, epic_id=100, task_num=1, payload=None) -> FunctionCallRequest:
    return FunctionCallRequest(
        function=function,
        actor=ActorContext(actor_id="test", session_id="s-1"),
        target=TargetRef(kind="epic_task", epic_id=epic_id, task_num=task_num),
        payload=payload or {},
    )


# ---------------------------------------------------------------------------
# epic_task handlers
# ---------------------------------------------------------------------------


class TestBodyReplaceHandler(unittest.TestCase):
    def test_writes_body_and_returns_line_counts(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first", body="line1\nline2")
        request = _build_request(
            "workflow_item.epic_task.body_replace",
            payload={"body": "one\ntwo\nthree"},
        )
        # Patch epic_task_crud.task_update_body to skip the sync_task_body branch.
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            with patch.object(task_handler.epic_task_crud, "task_update_body",
                              side_effect=lambda c, e, t, b, **kw: c.execute(
                                  "UPDATE epic_tasks SET body=%s "
                                  "WHERE epic_id=%s AND task_num=%s",
                                  (b, str(e), t)) or "ok"):
                outcome = task_handler.handle_body_replace(request)
        assert outcome.primary_success is True
        assert outcome.error is None
        assert outcome.result_payload["old_line_count"] == 2
        assert outcome.result_payload["new_line_count"] == 3

    def test_not_found(self):
        conn = _seed_conn()
        request = _build_request(
            "workflow_item.epic_task.body_replace",
            payload={"body": "x"},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_body_replace(request)
        assert outcome.primary_success is False
        assert outcome.error.code == "target_not_found"


class TestSplitHandler(unittest.TestCase):
    def test_splits_parent_into_children(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "parent")
        request = _build_request(
            "workflow_item.epic_task.split",
            payload={"children": [
                {"title": "child-A"}, {"title": "child-B"},
            ]},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_split(request)
        assert outcome.primary_success is True
        assert outcome.result_payload["new_task_nums"] == [2, 3]

    def test_target_not_found(self):
        conn = _seed_conn()
        request = _build_request(
            "workflow_item.epic_task.split",
            task_num=99,
            payload={"children": [{"title": "child"}]},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_split(request)
        assert outcome.error.code == "target_not_found"


class TestReassignHandler(unittest.TestCase):
    def test_updates_worktree(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first", worktree="old-wt")
        request = _build_request(
            "workflow_item.epic_task.reassign",
            payload={"new_worktree": "new-wt"},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_reassign(request)
        assert outcome.primary_success is True
        assert outcome.result_payload["old_worktree"] == "old-wt"
        assert outcome.result_payload["new_worktree"] == "new-wt"

    def test_not_found(self):
        conn = _seed_conn()
        request = _build_request(
            "workflow_item.epic_task.reassign",
            task_num=99,
            payload={"new_worktree": "new-wt"},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_reassign(request)
        assert outcome.error.code == "target_not_found"


class TestAddHandler(unittest.TestCase):
    def test_appends_task(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        # add omits task_num — payload provides the rest.
        request = FunctionCallRequest(
            function="workflow_item.epic_task.add",
            actor=ActorContext(actor_id="test", session_id="s-1"),
            target=TargetRef(kind="epic_task", epic_id=100),
            payload={"title": "added", "body": "body"},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_add(request)
        assert outcome.primary_success is True
        assert outcome.result_payload["task_num"] == 2
        assert outcome.result_payload["title"] == "added"

    def test_rejects_empty_title(self):
        conn = _seed_conn()
        request = FunctionCallRequest(
            function="workflow_item.epic_task.add",
            actor=ActorContext(actor_id="test", session_id="s-1"),
            target=TargetRef(kind="epic_task", epic_id=100),
            payload={"title": ""},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_add(request)
        assert outcome.error.code == "invalid_payload"


class TestRemoveHandler(unittest.TestCase):
    def test_removes_and_cascades(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        _add_task(conn, 100, 2, "depends_on_1", dependencies="1")
        request = _build_request(
            "workflow_item.epic_task.remove",
            payload={"reason": "no longer needed"},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_remove(request)
        assert outcome.primary_success is True
        cascade = outcome.result_payload["cascade_updated"]
        # Allow either int or string keys (pydantic dump path varies).
        normalized = {int(k): v for k, v in cascade.items()}
        assert normalized == {2: ""}

    def test_not_found(self):
        conn = _seed_conn()
        request = _build_request(
            "workflow_item.epic_task.remove",
            task_num=99,
            payload={"reason": ""},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_remove(request)
        assert outcome.error.code == "target_not_found"


class TestMetadataUpdateHandler(unittest.TestCase):
    def test_updates_fields(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        request = _build_request(
            "workflow_item.epic_task.metadata_update",
            payload={"fields": {"title": "renamed", "github_issue": "#42"}},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_metadata_update(request)
        assert outcome.primary_success is True
        assert outcome.result_payload["updated_fields"]["title"] == "renamed"

    def test_unknown_field_rejected(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        request = _build_request(
            "workflow_item.epic_task.metadata_update",
            payload={"fields": {"status": "planned"}},
        )
        with patch.object(task_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = task_handler.handle_metadata_update(request)
        assert outcome.error.code == "invalid_payload"


# ---------------------------------------------------------------------------
# epic_progress_note handler
# ---------------------------------------------------------------------------


class TestProgressNoteAppendHandler(unittest.TestCase):
    def test_inserts_row(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        request = _build_request(
            "workflow_item.epic_progress_note.append",
            payload={"note_num": 1, "body": "first note", "commit_hash": "abc1234"},
        )
        # Patch the epic_review delegate so we don't reach into the broader stack.
        with patch.object(progress_handler, "_open_connection", lambda: _conn_cm(conn)):
            with patch.object(
                progress_handler.epic, "progress_note_insert",
                side_effect=lambda c, e, t, n, b, h="": c.execute(
                    "INSERT INTO epic_progress_notes "
                    "(epic_id, task_num, note_num, body, commit_hash, created_at) "
                    "VALUES (%s, %s, %s, %s, %s, '2026-01-01T00:00:00Z')",
                    (str(e), t, n, b, h),
                ) or "ok",
            ):
                outcome = progress_handler.handle_append(request)
        assert outcome.primary_success is True
        assert outcome.result_payload["note_num"] == 1
        rows = conn.execute(
            "SELECT note_num, commit_hash FROM epic_progress_notes "
            "WHERE epic_id='100' AND task_num=1"
        ).fetchall()
        assert len(rows) == 1
        assert rows[0]["commit_hash"] == "abc1234"

    def test_not_found(self):
        conn = _seed_conn()
        request = _build_request(
            "workflow_item.epic_progress_note.append",
            task_num=99,
            payload={"note_num": 1, "body": "x"},
        )
        with patch.object(progress_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = progress_handler.handle_append(request)
        assert outcome.error.code == "target_not_found"

    def test_invalid_note_num(self):
        conn = _seed_conn()
        _add_task(conn, 100, 1, "first")
        request = _build_request(
            "workflow_item.epic_progress_note.append",
            payload={"note_num": 0, "body": "x"},
        )
        with patch.object(progress_handler, "_open_connection", lambda: _conn_cm(conn)):
            outcome = progress_handler.handle_append(request)
        assert outcome.error.code == "invalid_payload"


if __name__ == "__main__":
    unittest.main()
