"""Tests for DB-backed project policy capability defaults."""

from __future__ import annotations

import json
from collections.abc import Iterator
from typing import Any

import pytest

from runtime.api.domain.migrations import project_policy_capabilities as migration
from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_core.domain.project_policy_capabilities import (
    PROJECT_POLICY_CAPABILITY,
    SESSION_ROUTING_CAPABILITY,
    ensure_default_policy_capabilities,
)


_SCHEMA = """
CREATE TABLE projects (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    default_branch TEXT DEFAULT 'main',
    public_item_prefix TEXT DEFAULT 'YOK',
    created_at TEXT NOT NULL DEFAULT '2026-06-30T00:00:00Z'
);
CREATE TABLE project_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id),
    type TEXT NOT NULL,
    settings TEXT DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE(project_id, type)
);
"""


@pytest.fixture
def policy_conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        apply_sql_script(conn, _SCHEMA)
        conn.execute(
            "INSERT INTO projects "
            "(id, slug, name, default_branch) "
            "VALUES (%s, %s, %s, %s)",
            (1, "yoke", "Yoke", "stage"),
        )
        conn.execute(
            "INSERT INTO projects "
            "(id, slug, name, default_branch) "
            "VALUES (%s, %s, %s, %s)",
            (2, "buzz", "Buzz", "main"),
        )
        conn.commit()
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def _settings(conn: Any, project_id: int, cap_type: str) -> dict[str, Any]:
    row = conn.execute(
        "SELECT settings FROM project_capabilities "
        "WHERE project_id=%s AND type=%s",
        (project_id, cap_type),
    ).fetchone()
    assert row is not None
    return json.loads(row["settings"])


def test_ensure_creates_default_capabilities(policy_conn: Any) -> None:
    report = ensure_default_policy_capabilities(policy_conn, 1)
    policy_conn.commit()

    assert report["1"][PROJECT_POLICY_CAPABILITY]["created"] is True
    policy = _settings(policy_conn, 1, PROJECT_POLICY_CAPABILITY)
    assert policy["base_branch"] == "stage"
    assert policy["wip_cap"] == 5
    routing = _settings(policy_conn, 1, SESSION_ROUTING_CAPABILITY)
    assert routing["executor_default_lanes"]["claude*"] == "DARIUS"
    assert routing["executor_default_lanes"]["DARIUS"] == "DARIUS"
    assert "conduct" in routing["lane_paths"]["DARIUS"]
    assert "feed" in routing["lane_paths"]["DARIUS"]
    assert routing["process_offers"]["default"] is False


def test_ensure_repairs_missing_keys_without_overwriting(policy_conn: Any) -> None:
    conn = policy_conn
    conn.execute(
        "INSERT INTO project_capabilities "
        "(project_id, type, settings, created_at) "
        "VALUES (%s, %s, %s, %s)",
        (
            2,
            PROJECT_POLICY_CAPABILITY,
            '{"base_branch":"release","wip_cap":9}',
            "2026-06-30T00:00:00Z",
        ),
    )
    conn.commit()

    report = ensure_default_policy_capabilities(conn, 2)
    conn.commit()

    repaired = report["2"][PROJECT_POLICY_CAPABILITY]["repaired_keys"]
    assert "default_priority" in repaired
    policy = _settings(conn, 2, PROJECT_POLICY_CAPABILITY)
    assert policy["base_branch"] == "release"
    assert policy["wip_cap"] == 9
    assert policy["default_priority"] == "medium"


def test_migration_repairs_every_project(policy_conn: Any) -> None:
    migration.apply(policy_conn)
    migration.apply(policy_conn)
    policy_conn.commit()

    migration.invariants(policy_conn)
    assert _settings(policy_conn, 1, PROJECT_POLICY_CAPABILITY)
    assert _settings(policy_conn, 2, SESSION_ROUTING_CAPABILITY)
