"""Tests for the install bundle's managed-markdown + permissions layer."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_core.domain import (
    install_bundle,
    install_bundle_managed,
    install_bundle_tree_sync,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGED_ROOT = REPO_ROOT / install_bundle_tree_sync.PACKAGED_TREE_REL
PYPROJECT = REPO_ROOT / "packages/yoke-core/pyproject.toml"


@pytest.fixture()
def conn():
    name = pg_testdb.create_test_database()
    db = pg_testdb.connect_test_database(name)
    try:
        db.execute(
            "CREATE TABLE projects ("
            "id INTEGER PRIMARY KEY, slug TEXT, name TEXT, "
            "default_branch TEXT DEFAULT 'main')"
        )
        db.execute("INSERT INTO projects (id, slug, name) VALUES (1, 'yoke', 'Yoke')")
        db.execute(
            "CREATE TABLE strategy_docs ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, slug TEXT NOT NULL, "
            "content TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, "
            "updated_by_actor_id INTEGER, archived_at TEXT, "
            "UNIQUE(project_id, slug))"
        )
        db.execute(
            "CREATE TABLE project_capabilities ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, type TEXT NOT NULL, "
            "settings TEXT DEFAULT '{}', created_at TEXT NOT NULL, "
            "UNIQUE(project_id, type))"
        )
        db.commit()
        yield db
    finally:
        db.close()
        pg_testdb.drop_test_database(name)


def test_packaged_snapshot_carries_root_source_files() -> None:
    # The doctrine files are FILES, not dirs, so the per-dir byte test in the
    # sibling suite never sees them; guard them explicitly so the product wheel
    # carries the same AGENTS.md/CODEX.md build_bundle extracts blocks from.
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        source = REPO_ROOT / rel
        packaged = PACKAGED_ROOT / rel
        assert packaged.is_file(), f"packaged snapshot missing root file {rel}"
        assert packaged.read_bytes() == source.read_bytes(), (
            f"snapshot drift for {rel}: "
            f"source_sha256={hashlib.sha256(source.read_bytes()).hexdigest()} "
            f"packaged_sha256={hashlib.sha256(packaged.read_bytes()).hexdigest()}"
        )


def test_pyproject_package_data_covers_root_source_files() -> None:
    # A root file added to INSTALL_BUNDLE_SOURCE_FILES but not globbed here would
    # be materialized into the snapshot yet omitted from the wheel.
    text = PYPROJECT.read_text("utf-8")
    for rel in install_bundle_managed.INSTALL_BUNDLE_SOURCE_FILES:
        assert f'"{rel}"' in text, (
            f"pyproject package-data is missing a glob for root file {rel!r}"
        )


def test_bundle_ships_managed_markdown_and_permissions(conn) -> None:
    # A managed project needs the agnostic doctrine (AGENTS.md/CLAUDE.md) and the
    # Codex shell (CODEX.md) as marker-delimited blocks, plus the Claude tool
    # permissions — a fresh install otherwise has no rules files and prompts on
    # every Bash/Write/Edit/Monitor call. The block bodies are extracted from
    # this repo's OWN doctrine files (dogfooding), so what ships is what yoke runs.
    from yoke_contracts.project_contract.managed_block import (
        MANAGED_BLOCK_BEGIN,
        extract_block_body,
        render_block,
    )
    from yoke_core.domain.agents_render_claude import CLAUDE_PERMISSIONS

    bundle = install_bundle.build_bundle(1, conn)

    mm = bundle["managed_markdown"]
    assert set(mm["blocks"]) == {"doctrine", "codex_shell"}
    assert mm["targets"] == [
        {"path": "AGENTS.md", "block": "doctrine"},
        {"path": "CLAUDE.md", "block": "doctrine"},
        {"path": "CODEX.md", "block": "codex_shell"},
    ]
    for body in mm["blocks"].values():
        # Bodies are block *bodies*, not blocks — non-empty and marker-free.
        assert body and MANAGED_BLOCK_BEGIN not in body
    root = install_bundle.server_tree_root()
    agents_text = (root / "AGENTS.md").read_text("utf-8")
    assert mm["blocks"]["doctrine"] == extract_block_body(agents_text)
    # Re-rendering the shipped body reproduces the source file's exact block.
    assert render_block(mm["blocks"]["doctrine"]) in agents_text

    perms = bundle["claude_settings_permissions"]
    assert perms["allow"] == list(CLAUDE_PERMISSIONS["allow"])
    assert perms["auto_memory_enabled"] is False
