"""Tests for ``projects_capabilities_settings`` — capability settings CAS.

Exercises the get/CAS-write/merge family that
:mod:`yoke_core.domain.projects_capabilities_settings` owns against the
active Postgres authority, plus the parser/dispatch wiring through
``yoke_core.domain.projects`` main. The interleaved-writer cases pin the
field-note 12544/12545/12547 lost-update regression: a stale base (or a
lost create race) must get the typed conflict, never silent loss. Mirrors
the fixture shape of ``test_projects_capabilities.py``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterator

import pytest

from yoke_core.domain import db_backend
from yoke_core.domain import projects_capabilities_settings as pcs
from yoke_core.domain.settings_cas import SettingsConflictError
from runtime.api.fixtures.file_test_db import init_test_db


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _apply_capability_schema() -> None:
    """Create ``projects`` + ``project_capabilities`` (canonical columns)."""
    conn = db_backend.connect()
    try:
        conn.execute(
            """
            CREATE TABLE projects (
                id BIGINT PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                public_item_prefix TEXT NOT NULL DEFAULT 'YOK'
            )
            """
        )
        conn.execute(
            """
            INSERT INTO projects (id, slug, name, public_item_prefix)
            VALUES (1, 'yoke', 'Yoke', 'YOK'), (2, 'externalwebapp', 'ExternalWebapp', 'EXT')
            """
        )
        conn.execute(
            """
            CREATE TABLE project_capabilities (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id BIGINT NOT NULL REFERENCES projects(id),
                type TEXT NOT NULL,
                settings TEXT DEFAULT '{}',
                verified_at TEXT,
                created_at TEXT NOT NULL,
                UNIQUE(project_id, type)
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture
def cap_db(tmp_path: Path) -> Iterator[str]:
    """Per-test Postgres DB with the capability tables applied."""
    with init_test_db(tmp_path, apply_schema=_apply_capability_schema) as db_path:
        yield db_path


def _settings(db_path: str, cap_type: str = "docker") -> dict:
    raw = pcs.cmd_capability_get_settings("yoke", cap_type, db_path=db_path)
    assert raw is not None
    return json.loads(raw)


# ---------------------------------------------------------------------------
# Settings CRUD (CAS-protected)
# ---------------------------------------------------------------------------


class TestCapabilitySettings:
    def test_create_then_get_round_trip(self, cap_db: str) -> None:
        msg = pcs.cmd_capability_set_settings(
            "yoke", "health-endpoint", '{"url":"https://x"}',
            create=True, db_path=cap_db,
        )
        assert "health-endpoint" in msg
        assert pcs.cmd_capability_get_settings(
            "yoke", "health-endpoint", db_path=cap_db
        ) == '{"url":"https://x"}'

    def test_get_missing_returns_none(self, cap_db: str) -> None:
        assert pcs.cmd_capability_get_settings(
            "yoke", "absent", db_path=cap_db
        ) is None

    def test_cas_update_replaces_in_place(self, cap_db: str) -> None:
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"a"}', create=True, db_path=cap_db
        )
        base = pcs.cmd_capability_get_settings("yoke", "docker", db_path=cap_db)
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"b"}',
            base_settings_json=base, db_path=cap_db,
        )
        assert _settings(cap_db) == {"host": "b"}

    def test_set_without_base_or_new_is_usage_error(self, cap_db: str) -> None:
        with pytest.raises(ValueError, match="--base is required"):
            pcs.cmd_capability_set_settings(
                "yoke", "docker", "{}", db_path=cap_db
            )

    def test_set_with_base_and_new_is_usage_error(self, cap_db: str) -> None:
        with pytest.raises(ValueError, match="mutually exclusive"):
            pcs.cmd_capability_set_settings(
                "yoke", "docker", "{}",
                base_settings_json="{}", create=True, db_path=cap_db,
            )

    def test_set_non_object_json_is_loud(self, cap_db: str) -> None:
        with pytest.raises(ValueError, match="must be a JSON object"):
            pcs.cmd_capability_set_settings(
                "yoke", "docker", "[1]", create=True, db_path=cap_db
            )

# ---------------------------------------------------------------------------
# Lost-update regression: interleaved writers
# ---------------------------------------------------------------------------


class TestInterleavedWriters:
    def test_second_full_write_on_stale_base_conflicts(
        self, cap_db: str
    ) -> None:
        # A reads, B reads the same document, A writes, B writes — the
        # incident shape. B must get the typed conflict, never silent loss.
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"orig"}', create=True, db_path=cap_db
        )
        base_a = pcs.cmd_capability_get_settings("yoke", "docker", db_path=cap_db)
        base_b = pcs.cmd_capability_get_settings("yoke", "docker", db_path=cap_db)
        a_doc = '{"host": "orig", "registry": "ecr"}'
        pcs.cmd_capability_set_settings(
            "yoke", "docker", a_doc,
            base_settings_json=base_a, db_path=cap_db,
        )
        with pytest.raises(SettingsConflictError, match="settings_conflict"):
            pcs.cmd_capability_set_settings(
                "yoke", "docker", '{"host": "clobber"}',
                base_settings_json=base_b, db_path=cap_db,
            )
        # A's write survived untouched; B's clobber never landed.
        assert pcs.cmd_capability_get_settings(
            "yoke", "docker", db_path=cap_db
        ) == a_doc

    def test_create_race_second_new_conflicts(self, cap_db: str) -> None:
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"first"}', create=True, db_path=cap_db
        )
        with pytest.raises(SettingsConflictError, match="already exists"):
            pcs.cmd_capability_set_settings(
                "yoke", "docker", '{"host":"second"}',
                create=True, db_path=cap_db,
            )
        assert _settings(cap_db) == {"host": "first"}

    def test_base_against_absent_row_conflicts(self, cap_db: str) -> None:
        with pytest.raises(SettingsConflictError, match="no row"):
            pcs.cmd_capability_set_settings(
                "yoke", "ghost", "{}",
                base_settings_json='{"a":1}', db_path=cap_db,
            )


# ---------------------------------------------------------------------------
# Key-path merge (the collision-avoidance convenience)
# ---------------------------------------------------------------------------


class TestMergeSettings:
    def test_merge_creates_absent_capability(self, cap_db: str) -> None:
        msg = pcs.cmd_capability_merge_settings(
            "yoke", "docker", {"host": "a"}, db_path=cap_db
        )
        assert "docker" in msg
        assert _settings(cap_db) == {"host": "a"}

    def test_sequential_key_merges_compose(self, cap_db: str) -> None:
        pcs.cmd_capability_merge_settings(
            "yoke", "docker", {"host": "a"}, db_path=cap_db
        )
        pcs.cmd_capability_merge_settings(
            "yoke", "docker", {"runtime.network": "bridge"}, db_path=cap_db
        )
        final = _settings(cap_db)
        assert final["host"] == "a"
        assert final["runtime"]["network"] == "bridge"

    def test_merge_retries_once_when_base_moves(
        self, cap_db: str, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"a"}', create=True, db_path=cap_db
        )
        real_read = pcs._read_settings_text
        calls = {"n": 0}

        def contended_read(conn, project_id, cap_type):
            calls["n"] += 1
            if calls["n"] == 1:
                return '{"host":"stale"}'
            return real_read(conn, project_id, cap_type)

        monkeypatch.setattr(pcs, "_read_settings_text", contended_read)
        pcs.cmd_capability_merge_settings(
            "yoke", "docker", {"registry": "ecr"}, db_path=cap_db
        )
        final = _settings(cap_db)
        assert final == {"host": "a", "registry": "ecr"}
        assert calls["n"] >= 2

    def test_merge_conflict_after_retry_is_typed(
        self, cap_db: str, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        pcs.cmd_capability_set_settings(
            "yoke", "docker", '{"host":"a"}', create=True, db_path=cap_db
        )
        monkeypatch.setattr(
            pcs,
            "_read_settings_text",
            lambda conn, project_id, cap_type: '{"host":"stale"}',
        )
        with pytest.raises(SettingsConflictError, match="settings_conflict"):
            pcs.cmd_capability_merge_settings(
                "yoke", "docker", {"registry": "ecr"}, db_path=cap_db
            )
