"""Vocabulary + activation-filter tests for the ``coordination_only`` gate.

Covers two slices:

Task 001 — vocabulary:
* ``GatePoint.COORDINATION_ONLY`` enum membership and ``from_db`` resolution.
* ``is_coordination_only`` / ``is_activation_gate`` predicate behavior.
* ``shepherd_dependency.VALID_GATE_POINTS`` accepts the new value.
* ``shepherd_dependency._DEFAULT_SATISFACTION`` maps ``coordination_only``
  to ``fact:merged``.
* ``cmd_dependency_add`` writes a ``coordination_only`` row with the
  defaulted satisfaction against a fresh in-memory schema.

Task 002 — activation-filter regression:
* ``evaluate_batch_gates(gate_point='activation')`` ignores
  ``coordination_only`` rows.
* ``evaluate_batch_gates(gate_point='coordination_only')`` returns them.
* ``evaluate_item_gate(gate_point='activation')`` is not blocked by an
  item whose only edge is ``coordination_only``.
* ``compute_frontier``'s ``_UNBLOCKS_COUNT_SQL`` count is unchanged when
  a ``coordination_only`` row is added — the SQL hard-codes
  ``gate_point = 'activation'``.

These regression tests pin existing correct behavior; both
``dependency_planning.py`` and ``frontier_compute.py`` are intentionally
unchanged for Task 002 (architect-verified zero-line diff).
"""
from __future__ import annotations

from typing import Any, Iterator

import pytest

from runtime.api.fixtures import pg_testdb

from yoke_core.domain import shepherd_dependency
from yoke_core.domain.dependency_planning import (
    evaluate_batch_gates,
    evaluate_item_gate,
)
from yoke_core.domain.dependency_types import (
    GatePoint,
    is_activation_gate,
    is_coordination_only,
)
from yoke_core.domain.frontier_compute import compute_frontier
from yoke_core.domain.shepherd_dependency import cmd_dependency_add
from runtime.api.frontier_test_helpers import (
    insert_dep,
    insert_item,
    make_test_db,
)


@pytest.fixture
def conn() -> Iterator[Any]:
    name = pg_testdb.create_test_database()
    c = pg_testdb.connect_test_database(name)
    try:
        c.execute(
            "CREATE TABLE item_dependencies ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "dependent_item TEXT NOT NULL, "
            "blocking_item TEXT NOT NULL, "
            "gate_point TEXT NOT NULL DEFAULT 'activation', "
            "satisfaction TEXT NOT NULL DEFAULT 'status:done', "
            "source TEXT NOT NULL, session_id INTEGER, "
            "rationale TEXT NOT NULL DEFAULT '', "
            "evidence_json TEXT NOT NULL DEFAULT '{}', "
            "created_at TEXT NOT NULL, "
            "UNIQUE(dependent_item, blocking_item, gate_point))"
        )
        # Empty stub so the edge-write refresh hook's blocked-claims probe
        # finds the table; a failed probe would poison the Postgres
        # transaction for the assertions that follow.
        c.execute(
            "CREATE TABLE path_claims ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "item_id INTEGER, state TEXT NOT NULL DEFAULT 'planned', "
            "blocked_reason TEXT, integration_target TEXT)"
        )
        c.commit()
        yield c
    finally:
        c.close()
        pg_testdb.drop_test_database(name)


def test_gate_point_enum_includes_coordination_only() -> None:
    assert GatePoint.COORDINATION_ONLY.value == "coordination_only"
    assert GatePoint.from_db("coordination_only") is GatePoint.COORDINATION_ONLY


def test_is_coordination_only_predicate() -> None:
    assert is_coordination_only("coordination_only")
    assert not is_coordination_only("activation")
    assert not is_coordination_only("integration")
    assert not is_coordination_only("closure")


def test_is_activation_gate_predicate() -> None:
    assert is_activation_gate("activation")
    assert not is_activation_gate("coordination_only")
    assert not is_activation_gate("integration")
    assert not is_activation_gate("closure")


def test_valid_gate_points_includes_coordination_only() -> None:
    assert shepherd_dependency.VALID_GATE_POINTS == frozenset(
        {"activation", "integration", "closure", "coordination_only"}
    )


def test_valid_sources_include_idea_and_refine_authoring_paths(
    conn: Any,
) -> None:
    assert "idea" in shepherd_dependency.VALID_SOURCES
    assert "refine" in shepherd_dependency.VALID_SOURCES
    for idx, source in enumerate(("idea", "refine"), start=10):
        assert cmd_dependency_add(
            conn,
            f"YOK-{idx}",
            "YOK-99",
            source,
            gate_point="coordination_only",
        ) == "OK"


def test_default_satisfaction_coordination_only_is_fact_merged() -> None:
    assert shepherd_dependency._DEFAULT_SATISFACTION["coordination_only"] == "fact:merged"


def test_dependency_add_accepts_coordination_only(conn: Any) -> None:
    result = cmd_dependency_add(
        conn,
        "YOK-1",
        "YOK-2",
        "shepherd",
        gate_point="coordination_only",
    )
    assert result == "OK"

    rows = conn.execute(
        "SELECT dependent_item, blocking_item, gate_point, satisfaction "
        "FROM item_dependencies"
    ).fetchall()
    assert rows == [("YOK-1", "YOK-2", "coordination_only", "fact:merged")]


# ---------------------------------------------------------------------------
# Task 002: activation-filter regression tests (FR-2 pin)
# ---------------------------------------------------------------------------
#
# The full-schema fixture below uses ``frontier_test_helpers.make_test_db``
# so we can also exercise ``compute_frontier``. ``insert_dep`` only accepts
# the existing gate_point vocabulary, so coordination_only edges are
# written via raw INSERT to stay decoupled from any future helper signature.


def _insert_coordination_only_dep(
    conn: Any,
    dependent: str,
    blocking: str,
) -> None:
    conn.execute(
        "INSERT INTO item_dependencies "
        "(dependent_item, blocking_item, gate_point, satisfaction, source, "
        "created_at) "
        "VALUES (%s, %s, 'coordination_only', 'fact:merged', 'test', "
        "'2026-01-01T00:00:00Z')",
        (dependent, blocking),
    )


def test_evaluate_batch_gates_activation_ignores_coordination_only() -> None:
    """AC-1: ``evaluate_batch_gates(gate_point='activation')`` returns no
    blockers from ``coordination_only`` rows. The SQL filters by parameter,
    so a coordination_only row pointing at the same blocked item never
    appears in the activation result.
    """
    db = make_test_db()
    insert_item(db, 1, status="planned")
    insert_item(db, 2, status="implementing")
    insert_item(db, 3, status="implementing")
    # Item 1 has two edges: one activation, one coordination_only.
    insert_dep(db, "YOK-1", "YOK-2", gate_point="activation")
    _insert_coordination_only_dep(db, "YOK-1", "YOK-3")
    db.commit()

    blocks = evaluate_batch_gates(db, gate_point="activation")

    assert "YOK-1" in blocks
    blocking_items = {d.blocking_item for d in blocks["YOK-1"]}
    assert blocking_items == {"YOK-2"}, (
        "Activation evaluation must ignore coordination_only rows; "
        f"got {blocking_items}"
    )


def test_evaluate_batch_gates_coordination_only_returns_separate_set() -> None:
    """AC-1 companion: passing ``gate_point='coordination_only'`` returns
    the coordination_only row (proving the SQL filter is parametric, not
    a structural drop of the value).
    """
    db = make_test_db()
    insert_item(db, 1, status="planned")
    insert_item(db, 2, status="implementing")
    insert_item(db, 3, status="implementing")
    insert_dep(db, "YOK-1", "YOK-2", gate_point="activation")
    _insert_coordination_only_dep(db, "YOK-1", "YOK-3")
    db.commit()

    blocks = evaluate_batch_gates(db, gate_point="coordination_only")

    assert "YOK-1" in blocks
    blocking_items = {d.blocking_item for d in blocks["YOK-1"]}
    assert blocking_items == {"YOK-3"}, (
        "coordination_only evaluation must return only coordination_only "
        f"rows; got {blocking_items}"
    )


def test_evaluate_item_gate_activation_ignores_coordination_only() -> None:
    """AC-2: ``evaluate_item_gate(item, gate_point='activation')`` returns
    ``is_blocked=False`` when the item's only non-terminal blocker is
    ``coordination_only``-gated.
    """
    db = make_test_db()
    insert_item(db, 1, status="planned")
    insert_item(db, 2, status="implementing")
    _insert_coordination_only_dep(db, "YOK-1", "YOK-2")
    db.commit()

    result = evaluate_item_gate(db, "YOK-1", gate_point="activation")

    assert result.is_blocked is False
    assert result.unsatisfied_blockers == []


class TestRefreshHookWiring:
    """``cmd_dependency_{add,update,remove}`` trigger the wording refresh.

    The helper itself is exercised against full path-claim fixtures in
    ``test_path_claims_blocked_reason_refresh.py``. These
    tests pin the *wiring*: every edge-write path calls
    ``refresh_blocked_reason_for_edge_change`` with the normalized
    integer pair (no ``YOK-`` prefix) so the helper can compare against
    ``items.id`` (a bare integer column).
    """

    def _install_spy(self, monkeypatch):
        calls: list[tuple[int, int]] = []

        def _spy(conn, *, dependent_item_id: int, blocking_item_id: int):
            calls.append((dependent_item_id, blocking_item_id))
            return []

        monkeypatch.setattr(
            shepherd_dependency,
            "refresh_blocked_reason_for_edge_change",
            _spy,
        )
        # The wiring lives in shepherd_dependency._refresh_blocked_reasons,
        # which imports the helper via module-level binding — patching the
        # module attribute is enough.
        return calls

    def test_cmd_dependency_add_triggers_refresh(
        self, monkeypatch, conn: Any,
    ) -> None:
        calls = self._install_spy(monkeypatch)
        cmd_dependency_add(
            conn, "YOK-1701", "YOK-1702", "refine",
            gate_point="activation",
        )
        assert (1701, 1702) in calls

    def test_cmd_dependency_update_triggers_refresh(
        self, monkeypatch, conn: Any,
    ) -> None:
        calls = self._install_spy(monkeypatch)
        cmd_dependency_add(
            conn, "YOK-1703", "YOK-1704", "refine",
            gate_point="activation",
        )
        calls.clear()
        from yoke_core.domain.shepherd_dependency import cmd_dependency_update
        cmd_dependency_update(
            conn, "YOK-1703", "YOK-1704",
            gate_point="coordination_only",
            satisfaction="fact:merged",
        )
        assert (1703, 1704) in calls

    def test_cmd_dependency_remove_triggers_refresh(
        self, monkeypatch, conn: Any,
    ) -> None:
        calls = self._install_spy(monkeypatch)
        cmd_dependency_add(
            conn, "YOK-1705", "YOK-1706", "refine",
            gate_point="coordination_only",
        )
        calls.clear()
        from yoke_core.domain.shepherd_dependency import cmd_dependency_remove
        cmd_dependency_remove(conn, "YOK-1705", "YOK-1706")
        assert (1705, 1706) in calls

    def test_cmd_dependency_reconcile_triggers_refresh_for_deleted_and_inserted(
        self, monkeypatch, conn: Any,
    ) -> None:
        calls = self._install_spy(monkeypatch)
        cmd_dependency_add(
            conn, "YOK-1707", "YOK-1708", "refine",
            gate_point="activation",
        )
        calls.clear()
        from yoke_core.domain.shepherd_dependency import cmd_dependency_reconcile
        cmd_dependency_reconcile(
            conn,
            "refine",
            "YOK-1707",
            stdin_lines=[
                "YOK-1707 YOK-1709 coordination_only fact:merged refreshed",
            ],
        )
        assert (1707, 1708) in calls
        assert (1707, 1709) in calls


def test_frontier_unblocks_count_ignores_coordination_only() -> None:
    """AC-3: ``compute_frontier``'s ``_UNBLOCKS_COUNT_SQL`` counts only
    activation-gated downstreams. Adding a ``coordination_only`` row from
    item 2 to item 3 must NOT increase item 3's ``unblocks_count``.

    Baseline: item 1 -> item 3 activation edge means item 3 unblocks 1
    item. Adding a coordination_only edge item 2 -> item 3 must keep
    ``unblocks_count`` at 1, because ``_UNBLOCKS_COUNT_SQL`` hard-codes
    ``WHERE d.gate_point = 'activation'``.
    """
    db = make_test_db()
    insert_item(db, 1, status="planned")
    insert_item(db, 2, status="planned")
    insert_item(db, 3, status="implementing")
    insert_dep(db, "YOK-1", "YOK-3", gate_point="activation")
    _insert_coordination_only_dep(db, "YOK-2", "YOK-3")
    db.commit()

    result = compute_frontier(db, project_scope=["yoke"])

    by_id = {fi.item_id: fi for fi in result.runnable + result.blocked}
    assert "YOK-3" in by_id, f"YOK-3 missing from frontier: {by_id.keys()}"
    assert by_id["YOK-3"].unblocks_count == 1, (
        "coordination_only edges must not contribute to unblocks_count; "
        f"got {by_id['YOK-3'].unblocks_count}"
    )
