"""Tests for the install-bundle renderer (server side of ``yoke install``)."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest

from runtime.api.fixtures import pg_testdb
from yoke_cli.transport.response_limits import BUNDLE_JSON_RESPONSE_LIMIT_BYTES
from yoke_core.domain import install_bundle, install_bundle_tree_sync


REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGED_ROOT = REPO_ROOT / install_bundle_tree_sync.PACKAGED_TREE_REL
# Single source of truth — the same tuple the materializer and drift HC consume.
INSTALL_BUNDLE_SOURCE_DIRS = install_bundle.INSTALL_BUNDLE_SOURCE_DIRS
PYPROJECT = REPO_ROOT / "packages/yoke-core/pyproject.toml"


def _assert_same_file(source: Path, packaged: Path) -> None:
    source_bytes = source.read_bytes()
    packaged_bytes = packaged.read_bytes()
    if source_bytes == packaged_bytes:
        return
    shared_length = min(len(source_bytes), len(packaged_bytes))
    first_difference = next(
        (
            offset
            for offset in range(shared_length)
            if source_bytes[offset] != packaged_bytes[offset]
        ),
        shared_length,
    )
    pytest.fail(
        "install bundle content drift: "
        f"{source.relative_to(REPO_ROOT).as_posix()} != "
        f"{packaged.relative_to(REPO_ROOT).as_posix()}; "
        f"first_difference={first_difference}, "
        f"source_bytes={len(source_bytes)}, packaged_bytes={len(packaged_bytes)}, "
        f"source_sha256={hashlib.sha256(source_bytes).hexdigest()}, "
        f"packaged_sha256={hashlib.sha256(packaged_bytes).hexdigest()}",
        pytrace=False,
    )


@pytest.fixture()
def conn():
    name = pg_testdb.create_test_database()
    db = pg_testdb.connect_test_database(name)
    try:
        db.execute(
            "CREATE TABLE projects ("
            "id INTEGER PRIMARY KEY, slug TEXT, name TEXT, "
            "default_branch TEXT DEFAULT 'main')"
        )
        db.execute(
            "INSERT INTO projects (id, slug, name) VALUES "
            "(1, 'yoke', 'Yoke'), (2, 'externalwebapp', 'ExternalWebapp')"
        )
        db.execute(
            "CREATE TABLE strategy_docs ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, "
            "slug TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', "
            "updated_at TEXT NOT NULL, updated_by_actor_id INTEGER, "
            "archived_at TEXT, "
            "UNIQUE(project_id, slug))"
        )
        db.execute(
            "CREATE TABLE project_capabilities ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id INTEGER NOT NULL, "
            "type TEXT NOT NULL, settings TEXT DEFAULT '{}', "
            "created_at TEXT NOT NULL, UNIQUE(project_id, type))"
        )
        # Project 1 carries an established corpus; project 2 has none, so
        # bundle builds for it exercise the cold-start seeding path.
        db.execute(
            "INSERT INTO strategy_docs (project_id, slug, content, updated_at) "
            "VALUES (1, 'MISSION', '# Yoke mission\n', '2026-06-10T00:00:00Z')"
        )
        db.commit()
        yield db
    finally:
        db.close()
        pg_testdb.drop_test_database(name)


def test_build_bundle_is_deterministic(conn) -> None:
    first = install_bundle.build_bundle(2, conn)
    second = install_bundle.build_bundle(2, conn)

    first_stable = {
        key: value for key, value in first.items()
        if key != "project_policy_capabilities"
    }
    second_stable = {
        key: value for key, value in second.items()
        if key != "project_policy_capabilities"
    }
    assert first_stable == second_stable
    assert (
        first["project_policy_capabilities"]["2"]["project-policy"]["created"]
        is True
    )
    assert (
        second["project_policy_capabilities"]["2"]["project-policy"]["reused"]
        is True
    )
    assert first["bundle_schema"] == install_bundle.BUNDLE_SCHEMA
    assert first["project_id"] == 2
    assert first["project_slug"] == "externalwebapp"
    assert first["yoke_version"]
    paths = [entry["path"] for entry in first["files"]]
    assert paths == sorted(paths)
    assert len(paths) == len(set(paths)), "bundle paths must be unique"


def test_packaged_install_bundle_tree_matches_source_inputs() -> None:
    for rel in INSTALL_BUNDLE_SOURCE_DIRS:
        source = REPO_ROOT / rel
        packaged = PACKAGED_ROOT / rel
        source_files = sorted(
            path.relative_to(source).as_posix()
            for path in source.rglob("*")
            if path.is_file() and not install_bundle.is_bundle_junk_path(path)
        )
        packaged_files = sorted(
            path.relative_to(packaged).as_posix()
            for path in packaged.rglob("*")
            if path.is_file() and not install_bundle.is_bundle_junk_path(path)
        )
        assert packaged_files == source_files
        for file_rel in source_files:
            _assert_same_file(source / file_rel, packaged / file_rel)


def test_bundle_file_drift_reports_metadata_without_dumping_contents(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        "runtime.api.domain.test_install_bundle.REPO_ROOT", tmp_path,
    )
    source = tmp_path / "source" / "agent.md"
    packaged = tmp_path / "packaged" / "agent.md"
    source.parent.mkdir()
    packaged.parent.mkdir()
    source.write_text("source-private-content", encoding="utf-8")
    packaged.write_text("packaged-private-content", encoding="utf-8")

    with pytest.raises(pytest.fail.Exception) as raised:
        _assert_same_file(source, packaged)

    message = str(raised.value)
    assert "first_difference=" in message
    assert "source_sha256=" in message
    assert "packaged_sha256=" in message
    assert "private-content" not in message


def test_detect_drift_agrees_the_snapshot_is_in_sync() -> None:
    # The materializer's drift detector (which HC-install-bundle-drift consumes)
    # must agree with the byte-level invariant above — one code path guards the
    # shipped wheel, so a divergence between the two is itself the bug.
    assert install_bundle_tree_sync.detect_drift(target_root=REPO_ROOT) == []


def test_pyproject_package_data_covers_every_source_dir() -> None:
    # setuptools can only ship files it globs. If a source dir is added to
    # INSTALL_BUNDLE_SOURCE_DIRS (and materialized) but not globbed here, the
    # wheel silently omits it — drift the byte test can't see (the packaged
    # tree matches, but the wheel wouldn't carry it). Keep the two in lockstep.
    text = PYPROJECT.read_text("utf-8")
    for rel in INSTALL_BUNDLE_SOURCE_DIRS:
        assert f'"{rel}/**/*"' in text, (
            f"pyproject package-data is missing a glob for {rel!r}; the wheel "
            f"would not ship it"
        )


def test_full_skill_suite_has_canonical_and_harness_copies(conn) -> None:
    bundle = install_bundle.build_bundle(1, conn)
    assert len(json.dumps(bundle).encode("utf-8")) < BUNDLE_JSON_RESPONSE_LIMIT_BYTES
    by_path = {e["path"]: e["content"] for e in bundle["files"]}
    prefixes = {
        "canonical": ".agents/skills/yoke/",
        "claude": ".claude/skills/yoke/",
        "codex": ".codex/skills/yoke/",
    }
    skills = {
        name: sorted(p for p in by_path if p.startswith(prefix))
        for name, prefix in prefixes.items()
    }
    canonical_skills = skills["canonical"]
    assert canonical_skills, "bundle must carry canonical skill files"
    canonical_rels = [p.removeprefix(prefixes["canonical"]) for p in canonical_skills]
    for harness in ("claude", "codex"):
        expected = [f"{prefixes[harness]}{rel}" for rel in canonical_rels]
        assert expected == skills[harness]
    for canonical_path, rel in zip(canonical_skills, canonical_rels):
        for harness in ("claude", "codex"):
            assert by_path[canonical_path] == by_path[f"{prefixes[harness]}{rel}"]
    rels = set(canonical_rels)
    source = install_bundle.server_tree_root() / install_bundle.SKILLS_SOURCE
    source_rels = {
        p.relative_to(source).as_posix() for p in source.rglob("*") if p.is_file()
    }
    assert rels == source_rels
    skill_ref = r"\.agents/skills/yoke/[A-Za-z0-9_./-]+\.md"
    referenced = {
        ref
        for path in canonical_skills
        for ref in re.findall(skill_ref, by_path[path])
    }
    assert sorted(referenced - set(by_path)) == []
    shipped_skill_text = "\n".join(by_path[path] for path in canonical_skills)
    assert ".agents/skills/yoke/scripts" not in shipped_skill_text
    assert "SCRIPT_DIR" not in shipped_skill_text


def test_server_tree_root_honors_declared_env_override(
    tmp_path, monkeypatch
) -> None:
    monkeypatch.setenv("YOKE_SERVER_TREE_ROOT", str(tmp_path))

    assert install_bundle.server_tree_root() == tmp_path


def test_server_tree_root_rejects_invalid_declared_override(
    tmp_path, monkeypatch
) -> None:
    missing = tmp_path / "absent-tree"
    monkeypatch.setenv("YOKE_SERVER_TREE_ROOT", str(missing))

    with pytest.raises(install_bundle.InstallBundleError, match="not a directory"):
        install_bundle.server_tree_root()


def test_bundle_ships_rendered_agent_adapters(conn) -> None:
    # A managed project needs the lifecycle subagents (Architect/Engineer/
    # Tester/…) to run /yoke conduct etc., so the bundle ships the rendered
    # adapters for both harnesses plus the Claude references tree. (The earlier
    # "product-safe" boundary that withheld these — and the matching
    # no-internal-recipes guard — was removed: it left managed projects unable
    # to run any lifecycle command. The full operating layer is the contract;
    # scrubbing operator-debug fallback recipes from skills is separate work.)
    bundle = install_bundle.build_bundle(1, conn)

    paths = {e["path"] for e in bundle["files"]}
    roles = (
        "architect",
        "boss",
        "engineer",
        "product-designer",
        "product-manager",
        "simulator",
        "tester",
    )
    for role in roles:
        assert f".claude/agents/yoke-{role}.md" in paths
        assert f".codex/agents/yoke-{role}.toml" in paths
    assert any(
        p.startswith(".claude/agents/references/") for p in paths
    ), "the Claude agent references tree must ship"
    # Session rules the lifecycle skills assume are installed.
    assert ".claude/rules/session.md" in paths


def test_hooks_subtrees_match_canonical_renderers_and_committed_files(
    conn,
) -> None:
    from yoke_core.domain.agents_render_hooks import (
        render_claude_hooks_block,
        render_codex_hooks_block,
    )

    bundle = install_bundle.build_bundle(1, conn)

    assert bundle["hooks"]["claude_settings_hooks"] == render_claude_hooks_block()
    assert bundle["hooks"]["codex_hooks"] == render_codex_hooks_block()
    root = install_bundle.server_tree_root()
    committed_claude = json.loads(
        (root / "runtime/harness/claude/settings.json").read_text("utf-8")
    )
    committed_codex = json.loads(
        (root / "runtime/harness/codex/hooks.json").read_text("utf-8")
    )
    assert bundle["hooks"]["claude_settings_hooks"] == committed_claude["hooks"]
    assert bundle["hooks"]["codex_hooks"] == committed_codex["hooks"]


def test_build_bundle_round_trips_through_apply_bundle(conn, tmp_path) -> None:
    # The server renders the bundle; the client installer applies it. These
    # halves are otherwise tested with hand-built dicts and never meet — this
    # crosses the producer->consumer seam with the REAL rendered bundle so a
    # shape mismatch (e.g. a path apply_bundle's safety guard would reject)
    # cannot hide.
    from yoke_core.domain.project_install import apply_bundle

    bundle = install_bundle.build_bundle(2, conn)
    repo = tmp_path / "proj"
    repo.mkdir()

    report = apply_bundle(repo, bundle, source="test")

    bundle_paths = {e["path"] for e in bundle["files"]}
    # Every rendered file landed on disk and is recorded in the manifest.
    assert set(report["files_written"]) == bundle_paths
    for path in bundle_paths:
        assert (repo / path).is_file()
    manifest = json.loads(
        (repo / ".yoke/install-manifest.json").read_text("utf-8")
    )
    assert set(manifest["files"]) == bundle_paths
    # Hook subtrees merged into the harness settings files.
    assert (repo / ".claude/settings.json").is_file()
    assert (repo / ".codex/hooks.json").is_file()
    # Seed-if-missing project contract landed.
    for entry in bundle["project_contract_files"]:
        assert (repo / entry["path"]).is_file()


def test_unknown_project_raises_typed_error(conn) -> None:
    with pytest.raises(install_bundle.ProjectNotFoundError):
        install_bundle.build_bundle(999, conn)


def test_bundle_carries_project_contract_files(conn) -> None:
    from yoke_core.domain import project_contract

    bundle = install_bundle.build_bundle(2, conn)

    contract = bundle["project_contract_files"]
    assert contract == project_contract.bundle_contract_files("ExternalWebapp"), (
        "contract entries render from the project's display name"
    )
    paths = [e["path"] for e in contract]
    assert paths == sorted(paths)
    assert len(paths) == len(set(paths))
    for e in contract:
        assert e["path"].startswith(".yoke/")
        assert e["install_policy"] == project_contract.SEED_IF_MISSING
        assert e["category"] == project_contract.CATEGORY_PROJECT_POLICY
    managed = {e["path"] for e in bundle["files"]}
    assert managed.isdisjoint(paths), (
        "contract files and managed files are disjoint namespaces"
    )


def test_bundle_strategy_files_render_from_rows(conn) -> None:
    from yoke_core.domain.strategy_docs_header import parse_file_text

    bundle = install_bundle.build_bundle(1, conn)
    (entry,) = bundle["strategy_files"]
    assert entry["path"] == ".yoke/strategy/MISSION.md"
    assert entry["install_policy"] == "db_render"
    parsed = parse_file_text(entry["content"])
    assert parsed.slug == "MISSION"
    assert parsed.body == "# Yoke mission\n"
    # An established corpus is never replaced by placeholders.
    assert len(bundle["strategy_files"]) == 1


def test_bundle_cold_starts_strategy_corpus_for_empty_project(conn) -> None:
    from yoke_core.domain.strategy_docs_defaults import (
        DEFAULT_STRATEGY_DOC_SLUGS,
    )
    from yoke_core.domain.strategy_docs_header import parse_file_text

    bundle = install_bundle.build_bundle(2, conn)
    by_slug = {
        parse_file_text(e["content"]).slug: e for e in bundle["strategy_files"]
    }
    assert sorted(by_slug) == sorted(DEFAULT_STRATEGY_DOC_SLUGS)
    mission = parse_file_text(by_slug["MISSION"]["content"])
    assert "ExternalWebapp" in mission.body  # parameterized by display name
    # The seed is DB-first: the rows now exist and a re-build serves the
    # SAME corpus (no re-seed, no drift).
    again = install_bundle.build_bundle(2, conn)
    assert again["strategy_files"] == bundle["strategy_files"]
