"""What a project must already have before a capability row may be created.

The prerequisite list is data on ``capability_templates.requires``; these
cases pin that the gate reads that declaration rather than restating it, and
that the merge queue's one non-capability prerequisite — a CI workflow that
actually carries the ``merge_group`` trigger its integration gate runs —
refuses only when it is readable and provably absent.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterator

import pytest

from yoke_core.domain import capability_prerequisites as prereq
from yoke_core.domain import db_backend
from yoke_core.domain.db_helpers import iso8601_now
from runtime.api.fixtures.file_test_db import init_test_db


WITH_MERGE_GROUP = """
on:
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      yoke_dispatch_id:
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: make test
"""

WITHOUT_MERGE_GROUP = """
on:
  pull_request:
  workflow_dispatch:
    inputs:
      yoke_dispatch_id:
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: make test
"""


def _apply_schema() -> None:
    conn = db_backend.connect()
    try:
        conn.execute(
            "CREATE TABLE projects (id BIGINT PRIMARY KEY, slug TEXT NOT NULL "
            "UNIQUE, name TEXT NOT NULL)"
        )
        conn.execute(
            "INSERT INTO projects (id, slug, name) VALUES (1, 'yoke', 'Yoke')"
        )
        conn.execute(
            "CREATE TABLE project_capabilities ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "project_id BIGINT NOT NULL, type TEXT NOT NULL, "
            "settings TEXT DEFAULT '{}', created_at TEXT NOT NULL, "
            "UNIQUE(project_id, type))"
        )
        conn.execute(
            "CREATE TABLE capability_templates (id TEXT PRIMARY KEY, "
            "name TEXT NOT NULL, description TEXT, required_config TEXT, "
            "requires TEXT DEFAULT '[]', created_at TEXT)"
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture
def prereq_db(tmp_path: Path) -> Iterator[Path]:
    with init_test_db(tmp_path, apply_schema=_apply_schema):
        yield tmp_path


def _template(conn, cap_id: str, requires: list[str]) -> None:
    conn.execute(
        "INSERT INTO capability_templates (id, name, description, "
        "required_config, requires, created_at) "
        "VALUES (%s, %s, '', '[]', %s, %s)",
        (cap_id, cap_id, json.dumps(requires), iso8601_now()),
    )
    conn.commit()


def _capability(conn, cap_type: str, settings: str = "{}") -> None:
    conn.execute(
        "INSERT INTO project_capabilities (project_id, type, settings, "
        "created_at) VALUES (1, %s, %s, %s)",
        (cap_type, settings, iso8601_now()),
    )
    conn.commit()


def _require(conn, cap_type: str) -> None:
    prereq.require_prerequisites(
        conn, project_id=1, project="yoke", cap_type=cap_type,
    )


def test_prerequisites_come_from_the_template_row(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "aws-route53", ["aws-admin"])
        assert prereq.declared_prerequisites(conn, "aws-route53") == ["aws-admin"]
        assert prereq.declared_prerequisites(conn, "no-such-template") == []
    finally:
        conn.close()


def test_a_missing_prerequisite_capability_refuses_by_name(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "aws-route53", ["aws-admin"])
        with pytest.raises(prereq.CapabilityPrerequisiteError) as excinfo:
            _require(conn, "aws-route53")
        assert "aws-admin" in str(excinfo.value)
    finally:
        conn.close()


def test_a_declared_prerequisite_satisfies_the_gate(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "aws-route53", ["aws-admin"])
        _capability(conn, "aws-admin")
        _require(conn, "aws-route53")
    finally:
        conn.close()


def test_a_template_declaring_nothing_never_refuses(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "docker", [])
        _require(conn, "docker")
    finally:
        conn.close()


def test_merge_queue_refuses_without_github_and_ci_workflow(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        with pytest.raises(prereq.CapabilityPrerequisiteError) as excinfo:
            _require(conn, "merge_queue")
        message = str(excinfo.value)
        assert "ci_workflow_file" in message and "github" in message
    finally:
        conn.close()


def test_merge_queue_refuses_an_empty_workflow_declaration(prereq_db) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        _capability(conn, "github")
        _capability(conn, "ci_workflow_file", '{"workflow_file": ""}')
        with pytest.raises(prereq.CapabilityPrerequisiteError) as excinfo:
            _require(conn, "merge_queue")
        assert "no workflow_file" in str(excinfo.value)
    finally:
        conn.close()


def _checkout_with(monkeypatch, root: Path, text: str | None) -> None:
    if text is not None:
        directory = root / ".github" / "workflows"
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "ci.yml").write_text(text, encoding="utf-8")
    monkeypatch.setattr(
        prereq, "checkout_for_project_id", lambda project_id: root,
    )


def test_merge_queue_refuses_a_workflow_without_merge_group(
    prereq_db, monkeypatch, tmp_path,
) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        _capability(conn, "github")
        _capability(conn, "ci_workflow_file", '{"workflow_file": "ci.yml"}')
        _checkout_with(monkeypatch, tmp_path / "repo", WITHOUT_MERGE_GROUP)
        with pytest.raises(prereq.CapabilityPrerequisiteError) as excinfo:
            _require(conn, "merge_queue")
        assert "merge_group" in str(excinfo.value)
    finally:
        conn.close()


def test_merge_queue_accepts_a_workflow_carrying_merge_group(
    prereq_db, monkeypatch, tmp_path,
) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        _capability(conn, "github")
        _capability(conn, "ci_workflow_file", '{"workflow_file": "ci.yml"}')
        _checkout_with(monkeypatch, tmp_path / "repo", WITH_MERGE_GROUP)
        _require(conn, "merge_queue")
    finally:
        conn.close()


def test_merge_queue_refuses_a_workflow_absent_from_the_repository(
    prereq_db, monkeypatch, tmp_path,
) -> None:
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        _capability(conn, "github")
        _capability(conn, "ci_workflow_file", '{"workflow_file": "ci.yml"}')
        _checkout_with(monkeypatch, tmp_path / "repo", None)
        with pytest.raises(prereq.CapabilityPrerequisiteError) as excinfo:
            _require(conn, "merge_queue")
        assert "does not exist" in str(excinfo.value)
    finally:
        conn.close()


def test_a_host_without_the_checkout_cannot_refuse_on_merge_group(
    prereq_db, monkeypatch,
) -> None:
    """No checkout here is not evidence the trigger is missing."""
    conn = db_backend.connect()
    try:
        _template(conn, "merge_queue", ["ci_workflow_file", "github"])
        _capability(conn, "github")
        _capability(conn, "ci_workflow_file", '{"workflow_file": "ci.yml"}')
        monkeypatch.setattr(
            prereq, "checkout_for_project_id", lambda project_id: None,
        )
        _require(conn, "merge_queue")
    finally:
        conn.close()
