"""Shared database and request builders for workflow-item update tests."""

from __future__ import annotations

from contextlib import contextmanager
from typing import Any

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.file_test_db import apply_sql_script
from yoke_contracts.api.function_call import (
    ActorContext,
    FunctionCallRequest,
    TargetRef,
)

TASKS_SCHEMA = """
CREATE TABLE items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id TEXT,
    workflow_version_id INTEGER,
    project_id INTEGER DEFAULT 1
);
CREATE TABLE item_worktrees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    branch TEXT NOT NULL,
    path TEXT,
    lane_role TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    released_at TEXT
);
CREATE TABLE epic_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    title TEXT,
    item_worktree_id INTEGER,
    context_estimate TEXT,
    dependencies TEXT,
    status TEXT DEFAULT 'planning',
    dispatch_attempts INTEGER DEFAULT 0,
    body TEXT,
    github_issue TEXT,
    branch TEXT,
    worktree_path TEXT,
    blocked_by TEXT,
    max_attempts INTEGER DEFAULT 5,
    agent_id TEXT,
    last_heartbeat TEXT,
    UNIQUE(epic_id, task_num)
);
CREATE TABLE epic_progress_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    note_num INTEGER NOT NULL,
    body TEXT,
    commit_hash TEXT,
    synced_to_github INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    UNIQUE(epic_id, task_num, note_num)
);
"""


def seed_workflow_item_connection() -> Any:
    name = pg_testdb.create_test_database()
    conn = pg_testdb.drop_database_on_close(
        pg_testdb.connect_test_database(name),
        name,
    )
    apply_sql_script(conn, TASKS_SCHEMA)
    from yoke_core.domain.workflow_registry import converge_builtin_workflows
    from yoke_core.domain.workflow_schema import ensure_workflow_schema

    ensure_workflow_schema(conn)
    converge_builtin_workflows(conn)
    conn.commit()
    return conn


def add_epic_task(conn, epic_id, task_num, title, **kwargs):
    from yoke_core.domain.item_worktrees import record_worker_item_worktree
    from yoke_core.domain.workflow_registry import resolve_current_workflow_pin

    if (
        conn.execute(
            "SELECT 1 FROM items WHERE id = %s",
            (int(epic_id),),
        ).fetchone()
        is None
    ):
        workflow_id, version_id = resolve_current_workflow_pin(conn, "epic")
        conn.execute(
            "INSERT INTO items "
            "(id, workflow_id, workflow_version_id, project_id) "
            "VALUES (%s, %s, %s, 1)",
            (int(epic_id), workflow_id, version_id),
        )
    worktree = kwargs.get("worktree", "")
    lane_id = None
    if worktree:
        lane_id = int(
            record_worker_item_worktree(
                conn,
                item_id=int(epic_id),
                branch=worktree,
                path=None,
            )["id"]
        )
    conn.execute(
        "INSERT INTO epic_tasks (epic_id, task_num, title, item_worktree_id, "
        "context_estimate, dependencies, status, body) VALUES "
        "(%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            str(epic_id),
            task_num,
            title,
            lane_id,
            kwargs.get("context_estimate", ""),
            kwargs.get("dependencies", ""),
            kwargs.get("status", "planning"),
            kwargs.get("body", ""),
        ),
    )
    conn.commit()


@contextmanager
def retained_connection(conn):
    """Wrap a connection without transferring its lifecycle to the handler."""
    yield conn


def workflow_item_request(
    function: str,
    *,
    epic_id=100,
    task_num=1,
    payload=None,
) -> FunctionCallRequest:
    return FunctionCallRequest(
        function=function,
        actor=ActorContext(actor_id="test", session_id="s-1"),
        target=TargetRef(
            kind="epic_task",
            epic_id=epic_id,
            task_num=task_num,
        ),
        payload=payload or {},
    )
