"""Shared fixtures and seed helpers for the ``test_path_claims_*`` files.

Splits out of ``test_path_claims.py`` after the parent grew past the
350-line gate. Three test files share this fixture surface:

* ``test_path_claims.py`` — register / fixture coverage.
* ``test_path_claims_lifecycle.py`` — activate / release / cancel.
* ``test_path_claims_overlap.py`` — overlap classifier coverage.

The ``conn`` fixture builds the schema substrate the path-claim domain
needs (core + path-registry + actor / path-claim tables) and seeds
canonical actors. Tests that need a deterministic activation SHA use
the ``SNAP`` constant — a string SHA recorded on
``path_claims.base_commit_sha`` at activate time.

The ``conn`` fixture uses a disposable per-test Postgres DB because
these tests exercise real Yoke domain tables, event emission, and
Postgres-native registration/planning SQL. Parser-only or external
validation tests may still own explicit SQLite doubles.
"""

from __future__ import annotations

import json
from typing import Any, Optional

import pytest

from yoke_core.domain import db_backend, events_schema
from yoke_core.domain.actors import seed_canonical_actors, seed_human_actor
from yoke_core.domain.schema_common import _column_exists
from yoke_core.domain.schema_init_actor_path_claim_tables import (
    create_actor_path_claim_tables,
)
from yoke_core.domain.schema_init_columns import apply_harness_session_columns
from yoke_core.domain.schema_init_path_tables import create_path_registry_tables
from yoke_core.domain.schema_init_tables import create_core_tables
from runtime.api.fixtures.file_test_db import connect_test_db, init_test_db


# Deterministic activation commit SHA for tests that don't care which
# concrete head the door lock pins.
SNAP = "snap-default"


def _apply_path_claim_schema() -> None:
    """Build the minimal path-claim schema on the repointed test DSN.

    Runs as the ``init_test_db`` ``apply_schema`` strategy: ``db_backend``
    resolves the per-test disposable database the context just repointed
    ``YOKE_PG_DSN`` at, so the substrate lands in the throwaway database,
    not the shared ambient one.

    The schema is deliberately fuller than the path tables alone. On Postgres
    a read against a missing relation aborts the surrounding transaction, and
    the registration on-ramp tolerates absent ``projects`` /
    ``item_dependencies`` / ``event_registry`` rows by swallowing that read.
    Post-abort, that swallow would poison every later statement in the
    caller's transaction (or, for the retired-name guard, trigger a recovery
    rollback that discards the caller's pending path-target / claim rows).
    Materializing those tables empty keeps every tolerated lookup on the
    success path so the caller's transaction survives — the SQLite double the
    fixture replaced had no aborted-transaction state, so it tolerated the
    missing relations silently. ``events_schema.cmd_init`` supplies
    events + severity_config + event_registry against the same repointed DSN.
    """
    c = db_backend.connect()
    try:
        create_core_tables(c)
        c.commit()
    finally:
        c.close()

    events_schema.cmd_init()
    c = db_backend.connect()
    try:
        apply_harness_session_columns(c)
        create_path_registry_tables(c)
        create_actor_path_claim_tables(c)
        c.execute(
            "INSERT INTO projects "
            "(id, slug, name, default_branch, github_repo, "
            "public_item_prefix, created_at) "
            "VALUES "
            "(1, 'yoke', 'Yoke', 'main', NULL, 'YOK', "
            "'2026-05-01T00:00:00Z'), "
            "(2, 'buzz', 'Buzz', 'main', NULL, 'BUZ', "
            "'2026-05-01T00:00:00Z') "
            "ON CONFLICT (id) DO NOTHING"
        )
        c.execute(
            "CREATE TABLE IF NOT EXISTS item_dependencies ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "dependent_item TEXT NOT NULL, "
            "blocking_item TEXT NOT NULL, "
            "gate_point TEXT NOT NULL DEFAULT 'activation', "
            "satisfaction TEXT NOT NULL DEFAULT 'status:done', "
            "source TEXT NOT NULL DEFAULT 'test', session_id INTEGER, "
            "rationale TEXT NOT NULL DEFAULT '', "
            "evidence_json TEXT NOT NULL DEFAULT '{}', "
            "created_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00Z')"
        )
        seed_canonical_actors(c)
        c.commit()
    finally:
        c.close()


@pytest.fixture
def conn(tmp_path):
    with init_test_db(tmp_path, apply_schema=_apply_path_claim_schema) as db_path:
        c = connect_test_db(db_path)
        try:
            yield c
        finally:
            c.close()


def seed_target(conn: Any, *, path_string: str) -> int:
    """Insert a `path_targets` row and return its id."""
    cur = conn.execute(
        "INSERT INTO path_targets "
        "(project_id, kind, path_string, generation, created_at) "
        "VALUES (1, 'directory', %s, 1, '2026-05-01T00:00:00Z') "
        "RETURNING id",
        (path_string,),
    )
    return int(cur.fetchone()[0])


def local_human(conn: Any) -> int:
    """Resolve the seeded local human actor id, falling back to a fresh row."""
    row = conn.execute(
        "SELECT actor_id FROM actor_labels "
        "WHERE label='ben' AND surface='github_label'"
    ).fetchone()
    return int(row["actor_id"]) if row else seed_human_actor(conn)


def seed_item(conn: Any, *, item_id: int, status: str = "idea") -> int:
    """Insert a minimal ``items`` row and return its id."""
    conn.execute(
        "INSERT INTO items (id, title, type, status, priority, "
        "created_at, updated_at, project_id, project_sequence) "
        "VALUES (%s, 'item', 'issue', %s, 'medium', "
        "'2026-05-01T00:00:00Z', '2026-05-01T00:00:00Z', 1, %s)",
        (item_id, status, item_id),
    )
    conn.commit()
    return item_id


def seed_claim(
    conn: Any,
    *,
    item_id: int,
    target_id: int,
    state: str,
    blocked_reason: Optional[str] = None,
) -> int:
    """Insert a ``path_claims`` row plus target binding and return its id."""
    row = conn.execute(
        "INSERT INTO path_claims "
        "(state, mode, actor_id, item_id, integration_target, "
        "registered_at, blocked_reason) "
        "VALUES (%s, 'exclusive', %s, %s, 'main', "
        "'2026-05-01T00:00:00Z', %s) RETURNING id",
        (state, local_human(conn), item_id, blocked_reason),
    ).fetchone()
    claim_id = int(row[0])
    if state == "active":
        conn.execute(
            "UPDATE path_claims SET "
            "activated_at = '2026-05-01T01:00:00Z', base_commit_sha = %s "
            "WHERE id = %s",
            (SNAP, claim_id),
        )
    conn.execute(
        "INSERT INTO path_claim_targets (claim_id, target_id, declared_at) "
        "VALUES (%s, %s, '2026-05-01T00:00:00Z')",
        (claim_id, target_id),
    )
    conn.commit()
    return claim_id


def add_edge(
    conn: Any,
    *,
    dependent: int,
    blocking: int,
    gate_point: str,
) -> None:
    """Insert an ``item_dependencies`` edge between two YOK-prefixed items."""
    conn.execute(
        "INSERT INTO item_dependencies (dependent_item, blocking_item, "
        "gate_point, source, created_at) "
        "VALUES (%s, %s, %s, 'test', '2026-05-01T00:00:00Z')",
        (f"YOK-{dependent}", f"YOK-{blocking}", gate_point),
    )
    conn.commit()


def count_refresh_events(conn: Any, *, claim_id: int) -> int:
    """Count ``PathClaimBlockedReasonRefreshed`` events for a claim id."""
    rows = conn.execute(
        "SELECT envelope FROM events "
        "WHERE event_name = 'PathClaimBlockedReasonRefreshed'"
    ).fetchall()
    return sum(
        1 for row in rows
        if json.loads(row["envelope"])["context"]["claim_id"] == claim_id
    )


HOLDER_SESSION_ID = "sess-test-holder"
"""Canonical ``harness_sessions.session_id`` for the test holder session.

Used by every ``path-claims`` dispatch test that exercises a mutating
subcommand so the new ambient ownership guard sees a matching active
``work_claims`` row.
"""


def seed_test_holder_session(
    conn: Any, session_id: str = HOLDER_SESSION_ID
) -> None:
    """Insert the canonical test holder ``harness_sessions`` row idempotently."""
    actor_id = local_human(conn)
    if _column_exists(conn, "harness_sessions", "actor_id"):
        conn.execute(
            "INSERT INTO harness_sessions (session_id, executor, "
            "provider, model, project_id, execution_lane, capabilities, workspace, mode, "
            "offered_at, last_heartbeat, actor_id) "
            "VALUES (%s, 'test', 'test', 'test', 1, 'primary', '[]', '/tmp', "
            "'active', '2026-05-01T00:00:00Z', '2026-05-01T00:00:00Z', %s) "
            "ON CONFLICT(session_id) DO UPDATE SET actor_id = EXCLUDED.actor_id",
            (session_id, actor_id),
        )
        return
    conn.execute(
        "INSERT INTO harness_sessions (session_id, executor, "
        "provider, model, project_id, execution_lane, capabilities, workspace, mode, "
        "offered_at, last_heartbeat) "
        "VALUES (%s, 'test', 'test', 'test', 1, 'primary', '[]', '/tmp', "
        "'active', '2026-05-01T00:00:00Z', '2026-05-01T00:00:00Z') "
        "ON CONFLICT(session_id) DO NOTHING",
        (session_id,),
    )


def seed_work_claim_for(
    conn: Any, *, item_id: int,
    session_id: str = HOLDER_SESSION_ID,
) -> None:
    """Insert a live ``work_claims`` row owned by the test holder."""
    conn.execute(
        "INSERT INTO work_claims (session_id, target_kind, item_id, "
        "claimed_at, last_heartbeat) "
        "VALUES (%s, 'item', %s, '2026-05-01T00:00:00Z', "
        "'2026-05-01T00:00:00Z')",
        (session_id, int(item_id)),
    )


def seed_test_holder_for(conn: Any, *, item_id: int) -> None:
    """Seed both the canonical holder ``harness_sessions`` row and its claim."""
    seed_test_holder_session(conn)
    seed_work_claim_for(conn, item_id=item_id)


@pytest.fixture
def ambient_holder_session(monkeypatch):
    """Set ambient ``YOKE_SESSION_ID`` to the canonical test holder."""
    monkeypatch.setenv("YOKE_SESSION_ID", HOLDER_SESSION_ID)
    yield HOLDER_SESSION_ID
