"""Cursor harness substrate rendering — hooks.json, manifest.json, agent .md tree.

Renders Cursor-side substrate from universal Yoke source:

- ``runtime/harness/cursor/hooks.json`` — hook config in Cursor's schema
  (``{"version": 1, "hooks": {...}}``), surfaced as ``.cursor/hooks.json``.
- ``runtime/harness/cursor/manifest.json`` — Yoke-shaped harness manifest.
- ``runtime/harness/cursor/agents/yoke-{role}.md`` — Cursor custom-agent
  adapters whose body is the canonical ``runtime/agents/{role}.md`` plus
  per-role subdir fragments, surfaced as ``.cursor/agents``.

Agent body sourcing complies with the no-second-canonical-body rule: every
byte of the rendered body comes from existing canonical files, with
harness-conditional blocks resolved for the ``cursor`` id. The adapter
sidecar ``runtime/agents/{role}.cursor.json`` carries Cursor-specific
metadata without duplicating the body.

Cursor's custom-agent frontmatter has no per-tool allowlist — ``name`` and
``description`` are the schema, with ``readonly`` as the only restriction
lever — so roles that must not write declare ``readonly: true`` and the
hook layer owns tool-level policy. Only documented Cursor subagent fields
are emitted; no Claude adapter metadata leaks into Cursor output.
"""

from __future__ import annotations

import json
from pathlib import Path

from yoke_core.domain.agents_render_conditional import (
    CURSOR_HARNESS_ID,
    apply_conditional_blocks,
)
from yoke_core.domain.agents_render_context import expand_markers
from yoke_core.domain.agents_render_field_note import (
    expand_field_note_markers,
)
from yoke_core.domain.agents_render_hooks import render_cursor_hooks_block
from yoke_core.domain.agents_render_manifests import CURSOR_MANIFEST


# Generated-file lead comment for the rendered agent markdown.
GENERATED_MD_HEADER = (
    "<!-- Generated by yoke_core.domain.agents_render — do not hand-edit.\n"
    "     Source: runtime/agents/{role}.md (+ runtime/agents/{role}/*.md fragments)\n"
    "     Adapter sidecar: runtime/agents/{role}.cursor.json -->\n"
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _ordered_subdir_fragments(canonical_dir: Path, role: str) -> list[Path]:
    """Return per-role fragment files in deterministic (sorted) order."""
    subdir = canonical_dir / role
    if not subdir.is_dir():
        return []
    return sorted(p for p in subdir.iterdir() if p.is_file() and p.suffix == ".md")


def load_cursor_spec(canonical_dir: Path, role: str) -> dict:
    """Read ``runtime/agents/{role}.cursor.json`` adapter sidecar.

    Returns a dict with stable keys; raises FileNotFoundError if the
    sidecar is missing.
    """
    path = canonical_dir / f"{role}.cursor.json"
    return json.loads(_read_text(path))


def render_cursor_agent_body(canonical_dir: Path, role: str) -> str:
    """Concatenate canonical body + per-role subdir fragments.

    Harness-conditional blocks resolve for the ``cursor`` id, so
    Claude-only wake-primitive prose and Codex-only prose are both elided.
    """
    canonical_text = _read_text(canonical_dir / f"{role}.md")
    parts: list[str] = [
        apply_conditional_blocks(
            expand_field_note_markers(expand_markers(canonical_text)),
            CURSOR_HARNESS_ID,
        ).rstrip("\n")
    ]
    for fragment in _ordered_subdir_fragments(canonical_dir, role):
        parts.append(_read_text(fragment).rstrip("\n"))
    return "\n\n".join(parts) + "\n"


def render_cursor_agent(canonical_dir: Path, role: str) -> str:
    """Render the full Cursor agent adapter ``.md`` content for *role*.

    Emits Cursor's custom-agent schema: YAML frontmatter with required
    ``name`` / ``description`` plus ``readonly`` when the sidecar declares
    it, followed by the body as the system prompt.
    """
    spec = load_cursor_spec(canonical_dir, role)
    body = render_cursor_agent_body(canonical_dir, role)

    lines: list[str] = ["---"]
    lines.append(f"name: yoke-{role}")
    description = spec.get("description", "")
    lines.append(f"description: {json.dumps(description)}")
    if spec.get("readonly") is True:
        lines.append("readonly: true")
    lines.append("---")
    lines.append("")
    lines.append(GENERATED_MD_HEADER.replace("{role}", role).rstrip("\n"))
    lines.append("")
    lines.append(body.rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def render_cursor_hooks_json() -> str:
    """Render Cursor ``hooks.json`` content (schema version 1)."""
    payload = render_cursor_hooks_block()
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def render_cursor_manifest_json() -> str:
    """Render Cursor ``manifest.json`` content with leading marker."""
    payload = {
        "_generated": (
            "by yoke_core.domain.agents_render — do not hand-edit. "
            "Source: yoke_core.domain.agents_render_manifests.CURSOR_MANIFEST."
        ),
        **CURSOR_MANIFEST,
    }
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"
