"""Codex harness substrate rendering — hooks.json, manifest.json, agent .toml tree.

Renders Codex-side substrate from universal Yoke source:

- ``runtime/harness/codex/hooks.json`` — hook config in Codex's adapter-verb shape.
- ``runtime/harness/codex/manifest.json`` — Yoke-shaped harness manifest.
- ``runtime/harness/codex/agents/yoke-{role}.toml`` — Codex custom-agent
  adapters whose prompt body is the canonical
  ``runtime/agents/{role}.md`` plus per-role subdir fragments at
  ``runtime/agents/{role}/*.md`` (architect, engineer, simulator, tester).

Agent prompt body sourcing complies with the no-second-canonical-body
rule: every byte of the rendered ``developer_instructions`` comes from
existing canonical files. The Codex adapter sidecar
``runtime/agents/{role}.codex.json`` carries Codex-specific adapter
metadata (description, optional pinned-model policy, sandbox posture)
without duplicating the body.

The rendered ``.toml`` uses the current Codex custom-subagent schema:
required ``name`` / ``description`` / ``developer_instructions`` plus the
optional fields Codex inherits-when-omitted. ``model`` is omitted by
default so Codex follows the parent session, and is pinned only when the
sidecar opts in via ``model_policy="pinned"``; ``sandbox_mode`` posture is
emitted when the sidecar declares it. Only documented Codex subagent
fields are emitted — no Claude adapter metadata leaks into Codex output.
"""

from __future__ import annotations

import json
from pathlib import Path

from yoke_core.domain.agents_render_conditional import (
    CODEX_HARNESS_ID,
    apply_conditional_blocks,
)
from yoke_core.domain.agents_render_context import expand_markers
from yoke_core.domain.agents_render_field_note import (
    expand_field_note_markers,
)
from yoke_core.domain.agents_render_hooks import render_codex_hooks_block
from yoke_core.domain.agents_render_manifests import CODEX_MANIFEST


# Generated-file lead comment for TOML output.
GENERATED_TOML_HEADER = (
    "# Generated by yoke_core.domain.agents_render — do not hand-edit.\n"
    "# Source: runtime/agents/{role}.md (+ runtime/agents/{role}/*.md fragments)\n"
    "# Adapter sidecar: runtime/agents/{role}.codex.json\n"
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _ordered_subdir_fragments(canonical_dir: Path, role: str) -> list[Path]:
    """Return per-role fragment files in deterministic (sorted) order."""
    subdir = canonical_dir / role
    if not subdir.is_dir():
        return []
    return sorted(p for p in subdir.iterdir() if p.is_file() and p.suffix == ".md")


def load_codex_spec(canonical_dir: Path, role: str) -> dict:
    """Read ``runtime/agents/{role}.codex.json`` adapter sidecar.

    Returns a dict with stable keys; raises FileNotFoundError if the sidecar
    is missing.
    """
    path = canonical_dir / f"{role}.codex.json"
    return json.loads(_read_text(path))


def render_codex_agent_body(canonical_dir: Path, role: str) -> str:
    """Concatenate canonical body + per-role subdir fragments.

    Format: canonical body, blank line, then each fragment's raw text in
    sorted order separated by blank lines. The result becomes the
    ``developer_instructions`` field of the rendered TOML.
    """
    canonical_text = _read_text(canonical_dir / f"{role}.md")
    parts: list[str] = [
        apply_conditional_blocks(
            expand_field_note_markers(expand_markers(canonical_text)),
            CODEX_HARNESS_ID,
        ).rstrip("\n")
    ]
    for fragment in _ordered_subdir_fragments(canonical_dir, role):
        parts.append(_read_text(fragment).rstrip("\n"))
    return "\n\n".join(parts) + "\n"


def _toml_escape_triple_quoted(body: str) -> str:
    # Escape body content for a TOML triple-quoted basic-string literal.
    # Triple-quoted basic strings forbid the literal three-quote sequence
    # inside the body; we replace it with the canonical TOML escape. Also
    # escape backslashes so accidental \\u/\\x sequences are not interpreted
    # as escapes.
    escaped = body.replace("\\", "\\\\")
    escaped = escaped.replace('"""', '\\"\\"\\"')
    return escaped


def _resolve_pinned_model(spec: dict) -> str | None:
    """Codex model policy: omit ``model`` by default (inherit from parent).

    The Codex subagent docs treat omitted optional fields as inherited from
    the parent session. A sidecar opts into a fixed model only with
    ``model_policy="pinned"`` plus a concrete ``model`` value; ``inherit`` /
    ``latest`` / an absent policy all leave ``model`` off so Codex follows
    the current session/default model.
    """
    if spec.get("model_policy") != "pinned":
        return None
    model = spec.get("model")
    return model if isinstance(model, str) and model else None


def render_codex_agent(canonical_dir: Path, role: str) -> str:
    """Render the full Codex agent adapter ``.toml`` content for *role*.

    Emits the current Codex custom-subagent schema: required ``name`` /
    ``description`` / ``developer_instructions``, plus the optional
    ``model`` (only when pinned) and ``sandbox_mode`` posture when the
    sidecar declares it. Claude-only adapter metadata is never emitted.
    """
    spec = load_codex_spec(canonical_dir, role)
    body = render_codex_agent_body(canonical_dir, role)
    escaped = _toml_escape_triple_quoted(body)

    header = GENERATED_TOML_HEADER.replace("{role}", role)
    lines: list[str] = [header]
    lines.append(f'name = "yoke-{role}"')
    if "description" in spec:
        lines.append(f'description = {json.dumps(spec["description"])}')
    pinned_model = _resolve_pinned_model(spec)
    if pinned_model is not None:
        lines.append(f'model = {json.dumps(pinned_model)}')
    if "sandbox_mode" in spec:
        lines.append(f'sandbox_mode = {json.dumps(spec["sandbox_mode"])}')
    lines.append("")
    lines.append('developer_instructions = """')
    lines.append(escaped.rstrip("\n"))
    lines.append('"""')
    lines.append("")
    return "\n".join(lines)


def render_codex_hooks_json() -> str:
    """Render Codex ``hooks.json`` content in Codex's strict schema."""
    payload = {"hooks": render_codex_hooks_block()}
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def render_codex_manifest_json() -> str:
    """Render Codex ``manifest.json`` content with leading marker."""
    payload = {
        "_generated": (
            "by yoke_core.domain.agents_render — do not hand-edit. "
            "Source: yoke_core.domain.agents_render_manifests.CODEX_MANIFEST."
        ),
        **CODEX_MANIFEST,
    }
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"
