"""Cursor harness substrate rendering — hooks.json, manifest.json, agent .md tree.

Renders Cursor-side substrate from universal Yoke source:

- ``runtime/harness/cursor/hooks.json`` — hook config in Cursor's schema
  (``{"version": 1, "hooks": {...}}``), surfaced as ``.cursor/hooks.json``.
- ``runtime/harness/cursor/manifest.json`` — Yoke-shaped harness manifest.
- ``runtime/harness/cursor/agents/yoke-{role}.md`` — Cursor custom-agent
  adapters whose body is rendered from the canonical Yoke agent source and
  its always-needed reference material, surfaced as ``.cursor/agents``.

Agent body sourcing complies with the no-second-canonical-body rule: every
byte of the rendered body comes from existing canonical files, with
harness-conditional blocks resolved for the ``cursor`` id. The adapter
sidecar ``runtime/agents/{role}.cursor.json`` carries Cursor-specific
metadata without duplicating the body.

Cursor's custom-agent frontmatter has no per-tool allowlist — ``name`` and
``description`` are the schema, with ``readonly`` as the only restriction
lever — so roles that must not write declare ``readonly: true`` and the
hook layer owns tool-level policy. Only documented Cursor subagent fields
are emitted; no Claude adapter metadata leaks into Cursor output.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

from yoke_core.domain.agents_render_conditional import (
    CURSOR_HARNESS_ID,
)
from yoke_core.domain.agents_render_references import render_agent_prompt_body
from yoke_core.domain.agents_render_hooks import render_cursor_hooks_block
from yoke_core.domain.agents_render_manifests import CURSOR_MANIFEST


# Generated-file lead comment for the rendered agent markdown.
GENERATED_MD_HEADER = (
    "<!-- Generated by yoke_core.domain.agents_render — do not hand-edit.\n"
    "     Source: canonical Yoke agent prompt and reference material.\n"
    "     Adapter sidecar: canonical Cursor agent metadata -->\n"
)

CURSOR_QA_WALKER_READONLY_REASON = "cursor_qa_walker_readonly"
CURSOR_QA_WALKER_POSTURE_MISSING_REASON = "cursor_qa_walker_write_posture_missing"


class CursorAgentCapabilityError(ValueError):
    """A Cursor custom-agent adapter cannot satisfy its dispatch contract."""


def require_cursor_agent_write_capability(
    role: str,
    spec: Mapping[str, Any],
) -> None:
    """Require an explicit write-capable posture for mission walkers."""
    if role != "qa-walker":
        return
    readonly = spec.get("readonly")
    if readonly is True:
        raise CursorAgentCapabilityError(
            f"{CURSOR_QA_WALKER_READONLY_REASON}: Cursor's QA walker cannot "
            "run host, browser, or artifact commands while readonly. Set "
            "runtime/agents/qa-walker.cursor.json readonly to false, run "
            "`yoke agents render --target-root <checkout>`, and retry the "
            "QA plan run."
        )
    if readonly is not False:
        raise CursorAgentCapabilityError(
            f"{CURSOR_QA_WALKER_POSTURE_MISSING_REASON}: Cursor's QA walker "
            "must declare readonly=false explicitly. Set it in "
            "runtime/agents/qa-walker.cursor.json, run `yoke agents render "
            "--target-root <checkout>`, and retry the QA plan run."
        )


def load_rendered_cursor_spec(path: Path) -> dict[str, Any]:
    """Read the dispatch-relevant metadata from a rendered Cursor adapter."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise CursorAgentCapabilityError(
            "cursor_qa_walker_adapter_unavailable: Cursor's QA walker adapter "
            f"is not readable at {path}. Run `yoke agents render "
            "--target-root <checkout>` and retry the QA plan run."
        ) from exc
    if not lines or lines[0] != "---":
        raise CursorAgentCapabilityError(
            "cursor_qa_walker_adapter_invalid: Cursor's QA walker adapter "
            f"at {path} has no YAML frontmatter. Run `yoke agents render "
            "--target-root <checkout>` and retry the QA plan run."
        )
    spec: dict[str, Any] = {}
    frontmatter_closed = False
    for line in lines[1:]:
        if line == "---":
            frontmatter_closed = True
            break
        key, separator, value = line.partition(":")
        if separator and key.strip() == "readonly":
            normalized = value.strip().lower()
            if normalized in {"true", "false"}:
                spec["readonly"] = normalized == "true"
            else:
                spec["readonly"] = normalized
    if not frontmatter_closed:
        raise CursorAgentCapabilityError(
            "cursor_qa_walker_adapter_invalid: Cursor's QA walker adapter "
            f"at {path} has unterminated YAML frontmatter. Run `yoke agents "
            "render --target-root <checkout>` and retry the QA plan run."
        )
    return spec


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_cursor_spec(canonical_dir: Path, role: str) -> dict:
    """Read ``runtime/agents/{role}.cursor.json`` adapter sidecar.

    Returns a dict with stable keys; raises FileNotFoundError if the
    sidecar is missing.
    """
    path = canonical_dir / f"{role}.cursor.json"
    return json.loads(_read_text(path))


def render_cursor_agent_body(canonical_dir: Path, role: str) -> str:
    """Render the portable prompt body for a Cursor agent."""
    return render_agent_prompt_body(canonical_dir, role, harness_id=CURSOR_HARNESS_ID)


def render_cursor_agent(canonical_dir: Path, role: str) -> str:
    """Render the full Cursor agent adapter ``.md`` content for *role*.

    Emits Cursor's custom-agent schema: YAML frontmatter with required
    ``name`` / ``description`` plus ``readonly`` when the sidecar declares
    it, followed by the body as the system prompt.
    """
    spec = load_cursor_spec(canonical_dir, role)
    require_cursor_agent_write_capability(role, spec)
    body = render_cursor_agent_body(canonical_dir, role)

    lines: list[str] = ["---"]
    lines.append(f"name: yoke-{role}")
    description = spec.get("description", "")
    lines.append(f"description: {json.dumps(description)}")
    if "readonly" in spec:
        readonly = spec["readonly"]
        if not isinstance(readonly, bool):
            raise ValueError(f"Cursor agent {role!r} readonly must be a JSON boolean")
        lines.append(f"readonly: {str(readonly).lower()}")
    lines.append("---")
    lines.append("")
    lines.append(GENERATED_MD_HEADER.replace("{role}", role).rstrip("\n"))
    lines.append("")
    lines.append(body.rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def render_cursor_hooks_json() -> str:
    """Render Cursor ``hooks.json`` content (schema version 1)."""
    payload = render_cursor_hooks_block()
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def render_cursor_manifest_json() -> str:
    """Render Cursor ``manifest.json`` content with leading marker."""
    payload = {
        "_generated": (
            "by yoke_core.domain.agents_render — do not hand-edit. "
            "Source: yoke_core.domain.agents_render_manifests.CURSOR_MANIFEST."
        ),
        **CURSOR_MANIFEST,
    }
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"
