"""Idempotent table convergence for deployment-run storage."""

from __future__ import annotations

from typing import Optional

from yoke_core.domain.db_helpers import connect
from yoke_core.domain.deployment_stage_receipts import (
    DEPLOYMENT_STAGE_RECEIPTS_SQL,
)
from yoke_core.domain.schema_common import (
    _add_column_if_not_exists,
    _column_exists,
    environment_reference_column_sql,
)

DELIVERY_INTENT_COLUMN_SQL = "TEXT CHECK(delivery_intent IN ('progress','final'))"


def cmd_init(db_path: Optional[str] = None) -> None:
    """Create deployment-run tables and additive columns."""
    conn = connect(db_path)
    try:
        environment_ref = environment_reference_column_sql(conn)
        for statement in (
            f"""
            CREATE TABLE IF NOT EXISTS deployment_runs (
                id TEXT PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id),
                flow TEXT NOT NULL REFERENCES deployment_flows(id),
                target_tier TEXT,
                target_environment_id {environment_ref},
                release_lineage TEXT,
                status TEXT NOT NULL DEFAULT 'created'
                    CHECK(status IN ('created','executing','succeeded','failed','cancelled')),
                current_stage TEXT,
                created_at TEXT NOT NULL,
                started_at TEXT,
                completed_at TEXT,
                created_by TEXT DEFAULT 'operator',
                carried_work TEXT,
                bound_sources TEXT,
                artifact_identity TEXT,
                composition_resolution TEXT,
                composition_frozen_at TEXT,
                requirement_snapshot TEXT,
                CONSTRAINT deployment_runs_target_tier_vocabulary
                    CHECK (target_tier IS NULL
                           OR target_tier IN ('persistent','ephemeral')),
                CONSTRAINT deployment_runs_target_tier_environment
                    CHECK ((target_tier IS NOT NULL
                            AND target_tier = 'persistent')
                           = (target_environment_id IS NOT NULL))
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS deployment_run_items (
                run_id TEXT NOT NULL REFERENCES deployment_runs(id),
                item_id INTEGER NOT NULL,
                added_at TEXT NOT NULL,
                delivery_intent {DELIVERY_INTENT_COLUMN_SQL},
                requirement_selection TEXT,
                requirement_selection_source TEXT,
                requirement_snapshot TEXT,
                containment_attestation TEXT,
                PRIMARY KEY (run_id, item_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS deployment_run_qa (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id TEXT NOT NULL REFERENCES deployment_runs(id),
                check_name TEXT NOT NULL,
                source TEXT NOT NULL DEFAULT 'flow_default',
                blocking INTEGER NOT NULL DEFAULT 1,
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK(status IN ('pending','passed','failed','waived')),
                updated_at TEXT,
                UNIQUE(run_id, check_name)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS deployment_preview_environments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id),
                env_name TEXT NOT NULL,
                run_id TEXT REFERENCES deployment_runs(id),
                status TEXT NOT NULL DEFAULT 'available'
                    CHECK(status IN ('available','claimed','stale')),
                env_type TEXT NOT NULL DEFAULT 'adhoc'
                    CHECK(env_type IN ('shared','adhoc')),
                url TEXT,
                created_at TEXT NOT NULL,
                UNIQUE(project_id, env_name)
            )
            """,
            DEPLOYMENT_STAGE_RECEIPTS_SQL,
        ):
            conn.execute(statement)
        for column in (
            "artifact_identity",
            "composition_resolution",
            "composition_frozen_at",
            "requirement_snapshot",
        ):
            _add_column_if_not_exists(conn, "deployment_runs", column, "TEXT")
        for column, declaration in (
            ("delivery_intent", DELIVERY_INTENT_COLUMN_SQL),
            ("requirement_selection", "TEXT"),
            ("requirement_selection_source", "TEXT"),
            ("requirement_snapshot", "TEXT"),
            ("containment_attestation", "TEXT"),
        ):
            _add_column_if_not_exists(conn, "deployment_run_items", column, declaration)
        if not _column_exists(conn, "deployment_preview_environments", "env_type"):
            try:
                conn.execute(
                    "ALTER TABLE deployment_preview_environments "
                    "ADD COLUMN env_type TEXT NOT NULL DEFAULT 'adhoc' "
                    "CHECK(env_type IN ('shared','adhoc'))"
                )
                conn.commit()
            except Exception:
                pass
        conn.commit()
    finally:
        conn.close()


__all__ = ["DELIVERY_INTENT_COLUMN_SQL", "cmd_init"]
