"""Native schema declarations for deployment stage receipts."""

DEPLOYMENT_STAGE_RECEIPTS_SQL = """
CREATE TABLE IF NOT EXISTS deployment_stage_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES deployment_runs(id),
    stage_name TEXT NOT NULL CHECK(TRIM(stage_name) <> ''),
    attempt_number INTEGER NOT NULL CHECK(attempt_number > 0),
    correlation_id TEXT NOT NULL CHECK(TRIM(correlation_id) <> ''),
    target_kind TEXT NOT NULL
        CHECK(target_kind IN ('persistent_environment','run_preview')),
    target_name TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','ready','failed','cancelled')),
    observed_url TEXT,
    observed_release_lineage TEXT,
    observed_artifact_identity TEXT,
    executor TEXT NOT NULL CHECK(TRIM(executor) <> ''),
    executor_receipt TEXT,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT deployment_stage_receipts_ready_evidence CHECK(
        status <> 'ready' OR (
            TRIM(COALESCE(target_name,'')) <> ''
            AND TRIM(COALESCE(observed_release_lineage,'')) <> ''
            AND completed_at IS NOT NULL
        )
    ),
    UNIQUE(run_id,stage_name,attempt_number),
    UNIQUE(run_id,stage_name,correlation_id)
);
""".strip()
