"""Durable per-attempt deployment-stage observations consumed by scoped QA."""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any

from yoke_core.domain import db_backend
from yoke_core.domain.db_helpers import iso8601_now


RECEIPT_STATUSES = frozenset({"pending", "ready", "failed", "cancelled"})
TARGET_KINDS = frozenset({"persistent_environment", "run_preview"})

DEPLOYMENT_STAGE_RECEIPTS_SQL = """
CREATE TABLE IF NOT EXISTS deployment_stage_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES deployment_runs(id),
    stage_name TEXT NOT NULL CHECK(TRIM(stage_name) <> ''),
    attempt_number INTEGER NOT NULL CHECK(attempt_number > 0),
    correlation_id TEXT NOT NULL CHECK(TRIM(correlation_id) <> ''),
    target_kind TEXT NOT NULL
        CHECK(target_kind IN ('persistent_environment','run_preview')),
    target_name TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','ready','failed','cancelled')),
    observed_url TEXT,
    observed_release_lineage TEXT,
    observed_artifact_identity TEXT,
    executor TEXT NOT NULL CHECK(TRIM(executor) <> ''),
    executor_receipt TEXT,
    failure_reason TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    CONSTRAINT deployment_stage_receipts_ready_evidence CHECK(
        status <> 'ready' OR (
            TRIM(COALESCE(target_name,'')) <> ''
            AND TRIM(COALESCE(observed_release_lineage,'')) <> ''
            AND completed_at IS NOT NULL
        )
    ),
    UNIQUE(run_id,stage_name,attempt_number),
    UNIQUE(run_id,stage_name,correlation_id)
);
""".strip()


def ensure_deployment_stage_receipt_schema(conn: Any) -> None:
    """Create the additive receipt authority without selecting new flows."""
    conn.execute(DEPLOYMENT_STAGE_RECEIPTS_SQL)


def _p(conn: Any) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def _row(cursor: Any, value: Any) -> dict[str, Any] | None:
    if value is None:
        return None
    if hasattr(value, "keys"):
        return {str(key): value[key] for key in value.keys()}
    names = [str(getattr(col, "name", None) or col[0]) for col in cursor.description]
    return dict(zip(names, value, strict=True))


def _text(value: Any, *, field: str) -> str:
    text = str(value or "").strip()
    if not text:
        raise ValueError(f"{field} must be non-empty")
    return text


def _run_stage(conn: Any, run_id: str, stage_name: str) -> dict[str, Any]:
    cursor = conn.execute(
        "SELECT dr.id,dr.project_id,dr.flow,dr.status,dr.current_stage,"
        "dr.release_lineage,dr.artifact_identity,df.stages "
        "FROM deployment_runs dr JOIN deployment_flows df ON df.id=dr.flow "
        f"WHERE dr.id={_p(conn)} FOR UPDATE",
        (run_id,),
    )
    run = _row(cursor, cursor.fetchone())
    if run is None:
        raise LookupError(f"deployment run {run_id!r} not found")
    try:
        stages = json.loads(str(run["stages"]))
    except (TypeError, ValueError) as exc:
        raise ValueError("deployment flow stages are invalid JSON") from exc
    matches = [
        dict(stage)
        for stage in stages
        if isinstance(stage, Mapping) and str(stage.get("name") or "") == stage_name
    ]
    if len(matches) != 1:
        raise ValueError(
            f"deployment stage {stage_name!r} is not uniquely pinned by run {run_id!r}"
        )
    if matches[0].get("stage_kind") == "qa" or matches[0].get("step_runner") == "qa":
        raise ValueError(
            f"deployment stage {stage_name!r} is QA, not a receipt-producing stage"
        )
    run["stage"] = matches[0]
    return run


def allocate_deployment_stage_receipt(
    conn: Any,
    *,
    run_id: str,
    stage_name: str,
    correlation_id: str,
    target_kind: str,
    executor: str,
    commit: bool = True,
) -> dict[str, Any]:
    """Allocate ordered attempt identity before an executor is dispatched."""
    run_id = _text(run_id, field="run_id")
    stage_name = _text(stage_name, field="stage_name")
    correlation_id = _text(correlation_id, field="correlation_id")
    executor = _text(executor, field="executor")
    if target_kind not in TARGET_KINDS:
        raise ValueError(f"target_kind must be one of {sorted(TARGET_KINDS)}")
    try:
        run = _run_stage(conn, run_id, stage_name)
        if str(run["status"]) != "executing" or str(run["current_stage"]) != stage_name:
            raise ValueError(
                f"deployment run {run_id!r} is not executing stage {stage_name!r}"
            )
        cursor = conn.execute(
            "SELECT * FROM deployment_stage_receipts WHERE run_id=%s "
            "AND stage_name=%s AND correlation_id=%s",
            (run_id, stage_name, correlation_id),
        )
        existing = _row(cursor, cursor.fetchone())
        if existing is not None:
            if (
                str(existing["target_kind"]) != target_kind
                or str(existing["executor"]) != executor
            ):
                raise ValueError(
                    "deployment stage receipt correlation was reused with "
                    "different immutable dispatch inputs"
                )
            if commit:
                conn.commit()
            return existing
        row = conn.execute(
            "SELECT COALESCE(MAX(attempt_number),0)+1 FROM "
            "deployment_stage_receipts WHERE run_id=%s AND stage_name=%s",
            (run_id, stage_name),
        ).fetchone()
        attempt = int(row[0])
        cursor = conn.execute(
            "INSERT INTO deployment_stage_receipts("
            "run_id,stage_name,attempt_number,correlation_id,target_kind,status,"
            "executor,created_at) VALUES (%s,%s,%s,%s,%s,'pending',%s,%s) "
            "RETURNING *",
            (
                run_id,
                stage_name,
                attempt,
                correlation_id,
                target_kind,
                executor,
                iso8601_now(),
            ),
        )
        created = _row(cursor, cursor.fetchone())
        assert created is not None
        if commit:
            conn.commit()
        return created
    except Exception:
        if commit:
            conn.rollback()
        raise


def complete_deployment_stage_receipt(
    conn: Any,
    *,
    run_id: str,
    receipt_id: int,
    correlation_id: str,
    status: str,
    target_name: str | None = None,
    observed_url: str | None = None,
    observed_release_lineage: str | None = None,
    observed_artifact_identity: str | None = None,
    executor_receipt: str | None = None,
    failure_reason: str | None = None,
    commit: bool = True,
) -> dict[str, Any]:
    """Settle one allocated attempt once; conflicting callbacks are refused."""
    if status not in RECEIPT_STATUSES - {"pending"}:
        raise ValueError("receipt completion status must be ready, failed, or cancelled")
    run_id = _text(run_id, field="run_id")
    correlation_id = _text(correlation_id, field="correlation_id")
    try:
        cursor = conn.execute(
            "SELECT r.*,dr.release_lineage,dr.status AS run_status,"
            "dr.artifact_identity AS run_artifact_identity "
            "FROM deployment_stage_receipts r "
            "JOIN deployment_runs dr ON dr.id=r.run_id WHERE r.id=%s FOR UPDATE",
            (int(receipt_id),),
        )
        receipt = _row(cursor, cursor.fetchone())
        if receipt is None:
            raise LookupError(f"deployment stage receipt {receipt_id} not found")
        if str(receipt["run_id"]) != run_id:
            raise ValueError("deployment stage receipt does not belong to the authorized run")
        if str(receipt["correlation_id"]) != correlation_id:
            raise ValueError("deployment stage receipt correlation does not match")
        normalized = {
            "status": status,
            "target_name": str(target_name or "").strip() or None,
            "observed_url": str(observed_url or "").strip().rstrip("/") or None,
            "observed_release_lineage": (
                str(observed_release_lineage or "").strip() or None
            ),
            "observed_artifact_identity": (
                str(observed_artifact_identity or "").strip() or None
            ),
            "executor_receipt": str(executor_receipt or "").strip() or None,
            "failure_reason": str(failure_reason or "").strip() or None,
        }
        if status == "ready":
            if not normalized["target_name"] or not normalized["observed_release_lineage"]:
                raise ValueError(
                    "ready receipt requires observed target_name and release_lineage"
                )
            if normalized["observed_release_lineage"] != str(receipt["release_lineage"]):
                raise ValueError(
                    "ready receipt observed a different release lineage; retain the "
                    "receipt and dispatch the pinned candidate"
                )
            run_artifact = str(receipt["run_artifact_identity"] or "").strip()
            if run_artifact and normalized["observed_artifact_identity"] != run_artifact:
                raise ValueError(
                    "ready receipt observed a different artifact identity; retain "
                    "the receipt and dispatch the pinned artifact"
                )
        elif not normalized["failure_reason"]:
            raise ValueError(
                f"{status} receipt requires a failure_reason that teaches recovery"
            )
        if str(receipt["status"]) != "pending":
            if all(receipt[key] == value for key, value in normalized.items()):
                if commit:
                    conn.commit()
                return receipt
            raise ValueError(
                "deployment stage receipt is already terminal with different evidence"
            )
        if str(receipt["run_status"]) != "executing":
            raise ValueError(
                "deployment run is no longer executing; a cancelled or replaced "
                "run cannot accept a late stage-receipt completion"
            )
        completed_at = iso8601_now()
        conn.execute(
            "UPDATE deployment_stage_receipts SET status=%s,target_name=%s,"
            "observed_url=%s,observed_release_lineage=%s,"
            "observed_artifact_identity=%s,executor_receipt=%s,failure_reason=%s,"
            "completed_at=%s WHERE id=%s",
            (*normalized.values(), completed_at, int(receipt_id)),
        )
        cursor = conn.execute(
            "SELECT * FROM deployment_stage_receipts WHERE id=%s", (int(receipt_id),)
        )
        completed = _row(cursor, cursor.fetchone())
        assert completed is not None
        if commit:
            conn.commit()
        return completed
    except Exception:
        if commit:
            conn.rollback()
        raise


def deployment_stage_receipt_for_qa(
    conn: Any,
    *,
    run_id: str,
    source_stage: str,
    expected_target_kind: str,
    expected_target_name: str | None,
    expected_release_lineage: str,
    expected_artifact_identity: str | None = None,
    receipt_id: int | None = None,
) -> dict[str, Any]:
    """Return only the newest exact ready attempt for QA target binding."""
    cursor = conn.execute(
        "SELECT * FROM deployment_stage_receipts WHERE run_id=%s AND stage_name=%s "
        "ORDER BY attempt_number DESC LIMIT 2",
        (run_id, source_stage),
    )
    rows = [_row(cursor, value) for value in cursor.fetchall()]
    latest = rows[0] if rows else None
    if latest is None:
        raise ValueError(
            f"deployment stage {source_stage!r} has no durable receipt; execute "
            "and observe that stage before starting QA"
        )
    if receipt_id is not None and int(latest["id"]) != int(receipt_id):
        raise ValueError(
            "deployment QA receipt was superseded by a newer attempt; preserve "
            "the evidence and materialize a fresh execution"
        )
    if str(latest["status"]) != "ready":
        raise ValueError(
            f"latest deployment stage receipt is {latest['status']!r}, not ready; "
            "repair or retry the producer stage before starting QA"
        )
    if str(latest["target_kind"]) != expected_target_kind:
        raise ValueError("deployment stage receipt target kind does not match QA policy")
    if expected_target_name is not None and str(latest["target_name"]) != str(
        expected_target_name
    ):
        raise ValueError("deployment stage receipt target does not match QA policy")
    if str(latest["observed_release_lineage"]) != expected_release_lineage:
        raise ValueError(
            "deployment stage receipt candidate was replaced or differs from the "
            "pinned release lineage; retry the producer stage"
        )
    expected_artifact = str(expected_artifact_identity or "").strip()
    if (
        expected_artifact
        and str(latest["observed_artifact_identity"] or "") != expected_artifact
    ):
        raise ValueError(
            "deployment stage receipt artifact differs from the pinned artifact "
            "identity; retry the producer stage"
        )
    return latest


__all__ = [
    "DEPLOYMENT_STAGE_RECEIPTS_SQL",
    "RECEIPT_STATUSES",
    "allocate_deployment_stage_receipt",
    "complete_deployment_stage_receipt",
    "deployment_stage_receipt_for_qa",
    "ensure_deployment_stage_receipt_schema",
]
