"""Schema bootstrapping and row-shape primitives for the deployment_runs lane.

Contains:
- ``cmd_init``: idempotent DDL for ``deployment_runs``, ``deployment_run_items``,
  ``deployment_run_qa``, ``deployment_preview_environments`` plus the legacy
  ``env_type`` column add-if-missing.
- Row-shape constants: ``RUN_FIELDS``, ``UPDATABLE_FIELDS``, ``_RUN_SELECT``.
- Status enums: ``VALID_STATUSES``, ``VALID_QA_STATUSES``, ``VALID_ENV_TYPES``.
- Pipe-delimited formatters: ``_pipe_row``, ``_pipe_rows``.

These primitives are consumed directly by every deployment_runs sibling and by
the thin shim at ``deployment_runs.py``.
"""

from __future__ import annotations

from typing import Optional

from yoke_core.domain.db_helpers import connect
from yoke_core.domain.runs import RunStatus
from yoke_core.domain.schema_common import _column_exists


# ---------------------------------------------------------------------------
# Row-shape constants
# ---------------------------------------------------------------------------

RUN_FIELDS = (
    "id", "project", "flow", "target_env", "release_lineage",
    "status", "current_stage", "created_at", "started_at",
    "completed_at", "created_by",
)

UPDATABLE_FIELDS = ("status", "current_stage", "target_env", "release_lineage", "created_by")

VALID_STATUSES = tuple(s.value for s in RunStatus)

VALID_QA_STATUSES = ("pending", "passed", "failed", "waived")

VALID_ENV_TYPES = ("shared", "adhoc")

# Standard SELECT fragment for full run rows (COALESCE NULLs to empty strings
# to match the shell pipe-delimited output).
_RUN_SELECT = (
    "id, COALESCE((SELECT p.slug FROM projects p "
    "WHERE p.id = deployment_runs.project_id), '') AS project, "
    "flow, COALESCE(target_env,''), COALESCE(release_lineage,''), "
    "status, COALESCE(current_stage,''), created_at, "
    "COALESCE(started_at,''), COALESCE(completed_at,''), COALESCE(created_by,'')"
)


# ---------------------------------------------------------------------------
# Pipe-delimited formatters
# ---------------------------------------------------------------------------

def _pipe_row(row) -> str:
    """Format a DB row as a pipe-delimited string."""
    return "|".join(str(v) for v in row)


def _pipe_rows(rows) -> str:
    """Format a list of sqlite3.Row as pipe-delimited lines."""
    return "\n".join(_pipe_row(r) for r in rows)


# ---------------------------------------------------------------------------
# DDL bootstrap
# ---------------------------------------------------------------------------

def cmd_init(db_path: Optional[str] = None) -> None:
    """Create tables if not exist (idempotent)."""
    conn = connect(db_path)
    try:
        for statement in (
            """
            CREATE TABLE IF NOT EXISTS deployment_runs (
                id TEXT PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id),
                flow TEXT NOT NULL REFERENCES deployment_flows(id),
                target_env TEXT,
                release_lineage TEXT,
                status TEXT NOT NULL DEFAULT 'created'
                    CHECK(status IN ('created','executing','succeeded','failed','cancelled')),
                current_stage TEXT,
                created_at TEXT NOT NULL,
                started_at TEXT,
                completed_at TEXT,
                created_by TEXT DEFAULT 'operator'
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS deployment_run_items (
                run_id TEXT NOT NULL REFERENCES deployment_runs(id),
                item_id INTEGER NOT NULL,
                added_at TEXT NOT NULL,
                PRIMARY KEY (run_id, item_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS deployment_run_qa (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id TEXT NOT NULL REFERENCES deployment_runs(id),
                check_name TEXT NOT NULL,
                source TEXT NOT NULL DEFAULT 'flow_default',
                blocking INTEGER NOT NULL DEFAULT 1,
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK(status IN ('pending','passed','failed','waived')),
                updated_at TEXT,
                UNIQUE(run_id, check_name)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS deployment_preview_environments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id),
                env_name TEXT NOT NULL,
                run_id TEXT REFERENCES deployment_runs(id),
                status TEXT NOT NULL DEFAULT 'available'
                    CHECK(status IN ('available','claimed','stale')),
                env_type TEXT NOT NULL DEFAULT 'adhoc'
                    CHECK(env_type IN ('shared','adhoc')),
                url TEXT,
                created_at TEXT NOT NULL,
                UNIQUE(project_id, env_name)
            )
            """,
        ):
            conn.execute(statement)
        # Migration: add env_type column if missing (for existing DBs)
        if not _column_exists(conn, "deployment_preview_environments", "env_type"):
            try:
                conn.execute(
                    "ALTER TABLE deployment_preview_environments "
                    "ADD COLUMN env_type TEXT NOT NULL DEFAULT 'adhoc' "
                    "CHECK(env_type IN ('shared','adhoc'))"
                )
                conn.commit()
            except Exception:
                pass
        conn.commit()
    finally:
        conn.close()
