"""Shared dispatch descriptors — the cross-harness substrate for sub-agent spawn.

Every Yoke skill dispatches role-typed sub-agents (engineer, tester, architect,
simulator, boss, product-manager, product-designer). Each harness exposes that
spawn primitive differently:

- **Claude Code** renders an `Agent` tool call with `subagent_type: "yoke-<role>"`
  and a `prompt: |` block.
- **Codex** invokes a `.codex/agents/yoke-<role>.toml` custom-agent adapter.

A `DispatchDescriptor` names the role and the spawn semantics; `render_for_harness`
emits the harness-shaped invocation. Skills consume the rendered string verbatim
and never name harness-specific symbols themselves.

Result-ingestion shape is also descriptor-owned: each role declares a
`result_schema` (VERDICT line, SUBMISSION-CHECKS block, REFLECTION block) so the
parent skill knows how to parse the return regardless of harness.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final

from yoke_core.domain.harness_capability_registry import HARNESS_UNIVERSE


# Canonical role names. Each role corresponds to `runtime/agents/<role>.md` and
# adapter files at `.claude/agents/yoke-<role>.md` / `.codex/agents/yoke-<role>.toml`.
ROLES: Final[tuple[str, ...]] = (
    "engineer",
    "tester",
    "architect",
    "simulator",
    "boss",
    "product-manager",
    "product-designer",
)


# Result-parsing markers. Each role's adapter emits some subset of these in its
# final response. Parent skills pick fields from this schema by role.
REFLECTION_BLOCK: Final[str] = "---REFLECTION-START---"
SUBMISSION_CHECKS_BLOCK: Final[str] = "---SUBMISSION-CHECKS-START---"
VERDICT_PASS_FAIL: Final[str] = "VERDICT: PASS|FAIL"
VERDICT_READY_NOT_READY_CAVEATS: Final[str] = "VERDICT: READY|NOT_READY|CAVEATS"
VERDICT_SIMULATION: Final[str] = "SIMULATION: CLEAN|GAPS FOUND"


# Per-role parseable-result schema. Both harnesses' renderings reference the
# same schema entry so the parent skill parses identically regardless of harness.
ROLE_RESULT_SCHEMA: Final[dict[str, tuple[str, ...]]] = {
    "engineer": (SUBMISSION_CHECKS_BLOCK, REFLECTION_BLOCK),
    "tester": (VERDICT_PASS_FAIL, REFLECTION_BLOCK),
    "architect": (REFLECTION_BLOCK,),
    "simulator": (VERDICT_SIMULATION, REFLECTION_BLOCK),
    "boss": (VERDICT_READY_NOT_READY_CAVEATS, REFLECTION_BLOCK),
    "product-manager": (REFLECTION_BLOCK,),
    "product-designer": (REFLECTION_BLOCK,),
}


# Dispatch kinds. The descriptor names the spawn semantics so the renderer can
# emit the correct surface even when a future harness adds a third primitive.
DISPATCH_KIND_SUBAGENT: Final[str] = "subagent"


@dataclass(frozen=True)
class DispatchDescriptor:
    """A role-shaped dispatch contract independent of harness primitive.

    `role` is one of `ROLES`. `dispatch_kind` is `DISPATCH_KIND_SUBAGENT` for
    all current cases (Claude `Agent`-tool spawn / Codex `.codex/agents/*.toml`
    custom agent). `extras` carries optional invocation metadata such as the
    Claude `model` override (e.g. `"opus"` for retry attempts).
    """

    role: str
    dispatch_kind: str = DISPATCH_KIND_SUBAGENT
    extras: tuple[tuple[str, str], ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if self.role not in ROLES:
            raise ValueError(
                f"unknown dispatch role {self.role!r}; expected one of {ROLES}"
            )
        if self.dispatch_kind != DISPATCH_KIND_SUBAGENT:
            raise ValueError(
                f"unsupported dispatch_kind {self.dispatch_kind!r}; "
                f"only {DISPATCH_KIND_SUBAGENT!r} is defined today"
            )

    @property
    def subagent_type(self) -> str:
        """Stable adapter name shared across both harnesses."""
        return f"yoke-{self.role}"

    @property
    def result_schema(self) -> tuple[str, ...]:
        """Final-response markers a parent skill expects from this role."""
        return ROLE_RESULT_SCHEMA[self.role]


def render_for_harness(descriptor: DispatchDescriptor, harness_id: str) -> str:
    """Emit the harness-shaped sub-agent invocation snippet.

    The returned string is drop-in for skill prose: Claude renders a YAML-like
    Agent-tool block, Codex renders a custom-agent invocation that names the
    `.codex/agents/yoke-<role>.toml` adapter (generated by task 8).
    """
    if harness_id not in HARNESS_UNIVERSE:
        raise ValueError(
            f"unknown harness_id {harness_id!r}; expected one of {HARNESS_UNIVERSE}"
        )
    if harness_id == "claude-code":
        return _render_claude(descriptor)
    if harness_id == "codex":
        return _render_codex(descriptor)
    # Defensive: HARNESS_UNIVERSE membership has already been checked, so any
    # harness id reaching here is a renderer gap, not invalid input.
    raise NotImplementedError(
        f"no dispatch renderer for harness_id={harness_id!r}; "
        f"add a branch when extending HARNESS_UNIVERSE"
    )


def _render_claude(descriptor: DispatchDescriptor) -> str:
    """Render the Claude `Agent`-tool prose snippet.

    Matches the hand-authored shape in
    `.agents/skills/yoke/conduct/dispatch-context-prompts.md`: an `Agent tool:`
    header, a `subagent_type:` line, optional `model:` override from `extras`,
    and a `prompt: |` block placeholder the caller fills in.
    """
    lines = ["Agent tool:", f' subagent_type: "{descriptor.subagent_type}"']
    for key, value in descriptor.extras:
        if key == "model":
            lines.append(f' model: "{value}"')
    lines.append(" prompt: |")
    return "\n".join(lines)


def _render_codex(descriptor: DispatchDescriptor) -> str:
    """Render the Codex custom-agent invocation snippet.

    Codex spawns sub-agents by naming a `.codex/agents/<name>.toml` adapter
    file. The invocation shape is the adapter path plus a `prompt:` block
    placeholder; the parent skill fills the prompt body. Codex `agent:`
    dispatch runs in-process inside the parent harness session, so the
    subagent inherits ``session_id`` / ``cwd`` / hook chain from the
    parent without any auxiliary identity-propagation row.
    """
    adapter_path = f".codex/agents/{descriptor.subagent_type}.toml"
    lines = [f"codex agent: {adapter_path}"]
    for key, value in descriptor.extras:
        if key == "model":
            lines.append(f' model: "{value}"')
    lines.append(" prompt: |")
    return "\n".join(lines)
