"""Schema DDL and table initializer for the Yoke event platform.

Owns the ``events``, ``severity_config``, and ``event_registry`` table DDL
plus the supporting index CREATE statements. The split sibling modules
(``events_writes`` for inserts/severity, ``events_prune`` for retention)
focus on row-level operations and depend on the schema this module owns.
"""

from __future__ import annotations

from typing import Any, Optional

from yoke_core.domain import db_backend
from yoke_core.domain.db_helpers import connect, iso8601_now
from yoke_core.domain.schema_common import _add_column_if_not_exists
from yoke_core.domain.schema_common import _column_exists
from yoke_core.domain.schema_init_actor_path_claim_tables import (
    create_actor_identity_tables,
)
from yoke_core.domain.schema_init_apply import execute_schema_script
from yoke_core.domain.sql_json import json_valid_expr
from yoke_core.domain.projects_restart_schema import _projects_table_sql


# Canonical name of the partial composite index that bounds
# session-scoped tool-call telemetry lookups (audit/correlation queries
# keyed on (session_id, event_name, tool_use_id)). Tests read this
# constant so the index identity has one source of truth.
STOP_CLEANUP_INDEX_NAME = "idx_events_session_event_tool"


def _create_events_table(
    conn: Any,
    *,
    table_name: str = "events",
    include_sprint: bool = False,
    if_not_exists: bool = True,
) -> None:
    _ensure_project_dependency(conn)
    create_actor_identity_tables(conn)
    sprint_col = "                sprint TEXT,\n" if include_sprint else ""
    exists_clause = "IF NOT EXISTS " if if_not_exists else ""
    id_col = (
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if db_backend.connection_is_postgres(conn)
        else "id INTEGER PRIMARY KEY"
    )
    envelope_check = (
        json_valid_expr("envelope")
        if db_backend.connection_is_postgres(conn)
        else "json_valid(envelope)"
    )
    conn.execute(
        f"""
            CREATE TABLE {exists_clause}{table_name} (
                {id_col},
                event_id TEXT UNIQUE NOT NULL,
                source_type TEXT NOT NULL CHECK(source_type IN ('agent','backend','frontend','system','script','hook','skill')),
                session_id TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'INFO',
                event_kind TEXT NOT NULL,
                event_type TEXT NOT NULL,
                event_name TEXT NOT NULL,
                event_outcome TEXT,
                org_id TEXT,
                actor_id INTEGER REFERENCES actors(id),
                environment TEXT,
                service TEXT NOT NULL DEFAULT 'cli',
                project_id INTEGER REFERENCES projects(id),
                item_id TEXT,
                task_num INTEGER,
{sprint_col}                agent TEXT,
                tool_name TEXT,
                duration_ms INTEGER,
                exit_code INTEGER,
                trace_id TEXT,
                parent_id TEXT,
                anomaly_flags TEXT,
                tool_use_id TEXT,
                turn_id TEXT,
                hook_event_name TEXT,
                envelope TEXT CHECK(envelope IS NULL OR {envelope_check}),
                created_at TEXT NOT NULL
            );
        """
    )


def _ensure_project_dependency(conn: Any) -> None:
    """Ensure the events FK target TABLE exists for event-only schema init.

    No project row is seeded: events whose project token cannot be
    resolved index as global (NULL project), so an empty ``projects``
    table is a complete FK target.
    """
    execute_schema_script(conn, _projects_table_sql(if_not_exists=True))


_EVENT_COLUMNS = (
    ("event_outcome", "TEXT"),
    ("org_id", "TEXT"),
    ("environment", "TEXT"),
    ("service", "TEXT NOT NULL DEFAULT 'cli'"),
    ("project_id", "INTEGER REFERENCES projects(id)"),
    ("item_id", "TEXT"),
    ("task_num", "INTEGER"),
    ("agent", "TEXT"),
    ("tool_name", "TEXT"),
    ("duration_ms", "INTEGER"),
    ("exit_code", "INTEGER"),
    ("trace_id", "TEXT"),
    ("parent_id", "TEXT"),
    ("anomaly_flags", "TEXT"),
    ("tool_use_id", "TEXT"),
    ("turn_id", "TEXT"),
    ("hook_event_name", "TEXT"),
    ("envelope", "TEXT"),
)


def _ensure_event_columns(conn: Any) -> None:
    for column, definition in _EVENT_COLUMNS:
        _add_column_if_not_exists(conn, "events", column, definition)


def _actor_id_index_sql(conn: Any) -> list[str]:
    if not _column_exists(conn, "events", "actor_id"):
        return []
    return ["CREATE INDEX IF NOT EXISTS idx_events_actor_id ON events(actor_id)"]


def _execute_schema_statements(conn: Any, statements: list[str], sqlite_script: str) -> None:
    if db_backend.connection_is_postgres(conn):
        for statement in statements:
            conn.execute(statement)
        return
    execute_schema_script(conn, sqlite_script)


def ensure_event_schema(conn: Any) -> None:
    """Create events, severity_config, and event_registry tables on ``conn``.

    Existing ``events`` tables get legacy additive columns here. cloud-runtime
    ``actor_id`` on existing tables is governed by its migration module, not
    by this generic initializer.
    """
    _create_events_table(conn)
    _ensure_event_columns(conn)
    actor_id_index_sqlite = (
        "            CREATE INDEX IF NOT EXISTS idx_events_actor_id ON events(actor_id);\n"
        if _column_exists(conn, "events", "actor_id")
        else ""
    )
    stop_cleanup_index_sql = f"""
            CREATE INDEX IF NOT EXISTS {STOP_CLEANUP_INDEX_NAME}
                ON events(session_id, event_name, tool_use_id)
                WHERE tool_use_id IS NOT NULL
        """
    statements = [
        "DROP INDEX IF EXISTS idx_events_harness_session_id",
        "CREATE INDEX IF NOT EXISTS idx_events_source_type ON events(source_type)",
        "CREATE INDEX IF NOT EXISTS idx_events_session_id ON events(session_id)",
        "CREATE INDEX IF NOT EXISTS idx_events_event_name ON events(event_name)",
        "CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at)",
        *_actor_id_index_sql(conn),
        "CREATE INDEX IF NOT EXISTS idx_events_trace_id ON events(trace_id)",
        "CREATE INDEX IF NOT EXISTS idx_events_project_id ON events(project_id)",
        "CREATE INDEX IF NOT EXISTS idx_events_tool_name ON events(tool_name)",
        "CREATE INDEX IF NOT EXISTS idx_events_kind_type ON events(event_kind, event_type)",
        "CREATE INDEX IF NOT EXISTS idx_events_type_created ON events(event_type, created_at)",
        (
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_events_tool_use_id_dedup "
            "ON events(tool_use_id, event_name) WHERE tool_use_id IS NOT NULL"
        ),
        stop_cleanup_index_sql,
        """
            CREATE TABLE IF NOT EXISTS severity_config (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_name TEXT NOT NULL DEFAULT '*',
                source_type TEXT NOT NULL DEFAULT '*',
                min_severity TEXT NOT NULL DEFAULT 'INFO'
                    CHECK(min_severity IN ('DEBUG','INFO','STATUS','WARN','ERROR','FATAL')),
                created_at TEXT NOT NULL,
                UNIQUE(event_name, source_type)
            )
            """,
        """
            CREATE TABLE IF NOT EXISTS event_registry (
                event_name      TEXT PRIMARY KEY,
                event_kind      TEXT NOT NULL,
                event_type      TEXT NOT NULL,
                owner_service   TEXT NOT NULL,
                description     TEXT NOT NULL,
                context_schema  TEXT,
                severity_default TEXT NOT NULL DEFAULT 'INFO',
                added_in        TEXT,
                status          TEXT NOT NULL DEFAULT 'active'
            )
            """,
    ]
    sqlite_script = """
            DROP INDEX IF EXISTS idx_events_harness_session_id;
            CREATE INDEX IF NOT EXISTS idx_events_source_type ON events(source_type);
            CREATE INDEX IF NOT EXISTS idx_events_session_id ON events(session_id);
            CREATE INDEX IF NOT EXISTS idx_events_event_name ON events(event_name);
            CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
""" + actor_id_index_sqlite + """
            CREATE INDEX IF NOT EXISTS idx_events_trace_id ON events(trace_id);
            CREATE INDEX IF NOT EXISTS idx_events_project_id ON events(project_id);
            CREATE INDEX IF NOT EXISTS idx_events_tool_name ON events(tool_name);
            CREATE INDEX IF NOT EXISTS idx_events_kind_type ON events(event_kind, event_type);
            CREATE INDEX IF NOT EXISTS idx_events_type_created ON events(event_type, created_at);
            CREATE UNIQUE INDEX IF NOT EXISTS idx_events_tool_use_id_dedup ON events(tool_use_id, event_name) WHERE tool_use_id IS NOT NULL;
            -- Session-scoped composite for tool-call telemetry lookups
            -- (audit/correlation queries on session_id + event_name +
            -- tool_use_id). Without it those queries pick
            -- ``idx_events_event_name`` and scan every historical
            -- tool-call row on a busy DB; with it the seek is bounded by
            -- ``session_id`` first.
            CREATE INDEX IF NOT EXISTS """ + STOP_CLEANUP_INDEX_NAME + """
                ON events(session_id, event_name, tool_use_id)
                WHERE tool_use_id IS NOT NULL;

            CREATE TABLE IF NOT EXISTS severity_config (
                id INTEGER PRIMARY KEY,
                event_name TEXT NOT NULL DEFAULT '*',
                source_type TEXT NOT NULL DEFAULT '*',
                min_severity TEXT NOT NULL DEFAULT 'INFO'
                    CHECK(min_severity IN ('DEBUG','INFO','STATUS','WARN','ERROR','FATAL')),
                created_at TEXT NOT NULL,
                UNIQUE(event_name, source_type)
            );

            CREATE TABLE IF NOT EXISTS event_registry (
                event_name      TEXT PRIMARY KEY,
                event_kind      TEXT NOT NULL,
                event_type      TEXT NOT NULL,
                owner_service   TEXT NOT NULL,
                description     TEXT NOT NULL,
                context_schema  TEXT,
                severity_default TEXT NOT NULL DEFAULT 'INFO',
                added_in        TEXT,
                status          TEXT NOT NULL DEFAULT 'active'
            );
        """
    _execute_schema_statements(conn, statements, sqlite_script)
    placeholder = "%s" if db_backend.connection_is_postgres(conn) else "?"
    conn.execute(
        "INSERT INTO severity_config "
        "(event_name, source_type, min_severity, created_at) "
        f"VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}) "
        "ON CONFLICT(event_name, source_type) DO NOTHING",
        ("*", "*", "INFO", iso8601_now()),
    )
    conn.commit()


def cmd_init(db_path: Optional[str] = None) -> None:
    """Create events, severity_config, and event_registry tables (idempotent)."""
    conn = connect(db_path)
    try:
        ensure_event_schema(conn)
    finally:
        if conn is not None:
            conn.close()
