"""Installer campaign rows for installer, PATH, and account foundations."""

# fmt: off
ROWS = (
    ('INSTALL-SMOKE-001', 'Wave 1: Installer And First Wizard Smoke', 'bare-no-uv',
     'Interactive installer, accept uv, auto-launch onboard',
     'Welcome renders; uv consent default is Yes; `Starting Yoke onboard` appears; install summary appears'),
    ('INSTALL-SMOKE-002', 'Wave 1: Installer And First Wizard Smoke', 'bare-no-uv',
     'Installer `--yes`',
     'No TUI launch; prints `Run yoke onboard`; `yoke --version` works'),
    ('INSTALL-SMOKE-003', 'Wave 1: Installer And First Wizard Smoke', 'prepared-yoke',
     'Launch `yoke onboard` directly',
     'PATH screen or install summary appears; no crash'),
    ('INSTALL-SMOKE-004', 'Wave 1: Installer And First Wizard Smoke', 'prepared-yoke',
     'Machine-only stage onboarding',
     'Apply succeeds; report written; `yoke status` reaches stage'),
    ('INSTALL-SMOKE-005', 'Wave 1: Installer And First Wizard Smoke', 'prepared-yoke',
     'Machine-only prod onboarding',
     'Apply succeeds against prod with prod token; active env is prod'),
    ('INSTALL-UV-001', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Accept Astral uv path',
     'uv installed; helper downloaded; product install succeeds'),
    ('INSTALL-UV-002', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Decline uv consent',
     'Friendly decline screen names manual install and rerun command'),
    ('INSTALL-UV-003', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Default Enter on uv consent',
     'Proceeds as Yes'),
    ('INSTALL-UV-004', 'Wave 2: Installer Branches', 'bare-no-curl',
     'Missing curl with no uv',
     'Fails with actionable uv/curl message'),
    ('INSTALL-UV-005', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Script-file invocation with piped `y\\n`',
     'Prompt reads stdin safely; no `/dev/tty` noise'),
    ('INSTALL-UV-006', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Piped shell invocation without `--yes` and no tty',
     'Friendly failure/decline behavior; no raw tty errors'),
    ('INSTALL-UV-007', 'Wave 2: Installer Branches', 'bare-no-uv',
     '`YOKE_INSTALL_YES=1`',
     'No welcome prompt; installs quietly'),
    ('INSTALL-UV-008', 'Wave 2: Installer Branches', 'bare-no-uv',
     '`YOKE_NO_ONBOARD=1`',
     'Installs but never offers or launches onboard'),
    ('INSTALL-UV-009', 'Wave 2: Installer Branches', 'prepared-yoke',
     'Re-run installer',
     'Already-installed or reinstall success screen; no duplicate PATH damage'),
    ('INSTALL-UV-010', 'Wave 2: Installer Branches', 'fault-injection',
     'Bad channel pointer',
     'Failure screen names reason and rerun path'),
    ('INSTALL-UV-011', 'Wave 2: Installer Branches', 'fault-injection',
     'Package index unreachable',
     'Failure screen is actionable; no Python traceback'),
    ('INSTALL-UV-012', 'Wave 2: Installer Branches', 'prepared-screen-term',
     'Installer in screen/dumb terminal',
     'ASCII/plain glyphs; no unsafe glyphs'),
    ('INSTALL-UV-013', 'Wave 2: Installer Branches', 'bare-no-uv',
     'Fresh install with ambient uv indexes pointed away from PyPI',
     'Installer-owned Yoke/PyPI sources win; install succeeds; no ambient index credential appears'),
    ('PATH-001', 'Wave 3: PATH Front Door', 'prepared-path-broken',
     'Default `Add yoke to my PATH`',
     'Writes managed block; verified screen lists login and SSH command results'),
    ('PATH-002', 'Wave 3: PATH Front Door', 'prepared-path-broken',
     'Preview then Add',
     'Preview names exact startup files and block; apply succeeds'),
    ('PATH-003', 'Wave 3: PATH Front Door', 'prepared-path-broken',
     'Skip PATH repair',
     'Account destination picker still reachable; no write'),
    ('PATH-004', 'Wave 3: PATH Front Door', 'prepared-yoke',
     'Already on PATH',
     'All-clear screen; Continue advances'),
    ('PATH-005', 'Wave 3: PATH Front Door', 'prepared-path-broken',
     'SSH-only PATH missing',
     'Writes `.zshenv` or SSH startup file when needed'),
    ('PATH-006', 'Wave 3: PATH Front Door', 'prepared-path-broken',
     'Re-run after path fix',
     'Block not duplicated'),
    ('PATH-007', 'Wave 3: PATH Front Door', 'prepared-screen-term',
     'PATH screens in plain glyph mode',
     'ASCII text only; no box drawing artifacts'),
    ('PATH-008', 'Wave 3: PATH Front Door', 'prepared-yoke',
     'Quit from post-install summary',
     'Exits through the terminal interrupt path with durable code 130'),
    ('AUTH-001', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Stage env, token file',
     'Token verified; actor/org/project summary renders; token-file placeholder reflects selected env; no token leak'),
    ('AUTH-002', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Prod env, token file',
     'Prod API verified; active env prod after Apply'),
    ('AUTH-003', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     "Team-server URL via the picker's team-server lane",
     'Server URL accepted; token verification uses it'),
    ('AUTH-004', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Token paste',
     'Password field masks value; no capture leak'),
    ('AUTH-005', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Missing token file path',
     'Inline/actionable error; can retry'),
    ('AUTH-006', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Empty token file',
     'Friendly error; no crash'),
    ('AUTH-007', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Invalid token',
     'HTTP 401 friendly error; retry path works'),
    ('AUTH-008', 'Wave 4: Account And Yoke Token', 'fault-injection',
     'Valid token but no org/project access',
     'Permission copy is actionable'),
    ('AUTH-009', 'Wave 4: Account And Yoke Token', 'prepared-stored-state',
     'Stored token reuse',
     'Stored credential offered and verified, not blindly trusted'),
    ('AUTH-010', 'Wave 4: Account And Yoke Token', 'prepared-stored-state',
     'Stored token invalid',
     'Replacement route is available'),
    ('AUTH-011', 'Wave 4: Account And Yoke Token', 'prepared-yoke',
     'Token sees many projects/orgs',
     'Projects and orgs lists truncate consistently and do not overflow'),
)
# fmt: on

__all__ = ["ROWS"]
