"""Installer campaign rows for project source, metadata, and publishing."""

# fmt: off
ROWS = (
    ('PROJECT-SOURCE-001', 'Wave 6: Project Source Picker', 'prepared-git',
     'Machine-only',
     'Finish review has only machine/account writes'),
    ('PROJECT-SOURCE-002', 'Wave 6: Project Source Picker', 'prepared-git',
     'Create new project folder',
     'Folder input accepts `~/code/name`; next metadata screen appears'),
    ('PROJECT-SOURCE-003', 'Wave 6: Project Source Picker', 'prepared-git',
     'Existing local checkout',
     'Local path accepted; project metadata flow appears'),
    ('PROJECT-SOURCE-004', 'Wave 6: Project Source Picker', 'prepared-git',
     'Create-new points at existing code',
     'Redirect screen says existing project setup instead'),
    ('PROJECT-SOURCE-005', 'Wave 6: Project Source Picker', 'prepared-git',
     'Clone public repo URL',
     'Source reachable; default branch detected'),
    ('PROJECT-SOURCE-006', 'Wave 6: Project Source Picker', 'prepared-git',
     'Clone private repo with connected App',
     'Refreshed App user access authenticates the clone without persisting in git config'),
    ('PROJECT-SOURCE-007', 'Wave 6: Project Source Picker', 'prepared-git',
     'Clone URL unreachable',
     'Friendly reachability error, not traceback'),
    ('PROJECT-SOURCE-008', 'Wave 6: Project Source Picker', 'prepared-git',
     'Clone source default branch `master`',
     'Branch source recorded as source repo'),
    ('PROJECT-SOURCE-009', 'Wave 6: Project Source Picker', 'prepared-git',
     'Clone destination already non-empty conflict',
     'Inline/path error before Apply'),
    ('PROJECT-SOURCE-010', 'Wave 6: Project Source Picker', 'prepared-no-git',
     'Any checkout mode with no Git',
     'Git prerequisite screen appears before project details'),
    ('PROJECT-SOURCE-011', 'Wave 6: Project Source Picker', 'prepared-no-git',
     'Missing Git, install with package manager',
     'Install action runs; returns to flow when Git is available'),
    ('PROJECT-SOURCE-012', 'Wave 6: Project Source Picker', 'prepared-no-git-no-sudo',
     'Missing Git with no package manager/sudo',
     'Manual-only guidance; no dead-end'),
    ('PROJECT-SOURCE-013', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke denied',
     'Access-gate error friendly'),
    ('PROJECT-SOURCE-014', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke allowed',
     'Routes to source-dev/admin plan without accidental product writes'),
    ('PROJECT-SOURCE-015', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke into a fresh folder',
     'Post-apply: real clone with expected tree and git history; source-link symlinks and hooks present'),
    ('PROJECT-SOURCE-016', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke into an existing Yoke checkout',
     'Detected and reused; post-apply source-link install has symlinks and hooks, no product-copy dirs'),
    ('PROJECT-SOURCE-017', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke into a non-empty non-Yoke folder',
     'Refused before Apply; no product scaffold written; no `done`'),
    ('PROJECT-SOURCE-018', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke default folder and review wording',
     'Default folder and review copy are correct for source-dev'),
    ('PROJECT-SOURCE-019', 'Wave 6: Project Source Picker', 'prepared-git',
     'Develop Yoke push credential',
     'Post-apply: origin names Yoke repo and `git push --dry-run` authenticates'),
    ('PROJECT-META-001', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Valid slug/name/prefix/default branch',
     'Reaches review'),
    ('PROJECT-META-002', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Empty slug',
     'Inline validation blocks'),
    ('PROJECT-META-003', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Slug with invalid chars',
     'Inline validation message'),
    ('PROJECT-META-004', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Very long slug',
     'Validation/wrapping is readable'),
    ('PROJECT-META-005', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Empty display name',
     'Inline validation blocks'),
    ('PROJECT-META-006', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Branch prefix invalid',
     'Inline validation blocks'),
    ('PROJECT-META-007', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Public item prefix invalid',
     'Inline validation blocks'),
    ('PROJECT-META-008', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Multiple orgs visible',
     'Owner/org picker is clear'),
    ('PROJECT-META-009', 'Wave 7: Project Metadata Inputs', 'fault-injection',
     '`board.data.get` failure during board-art write',
     'Apply failure text is friendly and names the failing function and write step'),
    ('PROJECT-META-010', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Leading `~` immediate typing',
     'First char preserved in input'),
    ('PROJECT-META-011', 'Wave 7: Project Metadata Inputs', 'prepared-git',
     'Leading `~` settled typing',
     'Path accepted; validates baseline'),
    ('PUBLISH-001', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Create project, no GitHub publish',
     'No repo create planned'),
    ('PUBLISH-002', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Publish to user owner',
     'Owner picker, repo name, visibility, review plan correct'),
    ('PUBLISH-003', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Publish to org owner',
     'Org owner renders and applies'),
    ('PUBLISH-004', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Repo exists and empty',
     'Review note says Yoke will reuse/adopt'),
    ('PUBLISH-005', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Repo exists non-empty',
     'Block before Apply'),
    ('PUBLISH-006', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'App cannot create private repo',
     'Block before Apply'),
    ('PUBLISH-007', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'App can create but cannot push',
     'Block before orphaning empty repo'),
    ('PUBLISH-008', 'Wave 8: Publish And GitHub Adoption', 'fault-injection',
     'Repo created then push fails',
     'Failure report names repo, start-over cleanup, and retry resumes push'),
    ('PUBLISH-009', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Project uses backlog-only mode',
     'No binding stored'),
    ('PUBLISH-010', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Project GitHub App binding',
     'Project records the selected App installation/repository'),
    ('PUBLISH-011', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Project GitHub App binding unavailable',
     'Project remains backlog-only; no credential secret is stored'),
    ('PUBLISH-012', 'Wave 8: Publish And GitHub Adoption', 'prepared-git',
     'Project GitHub App binding reuse',
     'Project binding traces to the installed App repository'),
)
# fmt: on

__all__ = ["ROWS"]
