"""Installer campaign rows for apply, terminal, state, macOS, and modes."""

# fmt: off
ROWS = (
    ('APPLY-001', 'Wave 9: Review, Apply, Resume', 'prepared-yoke',
     'Machine-only review',
     'Plan groups machine/account writes; Apply success'),
    ('APPLY-002', 'Wave 9: Review, Apply, Resume', 'prepared-git',
     'Full create-project review',
     'Machine, account, control-plane, repo-local groups visible'),
    ('APPLY-003', 'Wave 9: Review, Apply, Resume', 'prepared-git',
     'Full clone/import review',
     'Clone/install/board steps visible'),
    ('APPLY-004', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Machine config write failure',
     'Report path and resume command shown'),
    ('APPLY-005', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Token store failure',
     'No token leak; resume possible'),
    ('APPLY-006', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Project create failure',
     'Friendly permission/HTTP text'),
    ('APPLY-007', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Clone failure',
     'Target folder recovery instructions'),
    ('APPLY-008', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Publish failure',
     'Empty repo recovery guidance if relevant; matching-origin retry does not skip push'),
    ('APPLY-009', 'Wave 9: Review, Apply, Resume', 'fault-injection',
     'Board-art/write-board failure',
     'Failure is grouped under repo-local write'),
    ('APPLY-010', 'Wave 9: Review, Apply, Resume', 'prepared-git',
     'Resume after partial failure',
     'Resume completes or reports exact remaining blocker'),
    ('APPLY-011', 'Wave 9: Review, Apply, Resume', 'prepared-git',
     'Apply report audit',
     'Report has `secret_free: true`; captures have no secrets'),
    ('APPLY-012', 'Wave 9: Review, Apply, Resume', 'prepared-git',
     'Ctrl-C during Apply',
     'Blocked or handled cleanly; no partial silent teardown'),
    ('TERM-001', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     '80x24 terminal',
     'Readable or scrollable; no fatal layout'),
    ('TERM-002', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     '100x32 terminal',
     'Matches golden-sized expectations'),
    ('TERM-003', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     '140x40 terminal',
     'Wide layout readable'),
    ('TERM-004', 'Wave 10: Terminal Interaction And Layout', 'prepared-screen-term',
     '`TERM=screen-256color`',
     'Plain glyphs; no unsafe glyphs'),
    ('TERM-005', 'Wave 10: Terminal Interaction And Layout', 'prepared-screen-term',
     '`TERM=dumb`',
     'Plain fallback; no unsafe glyphs; no crash'),
    ('TERM-006', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Up/Down on single Continue action',
     'Selection remains stable without exposing a fake Quit action'),
    ('TERM-007', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Space selects',
     'Same as Enter'),
    ('TERM-008', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Ctrl-J selects',
     'Same as Enter'),
    ('TERM-009', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Escape backs out of each step',
     'History works; no dead ends'),
    ('TERM-010', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Ctrl-C before Apply',
     'Exits cleanly'),
    ('TERM-011', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Mouse reporting off under screen compat',
     'No garbled mouse escape noise'),
    ('TERM-012', 'Wave 10: Terminal Interaction And Layout', 'prepared-git',
     'Very long repo/org/project names',
     'Wrap is readable; no overlap'),
    ('STATE-001', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Reuse active Yoke connection',
     'Verifies stored token; no blind trust'),
    ('STATE-002', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Reuse machine GitHub App authorization',
     'Verifies stored authorization; no blind trust'),
    ('STATE-003', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'One stored project checkout',
     'Auto-routes to project verification'),
    ('STATE-004', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Multiple stored project checkouts',
     'Picker appears'),
    ('STATE-005', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Stored project no longer visible',
     'Friendly lookup error and alternate path'),
    ('STATE-006', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Stage and prod credentials on same machine',
     'Env switch works; `YOKE_ENV` override works'),
    ('STATE-007', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Re-run onboarding after success',
     'No duplicate config; no duplicate PATH block'),
    ('STATE-008', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'One-shot SSH command after PATH repair',
     "`ssh host 'command -v yoke; yoke --version'` works"),
    ('STATE-009', 'Wave 11: Stored State And Repeatability', 'prepared-stored-state',
     'Reset script then reinstall',
     'Host returns to clean state and smoke passes'),
    ('MAC-001', 'Wave 12: macOS Lane', 'test Mac',
     'Stage installer in real SSH TTY',
     'Auto-launches wizard; PATH repair works'),
    ('MAC-002', 'Wave 12: macOS Lane', 'test Mac',
     '`ssh -tt -e none` leading `~` path input',
     'Leading `~` is preserved'),
    ('MAC-003', 'Wave 12: macOS Lane', 'test Mac',
     'No Command Line Tools, no Homebrew',
     'Apple Tools handoff screen; Check again works'),
    ('MAC-004', 'Wave 12: macOS Lane', 'test Mac',
     'No Command Line Tools with sudo session',
     '`softwareupdate` path installs tools and continues'),
    ('MAC-005', 'Wave 12: macOS Lane', 'test Mac',
     'Homebrew present',
     'Git recovery chooses `brew install git`'),
    ('MAC-006', 'Wave 12: macOS Lane', 'test Mac',
     'Visible Terminal PTY bridge',
     'Log captures TUI while child sees real terminal size; per-screen region screenshots through Terminal.app succeed'),
    ('MAC-007', 'Wave 12: macOS Lane', 'test Mac',
     'One-shot SSH PATH after full onboard',
     '`command -v uv; command -v uvx; command -v yoke` works once the wizard wrote `.zprofile` and `.zshenv`'),
    ('MAC-008', 'Wave 12: macOS Lane', 'test Mac',
     'Stage + prod credentials',
     'Env switching works without reinstalling project'),
    ('MAC-009', 'Wave 12: macOS Lane', 'test Mac',
     'Develop Yoke into a fresh `~/code/yoke`',
     'Post-apply: real clone, source-link symlinks, git hooks, and `git push --dry-run` authenticates'),
    ('MAC-010', 'Wave 12: macOS Lane', 'test Mac',
     'PATH repair writes both startup files',
     'Fresh login shell and one-shot SSH command both resolve `yoke`'),
    ('MAC-011', 'Wave 12: macOS Lane', 'test Mac',
     'Full `curl | bash` in Terminal.app, wizard left by `Quit`',
     'Shim hand-off block is the last screen and names reload, harness, and `/yoke onboard` in that order'),
    ('MAC-012', 'Wave 12: macOS Lane', 'test Mac',
     'Re-run the installer from a fresh login shell after PATH repair',
     'Hand-off drops the reload step; harness step is numbered 1'),
    ('LOCAL-BIRTH-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     '`yoke init --local`, then open the local universe',
     'Post-apply: local Postgres and API are healthy; one human actor exists; no user table or signup step appears; `yoke status` and the two-view UI both reach the new universe'),
    ('MODE-PICKER-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Onboard destination = this machine',
     'Post-apply: local birth completes; active connection is `local-postgres`; no hosted credential is written'),
    ('MODE-PICKER-002', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Onboard destination = team server',
     'Server URL and OIDC sign-in are required; Post-apply: connection uses `https`; no local universe is born'),
    ('MODE-PICKER-003', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Onboard destination = upyoke.com',
     'Post-apply: hosted sign-in completes; existing hosted projects are listed for clone/map; no duplicate project is created'),
    ('SELF-HOST-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Initialize the published self-host bundle, Compose up, then `yoke connect`',
     'Post-apply: server and Postgres containers are healthy; OIDC door signs in; connected CLI reports the exact server release; mounted App key is file-only and absent from retained evidence'),
    ('HOSTED-CONNECT-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Sign in to upyoke.com, create an org/project backlog-only, then connect the CLI',
     'Post-apply: platform membership maps to one tenant actor; board skeleton exists before machine mapping; CLI reuses the hosted project instead of creating another'),
    ('HOSTED-GITHUB-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Install the hosted GitHub App, choose a repository, create and bind its project',
     'Post-apply: platform installation and repository inventory exist; tenant binding is active; issue sync uses installation-token auth; no user token appears in browser, reports, or project settings'),
    ('PORTABILITY-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Export a populated local universe and upload it to a fresh hosted org',
     'Post-apply: stable-table digest and row counts match; hosted actor/token identities are regenerated; imported items, strategy, and projects render'),
    ('PORTABILITY-002', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Download a hosted universe and import it into a fresh local universe',
     'Post-apply: stable-table digest and row counts match; platform identities are absent; local bootstrap actor can read the imported work'),
    ('UPGRADE-001', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Upgrade an existing local universe to the next signed release',
     'Post-apply: release pin changes exactly once; migrations complete; data and API token remain usable; second upgrade is idempotent'),
    ('UPGRADE-002', 'Wave 13: Open Source Mode Closing Regression', 'prepared-yoke',
     'Pull the next signed self-host server image and restart Compose',
     'Post-apply: image digest and version endpoint match the target release; migrate-on-boot completes; OIDC sign-in and existing project reads remain healthy'),
)
# fmt: on

__all__ = ["ROWS"]
