"""``item_activity_days`` rollup — board activity state owner.

One row per ``(project_id, item_id, day)`` an item was touched by a REAL
item-scoped domain mutation: a status transition (item or epic task), a
work-claim acquire/release, a structured-field / section / progress-log
write, an epic-task body/metadata mutation, or a qa requirement/run write.

This is deliberately NOT an ``emit_event`` chokepoint and NOT tool-call
attribution — state must never depend on the telemetry pipeline. Each
domain mutation site calls :func:`touch_item_activity` directly. Decision
record: ``docs/archive/decisions/board-activity-semantics.md``.

The surrogate ``id`` column is the board cache's monotonic high-water
mark (``MAX(id)`` advances exactly when a new (project, item, day) tuple
lands), replacing the retired ``events.id`` watermark. Natural-key
uniqueness is enforced by ``UNIQUE(project_id, item_id, day)``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from yoke_core.domain import db_backend

_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS item_activity_days (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  day TEXT NOT NULL,
  UNIQUE(project_id, item_id, day)
)
"""

_TABLE_DDL_POSTGRES = _TABLE_DDL.replace(
    "id INTEGER PRIMARY KEY",
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
)


def _p(conn: Any) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def ensure_schema(conn: Any) -> None:
    """Create ``item_activity_days`` if missing (minimal test DBs).

    The canonical schema owner is ``yoke_core.domain.schema``; this
    helper keeps fixture DBs self-sufficient. Idempotent.
    """
    ddl = (
        _TABLE_DDL_POSTGRES
        if db_backend.connection_is_postgres(conn)
        else _TABLE_DDL
    )
    conn.execute(ddl)
    conn.commit()


def current_utc_day() -> str:
    """Return today's UTC ``YYYY-MM-DD`` bucket.

    Matches the backfill semantics: days are bucketed from UTC ISO
    timestamps (``substring(created_at, 1, 10)``).
    """
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def touch_item_activity(
    conn: Any,
    *,
    item_id: Any,
    project_id: Optional[int] = None,
    day: Optional[str] = None,
) -> bool:
    """Record "this item was touched today" — best-effort, same txn.

    Resolves ``project_id`` from ``items`` when not given. Uses a
    savepoint so a failure (missing table on a minimal fixture DB,
    unknown item) never poisons the caller's open transaction. The
    caller's own ``conn.commit()`` persists the row. Returns True when
    the upsert executed (including conflict no-ops), False when skipped.
    """
    try:
        numeric_item = int(str(item_id).strip().upper().replace("YOK-", ""))
    except (TypeError, ValueError):
        return False
    bucket = day or current_utc_day()
    p = _p(conn)
    try:
        conn.execute("SAVEPOINT item_activity_touch")
        if project_id is None:
            row = conn.execute(
                f"SELECT project_id FROM items WHERE id = {p}",
                (numeric_item,),
            ).fetchone()
            if row is None or row[0] is None:
                conn.execute("ROLLBACK TO SAVEPOINT item_activity_touch")
                conn.execute("RELEASE SAVEPOINT item_activity_touch")
                return False
            project_id = int(row[0])
        conn.execute(
            "INSERT INTO item_activity_days (project_id, item_id, day) "
            f"VALUES ({p}, {p}, {p}) "
            "ON CONFLICT(project_id, item_id, day) DO NOTHING",
            (int(project_id), numeric_item, bucket),
        )
        conn.execute("RELEASE SAVEPOINT item_activity_touch")
        return True
    except Exception:
        try:
            conn.execute("ROLLBACK TO SAVEPOINT item_activity_touch")
            conn.execute("RELEASE SAVEPOINT item_activity_touch")
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        return False


def touch_for_qa_requirement(conn: Any, requirement_id: Any) -> bool:
    """Touch the item (or parent epic) a qa requirement targets.

    Deployment-run-scoped requirements are not item activity — skipped.
    """
    p = _p(conn)
    try:
        conn.execute("SAVEPOINT item_activity_qa")
        row = conn.execute(
            f"SELECT item_id, epic_id FROM qa_requirements WHERE id = {p}",
            (int(requirement_id),),
        ).fetchone()
        conn.execute("RELEASE SAVEPOINT item_activity_qa")
    except Exception:
        try:
            conn.execute("ROLLBACK TO SAVEPOINT item_activity_qa")
            conn.execute("RELEASE SAVEPOINT item_activity_qa")
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        return False
    if row is None:
        return False
    target = row[0] if row[0] is not None else row[1]
    if target is None:
        return False
    return touch_item_activity(conn, item_id=target)


__all__ = [
    "current_utc_day",
    "ensure_schema",
    "touch_for_qa_requirement",
    "touch_item_activity",
]
