"""``item_status_transitions`` — item/task status transition history.

First-class state table written at mutation time by every status writer
(the backlog lifecycle executor, the epic-task status pipeline, the
cascade, repair surfaces, and the HTTP write/approve routes). Replaces
the retired ``ItemStatusChanged`` / ``TaskStatusChanged`` envelope scans
for board velocity, item execution status, GitHub evidence summaries,
drift review delivered-deltas, and the lifecycle Doctor HCs — the events
ledger stays telemetry-only.

Rows are append-only. ``task_num IS NULL`` marks an item-level
transition; non-null marks an epic-task transition (``item_id`` is the
parent epic's item id). Recording also upserts the
``item_activity_days`` rollup — a transition IS item activity.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, Optional

from yoke_core.domain import db_backend
from yoke_core.domain.item_activity import touch_item_activity

_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS item_status_transitions (
  id INTEGER PRIMARY KEY,
  item_id INTEGER NOT NULL,
  task_num INTEGER,
  from_status TEXT,
  to_status TEXT NOT NULL,
  source TEXT,
  session_id TEXT,
  actor_id INTEGER,
  project_id INTEGER,
  created_at TEXT NOT NULL
)
"""

_TABLE_DDL_POSTGRES = _TABLE_DDL.replace(
    "id INTEGER PRIMARY KEY",
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
)

_INDEX_DDL = (
    "CREATE INDEX IF NOT EXISTS idx_item_status_transitions_item_created "
    "ON item_status_transitions(item_id, created_at)"
)


def _p(conn: Any) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def ensure_schema(conn: Any) -> None:
    """Create the table + index if missing (minimal test DBs). Idempotent."""
    ddl = (
        _TABLE_DDL_POSTGRES
        if db_backend.connection_is_postgres(conn)
        else _TABLE_DDL
    )
    conn.execute(ddl)
    conn.execute(_INDEX_DDL)
    conn.commit()


def _resolve_identity(conn: Any, session_id: Optional[str]) -> tuple:
    """Resolve (session_id, actor_id) — ambient when not supplied."""
    if not session_id:
        try:
            from yoke_core.domain.session_ambient_identity import (
                resolve_ambient_session_id,
            )

            session_id = resolve_ambient_session_id()
        except Exception:
            session_id = None
    actor_id: Optional[int] = None
    if session_id:
        try:
            row = conn.execute(
                f"SELECT actor_id FROM harness_sessions WHERE session_id = {_p(conn)}",
                (session_id,),
            ).fetchone()
            if row is not None and row[0] is not None:
                actor_id = int(row[0])
        except Exception:
            actor_id = None
    return session_id, actor_id


def _record(
    conn: Any,
    *,
    item_id: Any,
    task_num: Optional[int],
    from_status: Optional[str],
    to_status: str,
    source: Optional[str],
    session_id: Optional[str],
    project_id: Optional[int],
) -> bool:
    try:
        numeric_item = int(str(item_id).strip().upper().replace("YOK-", ""))
    except (TypeError, ValueError):
        return False
    p = _p(conn)
    try:
        conn.execute("SAVEPOINT item_status_transition")
        if project_id is None:
            row = conn.execute(
                f"SELECT project_id FROM items WHERE id = {p}",
                (numeric_item,),
            ).fetchone()
            project_id = int(row[0]) if row is not None and row[0] is not None else None
        resolved_session, actor_id = _resolve_identity(conn, session_id)
        conn.execute(
            "INSERT INTO item_status_transitions "
            "(item_id, task_num, from_status, to_status, source, "
            " session_id, actor_id, project_id, created_at) "
            f"VALUES ({p}, {p}, {p}, {p}, {p}, {p}, {p}, {p}, {p})",
            (
                numeric_item,
                task_num,
                from_status or None,
                to_status,
                source or None,
                resolved_session or None,
                actor_id,
                project_id,
                _now_iso(),
            ),
        )
        conn.execute("RELEASE SAVEPOINT item_status_transition")
    except Exception:
        try:
            conn.execute("ROLLBACK TO SAVEPOINT item_status_transition")
            conn.execute("RELEASE SAVEPOINT item_status_transition")
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        return False
    touch_item_activity(conn, item_id=numeric_item, project_id=project_id)
    if task_num is not None:
        # A task transition is task activity for chain-head freshness.
        from yoke_core.domain.claim_chain_state import touch_epic_task_activity

        touch_epic_task_activity(
            conn, epic_id=numeric_item, task_num=task_num,
        )
    return True


def record_item_transition(
    conn: Any,
    *,
    item_id: Any,
    from_status: Optional[str],
    to_status: str,
    source: Optional[str] = None,
    session_id: Optional[str] = None,
    project_id: Optional[int] = None,
) -> bool:
    """Record an item-level status transition (best-effort, caller's txn).

    Uses a savepoint so minimal fixture DBs without the table never see
    the caller's transaction poisoned. The caller's ``conn.commit()``
    persists the row.
    """
    return _record(
        conn,
        item_id=item_id,
        task_num=None,
        from_status=from_status,
        to_status=to_status,
        source=source,
        session_id=session_id,
        project_id=project_id,
    )


def record_task_transition(
    conn: Any,
    *,
    epic_id: Any,
    task_num: Any,
    from_status: Optional[str],
    to_status: str,
    source: Optional[str] = None,
    session_id: Optional[str] = None,
    project_id: Optional[int] = None,
) -> bool:
    """Record an epic-task status transition (``item_id`` = parent epic)."""
    try:
        numeric_task = int(task_num)
    except (TypeError, ValueError):
        return False
    return _record(
        conn,
        item_id=epic_id,
        task_num=numeric_task,
        from_status=from_status,
        to_status=to_status,
        source=source,
        session_id=session_id,
        project_id=project_id,
    )


def record_and_emit_item_status_change(
    conn: Any,
    *,
    item_id: int,
    from_status: str,
    to_status: str,
    source: str,
    out: Any = None,
) -> None:
    """State first, telemetry second: the shared item-status-change tail.

    Records the transition row (committing it), then emits the
    ``ItemStatusChanged`` telemetry event through the canonical backlog
    emitter. Shared by the backlog update/close executors and the HTTP
    write/approve routes so the pairing stays identical everywhere.
    """
    import sys

    record_item_transition(
        conn,
        item_id=item_id,
        from_status=from_status,
        to_status=to_status,
        source=source,
    )
    conn.commit()
    from yoke_core.domain import backlog_rendering

    backlog_rendering._emit_event(
        "ItemStatusChanged",
        item_id,
        {
            "from_status": from_status,
            "to_status": to_status,
            "source": source,
        },
        out if out is not None else sys.stderr,
    )


def latest_transition(conn: Any, item_id: Any) -> Optional[Dict[str, Any]]:
    """Return the most recent transition row for *item_id* (item or task).

    Tolerant of a missing table (returns ``None``) so projection
    surfaces stay usable on minimal fixture DBs.
    """
    try:
        numeric_item = int(str(item_id).strip().upper().replace("YOK-", ""))
    except (TypeError, ValueError):
        return None
    p = _p(conn)
    try:
        row = conn.execute(
            "SELECT task_num, from_status, to_status, source, created_at "
            f"FROM item_status_transitions WHERE item_id = {p} "
            "ORDER BY id DESC LIMIT 1",
            (numeric_item,),
        ).fetchone()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        return None
    if row is None:
        return None
    return {
        "task_num": row[0],
        "from_status": row[1],
        "to_status": row[2],
        "source": row[3],
        "created_at": row[4],
    }


__all__ = [
    "ensure_schema",
    "latest_transition",
    "record_and_emit_item_status_change",
    "record_item_transition",
    "record_task_transition",
]
