"""migration_audit table DDL + idempotent bootstrap helper.

Yoke's governed migration apply contract writes audit rows to the
model's authoritative DB. For
Yoke-as-project the authoritative DB and the control plane DB
coincide, so `schema_init_tables.create_governed_tables` covers the
table at control-plane init. Project-configured recipes and runners let
webapp projects declare their own authoritative DB; that webapp
authoritative DB also needs `migration_audit` bootstrapped. This module is that
bootstrap — called from `migration_apply_rehearse._rehearse_inner`
and `migration_apply_live._live_apply_inner` after the audit
connection opens, and reused by `create_governed_tables` so the DDL
has one source of truth.
"""

from __future__ import annotations

from typing import Any

from yoke_core.domain.schema_init_apply import execute_schema_script


MIGRATION_AUDIT_DDL = """
    CREATE TABLE IF NOT EXISTS migration_audit (
        id INTEGER PRIMARY KEY,
        migration_name TEXT NOT NULL,
        description TEXT,
        tables_declared TEXT NOT NULL,
        expected_deltas TEXT NOT NULL,
        pre_row_counts TEXT NOT NULL,
        post_row_counts TEXT,
        pre_fk_violations INTEGER NOT NULL DEFAULT 0,
        post_fk_violations INTEGER,
        backup_path TEXT NOT NULL,
        state TEXT NOT NULL DEFAULT 'planned'
            CHECK(state IN (
                'planned','test_copy_created','test_applied',
                'test_verified','rehearsed','backup_created',
                'live_applied','live_verified','completed',
                'test_copy_failed','test_apply_failed',
                'test_verify_failed','backup_failed',
                'live_apply_failed','live_verify_failed'
            )),
        failure_reason TEXT,
        exception_reason TEXT,
        source_fingerprint TEXT,
        rehearsed_at TEXT,
        lease_id INTEGER,
        test_copy_path TEXT,
        baseline_verify_result TEXT,  -- → JSONB on Postgres
        author_verify_result TEXT,  -- → JSONB on Postgres
        session_id TEXT,
        model_name TEXT,
        project_id INTEGER,
        actor_id TEXT,
        worktree TEXT,
        source_branch TEXT,
        source_commit TEXT,
        integration_target TEXT,
        change_class TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        duration_ms INTEGER
    );
"""


MIGRATION_AUDIT_POSTGRES_DDL = """
    CREATE TABLE IF NOT EXISTS migration_audit (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        migration_name TEXT NOT NULL,
        description TEXT,
        tables_declared TEXT NOT NULL,
        expected_deltas TEXT NOT NULL,
        pre_row_counts TEXT NOT NULL,
        post_row_counts TEXT,
        pre_fk_violations INTEGER NOT NULL DEFAULT 0,
        post_fk_violations INTEGER,
        backup_path TEXT NOT NULL,
        state TEXT NOT NULL DEFAULT 'planned'
            CHECK(state IN (
                'planned','test_copy_created','test_applied',
                'test_verified','rehearsed','backup_created',
                'live_applied','live_verified','completed',
                'test_copy_failed','test_apply_failed',
                'test_verify_failed','backup_failed',
                'live_apply_failed','live_verify_failed'
            )),
        failure_reason TEXT,
        exception_reason TEXT,
        source_fingerprint TEXT,
        rehearsed_at TEXT,
        lease_id INTEGER,
        test_copy_path TEXT,
        baseline_verify_result TEXT,
        author_verify_result TEXT,
        session_id TEXT,
        model_name TEXT,
        project_id INTEGER,
        actor_id TEXT,
        worktree TEXT,
        source_branch TEXT,
        source_commit TEXT,
        integration_target TEXT,
        change_class TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        duration_ms INTEGER
    );
"""


def ensure_migration_audit_table(conn: Any) -> None:
    """Idempotently create migration_audit on *conn*.

    Used both at Yoke control-plane init (via create_governed_tables)
    and at first governed apply against a non-Yoke project's
    authoritative DB. `coordination_leases` is deliberately NOT
    bootstrapped here — leases live on the Yoke control plane.
    """
    from yoke_core.domain import db_backend

    if db_backend.connection_is_postgres(conn):
        ensure_migration_audit_table_postgres(conn)
        return

    execute_schema_script(conn, MIGRATION_AUDIT_DDL)
    conn.commit()


def ensure_migration_audit_table_postgres(conn: Any) -> None:
    """Idempotently create ``migration_audit`` using native Postgres DDL."""
    conn.execute(MIGRATION_AUDIT_POSTGRES_DDL)
    conn.commit()
