"""migration_audit table DDL + idempotent bootstrap helper.

Yoke's governed migration apply contract writes audit rows to the
model's authoritative DB. For
Yoke-as-project the authoritative DB and the control plane DB
coincide, so `schema_init_tables.create_governed_tables` covers the
table at control-plane init. Project-configured recipes and runners let
webapp projects declare their own authoritative DB; that webapp
authoritative DB also needs `migration_audit` bootstrapped. This module is that
bootstrap — called from `migration_apply_rehearse._rehearse_inner`
after the audit
connection opens, and reused by `create_governed_tables` so the DDL
has one source of truth.
"""

from __future__ import annotations

from typing import Any

from yoke_core.domain.schema_common import _add_column_if_not_exists
from yoke_core.domain.schema_init_apply import execute_schema_script
from yoke_core.domain.migration_content_schema import (
    AdoptionEvidenceContract,
    converge_migration_content_schema,
)
from yoke_core.domain.migration_ledger_contract import LedgerContract


MIGRATION_AUDIT_DDL = """
    CREATE TABLE IF NOT EXISTS migration_audit (
        id INTEGER PRIMARY KEY,
        migration_name TEXT NOT NULL,
        description TEXT,
        tables_declared TEXT NOT NULL,
        expected_deltas TEXT NOT NULL,
        pre_row_counts TEXT NOT NULL,
        post_row_counts TEXT,
        pre_fk_violations INTEGER NOT NULL DEFAULT 0,
        post_fk_violations INTEGER,
        backup_path TEXT NOT NULL,
        state TEXT NOT NULL DEFAULT 'planned'
            CHECK(state IN (
                'planned','test_copy_created','test_applied',
                'test_verified','rehearsed','backup_created',
                'live_applied','live_verified','completed',
                'test_copy_failed','test_apply_failed',
                'test_verify_failed','backup_failed',
                'live_apply_failed','live_verify_failed'
            )),
        failure_reason TEXT,
        exception_reason TEXT,
        source_fingerprint TEXT,
        rehearsed_at TEXT,
        lease_id INTEGER,
        test_copy_path TEXT,
        baseline_verify_result TEXT,  -- → JSONB on Postgres
        author_verify_result TEXT,  -- → JSONB on Postgres
        session_id TEXT,
        model_name TEXT,
        project_id INTEGER,
        actor_id TEXT,
        worktree TEXT,
        source_branch TEXT,
        source_commit TEXT,
        integration_target TEXT,
        change_class TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        duration_ms INTEGER
    );
"""


MIGRATION_AUDIT_POSTGRES_DDL = """
    CREATE TABLE IF NOT EXISTS migration_audit (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        migration_name TEXT NOT NULL,
        description TEXT,
        tables_declared TEXT NOT NULL,
        expected_deltas TEXT NOT NULL,
        pre_row_counts TEXT NOT NULL,
        post_row_counts TEXT,
        pre_fk_violations INTEGER NOT NULL DEFAULT 0,
        post_fk_violations INTEGER,
        backup_path TEXT NOT NULL,
        state TEXT NOT NULL DEFAULT 'planned'
            CHECK(state IN (
                'planned','test_copy_created','test_applied',
                'test_verified','rehearsed','backup_created',
                'live_applied','live_verified','completed',
                'test_copy_failed','test_apply_failed',
                'test_verify_failed','backup_failed',
                'live_apply_failed','live_verify_failed'
            )),
        failure_reason TEXT,
        exception_reason TEXT,
        source_fingerprint TEXT,
        rehearsed_at TEXT,
        lease_id INTEGER,
        test_copy_path TEXT,
        baseline_verify_result TEXT,
        author_verify_result TEXT,
        session_id TEXT,
        model_name TEXT,
        project_id INTEGER,
        actor_id TEXT,
        worktree TEXT,
        source_branch TEXT,
        source_commit TEXT,
        integration_target TEXT,
        change_class TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        duration_ms INTEGER
    );
"""


def ensure_migration_audit_table(conn: Any) -> None:
    """Idempotently create migration_audit on *conn*.

    Used both at Yoke control-plane init (via create_governed_tables)
    and at first governed apply against a non-Yoke project's
    authoritative DB. `work_claims` is deliberately NOT
    bootstrapped here — leases live on the Yoke control plane.
    """
    from yoke_core.domain import db_backend

    if db_backend.connection_is_postgres(conn):
        ensure_migration_audit_table_postgres(conn)
        return

    execute_schema_script(conn, MIGRATION_AUDIT_DDL)
    conn.commit()


def ensure_migration_audit_table_postgres(conn: Any) -> None:
    """Idempotently create ``migration_audit`` using native Postgres DDL."""
    conn.execute(MIGRATION_AUDIT_POSTGRES_DDL)
    conn.commit()


def ensure_migration_ledger_table(
    conn: Any,
    ledger: LedgerContract,
    evidence: AdoptionEvidenceContract,
    *,
    repair_existing_guards: bool = False,
) -> None:
    """Idempotently converge one caller-declared membership ledger.

    Shares its DDL with every consumer for the same reason
    :func:`ensure_migration_audit_table` does: a ledger that differs between
    the control plane, a project's authoritative database, and the test
    fixture schema would make "is this database current?" mean three things.

    ``CREATE TABLE IF NOT EXISTS`` does nothing where the table already
    stands, so a column added to the DDL above never reaches a database born
    before it. Each such column is converged explicitly — without that step
    the oldest ledgers, which are exactly the ones most likely to hold an
    entry a running build cannot survive, would be the ones missing the
    column that says so.

    A ledger created by this call receives the exact evidence and membership
    guards. A ledger that already existed receives only additive schema unless
    a trusted migration or adoption caller requests ``repair_existing_guards``.
    """
    from yoke_core.domain.schema_common import _table_exists

    ledger_already_existed = _table_exists(conn, ledger.table)
    execute_schema_script(
        conn,
        f"""
        CREATE TABLE IF NOT EXISTS {ledger.table} (
            {ledger.entry_column} TEXT PRIMARY KEY,
            {ledger.applied_at_column} TEXT NOT NULL,
            {ledger.applied_by_column} TEXT,
            {ledger.serving_floor_column} TEXT,
            {ledger.digest_column} TEXT
        );
        """,
    )
    _add_column_if_not_exists(
        conn, ledger.table, ledger.serving_floor_column, "TEXT"
    )
    converge_migration_content_schema(
        conn,
        ledger,
        evidence,
        repair_existing_guards=(repair_existing_guards or not ledger_already_existed),
    )
    conn.commit()
