"""``project_code_days`` — control-plane daily commit/line rollup (write side).

Local ``.commit-cache.json`` is ingest scratch only: a checkout with git
warms the cache, aggregates per ``(project_id, day)``, and upserts here
(via ``board.data.get`` payload or direct domain write). Readers live in
:mod:`yoke_contracts.board.momentum_series`, shared by board and Overview.
"""

from __future__ import annotations

from typing import Any, Mapping, Sequence

from yoke_core.domain import db_backend

_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS project_code_days (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  day TEXT NOT NULL,
  commit_count INTEGER NOT NULL DEFAULT 0,
  lines_changed INTEGER NOT NULL DEFAULT 0,
  UNIQUE(project_id, day)
)
"""

_TABLE_DDL_POSTGRES = _TABLE_DDL.replace(
    "id INTEGER PRIMARY KEY",
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
)


def _p(conn: Any) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def ensure_schema(conn: Any) -> None:
    """Create ``project_code_days`` if missing (minimal test DBs)."""

    ddl = (
        _TABLE_DDL_POSTGRES
        if db_backend.connection_is_postgres(conn)
        else _TABLE_DDL
    )
    conn.execute(ddl)
    conn.commit()


def upsert_days(
    conn: Any,
    rows: Sequence[Mapping[str, Any]],
) -> int:
    """Upsert daily aggregates. Each row needs project_id, day, commit_count, lines_changed."""

    if not rows:
        return 0
    p = _p(conn)
    written = 0
    for row in rows:
        project_id = int(row["project_id"])
        day = str(row["day"])
        commits = max(0, int(row.get("commit_count") or 0))
        lines = max(0, int(row.get("lines_changed") or 0))
        if not day:
            continue
        conn.execute(
            "INSERT INTO project_code_days "
            f"(project_id, day, commit_count, lines_changed) "
            f"VALUES ({p}, {p}, {p}, {p}) "
            "ON CONFLICT (project_id, day) DO UPDATE SET "
            f"commit_count = {p}, lines_changed = {p}",
            (project_id, day, commits, lines, commits, lines),
        )
        written += 1
    return written


def aggregate_cache_for_projects(
    cache: Mapping[str, Mapping[str, Any]],
    repo_to_project: Mapping[str, int],
) -> list[dict[str, Any]]:
    """Fold per-hash commit-cache entries into per-(project, day) rows."""

    from yoke_contracts.board.widgets_commit_cache import (
        aggregate_cache_for_projects as _aggregate,
    )

    return _aggregate(dict(cache), dict(repo_to_project))


__all__ = [
    "aggregate_cache_for_projects",
    "ensure_schema",
    "upsert_days",
]
