"""Native statement execution for schema initialization DDL."""

from __future__ import annotations

import re
from typing import Any, Iterator

from yoke_core.domain import db_backend


_INTEGER_PRIMARY_KEY_RE = re.compile(
    r"\bid\s+INTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b",
    re.IGNORECASE,
)


def iter_schema_statements(sql: str) -> Iterator[str]:
    """Yield non-empty statements from schema DDL text."""
    buffer: list[str] = []
    in_single_quote = False
    in_double_quote = False
    in_line_comment = False
    index = 0
    while index < len(sql):
        char = sql[index]
        next_char = sql[index + 1] if index + 1 < len(sql) else ""

        if in_line_comment:
            buffer.append(char)
            if char == "\n":
                in_line_comment = False
            index += 1
            continue

        if not in_single_quote and not in_double_quote and char == "-" and next_char == "-":
            in_line_comment = True
            buffer.extend((char, next_char))
            index += 2
            continue

        if char == "'" and not in_double_quote:
            buffer.append(char)
            if in_single_quote and next_char == "'":
                buffer.append(next_char)
                index += 2
                continue
            in_single_quote = not in_single_quote
            index += 1
            continue

        if char == '"' and not in_single_quote:
            in_double_quote = not in_double_quote
            buffer.append(char)
            index += 1
            continue

        if char == ";" and not in_single_quote and not in_double_quote:
            statement = "".join(buffer).strip()
            if statement:
                yield statement
            buffer.clear()
            index += 1
            continue

        buffer.append(char)
        index += 1

    tail = "".join(buffer).strip()
    if tail:
        yield tail


def _postgres_statement(statement: str) -> str:
    return _INTEGER_PRIMARY_KEY_RE.sub(
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        statement,
    )


def execute_schema_script(conn: Any, sql: str) -> None:
    """Execute a schema script one native statement at a time."""
    postgres = db_backend.connection_is_postgres(conn)
    for statement in iter_schema_statements(sql):
        if postgres:
            statement = _postgres_statement(statement)
        conn.execute(statement)


__all__ = ["execute_schema_script", "iter_schema_statements"]
