"""The ``harness_sessions`` packet note, in its own module.

Extracted from :mod:`schema_api_context_tables_claims` because it is
the longest note in the cheat sheet by a wide margin — one table's
worth of prose was most of that module's line budget, and a note that
cannot grow is a note that stops teaching the next stale guess.

Pure data only — no I/O, no DB connections, no imports.
"""

from __future__ import annotations


HARNESS_SESSION_NOTES = (
    "model / reasoning_effort / context_window_tokens hold ONLY "
    "provider-attested served truth read from the harness artifact. "
    "Per harness: claude reads model + effort from its transcript "
    "(message.model, effort) and context_window_tokens from the ONLY "
    "surface that states a window, the status line command's stdin JSON "
    "(context_window.context_window_size), which "
    "yoke_harness.claude_status_line records per session for the next "
    "hook event to relay — claude hook payloads and transcript rows "
    "carry usage and never a window, so a session whose status line has "
    "not run yet reports a model with the window still NULL; codex reads "
    "all three from its rollout (turn_context + model_context_window); "
    "cursor reads model (and effort, spelled in the variant name) from "
    "its conversation store modelName and attests NO window at all, a "
    "declared deferral with its evidence in "
    "yoke_contracts.session_context_window_sources. Read that module "
    "rather than guessing whether a harness can attest a window; it also "
    "names which harnesses record the window separately from the model, "
    "the reason a claude session keeps reporting one after its model has "
    "settled. "
    "NULL means not attested. A stale guess is that model holds what "
    "the session was launched with: that is requested_model, with "
    "requested_reasoning_effort / requested_context_window_tokens "
    "(claude-opus-5[1m] is only ever a request — no provider "
    "returns a tier selector). Stamped once, from "
    "the session env at registration AND from the launch record at "
    "launch binding (a pre-warmed pool serves a launch from a "
    "process older than it, so the child cannot read its own ask); "
    "a later write fills a gap, never rewrites. Never write a "
    "request into a plain column; a NULL plain column falls back to "
    "requested_model only with a label (model_display). "
    "executor stores only the canonical harness_id enum values "
    "claude-code, codex, or cursor (resolved at write time via "
    "yoke_harness.hooks.identity.canonical_harness_id); "
    "the surface-specific alias (claude-desktop, claude-vscode, "
    "claude-cli, codex-desktop, codex-vscode, codex-cli, "
    "cursor-desktop, cursor-cli) lives in executor_surface when "
    "known and is NULL otherwise. Rendering prefers it and "
    "falls back to executor; event-envelope executor fields are "
    "canonical-only. The primary key is `session_id` — there is "
    "Observed presentation is independent: presentation_surface "
    "records Remote Control only when bounded client state proves "
    "it; state/mode/source/observed_at describe the latest "
    "material transition, guessing no frontend or initiator. "
    "NO `id` column on this table (stale guess). Primary "
    "attribution key is current_item_id, written ONLY by the "
    "work-claim lifecycle: set when this session acquires an item "
    "work claim, and archived to recent_item_id (re-pointed at the "
    "session's newest remaining item claim) when that claim is "
    "released, reclaimed, handed off, or its item goes terminal. "
    "A stale guess is that filing or updating an item sets it: "
    "touching an item without claiming it records recent_item_id "
    "alone, so a filing or steering session never works the item. "
    "recent_item_id / recent_item_status / recent_item_recorded_at "
    "carry the most recent item worked after current_item_id "
    "clears. mode is the session's queue posture "
    "(session_mode.SESSION_MODES); parked_reason is the required "
    "why when mode is parked and stays until an explicit mode "
    "stamp leaves parked. No tool call unparks (stale guess). "
    "keepalive_until / keepalive_reason are a DIFFERENT concept "
    "from parked and are not interchangeable with it (a stale "
    "guess is that parked is what keeps an idle session alive): "
    "they are a bounded lease another caller takes to stop idle "
    "cleanup ending a session that legitimately holds nothing, "
    "taken with `yoke sessions keepalive hold <session-id> "
    "--reason ...`, cleared by `yoke sessions keepalive release` "
    "or by expiry. The held session's own tool "
    "calls neither set nor clear it. Read a live hold through "
    "session_keepalive_holds (an expired timestamp is not a "
    "hold), never by testing keepalive_until for NULL. "
    "offer_envelope is the JSON "
    "session-offer payload (see JSON-nested-field schemas below). "
    "The default routing lane is execution_lane on this row; "
    "session-offer uses it unless the caller supplies --lane / "
    "request body execution_lane, which overrides the row and "
    "emits SessionOfferLaneOverrideApplied. That override is for a "
    "DELIBERATE operator re-route only: an agent never resolves a "
    "lane of its own, because a lane guessed locally outranks the "
    "project's session-routing mapping and filters every frontier "
    "item behind a lane no lane_paths entry declares. Read the row "
    "back with `yoke sessions identity`, which returns this row's "
    "resolved identity plus the lane's permitted paths, and pass "
    "none of it onward. actor_id is bound AT REGISTRATION and is "
    "never NULL on a row this build wrote: the verified "
    "bearer-token actor over https, otherwise the universe's "
    "operating actor (the single human actor, or the one labeled "
    "with the machine's OS login). Registration refuses with a "
    "named SESSION_ACTOR_* reason rather than storing NULL, "
    "because an actor-less session cannot register a path claim. Legacy "
    "session-attribution column names predate the typed "
    "work-claim model and are NOT on this table. There is NO "
    "`status` column on harness_sessions; use mode for queue "
    "posture and recent_item_status for the most recent item "
    "lifecycle snapshot. There is NO `active` column; use "
    "ended_at / terminated_at / last_heartbeat plus work_claims for liveness and "
    "ownership. There is likewise NO `state` column — the posture "
    "column is `mode` and the recent-item lifecycle snapshot is "
    "`recent_item_status`, neither named `state` — and NO "
    "`started_at` column: the session-offer timestamp is "
    "`offered_at`, with liveness / teardown on last_heartbeat / "
    "ended_at. terminated_at is the permanent do-not-reactivate / "
    "do-not-wake terminal state; its actor, session, and reason "
    "columns record the authority that set it. Derived liveness has "
    "THREE states (active|stale|ended) — there is NO `terminated` "
    "liveness value and no --liveness terminated: a killed session "
    "reads liveness='ended' with ended_cause='killed', and the "
    "roster narrows it with --ended-cause killed|wound_down. Every "
    "refusal (register, wake, deliver) reads terminated_at directly, "
    "never the liveness word. Native turn posture is first-class state: "
    "turn_posture is running|waiting|unknown and turn_posture_at "
    "orders accepted hook/activity observations independently of "
    "claims, chain progress, and ended_at. Tool-call liveness is "
    "first-class state: "
    "last_tool_call_at / tool_call_count are stamped by the "
    "observe pipeline on each HarnessToolCallCompleted/Failed — "
    "read these columns, never MAX(events.created_at) (the "
    "events ledger is telemetry-only). episode_started_at is "
    "the current-episode boundary (stamped at register and "
    "reactivation; who-claims --current-episode resolves from "
    "it). pending_resume_notice is the render-once slim "
    "resume-block payload (written at reactivation, cleared at "
    "render). Chain progress is likewise first-class state: "
    "last_chain_step / last_checkpoint_at are stamped by "
    "update_chain_checkpoint on every ChainStepCompleted and "
    "survive offer-envelope rewrites — read them instead of "
    "MAX(step) over ChainStepCompleted envelopes (that state "
    "previously lived only in event envelopes; the events ledger "
    "is telemetry-only). project_id is the session's client-resolved "
    "project identity, stamped from the installing machine's checkout "
    "mapping at registration. workspace is display/debug context "
    "only; never join or prefix-match workspace against a shared "
    "project row to infer project identity. The sessions.begin "
    "entrypoint input helps canonicalize executor identity during "
    "registration; it is not stored in an `entrypoint` column, and "
    "harness_sessions has no such column."
)


__all__ = ["HARNESS_SESSION_NOTES"]
