"""Session tracking and work-claim lifecycle domain front door."""

from __future__ import annotations

from .sessions_analytics import (
    DEFAULT_PROGRESS_THRESHOLD_MINUTES,
    DEFAULT_STALE_THRESHOLD_MINUTES,
    EXECUTOR_STALE_TTL_OVERRIDES_MINUTES,
    EVENT_CHAIN_STEP_COMPLETED,
    EVENT_HARNESS_SESSION_ENDED,
    EVENT_HARNESS_SESSION_END_REJECTED_ACTIVE_CLAIM,
    EVENT_HARNESS_SESSION_END_RELEASED_CLAIMS,
    EVENT_HARNESS_SESSION_HOOK_FAILED,
    EVENT_HARNESS_SESSION_STALE_RECLAIMED,
    EVENT_HARNESS_SESSION_STALE_SWEEP_COMPLETED,
    EVENT_HARNESS_SESSION_STARTED,
    EVENT_OPERATOR_CLAIM_OVERRIDE,
    EVENT_SESSION_REACTIVATED_WITH_RELEASED_CLAIMS,
    EVENT_WORK_CLAIMED,
    EVENT_WORK_HANDED_OFF,
    EVENT_WORK_RECLAIMED,
    EVENT_WORK_RELEASED,
    SessionError,
    _NEXT_STEP_TO_PATH,
    _SESSION_EVENT_REGISTRY_ROWS,
    _emit_event,
    _emit_session_event,
    _resolve_resume_dispatch,
    emit_adapter_dispatch_chosen,
    emit_drift_review_completed,
    emit_lane_routing_decision,
    emit_next_action_chosen,
    emit_post_decision_telemetry,
    ensure_session_event_registry_entries,
)
from .sessions_cleanup import clean_stale_harness_sessions, cleanup_never_engaged_sessions
from .sessions_lifecycle import (
    _canonical_release_reason,
    _get_claim,
    _get_session,
    _validate_completed_release_status,
    claim_work,
    heartbeat,
    operator_override_release_claim,
    register_session,
    release_all_claims,
    release_claim,
    release_item_claim_for_execution,
    release_work_claim_for_execution,
    set_session_mode,
)
from .sessions_offer import session_offer_with_ownership
from .sessions_queries import (
    _claim_item_lookup_pair,
    _filter_schedule_for_offer,
    _now_iso,
    _required_path_for_step,
    _row_to_dict,
    _step_is_compatible_with_offer,
    derive_required_path,
    display_claim_item_id,
    get_claim_for_work_unit,
    list_claims_for_session,
    list_harness_sessions,
    normalize_claim_item_id,
    normalize_session_item_id,
    read_chain_checkpoint,
    resolve_claimed_work_context,
    resolve_harness_capabilities,
    update_chain_checkpoint,
)
from .sessions_queries_chain import (
    append_chain_skip_entry,
    read_chain_skip_memory,
)
from .sessions_render import (
    _resolve_effective_ttl,
    clear_current_item,
    end_session,
    end_session_if_empty,
    find_stale_sessions,
    get_session_attribution,
    handoff_claim,
    reclaim_stale_item_claims,
    reclaim_stale_session,
    release_claims_for_done_item,
    set_current_item,
)

__all__ = [
    # Analytics
    "SessionError",
    "DEFAULT_STALE_THRESHOLD_MINUTES",
    "DEFAULT_PROGRESS_THRESHOLD_MINUTES",
    "EXECUTOR_STALE_TTL_OVERRIDES_MINUTES",
    "EVENT_HARNESS_SESSION_STARTED",
    "EVENT_HARNESS_SESSION_ENDED",
    "EVENT_WORK_CLAIMED",
    "EVENT_WORK_RELEASED",
    "EVENT_WORK_RECLAIMED",
    "EVENT_WORK_HANDED_OFF",
    "EVENT_CHAIN_STEP_COMPLETED",
    "EVENT_HARNESS_SESSION_HOOK_FAILED",
    "EVENT_HARNESS_SESSION_STALE_RECLAIMED",
    "EVENT_HARNESS_SESSION_END_REJECTED_ACTIVE_CLAIM",
    "EVENT_OPERATOR_CLAIM_OVERRIDE",
    "EVENT_HARNESS_SESSION_STALE_SWEEP_COMPLETED",
    "EVENT_HARNESS_SESSION_END_RELEASED_CLAIMS",
    "EVENT_SESSION_REACTIVATED_WITH_RELEASED_CLAIMS",
    "_SESSION_EVENT_REGISTRY_ROWS",
    "ensure_session_event_registry_entries",
    "_emit_event",
    "_emit_session_event",
    "_NEXT_STEP_TO_PATH",
    "emit_next_action_chosen",
    "emit_drift_review_completed",
    "emit_lane_routing_decision",
    "emit_adapter_dispatch_chosen",
    "_resolve_resume_dispatch",
    "emit_post_decision_telemetry",
    # Queries
    "normalize_claim_item_id",
    "normalize_session_item_id",
    "display_claim_item_id",
    "_claim_item_lookup_pair",
    "_now_iso",
    "_row_to_dict",
    "_required_path_for_step",
    "derive_required_path",
    "resolve_claimed_work_context",
    "_step_is_compatible_with_offer",
    "_filter_schedule_for_offer",
    "update_chain_checkpoint",
    "read_chain_checkpoint",
    "read_chain_skip_memory",
    "append_chain_skip_entry",
    "list_harness_sessions",
    "list_claims_for_session",
    "get_claim_for_work_unit",
    "resolve_harness_capabilities",
    # Lifecycle
    "_get_session",
    "_get_claim",
    "register_session",
    "heartbeat",
    "set_session_mode",
    "claim_work",
    "release_claim",
    "_canonical_release_reason",
    "_validate_completed_release_status",
    "release_item_claim_for_execution",
    "release_work_claim_for_execution",
    "release_all_claims",
    "operator_override_release_claim",
    # Render
    "set_current_item",
    "get_session_attribution",
    "clear_current_item",
    "end_session",
    "end_session_if_empty",
    "find_stale_sessions",
    "reclaim_stale_session",
    "reclaim_stale_item_claims",
    "release_claims_for_done_item",
    "_resolve_effective_ttl",
    "handoff_claim",
    # Parent-owned
    "session_offer_with_ownership",
    "clean_stale_harness_sessions",
    "cleanup_never_engaged_sessions",
]
