"""``strategy_checkpoints`` — strategize / drift-review anchor state.

One row per completed strategize session or drift review, per project.
``MAX(created_at)`` per project is the checkpoint anchor that bounds
drift-review delivered-deltas (``yoke_core.domain.drift_review``) and
the strategize skill's delta window — replacing the retired
``StrategizeCompleted`` / ``DriftReviewCompleted`` envelope scans (the
events ledger stays telemetry-only; completion paths still emit the
matching events for audit).

CLI (used by the strategize skill's finalize/refresh phases)::

    python3 -m yoke_core.domain.strategy_checkpoints record \
        --project <slug-or-id> --kind strategize
    python3 -m yoke_core.domain.strategy_checkpoints latest \
        --project <slug-or-id>
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

from yoke_core.domain import db_backend
from yoke_core.domain.project_identity import resolve_project

VALID_KINDS: frozenset[str] = frozenset({"strategize", "drift_review"})

_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS strategy_checkpoints (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('strategize', 'drift_review')),
  created_at TEXT NOT NULL
)
"""

_TABLE_DDL_POSTGRES = _TABLE_DDL.replace(
    "id INTEGER PRIMARY KEY",
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
)

_INDEX_DDL = (
    "CREATE INDEX IF NOT EXISTS idx_strategy_checkpoints_project_created "
    "ON strategy_checkpoints(project_id, created_at)"
)


def _p(conn: Any) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def ensure_schema(conn: Any) -> None:
    """Create the table + index if missing (minimal test DBs). Idempotent."""
    ddl = (
        _TABLE_DDL_POSTGRES
        if db_backend.connection_is_postgres(conn)
        else _TABLE_DDL
    )
    conn.execute(ddl)
    conn.execute(_INDEX_DDL)
    conn.commit()


def _resolve_project_id(conn: Any, project: Any) -> Optional[int]:
    if isinstance(project, int):
        return project
    text = str(project).strip()
    if text.isdigit():
        return int(text)
    try:
        ident = resolve_project(conn, text, required=False)
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        return None
    return ident.id if ident is not None else None


def record_checkpoint(conn: Any, *, project: Any, kind: str) -> bool:
    """Insert one checkpoint row (caller's txn; caller commits).

    Returns False (never raises) when the kind is invalid, the project
    cannot be resolved, or the table is missing — completion paths must
    not fail on checkpoint bookkeeping.
    """
    if kind not in VALID_KINDS:
        return False
    project_id = _resolve_project_id(conn, project)
    if project_id is None:
        return False
    p = _p(conn)
    try:
        conn.execute("SAVEPOINT strategy_checkpoint")
        conn.execute(
            "INSERT INTO strategy_checkpoints (project_id, kind, created_at) "
            f"VALUES ({p}, {p}, {p})",
            (project_id, kind, _now_iso()),
        )
        conn.execute("RELEASE SAVEPOINT strategy_checkpoint")
        return True
    except Exception:
        try:
            conn.execute("ROLLBACK TO SAVEPOINT strategy_checkpoint")
            conn.execute("RELEASE SAVEPOINT strategy_checkpoint")
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        return False


def record_checkpoints(
    conn: Any, *, projects: Iterable[Any], kind: str
) -> int:
    """Insert one checkpoint row per scoped project; returns rows landed."""
    return sum(
        1 for project in projects
        if record_checkpoint(conn, project=project, kind=kind)
    )


def latest_checkpoint_at(conn: Any, project: Any) -> Optional[str]:
    """Return the ISO timestamp of the latest checkpoint for *project*."""
    project_id = _resolve_project_id(conn, project)
    if project_id is None:
        return None
    try:
        row = conn.execute(
            "SELECT MAX(created_at) FROM strategy_checkpoints "
            f"WHERE project_id = {_p(conn)}",
            (project_id,),
        ).fetchone()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        return None
    return row[0] if row is not None and row[0] else None


def main(argv: Optional[list] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] not in ("record", "latest"):
        print(
            "Usage: python3 -m yoke_core.domain.strategy_checkpoints "
            "{record|latest} --project <slug-or-id> [--kind strategize|drift_review]",
            file=sys.stderr,
        )
        return 2
    command = args[0]
    project: Optional[str] = None
    kind = "strategize"
    rest = args[1:]
    while rest:
        flag = rest.pop(0)
        if flag == "--project" and rest:
            project = rest.pop(0)
        elif flag == "--kind" and rest:
            kind = rest.pop(0)
        else:
            print(f"Error: unknown argument {flag!r}", file=sys.stderr)
            return 2
    if not project:
        print("Error: --project is required", file=sys.stderr)
        return 2

    from yoke_core.domain.db_helpers import connect

    conn = connect()
    try:
        if command == "record":
            if not record_checkpoint(conn, project=project, kind=kind):
                print(
                    f"Error: checkpoint not recorded (project={project!r}, "
                    f"kind={kind!r})",
                    file=sys.stderr,
                )
                return 1
            conn.commit()
            print(f"Recorded {kind} checkpoint for project {project}")
            return 0
        latest = latest_checkpoint_at(conn, project)
        if latest:
            print(latest)
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
