"""Shared fixtures and helpers for advance_path_claim_activation CLI tests."""

from __future__ import annotations

from typing import Optional
from unittest import mock

import pytest

from yoke_core.domain import db_backend
from yoke_core.domain import advance_path_claim_activation as activation_mod
from yoke_core.domain.advance_path_claim_activation import ActivationResult
from runtime.api.fixtures.file_test_db import connect_test_db, init_test_db


def _p(conn) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def _apply_activation_schema() -> None:
    conn = connect_test_db("")
    try:
        conn.execute(
            "CREATE TABLE projects ("
            "id INTEGER PRIMARY KEY, slug TEXT, name TEXT, "
            "public_item_prefix TEXT)"
        )
        conn.execute(
            "INSERT INTO projects (id, slug, name, public_item_prefix) "
            "VALUES (1, 'yoke', 'Yoke', 'YOK'), "
            "(2, 'buzz', 'Buzz', 'BUZ')"
        )
        conn.execute(
            "CREATE TABLE items ("
            "id INTEGER PRIMARY KEY, owner INTEGER, source INTEGER, "
            "project_id INTEGER, project_sequence INTEGER)"
        )
        conn.execute(
            "CREATE TABLE work_claims ("
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "session_id TEXT NOT NULL, "
            "target_kind TEXT NOT NULL, "
            "item_id INTEGER, "
            "epic_id INTEGER, "
            "task_num INTEGER, "
            "process_key TEXT, "
            "conflict_group TEXT, "
            "claim_type TEXT NOT NULL, "
            "claimed_at TEXT NOT NULL, "
            "released_at TEXT)"
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture
def fake_db(tmp_path):
    """Seed the CLI's active authority through the Postgres test seam."""
    with init_test_db(tmp_path, apply_schema=_apply_activation_schema) as db_path:
        yield db_path


def seed_item(
    db_path,
    item_id: int,
    *,
    owner: Optional[int],
    source: Optional[int],
    project_id: int = 1,
    project_sequence: Optional[int] = None,
) -> None:
    conn = connect_test_db(str(db_path))
    try:
        p = _p(conn)
        conn.execute(
            "INSERT INTO items "
            "(id, owner, source, project_id, project_sequence) "
            f"VALUES ({p}, {p}, {p}, {p}, {p})",
            (
                item_id,
                owner,
                source,
                project_id,
                item_id if project_sequence is None else project_sequence,
            ),
        )
        conn.commit()
    finally:
        conn.close()


def seed_work_claim(
    db_path,
    *,
    item_id: int,
    session_id: str,
    released: bool = False,
    claimed_at: str = "2026-05-06T12:00:00Z",
) -> None:
    conn = connect_test_db(str(db_path))
    try:
        p = _p(conn)
        conn.execute(
            "INSERT INTO work_claims "
            "(session_id, target_kind, item_id, claim_type, "
            " claimed_at, released_at) "
            f"VALUES ({p}, 'item', {p}, 'exclusive', {p}, {p})",
            (
                session_id,
                item_id,
                claimed_at,
                "2026-05-06T13:00:00Z" if released else None,
            ),
        )
        conn.commit()
    finally:
        conn.close()


def clear_session_env(monkeypatch) -> None:
    for var in ("YOKE_SESSION_ID", "CLAUDE_SESSION_ID", "CODEX_THREAD_ID"):
        monkeypatch.delenv(var, raising=False)


def stub_run(monkeypatch, *, result: ActivationResult) -> mock.MagicMock:
    stub = mock.MagicMock(return_value=result)
    monkeypatch.setattr(activation_mod, "run_activation_phase", stub)
    return stub
