"""Shared write/read-parity DB builders for ``test_parity_service_client_*``.

Filename omits the ``test_`` prefix so pytest does not collect it. Each split
file imports ``make_write_parity_env`` / ``make_read_parity_env`` and wraps
them in local ``@pytest.fixture`` shims.

Both builders delegate the per-test DB lifecycle to
:func:`runtime.api.fixtures.file_test_db.init_test_db`: a disposable Postgres
database with ``YOKE_PG_DSN`` repointed at it for the env's lifetime, dropped
on exit.

The schema + seed apply happens *inside* the ``init_test_db`` context (via the
``apply_schema`` strategy), so the ``service_client`` subprocess each test
spawns — which inherits the repointed ``YOKE_PG_DSN`` through
``os.environ.copy()`` in ``_run_service_client`` — reads the SAME per-test
database the in-process FastAPI ``TestClient`` writes. The in-process FastAPI
dependency overrides use the backend factory, which honors the repointed DSN.

The write-parity environment extends the base parity schema with
``epic_tasks``, ``qa_requirements``, and ``qa_runs`` tables required by the
mutation layer's gate logic. The read-parity environment uses the base parity
schema (``_SCHEMA`` + ``_seed_data`` from ``test_parity``); it is the
backend-aware counterpart to ``test_parity.parity_env`` for split files in this
cluster that need a read-side parity DB without importing a legacy fixture.
"""

from __future__ import annotations

import shutil
import tempfile
from contextlib import contextmanager
from pathlib import Path
from unittest.mock import patch

from fastapi.testclient import TestClient

from runtime.api.auth_test_helpers import mint_api_auth_context
from yoke_core.domain import db_backend
from runtime.api.fixtures.file_test_db import init_test_db
from runtime.api.fixtures.schema_ddl import apply_fixture_ddl
from yoke_core.api.main import app, get_db_path, get_db_readonly, get_db_readwrite
from runtime.api.parity_service_client_project_fixture import (
    SERVICE_CLIENT_PARITY_SCHEMA,
    seed_service_client_parity_data,
)


WRITE_PARITY_SCHEMA_EXTRAS = """
    CREATE TABLE epic_tasks (
        id INTEGER PRIMARY KEY,
        epic_id INTEGER NOT NULL,
        task_num INTEGER NOT NULL,
        title TEXT NOT NULL,
        status TEXT DEFAULT 'implementing',
        body TEXT,
        dependencies TEXT,
        milestone TEXT DEFAULT 'M',
        dispatched INTEGER DEFAULT 0,
        UNIQUE(epic_id, task_num)
    );

    CREATE TABLE qa_requirements (
        id INTEGER PRIMARY KEY,
        item_id INTEGER,
        epic_id INTEGER,
        task_num INTEGER,
        deployment_run_id TEXT,
        qa_kind TEXT NOT NULL,
        qa_phase TEXT NOT NULL DEFAULT 'verification',
        success_policy TEXT NOT NULL DEFAULT 'blocking'
    );
    CREATE INDEX IF NOT EXISTS idx_qa_requirements_deployment ON qa_requirements(deployment_run_id);

    CREATE TABLE qa_runs (
        id INTEGER PRIMARY KEY,
        qa_requirement_id INTEGER NOT NULL,
        executor_type TEXT,
        verdict TEXT,
        raw_result TEXT
    );
"""


def _resync_items_identity_sequence(conn) -> None:
    """Advance the ``items`` identity sequence past the explicitly-seeded ids.

    The facade translates ``INTEGER PRIMARY KEY`` to ``GENERATED BY DEFAULT AS
    IDENTITY``; explicit-id inserts (the seed rows 1-9) are accepted but do NOT
    advance the underlying sequence, so a subsequent id-less ``INSERT`` (e.g. the
    API create surface) would generate ``id=1`` and collide. No-op when
    ``items`` is empty.
    """
    conn.execute(
        "SELECT setval("
        "  pg_get_serial_sequence('items', 'id'),"
        "  (SELECT COALESCE(MAX(id), 1) FROM items),"
        "  true"
        ")"
    )
    conn.commit()


def _apply_write_parity_schema() -> None:
    """``init_test_db`` apply_schema strategy: the write-parity schema + seed
    rows against the repointed per-test Postgres DSN.

    Seeding lives here (not a post-yield step) so the ``service_client``
    subprocess under test, which inherits the repointed DSN, reads the same
    per-test database. Fixture DDL applies through the native helper.
    """
    conn = db_backend.connect()
    try:
        apply_fixture_ddl(conn, SERVICE_CLIENT_PARITY_SCHEMA + WRITE_PARITY_SCHEMA_EXTRAS)
        seed_service_client_parity_data(conn)
        _resync_items_identity_sequence(conn)
    finally:
        conn.close()


def _apply_read_parity_schema() -> None:
    """``init_test_db`` apply_schema strategy: the base read-parity schema +
    seed rows, backend-resolved. Counterpart to ``_apply_write_parity_schema``
    for the read-side ``parity_env`` equivalent."""
    conn = db_backend.connect()
    try:
        apply_fixture_ddl(conn, SERVICE_CLIENT_PARITY_SCHEMA)
        seed_service_client_parity_data(conn)
        _resync_items_identity_sequence(conn)
    finally:
        conn.close()


def _override_db_readonly(db_path: str):
    """Read connection factory for the FastAPI overrides."""
    del db_path
    return db_backend.connect()


def _override_db_readwrite(db_path: str):
    """Write connection factory for the FastAPI overrides."""
    del db_path
    return db_backend.connect()


@contextmanager
def _parity_env(apply_schema):
    """Shared body for the write/read parity environments.

    Provisions a Postgres per-test DB via :func:`init_test_db`
    (applying ``apply_schema`` inside the repointed-DSN context), then yields a
    dict with ``db_path``, ``tmp_dir``, and a ``TestClient`` whose DB
    dependency overrides resolve to that same per-test DB. Cleans up dependency
    overrides and the temp directory on exit.
    """
    tmp_dir = tempfile.mkdtemp(prefix="yoke-write-parity-")
    try:
        with init_test_db(Path(tmp_dir), apply_schema=apply_schema) as db_path:
            # The lifespan startup gate (``_ensure_db_initialized``) reads
            # through the monkey-patched ``get_db_readonly`` below, so it
            # validates the same backend-resolved authority the request path and
            # subprocess use. No SQLite decoy is seeded to satisfy it.

            def _override_db_path() -> str:
                return db_path

            def _ro():
                return _override_db_readonly(db_path)

            def _rw():
                return _override_db_readwrite(db_path)

            app.dependency_overrides[get_db_path] = _override_db_path
            app.dependency_overrides[get_db_readonly] = _ro
            app.dependency_overrides[get_db_readwrite] = _rw

            try:
                with patch("yoke_core.api.main.get_db_path", _override_db_path), \
                     patch("yoke_core.api.main.get_db_readonly", _ro), \
                     patch("yoke_core.api.main.get_db_readwrite", _rw):
                    with TestClient(app) as client:
                        conn = db_backend.connect()
                        try:
                            auth = mint_api_auth_context(conn)
                        finally:
                            conn.close()
                        client.headers.update(auth.headers)
                        yield {
                            "db_path": db_path,
                            "tmp_dir": tmp_dir,
                            "client": client,
                        }
            finally:
                app.dependency_overrides.clear()
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


@contextmanager
def make_write_parity_env():
    """Context manager yielding a write-parity test environment dict.

    See module docstring. Yields a dict with ``db_path``, ``tmp_dir``, and a
    ``TestClient`` bound to the per-test DB.
    """
    with _parity_env(_apply_write_parity_schema) as env:
        yield env


@contextmanager
def make_read_parity_env():
    """Context manager yielding a read-parity test environment dict.

    Backend-aware counterpart to ``test_parity.parity_env``. Yields a dict with
    ``db_path``, ``tmp_dir``, and a ``TestClient`` bound to the per-test DB.
    """
    with _parity_env(_apply_read_parity_schema) as env:
        yield env


__all__ = [
    "WRITE_PARITY_SCHEMA_EXTRAS",
    "make_write_parity_env",
    "make_read_parity_env",
]
