"""Regression tests for central fixture DDL application.

``apply_fixture_ddl`` executes native Postgres DDL one statement at a
time through the canonical schema-script executor — no dialect
translation happens in the fixture layer. The composed ``SCHEMA_DDL``
must therefore be native Postgres text, and legacy
``id INTEGER PRIMARY KEY`` fixture fragments still gain identity through
the same rewrite production schema init uses.
"""

from __future__ import annotations

import pytest

import psycopg

from runtime.api.fixtures import pg_testdb
from runtime.api.fixtures.schema_ddl import apply_fixture_ddl, apply_fixture_schema


@pytest.fixture
def scratch_db():
    """Connection to a fresh, empty disposable Postgres database."""
    name = pg_testdb.create_test_database()
    conn = pg_testdb.connect_test_database(name)
    try:
        yield conn
    finally:
        conn.close()
        pg_testdb.drop_test_database(name)


def test_apply_executes_native_postgres_ddl(scratch_db) -> None:
    """Identity columns and JSON checks execute natively, untranslated."""
    apply_fixture_ddl(
        scratch_db,
        """
        CREATE TABLE IF NOT EXISTS fixture_probe (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            envelope TEXT CHECK(envelope IS NULL OR (envelope IS JSON)),
            note TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_fixture_probe_note ON fixture_probe(note);
        """,
    )
    row = scratch_db.execute(
        "INSERT INTO fixture_probe (envelope) VALUES ('{\"ok\": true}') RETURNING id"
    ).fetchone()
    assert row[0] == 1
    with pytest.raises(psycopg.errors.CheckViolation):
        scratch_db.execute(
            "INSERT INTO fixture_probe (envelope) VALUES ('not json')"
        )
    scratch_db.rollback()


def test_legacy_integer_primary_key_fragments_gain_identity(scratch_db) -> None:
    """Fixture fragments still written as ``id INTEGER PRIMARY KEY`` ride the
    canonical schema-script rewrite, so inserts without an explicit id keep
    working for helpers that have not adopted native identity spelling yet."""
    apply_fixture_ddl(
        scratch_db,
        """
        CREATE TABLE legacy_probe (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL
        );
        """,
    )
    row = scratch_db.execute(
        "INSERT INTO legacy_probe (name) VALUES ('generated-id') RETURNING id"
    ).fetchone()
    assert row[0] == 1


def test_schema_ddl_carries_no_sqlite_dialect() -> None:
    """The composed fixture schema is native Postgres text."""
    from runtime.api.fixtures.schema_ddl import SCHEMA_DDL

    assert "AUTOINCREMENT" not in SCHEMA_DDL
    assert "WITHOUT ROWID" not in SCHEMA_DDL
    assert "json_valid" not in SCHEMA_DDL
    # Fixture tables carry no FK constraints so tests seed in any order.
    assert "FOREIGN KEY" not in SCHEMA_DDL
    assert " REFERENCES " not in SCHEMA_DDL


def test_composed_fixture_schema_includes_auth_foundation_tables(scratch_db) -> None:
    from yoke_core.domain.auth_schema import REQUIRED_AUTH_TABLES
    from yoke_core.domain.schema_common import _get_tables

    apply_fixture_schema(scratch_db)
    tables = set(_get_tables(scratch_db))
    assert set(REQUIRED_AUTH_TABLES) <= tables


def test_composed_fixture_schema_generates_ids(scratch_db) -> None:
    """Rows inserted without explicit ids get identity-generated ones."""
    apply_fixture_schema(scratch_db)
    row = scratch_db.execute(
        "INSERT INTO epic_tasks (epic_id, task_num, title) "
        "VALUES (1, 1, 'probe') RETURNING id"
    ).fetchone()
    assert row[0] >= 1
