"""Tests for the advance_path_claim_activation CLI entrypoint.

Coverage: success (planned -> active), blocked claim, no-owner item,
missing/invalid item args, and work-claim ownership refusal.
"""

from __future__ import annotations

from typing import Optional
from unittest import mock

import pytest

from yoke_core.domain import db_backend
from yoke_core.domain import advance_path_claim_activation as activation_mod
from yoke_core.domain.advance_path_claim_activation import (
    ActivationOutcome,
    ActivationResult,
)
from runtime.api.fixtures.file_test_db import connect_test_db, init_test_db


def _p(conn) -> str:
    return "%s" if db_backend.connection_is_postgres(conn) else "?"


def _apply_activation_schema() -> None:
    conn = connect_test_db("")
    try:
        conn.execute(
            "CREATE TABLE items ("
            "id INTEGER PRIMARY KEY, owner INTEGER, source INTEGER)"
        )
        conn.execute(
            "CREATE TABLE work_claims ("
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "session_id TEXT NOT NULL, "
            "target_kind TEXT NOT NULL, "
            "item_id INTEGER, "
            "epic_id INTEGER, "
            "task_num INTEGER, "
            "process_key TEXT, "
            "conflict_group TEXT, "
            "claim_type TEXT NOT NULL, "
            "claimed_at TEXT NOT NULL, "
            "released_at TEXT)"
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture
def fake_db(tmp_path):
    """Seed the CLI's active authority through the Postgres test seam."""
    with init_test_db(tmp_path, apply_schema=_apply_activation_schema) as db_path:
        yield db_path


def _seed_item(
    db_path, item_id: int, *, owner: Optional[int], source: Optional[int]
) -> None:
    conn = connect_test_db(str(db_path))
    try:
        p = _p(conn)
        conn.execute(
            f"INSERT INTO items (id, owner, source) VALUES ({p}, {p}, {p})",
            (item_id, owner, source),
        )
        conn.commit()
    finally:
        conn.close()


def _seed_work_claim(
    db_path,
    *,
    item_id: int,
    session_id: str,
    released: bool = False,
    claimed_at: str = "2026-05-06T12:00:00Z",
    ) -> None:
    conn = connect_test_db(str(db_path))
    try:
        p = _p(conn)
        conn.execute(
            "INSERT INTO work_claims "
            "(session_id, target_kind, item_id, claim_type, "
            " claimed_at, released_at) "
            f"VALUES ({p}, 'item', {p}, 'exclusive', {p}, {p})",
            (
                session_id,
                item_id,
                claimed_at,
                "2026-05-06T13:00:00Z" if released else None,
            ),
        )
        conn.commit()
    finally:
        conn.close()


def _clear_session_env(monkeypatch) -> None:
    for var in ("YOKE_SESSION_ID", "CLAUDE_SESSION_ID", "CODEX_THREAD_ID"):
        monkeypatch.delenv(var, raising=False)


def _stub_run(monkeypatch, *, result: ActivationResult) -> mock.MagicMock:
    stub = mock.MagicMock(return_value=result)
    monkeypatch.setattr(activation_mod, "run_activation_phase", stub)
    return stub


def test_cli_activates_planned_claims(fake_db, monkeypatch, capsys):
    _seed_item(fake_db, 9999, owner=42, source=None)
    result = ActivationResult(
        item_id=9999,
        actor_id=42,
        outcomes=[
            ActivationOutcome(
                claim_id=101,
                state_before="planned",
                state_after="active",
                commit_sha="deadbeefcafef00d00000007" + "0" * 16,
            )
        ],
    )
    stub = _stub_run(monkeypatch, result=result)

    rc = activation_mod.main(["--item", "9999"])

    captured = capsys.readouterr()
    assert rc == 0
    assert "activated=[101]" in captured.out
    assert captured.err == ""
    stub.assert_called_once()
    kwargs = stub.call_args.kwargs
    assert kwargs["item_id"] == 9999
    assert kwargs["actor_id"] == 42


def test_cli_strips_sun_prefix(fake_db, monkeypatch, capsys):
    _seed_item(fake_db, 5555, owner=None, source=17)
    _stub_run(
        monkeypatch,
        result=ActivationResult(item_id=5555, actor_id=17, outcomes=[]),
    )

    rc = activation_mod.main(["--item", "YOK-5555"])

    captured = capsys.readouterr()
    assert rc == 0
    assert "activated=[]" in captured.out


def test_cli_reports_blocked_claim(fake_db, monkeypatch, capsys):
    _seed_item(fake_db, 1234, owner=99, source=None)
    blocked = ActivationResult(
        item_id=1234,
        actor_id=99,
        outcomes=[
            ActivationOutcome(
                claim_id=33,
                state_before="blocked",
                state_after="blocked",
                error="blocked: claim 30",
            )
        ],
        blocked_errors=[
            "claim 33 is blocked: claim 30; resolve the upstream claim "
            "before activating"
        ],
    )
    _stub_run(monkeypatch, result=blocked)

    rc = activation_mod.main(["--item", "1234"])

    captured = capsys.readouterr()
    assert rc == 1
    assert "BLOCKED: claim 33 is blocked" in captured.err
    assert captured.out == ""


def test_cli_reports_diverged_refs(fake_db, monkeypatch, capsys):
    _seed_item(fake_db, 4321, owner=8, source=None)
    diverged = ActivationResult(
        item_id=4321,
        actor_id=8,
        outcomes=[],
        diverged_error="origin/main and refs/heads/main have diverged",
    )
    _stub_run(monkeypatch, result=diverged)

    rc = activation_mod.main(["--item", "4321"])

    captured = capsys.readouterr()
    assert rc == 1
    assert "DIVERGED: origin/main and refs/heads/main have diverged" in (
        captured.err
    )


def test_cli_blocks_item_without_actor(fake_db, monkeypatch, capsys):
    _seed_item(fake_db, 7777, owner=None, source=None)
    stub = _stub_run(
        monkeypatch,
        result=ActivationResult(item_id=7777, actor_id=0, outcomes=[]),
    )

    rc = activation_mod.main(["--item", "7777"])

    captured = capsys.readouterr()
    assert rc == 1
    assert "BLOCKED: item has no owner/source actor" in captured.err
    stub.assert_not_called()


def test_cli_returns_2_for_missing_item(fake_db, monkeypatch, capsys):
    _stub_run(
        monkeypatch,
        result=ActivationResult(item_id=0, actor_id=0, outcomes=[]),
    )

    rc = activation_mod.main(["--item", "404"])

    captured = capsys.readouterr()
    assert rc == 2
    assert "ERROR: item 404 not found" in captured.err


def test_cli_returns_2_for_invalid_item(fake_db, monkeypatch, capsys):
    rc = activation_mod.main(["--item", "not-a-number"])

    captured = capsys.readouterr()
    assert rc == 2
    assert "ERROR: invalid --item value" in captured.err


# AC-18/19/20 (first set) — activation must not flip planned claims to
# active when another live session owns the item's work claim.
# Reproduces the claim-33 shape.


class TestWorkClaimOwnership:
    def test_refuses_when_other_session_holds_work_claim(
        self, fake_db, monkeypatch, capsys
    ):
        _clear_session_env(monkeypatch)
        _seed_item(fake_db, 1594, owner=42, source=None)
        _seed_work_claim(fake_db, item_id=1594, session_id="other-live")
        stub = _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1594, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(
            ["--item", "1594", "--session-id", "mine"]
        )
        captured = capsys.readouterr()
        assert rc == 1
        assert "BLOCKED: work claim for item 1594" in captured.err
        assert "other-live" in captured.err
        assert "avoid stranded path claims" in captured.err
        stub.assert_not_called()

    def test_proceeds_when_caller_owns_work_claim(
        self, fake_db, monkeypatch, capsys
    ):
        _clear_session_env(monkeypatch)
        _seed_item(fake_db, 1700, owner=42, source=None)
        _seed_work_claim(fake_db, item_id=1700, session_id="mine")
        _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1700, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(["--item", "1700", "--session-id", "mine"])
        assert rc == 0

    def test_proceeds_when_no_work_claim_yet(
        self, fake_db, monkeypatch, capsys
    ):
        # Orchestrator path: claim_work runs after this CLI.
        _clear_session_env(monkeypatch)
        _seed_item(fake_db, 1701, owner=42, source=None)
        _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1701, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(["--item", "1701", "--session-id", "mine"])
        assert rc == 0

    def test_skips_check_when_session_id_empty(
        self, fake_db, monkeypatch, capsys
    ):
        _clear_session_env(monkeypatch)
        _seed_item(fake_db, 1702, owner=42, source=None)
        _seed_work_claim(fake_db, item_id=1702, session_id="other")
        _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1702, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(["--item", "1702"])
        assert rc == 0

    def test_ignores_released_work_claims(
        self, fake_db, monkeypatch, capsys
    ):
        _clear_session_env(monkeypatch)
        _seed_item(fake_db, 1703, owner=42, source=None)
        _seed_work_claim(
            fake_db, item_id=1703, session_id="prior", released=True,
        )
        _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1703, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(["--item", "1703", "--session-id", "mine"])
        assert rc == 0

    def test_uses_env_session_id_when_flag_absent(
        self, fake_db, monkeypatch, capsys
    ):
        _clear_session_env(monkeypatch)
        monkeypatch.setenv("CLAUDE_SESSION_ID", "env-session")
        _seed_item(fake_db, 1704, owner=42, source=None)
        _seed_work_claim(fake_db, item_id=1704, session_id="other")
        stub = _stub_run(
            monkeypatch,
            result=ActivationResult(item_id=1704, actor_id=42, outcomes=[]),
        )
        rc = activation_mod.main(["--item", "1704"])
        captured = capsys.readouterr()
        assert rc == 1
        assert "other" in captured.err
        stub.assert_not_called()
