"""Regression for the CI-declaration check.

``merge_worktree_ci._project_declares_ci_workflow`` parsed the capability
settings through a nonexistent ``json_helper.loads`` and the broad
``except Exception`` swallowed the ``AttributeError`` — so the check
returned False for every project and the "CI declared, wait for check
registration" branch never fired. These tests pin the true path against a
real capability row. Fixture shape mirrors
``test_projects_capabilities_settings.py``.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Iterator

import pytest

from yoke_core.domain import db_backend
from yoke_core.engines import merge_worktree_ci
from runtime.api.fixtures.file_test_db import init_test_db


def _apply_capability_schema() -> None:
    conn = db_backend.connect()
    try:
        conn.execute(
            """
            CREATE TABLE projects (
                id BIGINT PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                public_item_prefix TEXT NOT NULL DEFAULT 'YOK'
            )
            """
        )
        conn.execute(
            """
            INSERT INTO projects (id, slug, name, public_item_prefix)
            VALUES (1, 'yoke', 'Yoke', 'YOK'), (2, 'externalwebapp', 'ExternalWebapp', 'EXT')
            """
        )
        conn.execute(
            """
            CREATE TABLE project_capabilities (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id BIGINT NOT NULL REFERENCES projects(id),
                type TEXT NOT NULL,
                settings TEXT DEFAULT '{}',
                verified_at TEXT,
                created_at TEXT NOT NULL DEFAULT '2026-01-01T00:00:00Z'
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


@pytest.fixture()
def capability_db(tmp_path) -> Iterator[None]:
    with init_test_db(tmp_path, apply_schema=_apply_capability_schema):
        yield


def _seed_capability(settings_json: str) -> None:
    conn = db_backend.connect()
    try:
        conn.execute(
            "INSERT INTO project_capabilities (project_id, type, settings) "
            "VALUES (1, 'ci_workflow_file', %s)",
            (settings_json,),
        )
        conn.commit()
    finally:
        conn.close()


def _ctx(project: str | None) -> SimpleNamespace:
    return SimpleNamespace(project=project)


def test_declared_workflow_returns_true(capability_db) -> None:
    _seed_capability('{"workflow_file": "ci.yml"}')
    assert merge_worktree_ci._project_declares_ci_workflow(_ctx("yoke"))


def test_no_capability_row_returns_false(capability_db) -> None:
    assert not merge_worktree_ci._project_declares_ci_workflow(_ctx("yoke"))


def test_settings_without_workflow_file_returns_false(capability_db) -> None:
    _seed_capability('{"unrelated": true}')
    assert not merge_worktree_ci._project_declares_ci_workflow(_ctx("yoke"))


def test_missing_project_context_returns_false(capability_db) -> None:
    assert not merge_worktree_ci._project_declares_ci_workflow(_ctx(None))
