"""Internal helper tests for ``yoke_core.domain.epic``.

Covers cascade_task_status, orphan_check, migrate_task_files,
_parse_epic_id, _validate_epic_exists, history_insert, and pipe helpers.

Split from ``test_epic_full.py``.
"""

from __future__ import annotations

import pytest

from yoke_core.domain import epic
from runtime.api.conftest import insert_epic_task, insert_item
from runtime.api.fixtures.file_test_db import apply_sql_script

TEST_EPIC_ID = 42
TEST_EPIC_REF = f"YOK-{TEST_EPIC_ID}"


class TestCascadeTaskStatus:
    def test_unknown_cascade_returns_zero(self, test_db):
        result = epic.cascade_task_status(test_db, "42", "idea", "done")
        assert result == "0"

    def test_no_eligible_tasks_returns_zero(self, test_db):
        epic.task_upsert(test_db, "42", 1, "Task 1", "", "", "")
        epic.task_update_status(test_db, "42", 1, "implementing")
        # cascade planning -> plan-drafted won't match tasks in implementing
        result = epic.cascade_task_status(test_db, "42", "planning", "plan-drafted")
        assert result == "0"

    def test_cascade_map_entries(self):
        """Verify all expected cascade mappings exist."""
        expected_keys = [
            ("planning", "plan-drafted"),
            ("plan-drafted", "refining-plan"),
            ("refining-plan", "planned"),
            ("reviewed-implementation", "polishing-implementation"),
            ("polishing-implementation", "implemented"),
            ("implemented", "release"),
            ("release", "done"),
            # Reverse
            ("plan-drafted", "planning"),
            ("planned", "refining-plan"),
            ("refining-plan", "plan-drafted"),
            ("planned", "plan-drafted"),
            ("polishing-implementation", "reviewed-implementation"),
            ("implemented", "polishing-implementation"),
            ("release", "implemented"),
            ("done", "release"),
        ]
        for key in expected_keys:
            assert key in epic._CASCADE_MAP, f"Missing cascade key: {key}"


class TestOrphanCheck:
    def test_finds_orphans(self, test_db):
        # Epic 201: has tasks but no Technical Plan
        insert_item(test_db, id=201, title="Epic 201", type="epic", spec="Just a description")
        insert_epic_task(test_db, epic_id=201, task_num=1, title="Task 1")

        # Epic 202: has tasks but null body
        insert_item(test_db, id=202, title="Epic 202", type="epic", spec=None)
        insert_epic_task(test_db, epic_id=202, task_num=1, title="Task 1")

        # Epic 200: has tasks AND Technical Plan (not orphan)
        insert_item(test_db, id=200, title="Epic 200", type="epic",
                     technical_plan="Plan details here.")
        insert_epic_task(test_db, epic_id=200, task_num=1, title="Task 1")

        result = epic.orphan_check(test_db)
        lines = [l for l in result.strip().split("\n") if l]
        assert len(lines) == 2
        assert "YOK-201" in result
        assert "YOK-202" in result
        assert "YOK-200" not in result

    def test_no_orphans(self, test_db):
        insert_item(test_db, id=200, title="Epic 200", type="epic",
                     technical_plan="Plan details.")
        insert_epic_task(test_db, epic_id=200, task_num=1, title="Task 1")
        result = epic.orphan_check(test_db)
        assert result == ""


class TestMigrateTaskFiles:
    def test_already_has_unique(self, test_db):
        """When UNIQUE already in place, migration is no-op."""
        epic.task_upsert(test_db, "42", 1, "Widget", "", "", "")
        result = epic.migrate_task_files(test_db)
        assert "already in place" in result

    def test_migration_deduplicates(self, test_db):
        """Build a table without UNIQUE, insert duplicates, migrate."""
        epic.task_upsert(test_db, "42", 1, "Widget", "", "", "")

        # Drop and recreate without UNIQUE constraint
        apply_sql_script(test_db, """
            DROP TABLE epic_task_files;
            CREATE TABLE epic_task_files (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                epic_id INTEGER NOT NULL,
                task_num INTEGER NOT NULL,
                file_path TEXT NOT NULL,
                action TEXT,
                FOREIGN KEY (epic_id, task_num) REFERENCES epic_tasks(epic_id, task_num)
            );
        """)

        # Insert duplicates
        test_db.execute(
            "INSERT INTO epic_task_files (epic_id, task_num, file_path, action) VALUES (42, 1, 'src/a.sh', 'create')"
        )
        test_db.execute(
            "INSERT INTO epic_task_files (epic_id, task_num, file_path, action) VALUES (42, 1, 'src/a.sh', 'modify')"
        )
        test_db.execute(
            "INSERT INTO epic_task_files (epic_id, task_num, file_path, action) VALUES (42, 1, 'src/b.sh', 'create')"
        )
        test_db.commit()

        pre_count = test_db.execute("SELECT COUNT(*) FROM epic_task_files").fetchone()[0]
        assert pre_count == 3

        result = epic.migrate_task_files(test_db)
        assert "Migration complete" in result

        post_count = test_db.execute("SELECT COUNT(*) FROM epic_task_files").fetchone()[0]
        assert post_count == 2

    def test_idempotent_after_migration(self, test_db):
        """Second migration call is no-op."""
        result = epic.migrate_task_files(test_db)
        assert "already in place" in result


class TestParseEpicId:
    def test_bare_integer(self):
        assert epic._parse_epic_id("42") == "42"

    def test_sun_prefix(self):
        assert epic._parse_epic_id(TEST_EPIC_REF) == str(TEST_EPIC_ID)

    def test_sun_prefix_case_insensitive(self):
        assert epic._parse_epic_id("yok-42") == "42"

    def test_leading_zeros_stripped(self):
        assert epic._parse_epic_id("042") == "42"

    def test_empty_raises(self):
        with pytest.raises(ValueError, match="epic ID is required"):
            epic._parse_epic_id("")


class TestValidateEpicExists:
    def test_integer_always_passes(self, test_db):
        """Pure integer IDs are assumed valid (no DB check)."""
        epic._validate_epic_exists(test_db, "42")  # Should not raise

    def test_nonexistent_slug_raises(self, test_db):
        with pytest.raises(LookupError, match="not found in epic_tasks"):
            epic._validate_epic_exists(test_db, "implement-jwt-auth-middleware")

    def test_existing_slug_passes(self, test_db):
        insert_epic_task(test_db, epic_id=42, task_num=1, title="Task 1")
        # "42" is an integer string, so it passes without DB check
        epic._validate_epic_exists(test_db, "42")


class TestHistoryInsert:
    def test_returns_message(self, test_db):
        """history_insert returns a formatted message (subprocess may fail in test)."""
        epic.task_upsert(test_db, "42", 1, "Widget", "", "", "")
        result = epic.history_insert(
            test_db, "42", 1, "planning", "implementing", "First transition",
            scripts_dir="/nonexistent"
        )
        assert "Inserted history: 42/1 planning -> implementing" in result


class TestPipeHelpers:
    def test_pipe_row(self, test_db):
        epic.task_upsert(test_db, "42", 1, "Widget", "", "", "")
        row = test_db.execute(
            "SELECT id, epic_id, task_num, title FROM epic_tasks WHERE epic_id='42'"
        ).fetchone()
        result = epic._pipe_row(row, ["id", "epic_id", "task_num", "title"])
        parts = result.split("|")
        assert len(parts) == 4
        assert parts[1] == "42"
        assert parts[3] == "Widget"

    def test_pipe_row_null_values(self, test_db):
        epic.task_upsert(test_db, "42", 1, "Widget", "", "", "")
        row = test_db.execute(
            "SELECT id, body FROM epic_tasks WHERE epic_id='42'"
        ).fetchone()
        result = epic._pipe_row(row, ["id", "body"])
        # body is NULL -> empty string in pipe output
        assert result.endswith("|")
