export function ok(result) {
  return { status: 200, envelope: { success: true, result } };
}

const noCapabilities = {
  required_capability_kinds: [],
  required_capabilities: [],
};

const browserCapabilities = {
  required_capability_kinds: ["browser-control"],
  required_capabilities: [{
    kind: "browser-control",
    label: "Browser control",
    state: "ready",
    context: { state: "ready" },
  }],
};

export const methods = [
  {
    id: "command",
    name: "Command",
    description:
      "Run deterministic project commands in a worktree.",
    source_kind: "built_in",
    source_ref: null,
    runner_id: "worktree_run",
    runner_gloss: "runs the case's command in the item worktree",
    ...noCapabilities,
    verdict_path: "automatic",
    verdict_contract: "exit 0 = pass",
    evidence_contract: "exit code · captured output tail",
    success_policy_id: "all-pass",
    concurrency_mode: "parallel",
    used_by_plan_count: 2,
  },
  {
    id: "browser-check",
    name: "Browser check",
    description: "Playwright-style assertions against declared routes.",
    source_kind: "built_in",
    source_ref: null,
    runner_id: "browser_substrate",
    runner_gloss: "the registered browser-control substrate",
    ...browserCapabilities,
    verdict_path: "automatic",
    verdict_contract: "assertions",
    evidence_contract: "assertions · trace · logs",
    success_policy_id: "all-pass",
    concurrency_mode: "parallel",
    used_by_plan_count: 1,
  },
];

export const planRow = {
  id: 7,
  project: "yoke",
  slug: "release-readiness",
  name: "Release readiness",
  description: "",
  case_count: 2,
  materialized_requirement_count: 2,
  method_ids: ["command", "browser-check"],
  attachments: [{
    kind: "project_default",
    project: "yoke",
    workflow_id: "issue",
    transition_id: "reviewed-implementation",
    transition_label: "Review gate",
    item_id: null,
  }, {
    kind: "item",
    project: "yoke",
    workflow_id: "issue",
    transition_id: "reviewing-implementation",
    transition_label: "Implementation review",
    item_id: 2001,
    item_ref: "YOK-2001",
  }],
  last_outcome: "needs_review",
  last_at: "2026-07-26T12:00:00Z",
};

export const planDetail = {
  ...planRow,
  project_id: 1,
  success_policy_id: "all-pass",
  success_policy_params: {},
  created_at: "2026-07-26T10:00:00Z",
  updated_at: "2026-07-26T10:00:00Z",
  retired_at: null,
  cases: [
    {
      id: 1,
      case_key: "backend-suite",
      position: 1,
      method_id: "command",
      method_name: "Command",
      runner_id: "worktree_run",
      ...noCapabilities,
      verdict_path: "automatic",
      instructions: "Run it.",
      expected_outcome: "It passes.",
      method_config: {},
      success_policy_id: null,
      success_policy_params: null,
      host_baselines: [],
      entry_surface: null,
      required_completion: null,
      last_result: {
        requirement_id: 31,
        run_id: 91,
        outcome: "passed",
        evidence: [{
          id: 4,
          artifact_type: "output",
          content_type: "text/plain",
          artifact_handle: "{\"backend\":\"local\",\"path\":\"output.txt\"}",
          metadata: {},
        }],
      },
    },
    {
      id: 2,
      case_key: "checkout-flow",
      position: 2,
      method_id: "browser-check",
      method_name: "Browser check",
      runner_id: "browser_substrate",
      ...browserCapabilities,
      verdict_path: "automatic",
      instructions: "Open checkout.",
      expected_outcome: "Confirmation is visible.",
      method_config: {},
      success_policy_id: null,
      success_policy_params: null,
      host_baselines: [],
      entry_surface: null,
      required_completion: null,
      last_result: {
        requirement_id: 32,
        run_id: 92,
        outcome: "needs_review",
        evidence: [],
      },
    },
    {
      id: 3,
      case_key: "queued-browser",
      position: 3,
      method_id: "browser-check",
      method_name: "Browser check",
      runner_id: "browser_substrate",
      ...browserCapabilities,
      verdict_path: "automatic",
      instructions: "Wait for its turn.",
      expected_outcome: "It eventually runs.",
      method_config: {},
      success_policy_id: null,
      success_policy_params: null,
      host_baselines: [],
      entry_surface: null,
      required_completion: null,
      last_result: {
        requirement_id: 33,
        run_id: null,
        outcome: "queued",
        evidence: [],
      },
    },
    {
      id: 4,
      case_key: "cold-start-hosted",
      position: 4,
      method_id: "browser-check",
      method_name: "Browser check",
      runner_id: "browser_substrate",
      ...browserCapabilities,
      verdict_path: "automatic",
      instructions: "Verify the hosted cold start.",
      expected_outcome: "The correct handoff is visible.",
      method_config: {},
      success_policy_id: null,
      success_policy_params: null,
      host_baselines: ["fresh-host", "shell-preconfigured"],
      entry_surface: null,
      required_completion: null,
      proofs: [{
        requirement_id: 34,
        run_id: 94,
        host_baseline: "fresh-host",
        outcome: "failed",
        evidence: [{
          id: 6,
          artifact_type: "screenshot",
          content_type: "image/png",
          artifact_handle:
            "{\"backend\":\"local\",\"path\":\"fresh-host.png\"}",
          metadata: {},
        }],
      }, {
        requirement_id: 35,
        run_id: 95,
        host_baseline: "shell-preconfigured",
        outcome: "needs_review",
        evidence: [{
          id: 7,
          artifact_type: "screenshot",
          content_type: "image/png",
          artifact_handle:
            "{\"backend\":\"local\",\"path\":\"shell-preconfigured.png\"}",
          metadata: {},
        }],
      }],
    },
  ],
  union: {
    satisfied: false,
    counts: { passed: 1, needs_review: 2, queued: 1, failed: 1 },
  },
};
