const commonMethod = {
  description: "A registered QA method.",
  success_policy_id: "all-pass",
  success_policy_params: {},
  used_by_plan_count: 0,
  plans: [],
};

const machineContext = {
  state: "in_use",
  concurrency_mode: "serial",
  wait_reason: "serial_lease_in_use",
  active_lease: { item_ref: "YOK-2001" },
};

export const methods = [
  {
    ...commonMethod,
    id: "command",
    name: "Command",
    source_kind: "built_in",
    source_ref: null,
    runner_id: "worktree_run",
    runner_gloss: "runs the case's command in the item worktree",
    required_capability_kind: null,
    verdict_path: "automatic",
    verdict_contract: "exit 0 = pass",
    evidence_contract: "exit code · captured output tail",
    concurrency_mode: "parallel",
    capability_state: "available",
    capability_context: { state: "available" },
  },
  {
    ...commonMethod,
    id: "browser-check",
    name: "Browser check",
    source_kind: "built_in",
    source_ref: null,
    runner_id: "browser_substrate",
    runner_gloss:
      "the machine-local browser daemon — recorded on every run today",
    required_capability_label: "Browser control",
    required_capability_kind: "browser-control",
    verdict_path: "automatic",
    verdict_contract: "assertions",
    evidence_contract: "assertions · trace · logs",
    concurrency_mode: "parallel",
    capability_state: "ready",
    capability_context: { state: "ready" },
  },
  {
    ...commonMethod,
    id: "browser-inspection",
    name: "Browser inspection",
    source_kind: "built_in",
    source_ref: null,
    runner_id: "browser_substrate",
    runner_gloss:
      "the machine-local browser daemon — recorded on every run today",
    required_capability_label: "Browser control",
    required_capability_kind: "browser-control",
    verdict_path: "agent",
    verdict_contract:
      "inspects the screenshot against the case's expected outcome",
    evidence_contract: "screenshots · inspection verdict",
    concurrency_mode: "parallel",
    capability_state: "ready",
    capability_context: { state: "ready" },
  },
  {
    ...commonMethod,
    id: "terminal-check",
    name: "Terminal check",
    source_kind: "pack",
    source_ref: "machine-qa",
    runner_id: "host_control",
    runner_gloss: "SSH + PTY on the capability-named machine",
    required_capability_label: "Test machine",
    required_capability_kind: "test-machine",
    verdict_path: "automatic",
    verdict_contract: "transcript checkpoints met",
    evidence_contract: "step transcript · checkpoint expectations",
    concurrency_mode: "serial",
    capability_state: "in_use",
    capability_context: machineContext,
  },
  {
    ...commonMethod,
    id: "terminal-inspection",
    name: "Terminal inspection",
    source_kind: "pack",
    source_ref: "machine-qa",
    runner_id: "host_control",
    runner_gloss: "SSH + PTY on the capability-named machine",
    required_capability_label: "Test machine",
    required_capability_kind: "test-machine",
    verdict_path: "agent",
    verdict_contract:
      "inspects Terminal captures against the case's expected outcome",
    evidence_contract:
      "paired text + Terminal screenshots · inspection verdict",
    concurrency_mode: "serial",
    capability_state: "in_use",
    capability_context: machineContext,
  },
  {
    ...commonMethod,
    id: "machine-state-check",
    name: "Machine state check",
    source_kind: "pack",
    source_ref: "machine-qa",
    runner_id: "host_control",
    runner_gloss: "shell assertions on the controlled host",
    required_capability_label: "Test machine",
    required_capability_kind: "test-machine",
    verdict_path: "automatic",
    verdict_contract: "exit 0 on the host",
    evidence_contract: "assertion commands · outputs · secret scan",
    concurrency_mode: "serial",
    capability_state: "in_use",
    capability_context: machineContext,
  },
];
