"""Shared fixtures for the board renderer test suite."""

from __future__ import annotations

import textwrap
from datetime import datetime, timedelta
from functools import partial
import pytest

from yoke_core.board.db import BoardDB
from yoke_core.board.tests.helpers import (
    insert_activity_day,
    insert_deployment_run,
    insert_event,
    insert_item,
    insert_item_raw,
    insert_projects,
    insert_run_item,
    insert_task,
    insert_transition,
    insert_zen_items,
)
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)


# ---------------------------------------------------------------------------
# Schema DDL — single source for test DB creation
# ---------------------------------------------------------------------------

_SCHEMA_DDL = textwrap.dedent("""\
    CREATE TABLE items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT,
        type TEXT DEFAULT 'issue',
        priority TEXT DEFAULT 'medium',
        status TEXT DEFAULT 'idea',
        progress TEXT DEFAULT '',
        worktree TEXT DEFAULT '',
        project_id INTEGER DEFAULT 1,
        project_sequence INTEGER,
        updated_at TEXT DEFAULT '2025-01-01',
        created_at TEXT DEFAULT '2025-01-01',
        frozen INTEGER DEFAULT 0,
        blocked INTEGER DEFAULT 0,
        blocked_reason TEXT
    );

    CREATE TABLE projects (
        id INTEGER PRIMARY KEY,
        slug TEXT NOT NULL UNIQUE,
        name TEXT DEFAULT '',
        emoji TEXT DEFAULT '',
        default_branch TEXT DEFAULT 'main',
        github_repo TEXT DEFAULT '',
        public_item_prefix TEXT DEFAULT 'YOK',
        created_at TEXT DEFAULT '2025-01-01'
    );

    CREATE TABLE epic_tasks (
        epic_id INTEGER,
        task_num INTEGER,
        title TEXT,
        status TEXT DEFAULT 'pending',
        PRIMARY KEY (epic_id, task_num)
    );

    CREATE TABLE config (
        key TEXT PRIMARY KEY,
        value TEXT
    );

    CREATE TABLE item_activity_days (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        project_id INTEGER NOT NULL,
        item_id INTEGER NOT NULL,
        day TEXT NOT NULL,
        UNIQUE(project_id, item_id, day)
    );

    CREATE TABLE item_status_transitions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_id INTEGER NOT NULL,
        task_num INTEGER,
        from_status TEXT,
        to_status TEXT NOT NULL,
        source TEXT,
        session_id TEXT,
        actor_id INTEGER,
        project_id INTEGER,
        created_at TEXT NOT NULL
    );

    CREATE TABLE deployment_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        flow_id INTEGER,
        current_stage TEXT,
        status TEXT DEFAULT 'running',
        created_by TEXT DEFAULT '',
        created_at TEXT DEFAULT '',
        completed_at TEXT DEFAULT ''
    );

    CREATE TABLE deployment_run_items (
        run_id INTEGER,
        item_id INTEGER,
        PRIMARY KEY (run_id, item_id)
    );

    CREATE TABLE events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_name TEXT,
        project_id INTEGER,
        envelope TEXT,
        created_at TEXT
    );

    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (1, 'yoke', 'Yoke', '', 'YOK');
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (2, 'buzz', 'Buzz', '', 'BUZ');
""")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def test_db_path(tmp_path):
    with init_test_db(
        tmp_path,
        apply_schema=partial(apply_inline_ddl, _SCHEMA_DDL),
    ) as db_path:
        yield db_path


@pytest.fixture
def test_db(test_db_path):
    db = BoardDB(test_db_path)
    yield db
    db.close()


@pytest.fixture
def config_file(tmp_path):
    cfg = tmp_path / "config"
    cfg.write_text(textwrap.dedent("""\
        dashboard_velocity=true
        dashboard_weather=true
        dashboard_velocity_meter=false
    """))
    return str(cfg)


_ZEN_DDL = textwrap.dedent("""\
    CREATE TABLE projects (
        id INTEGER PRIMARY KEY,
        slug TEXT NOT NULL UNIQUE,
        name TEXT DEFAULT '',
        emoji TEXT DEFAULT '',
        public_item_prefix TEXT DEFAULT 'YOK'
    );
    CREATE TABLE items (
        id INTEGER PRIMARY KEY,
        title TEXT,
        project_id INTEGER DEFAULT 1,
        project_sequence INTEGER,
        status TEXT,
        type TEXT DEFAULT 'issue',
        created_at TEXT DEFAULT '2025-01-15',
        frozen INTEGER DEFAULT 0
    );
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (1, 'yoke', 'Yoke', '\U0001f305', 'YOK');
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (2, 'buzz', 'Buzz', '\U0001f41d', 'BUZ');
""")


@pytest.fixture
def zen_db(tmp_path):
    with init_test_db(
        tmp_path,
        apply_schema=partial(apply_inline_ddl, _ZEN_DDL),
    ) as db_path:
        yield db_path


def _execute_many(conn, sql: str, rows: list) -> None:
    for row in rows:
        conn.execute(sql, row)


@pytest.fixture
def populated_db(test_db_path):
    """Add sample items and epic tasks to the test DB, return the path."""
    conn = connect_test_db(test_db_path)
    _execute_many(
        conn,
        "INSERT INTO items "
        "(id, title, type, priority, status, project_id, "
        "project_sequence, updated_at)"
        " VALUES (%s, %s, %s, %s, %s, 1, %s, %s)",
        [
            (1, "First item", "issue", "high", "implementing", 1, "2025-03-01"),
            (2, "Second item", "issue", "medium", "idea", 2, "2025-03-02"),
            (3, "Third item", "epic", "high", "implementing", 3, "2025-03-03"),
            (4, "Done item", "issue", "low", "done", 4, "2025-03-04"),
            (5, "Frozen item", "issue", "medium", "idea", 5, "2025-03-05"),
        ],
    )
    conn.execute("UPDATE items SET frozen = 1 WHERE id = 5")
    _execute_many(
        conn,
        "INSERT INTO epic_tasks (epic_id, task_num, title, status) VALUES (%s, %s, %s, %s)",
        [
            (3, 1, "Task A", "done"),
            (3, 2, "Task B", "pending"),
        ],
    )
    conn.commit()
    conn.close()
    return test_db_path
