"""Minimal board database for rendering the Sessions section.

Seeds just the tables and columns ``render_sessions_section`` reads, plus
helpers that insert one session row or one item claim.
"""

from __future__ import annotations

from yoke_contracts.timestamps import parse_instant

import contextlib
from pathlib import Path

from yoke_core.board.db import BoardDB
from yoke_core.domain.model_reference_store import (
    create_model_reference_table,
    seed_initial_catalog,
)
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)
from yoke_core.domain.work_claim_targets import make_item_target


_RENDER_SCHEMA = """
    CREATE TABLE projects (
        id INTEGER PRIMARY KEY,
        slug TEXT UNIQUE,
        name TEXT DEFAULT '',
        emoji TEXT DEFAULT '',
        public_item_prefix TEXT DEFAULT 'YOK'
    );
    CREATE TABLE harness_sessions (
        session_id TEXT PRIMARY KEY,
        executor TEXT NOT NULL,
        executor_surface TEXT DEFAULT NULL,
        provider TEXT,
        model TEXT,
        reasoning_effort TEXT DEFAULT NULL,
        context_window_tokens INTEGER DEFAULT NULL,
        requested_model TEXT DEFAULT NULL,
        requested_reasoning_effort TEXT DEFAULT NULL,
        requested_context_window_tokens INTEGER DEFAULT NULL,
        usage_totals TEXT DEFAULT NULL,
        execution_level TEXT DEFAULT 'primary',
        mode TEXT DEFAULT 'wait',
        workspace TEXT DEFAULT '',
        project_id INTEGER NOT NULL REFERENCES projects(id),
        offered_at TIMESTAMPTZ NOT NULL,
        last_heartbeat TIMESTAMPTZ,
        last_tool_call_at TIMESTAMPTZ,
        ended_at TIMESTAMPTZ,
        terminated_at TIMESTAMPTZ
    );
    CREATE TABLE items (
        id INTEGER PRIMARY KEY,
        project_id INTEGER,
        project_sequence INTEGER
    );
    CREATE TABLE work_claims (
        id INTEGER PRIMARY KEY,
        session_id TEXT,
        scope TEXT NOT NULL,
        claim_type TEXT,
        claimed_at TIMESTAMPTZ,
        released_at TIMESTAMPTZ,
        release_reason TEXT,
        target_kind TEXT
    );
    CREATE TABLE path_claims (
        id INTEGER PRIMARY KEY,
        owner_kind TEXT,
        owner_item_id INTEGER,
        owner_session_id TEXT,
        owner_work_claim_id INTEGER,
        released_at TIMESTAMPTZ,
        cancelled_at TIMESTAMPTZ,
        release_reason TEXT,
        cancel_reason TEXT
    );
    CREATE TABLE path_claim_targets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        claim_id INTEGER
    );
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (1, 'yoke', 'Yoke', '🐂', 'YOK');
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (2, 'externalwebapp', 'ExternalWebapp', '🧩', 'EXT');
"""


def _apply_render_schema() -> None:
    apply_inline_ddl(_RENDER_SCHEMA)


@contextlib.contextmanager
def make_render_db(tmp_path: Path):
    """Yield a minimal BoardDB with the columns ``render_sessions_section`` reads.

    Context manager so the disposable per-test Postgres database
    :func:`init_test_db` provisions is dropped after the test body runs.
    """
    from yoke_contracts.board.sections_sessions import render_sessions_section

    with init_test_db(tmp_path, apply_schema=_apply_render_schema) as db_path:
        with connect_test_db(db_path) as conn:
            create_model_reference_table(conn)
            seed_initial_catalog(conn)
        db = BoardDB(db_path)
        db.path = db_path
        yield db, render_sessions_section


def _native_clock(value):
    return parse_instant(value) if value is not None else None


def insert_render_session(db, **kwargs) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            """INSERT INTO harness_sessions
               (session_id, executor, executor_surface, provider, model,
                execution_level, mode, workspace, project_id, offered_at, last_heartbeat,
                ended_at, terminated_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                kwargs["session_id"],
                kwargs["executor"],
                kwargs.get("executor_surface"),
                kwargs.get("provider", "anthropic"),
                kwargs.get("model", "claude-opus-4-7[1m]"),
                kwargs.get("execution_level", "primary"),
                kwargs.get("mode", "wait"),
                kwargs.get("workspace", ""),
                kwargs.get("project_id", 1),
                _native_clock(kwargs.get("offered_at", "2026-05-19T20:00:00Z")),
                _native_clock(kwargs.get("last_heartbeat", "2026-05-19T20:01:00Z")),
                _native_clock(kwargs.get("ended_at")),
                _native_clock(kwargs.get("terminated_at")),
            ),
        )
        raw.commit()
    finally:
        raw.close()


def insert_render_item_claim(
    db, *, session_id: str, item_id: int, project: str
) -> None:
    raw = connect_test_db(db.path)
    try:
        project_id = 2 if project == "externalwebapp" else 1
        raw.execute(
            "INSERT INTO items (id, project_id, project_sequence) VALUES (%s, %s, %s)",
            (item_id, project_id, item_id),
        )
        raw.execute(
            """INSERT INTO work_claims
               (id, session_id, scope, claim_type, claimed_at, target_kind)
               VALUES (%s, %s, %s, %s, %s, %s)""",
            (
                item_id,
                session_id,
                make_item_target(item_id).scope_json(),
                "work",
                parse_instant("2026-05-19T20:02:00Z"),
                "item",
            ),
        )
        raw.commit()
    finally:
        raw.close()
