"""Regression tests for item-linked path-claim rollup on active sessions.

Covers the rollup behavior where a ``work_claim`` on ``YOK-N`` must
decorate its keycap with the summed declared-path count from
non-terminal ``path_claims`` rows where ``path_claims.item_id = N``, even
when those rows have ``session_id IS NULL``. Lives in a focused sibling
module so :mod:`test_sections_sessions` stays under the 350-line file
budget hard limit.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from yoke_core.board.db import BoardDB
from yoke_contracts.board.sections_sessions_extra_claims import build_session_keycaps
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)


_SCHEMA = """
CREATE TABLE work_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    process_key TEXT
);
CREATE TABLE path_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    item_id INTEGER,
    work_claim_id INTEGER,
    owner_kind TEXT,
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    registered_by_actor_id INTEGER,
    registered_by_session_id TEXT,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT
);
CREATE TABLE path_claim_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER
);
CREATE TABLE coordination_leases (
    id INTEGER PRIMARY KEY,
    project_id TEXT,
    lease_key TEXT,
    session_id TEXT,
    released_at TEXT,
    release_reason TEXT
);
"""


def _apply_board_schema() -> None:
    apply_inline_ddl(_SCHEMA)


@pytest.fixture
def board_db(tmp_path: Path):
    with init_test_db(tmp_path, apply_schema=_apply_board_schema) as db_path:
        db = BoardDB(db_path)
        db.path = db_path
        yield db


def _insert_path_claim(
    db, *, claim_id: int, session_id, item_id, declared_count: int,
    work_claim_id=None, released_at=None, cancelled_at=None,
    release_reason=None, cancel_reason=None,
    owner_kind=None, owner_item_id=None, owner_session_id=None,
    owner_work_claim_id=None,
) -> None:
    # Derive typed owner from legacy signals when not explicit (matches
    # migration backfill rules).
    if (
        owner_kind is None
        and owner_item_id is None
        and owner_session_id is None
        and owner_work_claim_id is None
    ):
        if item_id is not None:
            owner_kind = "item"
            owner_item_id = item_id
        elif work_claim_id is not None:
            owner_kind = "process"
            owner_work_claim_id = work_claim_id
        elif session_id is not None:
            owner_kind = "session"
            owner_session_id = session_id
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO path_claims (id, session_id, item_id, work_claim_id, "
            "owner_kind, owner_item_id, owner_session_id, "
            "owner_work_claim_id, "
            "released_at, cancelled_at, release_reason, cancel_reason) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (
                claim_id, session_id, item_id, work_claim_id,
                owner_kind, owner_item_id, owner_session_id,
                owner_work_claim_id,
                released_at, cancelled_at, release_reason, cancel_reason,
            ),
        )
        for _ in range(declared_count):
            raw.execute(
                "INSERT INTO path_claim_targets (claim_id) VALUES (%s)",
                (claim_id,),
            )
        raw.commit()
    finally:
        raw.close()


class TestItemLinkedPathClaimRollup:
    """Item-linked path_claims with session_id IS NULL decorate the work claim."""

    def test_null_session_item_claim_decorates_active_work_claim(
        self, board_db: BoardDB,
    ) -> None:
        # Roll up item-linked rows for the work-claim item.
        _insert_path_claim(
            board_db, claim_id=30, session_id=None, item_id=1665,
            declared_count=186,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, None)], active_only=True,
        )
        assert keycaps == ["YOK-1665 \U0001f4c1186"]

    def test_item_linked_claim_not_in_work_claims_unchanged(
        self, board_db: BoardDB,
    ) -> None:
        # An item-linked claim on a different item with no session
        # attribution must not synthesize a decoration or orphan keycap on
        # the active session row.
        _insert_path_claim(
            board_db, claim_id=31, session_id=None, item_id=1666,
            declared_count=4,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == ["YOK-1663"]

    def test_released_item_linked_claim_hidden_from_active_row(
        self, board_db: BoardDB,
    ) -> None:
        # Released item-linked rows must not decorate active rows.
        _insert_path_claim(
            board_db, claim_id=32, session_id=None, item_id=1665,
            declared_count=12, released_at="2026-05-01T00:00:00Z",
            release_reason="merged",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, None)], active_only=True,
        )
        assert keycaps == ["YOK-1665"]

    def test_cancelled_item_linked_claim_hidden_from_active_row(
        self, board_db: BoardDB,
    ) -> None:
        # Cancelled item-linked rows are also non-terminal-only.
        _insert_path_claim(
            board_db, claim_id=33, session_id=None, item_id=1665,
            declared_count=8, cancelled_at="2026-05-01T00:00:00Z",
            cancel_reason="superseded",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, None)], active_only=True,
        )
        assert keycaps == ["YOK-1665"]

    def test_session_and_item_linked_row_counted_once(
        self, board_db: BoardDB,
    ) -> None:
        # A single path_claim that is both session-linked AND
        # item-linked is counted exactly once.
        _insert_path_claim(
            board_db, claim_id=34, session_id="sess-A", item_id=1665,
            declared_count=7,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, None)], active_only=True,
        )
        assert keycaps == ["YOK-1665 \U0001f4c17"]

    def test_true_session_owned_orphan_renders_alongside_item_rollup(
        self, board_db: BoardDB,
    ) -> None:
        # Typed contract: a true session-owned claim (no item, no work
        # claim) renders as a bare keycap alongside the item-linked
        # rollup on the held work claim. An item-owned claim on a
        # different item is provenance-only and does NOT render.
        _insert_path_claim(
            board_db, claim_id=35, session_id=None, item_id=1665,
            declared_count=186,
        )
        _insert_path_claim(
            board_db, claim_id=36, session_id="sess-A", item_id=None,
            owner_kind="session", owner_session_id="sess-A",
            declared_count=2,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, None)], active_only=True,
        )
        assert keycaps == [
            "YOK-1665 \U0001f4c1186",
            "\U0001f4c12",
        ]

    def test_item_linked_fallback_is_active_row_only(
        self, board_db: BoardDB,
    ) -> None:
        # Recent-session rows keep their existing session-linked behavior;
        # sessionless item claims belong to the active item holder only.
        _insert_path_claim(
            board_db, claim_id=37, session_id=None, item_id=1665,
            declared_count=5,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1665", 1665, "completed")],
            active_only=False,
        )
        assert keycaps == ["YOK-1665 (completed)"]
