"""Tests for the BOARD.md Claims column renderer.

Covers:

* :func:`_render_claim_target` — the existing INTEGER ``item_id`` coercion.
* :func:`build_session_keycaps` — the three keycap shapes contributed by
  this ticket (work-claim only, work+path-claim decoration, orphan path-
  claim parens shape, lease keycap, same-item path-claim roll-up,
  multi-item path-claim separation, ``item_id IS NULL`` process anchor
  fallback, and closed-session ``(release_reason)`` decoration).
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

import pytest

from yoke_core.board.db import BoardDB
from yoke_contracts.board.sections_sessions import _render_claim_target
from yoke_contracts.board.sections_sessions_extra_claims import build_session_keycaps
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)


def test_render_claim_target_with_int_item_id():
    assert _render_claim_target(1577, None, None) == "YOK-1577"


def test_render_claim_target_with_str_item_id_keeps_prefix():
    assert _render_claim_target("YOK-1577", None, None) == "YOK-1577"


def test_render_claim_target_with_str_item_id_adds_prefix():
    assert _render_claim_target("1577", None, None) == "YOK-1577"


def test_render_claim_target_with_epic_task_falls_back():
    assert _render_claim_target(None, 1577, 4) == "YOK-1577 T004"


def test_render_claim_target_with_no_target_returns_question():
    assert _render_claim_target(None, None, None) == "?"


_SCHEMA = """
CREATE TABLE work_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    process_key TEXT
);
CREATE TABLE path_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    item_id INTEGER,
    work_claim_id INTEGER,
    owner_kind TEXT,
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    registered_by_actor_id INTEGER,
    registered_by_session_id TEXT,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT
);
CREATE TABLE path_claim_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER
);
CREATE TABLE coordination_leases (
    id INTEGER PRIMARY KEY,
    project_id TEXT,
    lease_key TEXT,
    session_id TEXT,
    released_at TEXT,
    release_reason TEXT
);
"""


def _apply_board_schema() -> None:
    apply_inline_ddl(_SCHEMA)


@pytest.fixture
def board_db(tmp_path: Path):
    with init_test_db(tmp_path, apply_schema=_apply_board_schema) as db_path:
        db = BoardDB(db_path)
        db.path = db_path
        yield db


def _insert_path_claim(
    db, *, claim_id: int, session_id, item_id, declared_count: int,
    work_claim_id=None, released_at=None, cancelled_at=None,
    release_reason=None, cancel_reason=None,
    owner_kind=None, owner_item_id=None, owner_session_id=None,
    owner_work_claim_id=None,
) -> None:
    # Derive typed owner from legacy signals when not explicitly provided
    # (matches migration backfill: item > process > session).
    if owner_kind is None and not any(
        (owner_item_id, owner_session_id, owner_work_claim_id)
    ):
        if item_id is not None:
            owner_kind, owner_item_id = "item", item_id
        elif work_claim_id is not None:
            owner_kind, owner_work_claim_id = "process", work_claim_id
        elif session_id is not None:
            owner_kind, owner_session_id = "session", session_id
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO path_claims (id, session_id, item_id, work_claim_id, "
            "owner_kind, owner_item_id, owner_session_id, owner_work_claim_id, "
            "released_at, cancelled_at, release_reason, cancel_reason) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (claim_id, session_id, item_id, work_claim_id,
             owner_kind, owner_item_id, owner_session_id, owner_work_claim_id,
             released_at, cancelled_at, release_reason, cancel_reason),
        )
        for _ in range(declared_count):
            raw.execute(
                "INSERT INTO path_claim_targets (claim_id) VALUES (%s)",
                (claim_id,),
            )
        raw.commit()
    finally:
        raw.close()


def _insert_lease(
    db, *, lease_id: int, session_id: str, lease_key: str,
    released_at=None, release_reason=None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO coordination_leases "
            "(id, project_id, lease_key, session_id, released_at, release_reason) "
            "VALUES (%s, %s, %s, %s, %s, %s)",
            (lease_id, "yoke", lease_key, session_id, released_at, release_reason),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_work_claim(db, *, claim_id: int, process_key: str) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims (id, session_id, process_key) VALUES (%s, %s, %s)",
            (claim_id, "sess-A", process_key),
        )
        raw.commit()
    finally:
        raw.close()


class TestActiveSessionKeycaps:
    def test_work_claim_only(self, board_db: BoardDB) -> None:
        targets: List[Tuple] = [("YOK-1663", 1663, None)]
        keycaps = build_session_keycaps(
            board_db, "sess-A", targets, active_only=True,
        )
        assert keycaps == ["YOK-1663"]

    def test_work_claim_with_same_item_path_claim_decoration(
        self, board_db: BoardDB,
    ) -> None:
        _insert_path_claim(
            board_db, claim_id=10, session_id="sess-A", item_id=1663,
            declared_count=23,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == ["YOK-1663 \U0001f4c123"]

    def test_item_owned_no_work_claim_hidden(self, board_db: BoardDB) -> None:
        # Typed contract: item-owned claim registered by session is
        # provenance only; no work_claim on the item → no decoration.
        _insert_path_claim(
            board_db, claim_id=11, session_id="sess-A", item_id=1664,
            declared_count=5,
        )
        assert build_session_keycaps(
            board_db, "sess-A", [], active_only=True,
        ) == []

    def test_session_owned_renders_bare(self, board_db: BoardDB) -> None:
        # True session-owned (owner_kind='session', no item / work_claim).
        _insert_path_claim(
            board_db, claim_id=21, session_id="sess-A", item_id=None,
            owner_kind="session", owner_session_id="sess-A",
            declared_count=5,
        )
        assert build_session_keycaps(
            board_db, "sess-A", [], active_only=True,
        ) == ["\U0001f4c15"]

    def test_same_item_multiple_path_claims_roll_up(
        self, board_db: BoardDB,
    ) -> None:
        _insert_path_claim(
            board_db, claim_id=12, session_id="sess-A", item_id=1663,
            declared_count=10,
        )
        _insert_path_claim(
            board_db, claim_id=13, session_id="sess-A", item_id=1663,
            declared_count=13,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == ["YOK-1663 \U0001f4c123"]

    def test_multi_item_path_claims_split(self, board_db: BoardDB) -> None:
        # Item-owned claim for 1664 is hidden when session has no
        # work_claim on 1664 — only the 1663 claim that matches a
        # held work_claim decorates the row.
        _insert_path_claim(
            board_db, claim_id=14, session_id="sess-A", item_id=1663,
            declared_count=7,
        )
        _insert_path_claim(
            board_db, claim_id=15, session_id="sess-A", item_id=1664,
            declared_count=4,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == ["YOK-1663 \U0001f4c17"]

    def test_process_anchor_when_item_id_null(self, board_db: BoardDB) -> None:
        _insert_work_claim(board_db, claim_id=99, process_key="FEED")
        _insert_path_claim(
            board_db, claim_id=16, session_id="sess-A", item_id=None,
            work_claim_id=99, declared_count=3,
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [], active_only=True,
        )
        assert keycaps == ["\U0001f4c13 (🔩 FEED)"]

    def test_lease_keycap_separate_from_work_claim(
        self, board_db: BoardDB,
    ) -> None:
        _insert_lease(
            board_db, lease_id=1, session_id="sess-A",
            lease_key="LIVE_DB_MIGRATION:primary",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == ["YOK-1663", "\U0001f512 LIVE_DB_MIGRATION:primary"]

    def test_all_three_primitives_concurrent(self, board_db: BoardDB) -> None:
        # Item-owned claim for 1664 is hidden (no work_claim on 1664).
        # Item-owned claim for 1663 decorates the work_claim row.
        # Lease appears as a separate keycap.
        _insert_path_claim(
            board_db, claim_id=17, session_id="sess-A", item_id=1663,
            declared_count=23,
        )
        _insert_path_claim(
            board_db, claim_id=18, session_id="sess-A", item_id=1664,
            declared_count=5,
        )
        _insert_lease(
            board_db, lease_id=2, session_id="sess-A",
            lease_key="LIVE_DB_MIGRATION:primary",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [("YOK-1663", 1663, None)], active_only=True,
        )
        assert keycaps == [
            "YOK-1663 \U0001f4c123",
            "\U0001f512 LIVE_DB_MIGRATION:primary",
        ]


class TestClosedSessionKeycaps:
    def test_terminal_work_claim_decoration(self, board_db: BoardDB) -> None:
        keycaps = build_session_keycaps(
            board_db, "sess-A",
            [("YOK-1663", 1663, "completed")],
            active_only=False,
        )
        assert keycaps == ["YOK-1663 (completed)"]

    def test_terminal_session_owned_orphan_decoration(self, board_db: BoardDB) -> None:
        # Closed-session view of a true session-owned terminal claim:
        # bare "📁N (release_reason)". Item-owned terminal claims do
        # not appear here for the same reason they don't appear when
        # active — provenance is not authority.
        _insert_path_claim(
            board_db, claim_id=19, session_id="sess-A", item_id=None,
            owner_kind="session", owner_session_id="sess-A",
            declared_count=5, released_at="2026-05-01T00:00:00Z",
            release_reason="merged",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [], active_only=False,
        )
        assert keycaps == ["\U0001f4c15 (merged)"]

    def test_terminal_lease_decoration(self, board_db: BoardDB) -> None:
        _insert_lease(
            board_db, lease_id=3, session_id="sess-A",
            lease_key="LIVE_DB_MIGRATION:primary",
            released_at="2026-05-01T00:00:00Z",
            release_reason="completed",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [], active_only=False,
        )
        assert keycaps == ["\U0001f512 LIVE_DB_MIGRATION:primary (completed)"]

    def test_active_filter_hides_released_path_and_lease(
        self, board_db: BoardDB,
    ) -> None:
        _insert_path_claim(
            board_db, claim_id=20, session_id="sess-A", item_id=1664,
            declared_count=5, released_at="2026-05-01T00:00:00Z",
            release_reason="merged",
        )
        _insert_lease(
            board_db, lease_id=4, session_id="sess-A",
            lease_key="LIVE_DB_MIGRATION:primary",
            released_at="2026-05-01T00:00:00Z",
            release_reason="completed",
        )
        keycaps = build_session_keycaps(
            board_db, "sess-A", [], active_only=True,
        )
        assert keycaps == []


# Executor display rendering coverage lives in the sibling module
# ``test_sections_sessions_executor.py`` (keeps this file under the cap).
