"""Steering and typed work-claim labels live in the sessions Claims column."""

from __future__ import annotations

import contextlib
from pathlib import Path

from yoke_contracts.board.renderer import render_board_from_payload
from yoke_contracts.board.sections_sessions_holdings import session_holding_labels
from yoke_contracts.board.sections_sessions_occupancy import prefetch_session_occupancy
from yoke_contracts.board.sections_sessions_rendering import (
    _claims_for_session,
    _render_claim_target,
)
from yoke_core.board.db import BoardDB
from yoke_core.domain.work_claim_targets import make_steering_target
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)


_SCHEMA = """
CREATE TABLE projects (id INTEGER PRIMARY KEY, slug TEXT UNIQUE);
CREATE TABLE work_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    target_kind TEXT,
    scope TEXT,
    claim_type TEXT,
    claimed_at TEXT,
    released_at TEXT,
    release_reason TEXT
);
CREATE TABLE strategy_doc_claims (
    project_id INTEGER,
    strategy_doc_slug TEXT,
    owner_kind TEXT,
    owner_session_id TEXT,
    released_at TEXT
);
CREATE TABLE harness_sessions (
    session_id TEXT PRIMARY KEY,
    last_heartbeat TEXT,
    last_tool_call_at TEXT,
    ended_at TEXT,
    terminated_at TEXT
);
CREATE TABLE path_claims (
    id INTEGER PRIMARY KEY,
    owner_kind TEXT,
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT
);
CREATE TABLE path_claim_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER
);
"""


@contextlib.contextmanager
def _board_db(tmp_path: Path):
    with init_test_db(
        tmp_path,
        apply_schema=lambda: apply_inline_ddl(_SCHEMA),
    ) as db_path:
        db = BoardDB(db_path)
        try:
            yield db, db_path
        finally:
            db.close()


def _seed(db_path: str) -> None:
    conn = connect_test_db(db_path)
    try:
        conn.execute("INSERT INTO projects VALUES (1,'yoke')")
        conn.execute("INSERT INTO projects VALUES (3,'platform')")
        conn.execute(
            "INSERT INTO harness_sessions VALUES ('holder-1',NULL,NULL,NULL,NULL)"
        )
        conn.execute(
            "INSERT INTO work_claims VALUES (%s,%s,'steering',%s,NULL,%s,NULL,NULL)",
            (
                1,
                "holder-1",
                make_steering_target(1).scope_json(),
                "2026-08-26T11:00:00Z",
            ),
        )
        conn.execute(
            "INSERT INTO work_claims VALUES (%s,%s,'steering',%s,NULL,%s,NULL,NULL)",
            (
                2,
                "holder-1",
                make_steering_target(3).scope_json(),
                "2026-08-26T11:00:01Z",
            ),
        )
        conn.execute(
            "INSERT INTO strategy_doc_claims VALUES "
            "(1,'MISSION','session','holder-1',NULL)"
        )
        conn.execute(
            "INSERT INTO strategy_doc_claims VALUES "
            "(3,'CURRENT-PLAN','session','holder-1',NULL)"
        )
        conn.commit()
    finally:
        conn.close()


def test_steering_claims_stay_readable_as_typed_claim_rows(tmp_path: Path) -> None:
    """The claim rows still carry the kind; only the rendering collapsed."""
    with _board_db(tmp_path) as (db, db_path):
        _seed(db_path)
        claims = _claims_for_session(db, "holder-1")

    assert [claim[7] for claim in claims] == ["steering", "steering"]


def test_unknown_kind_renders_compact_scope() -> None:
    assert (
        _render_claim_target(
            None,
            None,
            None,
            target_kind="future_kind",
            scope={"grant_key": "abc"},
        )
        == 'future_kind:{"grant_key":"abc"}'
    )


def test_steering_claims_and_document_locks_are_each_holdings(
    tmp_path: Path,
) -> None:
    """One entry, not a lock row per project plus a separate document row."""
    with _board_db(tmp_path) as (db, db_path):
        _seed(db_path)
        prefetch_session_occupancy(db, "all")
        keycaps = session_holding_labels(db, "holder-1")

    assert keycaps == [
        "🛞 steering platform",
        "🛞 steering yoke",
        "🛞 yoke · MISSION",
        "🛞 platform · CURRENT-PLAN",
    ]


def test_a_project_steered_without_a_document_still_names_itself(
    tmp_path: Path,
) -> None:
    with _board_db(tmp_path) as (db, db_path):
        _seed(db_path)
        conn = connect_test_db(db_path)
        try:
            conn.execute(
                "INSERT INTO harness_sessions VALUES ('holder-2',NULL,NULL,NULL,NULL)"
            )
            conn.execute(
                "INSERT INTO work_claims VALUES (3,%s,'steering',%s,NULL,%s,NULL,NULL)",
                (
                    "holder-2",
                    make_steering_target(3).scope_json(),
                    "2026-08-26T11:00:02Z",
                ),
            )
            conn.commit()
        finally:
            conn.close()
        prefetch_session_occupancy(db, "all")
        keycaps = session_holding_labels(db, "holder-2")

    assert keycaps == ["🛞 steering platform"]


def test_board_renderer_omits_the_steering_section() -> None:
    source = Path(render_board_from_payload.__code__.co_filename).read_text()
    assert "render_steering_section" not in source
    assert "sections_steering" not in source
