"""Tests for the BOARD.md session holdings projection."""

from __future__ import annotations

from pathlib import Path

import pytest

from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)
from yoke_contracts.board.sections_sessions_holdings import session_holding_labels
from yoke_contracts.board.sections_sessions_occupancy import (
    prefetch_session_occupancy,
)
from yoke_contracts.board.sections_sessions_rendering import _render_claim_target
from yoke_core.board.db import BoardDB
from yoke_core.domain.work_claim_targets import (
    make_item_target,
    make_qa_admission_target,
    make_steering_target,
)


def test_render_claim_target_with_int_item_id() -> None:
    assert _render_claim_target(1577, None, None) == "YOK-1577"


def test_render_claim_target_with_prefixed_item_ref() -> None:
    assert _render_claim_target("YOK-1577", None, None) == "YOK-1577"


def test_render_claim_target_with_numeric_string_adds_prefix() -> None:
    assert _render_claim_target("1577", None, None) == "YOK-1577"


def test_render_claim_target_with_epic_task() -> None:
    assert _render_claim_target(None, 1577, 4) == "YOK-1577 T004"


def test_render_claim_target_without_coordinates_is_unknown() -> None:
    assert _render_claim_target(None, None, None) == "?"


_SCHEMA = """
CREATE TABLE projects (
    id INTEGER PRIMARY KEY,
    slug TEXT,
    public_item_prefix TEXT
);
CREATE TABLE items (
    id INTEGER PRIMARY KEY,
    project_id INTEGER,
    project_sequence INTEGER,
    workflow_id TEXT,
    status TEXT
);
CREATE TABLE work_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    target_kind TEXT NOT NULL,
    scope TEXT NOT NULL,
    claim_type TEXT,
    claimed_at TEXT,
    released_at TEXT,
    release_reason TEXT
);
CREATE TABLE path_claims (
    id INTEGER PRIMARY KEY,
    owner_kind TEXT,
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT
);
CREATE TABLE path_claim_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER
);
CREATE TABLE strategy_doc_claims (
    project_id INTEGER,
    strategy_doc_slug TEXT,
    owner_kind TEXT,
    owner_session_id TEXT,
    registered_at TEXT,
    released_at TEXT
);
"""


@pytest.fixture
def board_db(tmp_path: Path):
    with init_test_db(
        tmp_path,
        apply_schema=lambda: apply_inline_ddl(_SCHEMA),
    ) as db_path:
        raw = connect_test_db(db_path)
        try:
            raw.execute("INSERT INTO projects VALUES (1,'yoke','YOK')")
            raw.execute("INSERT INTO projects VALUES (2,'platform','PLAT')")
            for item_id in range(1, 20):
                raw.execute(
                    "INSERT INTO items VALUES (%s,1,%s,'dash','done')",
                    (item_id, item_id),
                )
            raw.commit()
        finally:
            raw.close()
        db = BoardDB(db_path)
        db.path = db_path
        yield db


def _insert_item_claim(
    db: BoardDB,
    claim_id: int,
    item_id: int,
    *,
    released_at: str | None = None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at,released_at) "
            "VALUES (%s,'sess-A','item',%s,%s,%s)",
            (
                claim_id,
                make_item_target(item_id).scope_json(),
                f"2026-08-28T12:{claim_id:02d}:00Z",
                released_at,
            ),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_lease(
    db: BoardDB,
    claim_id: int,
    key: str,
    *,
    released_at: str | None = None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at,released_at) "
            "VALUES (%s,'sess-A','qa_admission',%s,%s,%s)",
            (
                claim_id,
                make_qa_admission_target(key).scope_json(),
                f"2026-08-28T13:{claim_id:02d}:00Z",
                released_at,
            ),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_steering_claim(
    db: BoardDB,
    claim_id: int,
    project_id: int,
    *,
    claimed_at: str = "2026-08-28T12:00:00Z",
    released_at: str | None = None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at,released_at) "
            "VALUES (%s,'sess-A','steering',%s,%s,%s)",
            (
                claim_id,
                make_steering_target(project_id).scope_json(),
                claimed_at,
                released_at,
            ),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_document_lock(
    db: BoardDB,
    project_id: int,
    slug: str,
    *,
    registered_at: str = "2026-08-28T11:55:00Z",
    released_at: str | None = None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO strategy_doc_claims VALUES (%s,%s,'session','sess-A',%s,%s)",
            (project_id, slug, registered_at, released_at),
        )
        raw.commit()
    finally:
        raw.close()


def _steering_labels(db: BoardDB) -> list[str]:
    prefetch_session_occupancy(db, "all")
    return session_holding_labels(db, "sess-A")


def test_current_holding_omits_the_items_present_status(board_db: BoardDB) -> None:
    _insert_item_claim(board_db, 1, 7)
    assert session_holding_labels(board_db, "sess-A") == ["YOK-7"]


def test_current_target_removes_its_released_occurrences(board_db: BoardDB) -> None:
    _insert_item_claim(board_db, 1, 7, released_at="2026-08-28T12:30:00Z")
    _insert_item_claim(board_db, 2, 7)
    assert session_holding_labels(board_db, "sess-A") == ["YOK-7"]


def test_previous_target_renders_once_after_repeat_claims(board_db: BoardDB) -> None:
    _insert_item_claim(board_db, 1, 7, released_at="2026-08-28T12:30:00Z")
    _insert_item_claim(board_db, 2, 7, released_at="2026-08-28T12:40:00Z")
    assert session_holding_labels(board_db, "sess-A") == ["YOK-7"]


def test_current_holdings_sort_before_previous(board_db: BoardDB) -> None:
    _insert_item_claim(board_db, 1, 7, released_at="2026-08-28T12:30:00Z")
    _insert_item_claim(board_db, 2, 8)
    assert session_holding_labels(board_db, "sess-A") == ["YOK-8", "YOK-7"]


def test_released_coordination_target_is_previous_history(board_db: BoardDB) -> None:
    _insert_lease(board_db, 1, "test-mac", released_at="2026-08-28T12:30:00Z")
    assert session_holding_labels(board_db, "sess-A") == ["🔒 QA_HOST:test-mac"]


def test_previous_budget_appends_remainder_affordance(board_db: BoardDB) -> None:
    for claim_id in range(1, 6):
        _insert_item_claim(
            board_db,
            claim_id,
            claim_id,
            released_at=f"2026-08-28T14:{claim_id:02d}:00Z",
        )
    assert session_holding_labels(board_db, "sess-A", previous_limit=2) == [
        "YOK-5",
        "YOK-4",
        "and 3 more",
    ]


def test_steering_seat_folds_its_document_lock(board_db: BoardDB) -> None:
    _insert_steering_claim(board_db, 20, 1)
    _insert_document_lock(board_db, 1, "CURRENT-PLAN")
    assert _steering_labels(board_db) == ["🛞 steering yoke · CURRENT-PLAN"]


def test_document_lock_without_a_steering_seat_keeps_its_row(
    board_db: BoardDB,
) -> None:
    _insert_document_lock(board_db, 1, "MISSION")
    assert _steering_labels(board_db) == ["🛞 yoke · MISSION"]


def test_same_named_documents_stay_distinct_across_steered_projects(
    board_db: BoardDB,
) -> None:
    _insert_steering_claim(board_db, 20, 1, claimed_at="2026-08-28T12:00:00Z")
    _insert_steering_claim(board_db, 21, 2, claimed_at="2026-08-28T12:01:00Z")
    _insert_document_lock(board_db, 1, "CURRENT-PLAN")
    _insert_document_lock(board_db, 2, "CURRENT-PLAN")
    assert _steering_labels(board_db) == [
        "🛞 steering platform · CURRENT-PLAN",
        "🛞 steering yoke · CURRENT-PLAN",
    ]


def test_released_seat_folds_overlapping_lock_for_recent_rows(
    board_db: BoardDB,
) -> None:
    _insert_steering_claim(
        board_db,
        20,
        1,
        released_at="2026-08-28T12:30:00Z",
    )
    _insert_document_lock(
        board_db,
        1,
        "CURRENT-PLAN",
        released_at="2026-08-28T12:20:00Z",
    )
    assert _steering_labels(board_db) == ["🛞 steering yoke · CURRENT-PLAN"]
