"""Render parity: direct-DB assembly vs the record/replay data path.

The board data layer's core guarantee: a render fed by a recorded
``board.data.get`` payload (after a JSON transport round-trip) is
byte-identical to the same assembly running directly against the live
DB with the same inputs. A divergence is a parity bug — the replay
handle raises :class:`BoardDataMissError` rather than guessing.
"""

from __future__ import annotations

import json
import textwrap

import pytest

from yoke_contracts.board.config import parse_config
from yoke_contracts.board.art import ArtConfig, parse_art_config
from yoke_contracts.board.renderer import render_board_from_payload
from yoke_core.board.data import (
    BoardDataMissError,
    ReplayBoardDB,
    collect_board_data,
    entry_key,
)
from yoke_core.board.db import BoardDB
from yoke_core.board.renderer import _assemble
from runtime.api.fixtures.file_test_db import connect_test_db


def _direct_render(
    db_path, scope, config_path, *, seed, repo_root=None, vision_entries=(),
):
    """The pre-data-layer render shape: one live BoardDB, one assembly."""
    config = parse_config(config_path, repo_root=repo_root)
    art_config = parse_art_config(config_path, repo_root=repo_root)
    with BoardDB(db_path) as db:
        return _assemble(
            db, config, art_config, scope, seed, repo_root,
            list(vision_entries),
        )


def _data_fed_render(
    db_path, scope, config_path, *, seed, repo_root=None, vision_entries=(),
):
    """Collect → JSON round-trip → replay render, same inputs."""
    config = parse_config(config_path, repo_root=repo_root)
    art_config = parse_art_config(config_path, repo_root=repo_root)
    with BoardDB(db_path) as db:
        payload = collect_board_data(
            db,
            scope=scope,
            config=config,
            repo_root=repo_root,
            vision_entries=vision_entries,
        )
    # Prove transport fidelity: everything survives a JSON round trip.
    payload = json.loads(json.dumps(payload))
    replay = ReplayBoardDB.from_payload(payload)
    return _assemble(
        replay, config, art_config, scope, seed, repo_root,
        list(vision_entries),
    )


def test_parity_populated_board(populated_db, config_file):
    direct = _direct_render(populated_db, "yoke", config_file, seed=42)
    fed = _data_fed_render(populated_db, "yoke", config_file, seed=42)
    assert fed == direct
    assert "First item" in fed


def test_parity_empty_board(test_db_path, config_file):
    direct = _direct_render(test_db_path, "yoke", config_file, seed=7)
    fed = _data_fed_render(test_db_path, "yoke", config_file, seed=7)
    assert fed == direct


def test_payload_uses_stamped_session_project_identity(populated_db, config_file):
    conn = connect_test_db(populated_db)
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS harness_sessions (
                session_id TEXT PRIMARY KEY,
                executor TEXT NOT NULL,
                executor_display_name TEXT DEFAULT NULL,
                provider TEXT,
                model TEXT,
                execution_lane TEXT DEFAULT 'primary',
                mode TEXT DEFAULT 'wait',
                workspace TEXT DEFAULT '',
                project_id INTEGER NOT NULL REFERENCES projects(id),
                offered_at TEXT NOT NULL,
                last_heartbeat TEXT,
                ended_at TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS work_claims (
                id INTEGER PRIMARY KEY,
                session_id TEXT,
                item_id INTEGER,
                epic_id INTEGER,
                task_num INTEGER,
                claim_type TEXT,
                claimed_at TEXT,
                released_at TEXT,
                release_reason TEXT,
                target_kind TEXT,
                process_key TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS path_claims (
                id INTEGER PRIMARY KEY,
                session_id TEXT,
                item_id INTEGER,
                work_claim_id INTEGER,
                released_at TEXT,
                cancelled_at TEXT,
                release_reason TEXT,
                cancel_reason TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS path_claim_targets (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                claim_id INTEGER
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS coordination_leases (
                id INTEGER PRIMARY KEY,
                project_id INTEGER,
                lease_key TEXT,
                session_id TEXT,
                released_at TEXT,
                release_reason TEXT
            )
        """)
        conn.execute("""
            INSERT INTO harness_sessions
                (session_id, executor, executor_display_name, provider, model,
                 execution_lane, mode, workspace, project_id, offered_at,
                 last_heartbeat)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            "mac-yoke",
            "claude-code",
            "claude-desktop",
            "anthropic",
            "claude-opus",
            "primary",
            "wait",
            "/Users/testy/code/yoke",
            1,
            "2026-06-30T12:00:00Z",
            "2026-06-30T12:01:00Z",
        ))
        conn.commit()
    finally:
        conn.close()

    repo_root = "/Users/testy/code/yoke"
    config = parse_config(config_file, repo_root=repo_root)
    art_config = parse_art_config(config_file, repo_root=repo_root)
    with BoardDB(populated_db) as db:
        payload = collect_board_data(
            db,
            scope="yoke",
            config=config,
            repo_root=repo_root,
        )

    assert "session_workspace_aliases" not in payload
    rendered = render_board_from_payload(
        json.loads(json.dumps(payload)),
        scope="yoke",
        config=config,
        art_config=art_config,
        repo_root=repo_root,
    )
    assert "mac-yoke" in rendered
    assert "yoke" in rendered


def test_parity_all_scope_with_zen_and_vision(populated_db, tmp_path):
    """Zen visible + vision entries: the vision-derived zone width feeds a
    SQL parameter, so record and replay must agree through the injected
    entries, not a cwd walk."""
    cfg = tmp_path / "config"
    cfg.write_text(textwrap.dedent("""\
        dashboard_velocity=true
        dashboard_weather=true
        dashboard_velocity_meter=true
        timeline_widget=always
    """))
    vision = [("1mo", "autonomous"), ("6mo", "fleet")]
    direct = _direct_render(
        populated_db, "all", str(cfg), seed=3, vision_entries=vision,
    )
    fed = _data_fed_render(
        populated_db, "all", str(cfg), seed=3, vision_entries=vision,
    )
    assert fed == direct


def test_replay_miss_raises_loudly(populated_db, config_file):
    config = parse_config(config_file)
    with BoardDB(populated_db) as db:
        payload = collect_board_data(db, scope="yoke", config=config)
    replay = ReplayBoardDB.from_payload(json.loads(json.dumps(payload)))
    with pytest.raises(BoardDataMissError, match="parity bug"):
        replay.query("SELECT 1 FROM items WHERE id = %s", (424242,))


def test_payload_versions_must_match(populated_db, config_file):
    from yoke_core.board.data import BoardDataError

    config = parse_config(config_file)
    with BoardDB(populated_db) as db:
        payload = collect_board_data(db, scope="yoke", config=config)
    payload["version"] = 999
    with pytest.raises(BoardDataError, match="version"):
        ReplayBoardDB.from_payload(payload)


def test_entry_key_stable_across_json_round_trip():
    live = entry_key("query", "SELECT 1", (5, "x"))
    round_tripped = entry_key(
        "query", "SELECT 1", tuple(json.loads(json.dumps([5, "x"])))
    )
    assert live == round_tripped


def test_collection_uses_empty_art_config(populated_db, config_file):
    """Art shapes only the discarded text; the recorded plan must not
    depend on it. Rendering the same payload under two different art
    configs replays cleanly both times."""
    config = parse_config(config_file)
    with BoardDB(populated_db) as db:
        payload = collect_board_data(db, scope="yoke", config=config)
    replay_a = ReplayBoardDB.from_payload(payload)
    replay_b = ReplayBoardDB.from_payload(payload)
    out_a = _assemble(replay_a, config, ArtConfig(), "yoke", 1, None, [])
    out_b = _assemble(replay_b, config, ArtConfig(), "yoke", 99, None, [])
    assert out_a  # both rendered without a miss
    assert out_b
