"""Item-linked file and coordination holdings on BOARD.md session rows."""

from __future__ import annotations

from pathlib import Path

import pytest

from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)
from yoke_contracts.board.sections_sessions_holdings import session_holding_labels
from yoke_core.board.db import BoardDB
from yoke_core.domain.work_claim_targets import (
    make_item_target,
    make_migration_serialization_target,
    make_process_target,
)


_SCHEMA = """
CREATE TABLE projects (
    id INTEGER PRIMARY KEY,
    slug TEXT,
    public_item_prefix TEXT
);
CREATE TABLE items (
    id INTEGER PRIMARY KEY,
    project_id INTEGER,
    project_sequence INTEGER
);
CREATE TABLE work_claims (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    target_kind TEXT NOT NULL,
    scope TEXT NOT NULL,
    claim_type TEXT,
    claimed_at TEXT,
    released_at TEXT,
    release_reason TEXT
);
CREATE TABLE path_claims (
    id INTEGER PRIMARY KEY,
    owner_kind TEXT,
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT
);
CREATE TABLE path_claim_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER
);
CREATE TABLE strategy_doc_claims (
    project_id INTEGER,
    strategy_doc_slug TEXT,
    owner_kind TEXT,
    owner_session_id TEXT,
    registered_at TEXT,
    released_at TEXT
);
"""


@pytest.fixture
def board_db(tmp_path: Path):
    with init_test_db(
        tmp_path,
        apply_schema=lambda: apply_inline_ddl(_SCHEMA),
    ) as db_path:
        raw = connect_test_db(db_path)
        try:
            raw.execute("INSERT INTO projects VALUES (1,'yoke','YOK')")
            raw.execute("INSERT INTO items VALUES (1665,1,1665)")
            raw.commit()
        finally:
            raw.close()
        db = BoardDB(db_path)
        db.path = db_path
        yield db


def _insert_work_claim(
    db: BoardDB,
    *,
    claim_id: int = 1,
    released_at: str | None = None,
) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at,released_at) "
            "VALUES (%s,'sess-A','item',%s,'2026-08-28T12:00:00Z',%s)",
            (claim_id, make_item_target(1665).scope_json(), released_at),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_path_claim(
    db: BoardDB,
    *,
    claim_id: int,
    declared_count: int,
    owner_kind: str = "item",
    owner_work_claim_id: int | None = None,
    released_at: str | None = None,
) -> None:
    owner_item_id = 1665 if owner_kind == "item" else None
    owner_session_id = "sess-A" if owner_kind == "session" else None
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            "INSERT INTO path_claims "
            "(id,owner_kind,owner_item_id,owner_session_id,owner_work_claim_id,"
            "released_at) VALUES (%s,%s,%s,%s,%s,%s)",
            (
                claim_id,
                owner_kind,
                owner_item_id,
                owner_session_id,
                owner_work_claim_id,
                released_at,
            ),
        )
        for _ in range(declared_count):
            raw.execute(
                "INSERT INTO path_claim_targets (claim_id) VALUES (%s)",
                (claim_id,),
            )
        raw.commit()
    finally:
        raw.close()


def test_item_owned_paths_merge_into_the_current_item_row(board_db: BoardDB) -> None:
    _insert_work_claim(board_db)
    _insert_path_claim(board_db, claim_id=10, declared_count=23)
    assert session_holding_labels(board_db, "sess-A") == ["YOK-1665 📁23"]


def test_released_paths_do_not_duplicate_a_current_item(board_db: BoardDB) -> None:
    _insert_work_claim(board_db)
    _insert_path_claim(
        board_db,
        claim_id=11,
        declared_count=4,
        released_at="2026-08-28T13:00:00Z",
    )
    assert session_holding_labels(board_db, "sess-A") == ["YOK-1665"]


def test_multiple_item_path_claims_roll_into_one_target(board_db: BoardDB) -> None:
    _insert_work_claim(board_db)
    _insert_path_claim(board_db, claim_id=14, declared_count=2)
    _insert_path_claim(board_db, claim_id=15, declared_count=3)
    assert session_holding_labels(board_db, "sess-A") == ["YOK-1665 📁5"]


def test_item_owned_files_stay_off_a_session_without_the_item(
    board_db: BoardDB,
) -> None:
    _insert_path_claim(board_db, claim_id=16, declared_count=2)
    assert session_holding_labels(board_db, "sess-A") == []


def test_previous_item_keeps_its_terminal_file_count(board_db: BoardDB) -> None:
    released = "2026-08-28T13:00:00Z"
    _insert_work_claim(board_db, released_at=released)
    _insert_path_claim(
        board_db,
        claim_id=12,
        declared_count=5,
        released_at=released,
    )
    assert session_holding_labels(board_db, "sess-A") == ["YOK-1665 📁5"]


def test_session_owned_files_render_as_their_own_target(board_db: BoardDB) -> None:
    _insert_path_claim(
        board_db,
        claim_id=13,
        declared_count=2,
        owner_kind="session",
    )
    assert session_holding_labels(board_db, "sess-A") == ["📁2"]


def test_process_owned_files_merge_into_the_process_target(board_db: BoardDB) -> None:
    raw = connect_test_db(board_db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at) "
            "VALUES (30,'sess-A','process',%s,'2026-08-28T12:00:00Z')",
            (make_process_target("FEED", "yoke").scope_json(),),
        )
        raw.commit()
    finally:
        raw.close()
    _insert_path_claim(
        board_db,
        claim_id=31,
        declared_count=3,
        owner_kind="process",
        owner_work_claim_id=30,
    )
    assert session_holding_labels(board_db, "sess-A") == ["🔩 FEED 📁3"]


def test_item_owned_coordination_names_the_held_item(board_db: BoardDB) -> None:
    _insert_work_claim(board_db, claim_id=40)
    raw = connect_test_db(board_db.path)
    try:
        raw.execute(
            "INSERT INTO work_claims "
            "(id,session_id,target_kind,scope,claimed_at) "
            "VALUES (41,'rehearse','migration_serialization',%s,%s)",
            (
                make_migration_serialization_target(1, "primary", 1665).scope_json(),
                "2026-08-28T13:00:00Z",
            ),
        )
        raw.commit()
    finally:
        raw.close()
    assert session_holding_labels(board_db, "sess-A") == [
        "YOK-1665",
        "🔒 LIVE_DB_MIGRATION:primary (YOK-1665)",
    ]
