"""Executor display rendering — surface alias preferred, canonical fallback.

Companion to ``test_sections_sessions.py``; split out so both files stay
under the 350-line authored cap.
"""

from __future__ import annotations

import contextlib
from pathlib import Path

from yoke_core.board.db import BoardDB
from runtime.api.fixtures.file_test_db import (
    apply_inline_ddl,
    connect_test_db,
    init_test_db,
)


_RENDER_SCHEMA = """
    CREATE TABLE projects (
        id INTEGER PRIMARY KEY,
        slug TEXT UNIQUE,
        name TEXT DEFAULT '',
        emoji TEXT DEFAULT '',
        public_item_prefix TEXT DEFAULT 'YOK'
    );
    CREATE TABLE harness_sessions (
        session_id TEXT PRIMARY KEY,
        executor TEXT NOT NULL,
        executor_display_name TEXT DEFAULT NULL,
        provider TEXT,
        model TEXT,
        execution_lane TEXT DEFAULT 'primary',
        mode TEXT DEFAULT 'wait',
        workspace TEXT DEFAULT '',
        project_id INTEGER NOT NULL REFERENCES projects(id),
        offered_at TEXT NOT NULL,
        last_heartbeat TEXT,
        ended_at TEXT
    );
    CREATE TABLE items (
        id INTEGER PRIMARY KEY,
        project_id INTEGER,
        project_sequence INTEGER
    );
    CREATE TABLE work_claims (
        id INTEGER PRIMARY KEY,
        session_id TEXT,
        item_id INTEGER,
        epic_id INTEGER,
        task_num INTEGER,
        claim_type TEXT,
        claimed_at TEXT,
        released_at TEXT,
        release_reason TEXT,
        target_kind TEXT,
        process_key TEXT
    );
    CREATE TABLE path_claims (
        id INTEGER PRIMARY KEY,
        session_id TEXT,
        item_id INTEGER,
        work_claim_id INTEGER,
        released_at TEXT,
        cancelled_at TEXT,
        release_reason TEXT,
        cancel_reason TEXT
    );
    CREATE TABLE path_claim_targets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        claim_id INTEGER
    );
    CREATE TABLE coordination_leases (
        id INTEGER PRIMARY KEY,
        project_id INTEGER,
        lease_key TEXT,
        session_id TEXT,
        released_at TEXT,
        release_reason TEXT
    );
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (1, 'yoke', 'Yoke', '🐂', 'YOK');
    INSERT INTO projects (id, slug, name, emoji, public_item_prefix)
    VALUES (2, 'externalwebapp', 'ExternalWebapp', '🧩', 'EXT');
"""


def _apply_render_schema() -> None:
    apply_inline_ddl(_RENDER_SCHEMA)


@contextlib.contextmanager
def _make_render_db(tmp_path: Path):
    """Yield a minimal BoardDB with the columns ``render_sessions_section`` reads.

    Context manager so the disposable per-test Postgres database
    :func:`init_test_db` provisions is dropped after the test body runs.
    """
    from yoke_contracts.board.sections_sessions import render_sessions_section

    with init_test_db(tmp_path, apply_schema=_apply_render_schema) as db_path:
        db = BoardDB(db_path)
        db.path = db_path
        yield db, render_sessions_section


def _insert_render_session(db, **kwargs) -> None:
    raw = connect_test_db(db.path)
    try:
        raw.execute(
            """INSERT INTO harness_sessions
               (session_id, executor, executor_display_name, provider, model,
                execution_lane, mode, workspace, project_id, offered_at, last_heartbeat,
                ended_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                kwargs["session_id"],
                kwargs["executor"],
                kwargs.get("executor_display_name"),
                kwargs.get("provider", "anthropic"),
                kwargs.get("model", "claude-opus-4-7[1m]"),
                kwargs.get("execution_lane", "primary"),
                kwargs.get("mode", "wait"),
                kwargs.get("workspace", ""),
                kwargs.get("project_id", 1),
                kwargs.get("offered_at", "2026-05-19T20:00:00Z"),
                kwargs.get("last_heartbeat", "2026-05-19T20:01:00Z"),
                kwargs.get("ended_at"),
            ),
        )
        raw.commit()
    finally:
        raw.close()


def _insert_render_item_claim(db, *, session_id: str, item_id: int, project: str) -> None:
    raw = connect_test_db(db.path)
    try:
        project_id = 2 if project == "externalwebapp" else 1
        raw.execute(
            "INSERT INTO items "
            "(id, project_id, project_sequence) "
            "VALUES (%s, %s, %s)",
            (item_id, project_id, item_id),
        )
        raw.execute(
            """INSERT INTO work_claims
               (id, session_id, item_id, claim_type, claimed_at, target_kind)
               VALUES (%s, %s, %s, %s, %s, %s)""",
            (item_id, session_id, item_id, "work", "2026-05-19T20:02:00Z", "item"),
        )
        raw.commit()
    finally:
        raw.close()


class TestExecutorDisplayRendering:
    """Board prefers ``executor_display_name`` and falls back to ``executor``."""

    def test_display_alias_preferred_when_present(self, tmp_path: Path) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="surface-claude",
                executor="claude-code", executor_display_name="claude-desktop",
            )
            section = render(db)
        assert "claude-desktop" in section
        # canonical id not shown standalone when the alias is present
        assert "claude-code" not in section

    def test_canonical_used_when_display_alias_absent(self, tmp_path: Path) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="coarse-codex",
                executor="codex", executor_display_name=None,
            )
            section = render(db)
        assert "codex" in section

    def test_closed_session_also_prefers_display_alias(self, tmp_path: Path) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="ended-codex",
                executor="codex", executor_display_name="codex-vscode",
                ended_at="2026-05-19T20:30:00Z",
            )
            section = render(db)
        assert "codex-vscode" in section

    def test_project_scope_filters_active_sessions(self, tmp_path: Path) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="externalwebappsess", executor="codex",
                executor_display_name="codex-vscode",
                project_id=2,
            )
            _insert_render_session(
                db, session_id="yokesess", executor="codex",
                executor_display_name="codex-desktop",
                project_id=1,
            )
            _insert_render_item_claim(
                db, session_id="externalwebappsess", item_id=10, project="externalwebapp",
            )
            _insert_render_item_claim(
                db, session_id="yokesess", item_id=11, project="yoke",
            )
            section = render(db, scope="externalwebapp")
        assert "externalwebappsess" in section
        assert "yokesess" not in section

    def test_project_scope_uses_session_project_id_before_workspace(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="externalwebappdir", executor="codex",
                executor_display_name="codex-desktop",
                workspace="/some/other/machine/externalwebapp",
                project_id=2,
            )
            _insert_render_session(
                db, session_id="yokedir", executor="codex",
                executor_display_name="codex-desktop",
                workspace="/tmp/externalwebapp",
                project_id=1,
            )
            section = render(db, scope="externalwebapp")
        assert "externalwebappdir" in section
        assert "yokedir" not in section

    def test_project_scope_uses_stamped_client_checkout_identity(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="mac-externalwebapp", executor="claude-code",
                executor_display_name="claude-desktop",
                workspace="/Users/testy/code/externalwebapp",
                project_id=2,
            )
            section = render(db, scope="externalwebapp")
        assert "mac-externalwebapp" in section
        assert "🧩 externalwebapp" in section

    def test_project_scope_excludes_other_project_even_when_workspace_matches_repo_path(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="mac-externalwebapp", executor="claude-code",
                executor_display_name="claude-desktop",
                workspace="/Users/testy/code/externalwebapp",
                project_id=1,
            )
            section = render(db, scope="externalwebapp")
        assert "mac-externalwebapp" not in section

    def test_active_session_renders_workspace_project_column(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="externalwebappdir", executor="codex",
                executor_display_name="codex-desktop",
                workspace="/tmp/externalwebapp/app",
                project_id=2,
            )
            section = render(db, scope="externalwebapp")
        assert "| Project" in section
        assert "| Executor" in section
        assert "🧩 externalwebapp" in section

    def test_closed_session_renders_workspace_project_column(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="yokedir", executor="claude-code",
                executor_display_name="claude-desktop",
                execution_lane="ALTMAN",
                workspace="/tmp/yoke",
                project_id=1,
                ended_at="2026-05-19T20:30:00Z",
            )
            section = render(db, scope="yoke")
        assert "Recent Harness Sessions" in section
        assert "Project" in section
        assert "Lane" in section
        assert "👓 ALTMAN" in section
        assert "🐂 yoke" in section

    def test_claim_scope_can_include_an_active_session_from_another_checkout(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="known-yoke", executor="codex",
                workspace="/tmp/yoke",
                project_id=1,
            )
            _insert_render_item_claim(
                db, session_id="known-yoke", item_id=12, project="externalwebapp",
            )
            section = render(db, scope="externalwebapp")
        assert "known-yoke" in section
        assert "🐂 yoke" in section

    def test_project_identity_does_not_fall_back_to_workspace_path(
        self, tmp_path: Path,
    ) -> None:
        with _make_render_db(tmp_path) as (db, render):
            _insert_render_session(
                db, session_id="externalwebapp-path-yoke-project", executor="codex",
                workspace="/tmp/externalwebapp",
                project_id=1,
            )
            section = render(db, scope="externalwebapp")
        assert "externalwebapp-path-yoke-project" not in section
