"""Canonical expected-schema declaration for HC-schema-drift.

Centralizes the table/column expectation that ``hc_schema_drift``
diffs against the live DB. Extracted from
``doctor_hc_db_project_schema`` to keep that module within the
authored-file budget (350-line hard limit) when the live schema
grows.

The declaration is kept as one compact ``"|"``-separated string so
the per-table sections stay legible in version control diffs. Each
section is ``<table>:<col>/<TYPE>,<col>/<TYPE>,...``. The parser is
a thin split routine; it intentionally has no schema-loading logic
(no PRAGMA, no DB connection) so it stays cheap to import and easy
to unit-test against a fixed string.
"""

from __future__ import annotations

from typing import Dict


_EXPECTED_SCHEMA_STR = (
    "items:id/INTEGER,title/TEXT,type/TEXT,status/TEXT,priority/TEXT,flow/TEXT,"
    "rework_count/INTEGER,frozen/INTEGER,github_issue/TEXT,deployed_to/TEXT,"
    "worktree/TEXT,merged_at/TEXT,created_at/TEXT,updated_at/TEXT,source/TEXT,"
    "project_id/INTEGER,project_sequence/INTEGER,deployment_flow/TEXT,deploy_stage/TEXT,spec/TEXT,design_spec/TEXT,"
    "technical_plan/TEXT,worktree_plan/TEXT,shepherd_log/TEXT,shepherd_caveats/TEXT,"
    "test_results/TEXT,deploy_log/TEXT,spec_updated_at/TEXT,spec_updated_by/TEXT,"
    "resolution/TEXT,resolution_ref/TEXT,resolution_comment/TEXT,"
    "browser_qa_metadata/TEXT,db_mutation_profile/TEXT,"
    "db_compatibility_attestation/TEXT,owner/TEXT,blocked/INTEGER,"
    "blocked_reason/TEXT,architecture_impact/TEXT,"
    "github_body_compact_pending/TEXT"
    "|shepherd_verdicts:id/INTEGER,item/TEXT,transition/TEXT,worker/TEXT,verdict/TEXT,"
    "caveats/TEXT,attempt/INTEGER,created_at/TEXT"
    "|deployment_flows:id/TEXT,project_id/INTEGER,name/TEXT,description/TEXT,stages/TEXT,"
    "on_failure/TEXT,created_at/TEXT,target_env/TEXT,done_description/TEXT"
    "|caveat_dispositions:id/INTEGER,item/TEXT,transition/TEXT,attempt/INTEGER,"
    "caveat_num/INTEGER,caveat_text/TEXT,disposition/TEXT,resolution_details/TEXT,"
    "verdict_id/INTEGER,created_at/TEXT"
    "|item_dependencies:id/INTEGER,dependent_item/TEXT,blocking_item/TEXT,"
    "gate_point/TEXT,satisfaction/TEXT,source/TEXT,session_id/INTEGER,rationale/TEXT,"
    "evidence_json/TEXT,created_at/TEXT"
    "|ouroboros_entries:id/INTEGER,timestamp/TEXT,agent/TEXT,context/TEXT,category/TEXT,"
    "body/TEXT,reviewed_at/TEXT,archived_at/TEXT,created_at/TEXT,project_id/INTEGER"
    "|wrapup_reports:id/INTEGER,session_timestamp/TEXT,body/TEXT,created_at/TEXT"
    "|epic_tasks:id/INTEGER,epic_id/INTEGER,task_num/INTEGER,title/TEXT,worktree/TEXT,"
    "context_estimate/TEXT,dependencies/TEXT,status/TEXT,dispatch_attempts/INTEGER,"
    "body/TEXT,github_issue/TEXT,branch/TEXT,worktree_path/TEXT,blocked_by/TEXT,"
    "max_attempts/INTEGER,agent_id/TEXT,last_heartbeat/TEXT,last_activity_at/TEXT"
    "|epic_task_files:id/INTEGER,epic_id/INTEGER,task_num/INTEGER,file_path/TEXT,action/TEXT"
    "|epic_dispatch_chains:id/INTEGER,epic_id/INTEGER,worktree/TEXT,worktree_path/TEXT,"
    "queue/TEXT,current_index/INTEGER,current_task/TEXT,current_attempt/INTEGER,"
    "max_attempts/INTEGER,no_chain/INTEGER,started_at/TEXT,last_updated/TEXT"
    "|epic_progress_notes:id/INTEGER,epic_id/INTEGER,task_num/INTEGER,note_num/INTEGER,"
    "body/TEXT,commit_hash/TEXT,synced_to_github/INTEGER,created_at/TEXT"
    "|qa_requirements:id/INTEGER,item_id/INTEGER,epic_id/INTEGER,task_num/INTEGER,"
    "deployment_run_id/TEXT,qa_kind/TEXT,qa_phase/TEXT,target_env/TEXT,blocking_mode/TEXT,"
    "requirement_source/TEXT,success_policy/TEXT,capability_requirements/TEXT,"
    "suite_id/TEXT,waived_at/TEXT,waiver_rationale/TEXT,waiver_source/TEXT,created_at/TEXT"
    "|qa_runs:id/INTEGER,qa_requirement_id/INTEGER,executor_type/TEXT,qa_kind/TEXT,"
    "verdict/TEXT,score/REAL,confidence/REAL,raw_result/TEXT,duration_ms/INTEGER,"
    "started_at/TEXT,completed_at/TEXT,created_at/TEXT,execution_status/TEXT"
    "|qa_artifacts:id/INTEGER,qa_run_id/INTEGER,artifact_type/TEXT,content_type/TEXT,"
    "artifact_handle/TEXT,metadata/TEXT,created_at/TEXT"
    "|release_entries:id/INTEGER,item_id/INTEGER,category/TEXT,title/TEXT,version/TEXT,"
    "project_id/INTEGER,created_at/TEXT"
    "|merge_locks:id/INTEGER,session_id/TEXT,branch/TEXT,epic_id/TEXT,acquired_at/TEXT,"
    "expires_at/TEXT"
    "|designs:id/INTEGER,item_id/INTEGER,slug/TEXT,body/TEXT,created_at/TEXT,updated_at/TEXT"
    "|projects:id/INTEGER,slug/TEXT,name/TEXT,emoji/TEXT,default_branch/TEXT,"
    "github_repo/TEXT,public_item_prefix/TEXT,created_at/TEXT,breakage_policy/TEXT,"
    "org_id/INTEGER,github_sync_mode/TEXT"
    "|sites:id/TEXT,project_id/INTEGER,name/TEXT,description/TEXT,created_at/TEXT,settings/TEXT"
    "|environments:id/TEXT,site/TEXT,name/TEXT,url/TEXT,deploy_method/TEXT,"
    "deploy_command/TEXT,health_check_url/TEXT,config_notes/TEXT,last_deployed_at/TEXT,"
    "created_at/TEXT"
    "|project_capabilities:id/INTEGER,project_id/INTEGER,type/TEXT,verified_at/TEXT,"
    "created_at/TEXT,settings/TEXT"
    "|project_onboarding_runs:run_id/TEXT,schema_version/INTEGER,project_id/INTEGER,"
    "branch/TEXT,checkout_path/TEXT,machine_config_path/TEXT,github_repo/TEXT,"
    "status/TEXT,metadata_json/TEXT,created_at/TEXT,updated_at/TEXT"
    "|project_onboarding_checklist_rows:run_id/TEXT,row_id/TEXT,step/TEXT,title/TEXT,"
    "layer/TEXT,owner/TEXT,status/TEXT,hint/TEXT,evidence_json/TEXT,blocker/TEXT,"
    "note/TEXT,updated_at/TEXT"
    "|capability_templates:id/TEXT,name/TEXT,description/TEXT,required_config/TEXT,"
    "requires/TEXT,created_at/TEXT"
    "|capability_secrets:id/INTEGER,project_id/INTEGER,type/TEXT,key/TEXT,value/TEXT,"
    "source/TEXT,created_at/TEXT"
    "|ephemeral_environments:id/INTEGER,project_id/INTEGER,branch/TEXT,item/TEXT,"
    "workflow_run_id/TEXT,github_ref/TEXT,port_api/INTEGER,port_web/INTEGER,url/TEXT,"
    "status/TEXT,started_at/TEXT,stopped_at/TEXT,health_check_url/TEXT,"
    "created_at/TEXT,deployed_sha/TEXT"
    "|events:id/INTEGER,event_id/TEXT,source_type/TEXT,session_id/TEXT,severity/TEXT,"
    "event_kind/TEXT,event_type/TEXT,event_name/TEXT,event_outcome/TEXT,"
    "org_id/TEXT,actor_id/INTEGER,environment/TEXT,service/TEXT,project_id/INTEGER,item_id/TEXT,"
    "task_num/INTEGER,agent/TEXT,tool_name/TEXT,duration_ms/INTEGER,exit_code/INTEGER,"
    "trace_id/TEXT,parent_id/TEXT,anomaly_flags/TEXT,tool_use_id/TEXT,turn_id/TEXT,"
    "hook_event_name/TEXT,envelope/TEXT,created_at/TEXT"
    "|event_registry:event_name/TEXT,event_kind/TEXT,event_type/TEXT,owner_service/TEXT,"
    "description/TEXT,context_schema/TEXT,severity_default/TEXT,added_in/TEXT,status/TEXT"
    "|severity_config:id/INTEGER,event_name/TEXT,source_type/TEXT,min_severity/TEXT,"
    "created_at/TEXT"
    "|item_sections:item_id/INTEGER,section_name/TEXT,content/TEXT,ordering/INTEGER,"
    "created_at/TEXT,updated_at/TEXT,source/TEXT"
    "|deployment_runs:id/TEXT,project_id/INTEGER,flow/TEXT,target_env/TEXT,release_lineage/TEXT,"
    "status/TEXT,current_stage/TEXT,created_at/TEXT,started_at/TEXT,completed_at/TEXT,"
    "created_by/TEXT"
    "|deployment_run_items:run_id/TEXT,item_id/INTEGER,added_at/TEXT"
    "|deployment_run_qa:id/INTEGER,run_id/TEXT,check_name/TEXT,source/TEXT,"
    "blocking/INTEGER,status/TEXT,updated_at/TEXT"
    "|deployment_preview_environments:id/INTEGER,project_id/INTEGER,env_name/TEXT,run_id/TEXT,"
    "status/TEXT,url/TEXT,created_at/TEXT,env_type/TEXT"
    "|harness_sessions:session_id/TEXT,executor/TEXT,provider/TEXT,model/TEXT,"
    "execution_lane/TEXT,capabilities/TEXT,workspace/TEXT,mode/TEXT,offered_at/TEXT,"
    "last_heartbeat/TEXT,ended_at/TEXT,offer_envelope/TEXT,current_item_id/TEXT,"
    "current_item_set_at/TEXT,recent_item_id/TEXT,recent_item_status/TEXT,"
    "recent_item_recorded_at/TEXT,actor_id/INTEGER,last_seen_main_sha/TEXT,"
    "last_drift_check_at/TEXT,last_tool_call_at/TEXT,tool_call_count/INTEGER,"
    "episode_started_at/TEXT,pending_resume_notice/TEXT,last_chain_step/INTEGER,"
    "last_checkpoint_at/TEXT"
    "|session_tool_calls:id/INTEGER,session_id/TEXT,tool_use_id/TEXT,"
    "tool_name/TEXT,started_at/TEXT,completed_at/TEXT,outcome/TEXT,"
    "command_summary/TEXT"
    "|work_claims:id/INTEGER,session_id/TEXT,target_kind/TEXT,item_id/INTEGER,"
    "epic_id/INTEGER,task_num/INTEGER,process_key/TEXT,conflict_group/TEXT,"
    "claim_type/TEXT,claimed_at/TEXT,last_heartbeat/TEXT,released_at/TEXT,"
    "release_reason/TEXT,reason/TEXT,reason_intent/TEXT,release_reason_intent/TEXT"
    "|actors:id/INTEGER,kind/TEXT,system_component/TEXT,created_at/TEXT"
    "|actor_labels:id/INTEGER,actor_id/INTEGER,surface/TEXT,label/TEXT,created_at/TEXT"
    "|api_tokens:id/INTEGER,token_hash/TEXT,actor_id/INTEGER,name/TEXT,status/TEXT,"
    "created_at/TEXT,revoked_at/TEXT,expires_at/TEXT,last_used_at/TEXT,"
    "diagnostic_metadata/TEXT"
    "|api_token_audit:id/INTEGER,api_token_id/INTEGER,actor_id/INTEGER,"
    "project_id/INTEGER,event_type/TEXT,outcome/TEXT,permission_key/TEXT,"
    "diagnostic_metadata/TEXT,created_at/TEXT"
    "|roles:id/INTEGER,name/TEXT,description/TEXT,created_at/TEXT"
    "|permissions:id/INTEGER,key/TEXT,description/TEXT,created_at/TEXT"
    "|role_permissions:role_id/INTEGER,permission_id/INTEGER,created_at/TEXT"
    "|actor_project_roles:actor_id/INTEGER,project_id/INTEGER,role_id/INTEGER,"
    "granted_at/TEXT,granted_by_actor_id/INTEGER"
    "|organizations:id/INTEGER,slug/TEXT,name/TEXT,created_at/TEXT"
    "|actor_org_roles:actor_id/INTEGER,org_id/INTEGER,role_id/INTEGER,"
    "granted_at/TEXT,granted_by_actor_id/INTEGER"
    "|coordination_leases:id/INTEGER,project_id/TEXT,lease_key/TEXT,session_id/TEXT,"
    "acquired_at/TEXT,released_at/TEXT,release_reason/TEXT,actor_id/TEXT,"
    "heartbeat_at/TEXT"
    "|migration_audit:id/INTEGER,migration_name/TEXT,description/TEXT,"
    "tables_declared/TEXT,expected_deltas/TEXT,pre_row_counts/TEXT,post_row_counts/TEXT,"
    "pre_fk_violations/INTEGER,post_fk_violations/INTEGER,backup_path/TEXT,state/TEXT,"
    "failure_reason/TEXT,exception_reason/TEXT,source_fingerprint/TEXT,"
    "rehearsed_at/TEXT,lease_id/INTEGER,test_copy_path/TEXT,"
    "baseline_verify_result/TEXT,author_verify_result/TEXT,session_id/TEXT,"
    "model_name/TEXT,project_id/TEXT,started_at/TEXT,completed_at/TEXT,"
    "duration_ms/INTEGER,actor_id/TEXT,worktree/TEXT,source_branch/TEXT,"
    "source_commit/TEXT,integration_target/TEXT,change_class/TEXT"
    "|path_targets:id/INTEGER,project_id/TEXT,kind/TEXT,path_string/TEXT,"
    "generation/INTEGER,parent_target_id/INTEGER,created_at/TEXT,"
    "materialization_state/TEXT,materialization_updated_at/TEXT,"
    "planned_by_item_id/INTEGER,planned_by_claim_id/INTEGER"
    "|path_claims:id/INTEGER,state/TEXT,mode/TEXT,actor_id/INTEGER,session_id/TEXT,"
    "item_id/INTEGER,integration_target/TEXT,base_commit_sha/TEXT,"
    "registered_at/TEXT,activated_at/TEXT,released_at/TEXT,cancelled_at/TEXT,"
    "release_reason/TEXT,cancel_reason/TEXT,blocked_reason/TEXT,exception_reason/TEXT,"
    "work_claim_id/INTEGER,owner_kind/TEXT,owner_item_id/INTEGER,"
    "owner_session_id/TEXT,owner_work_claim_id/INTEGER,"
    "registered_by_actor_id/INTEGER,registered_by_session_id/TEXT"
    "|path_claim_targets:id/INTEGER,claim_id/INTEGER,target_id/INTEGER,declared_at/TEXT"
    "|path_claim_amendments:id/INTEGER,claim_id/INTEGER,amended_at/TEXT,"
    "amendment_kind/TEXT,payload/TEXT,reason/TEXT"
    "|path_claim_overrides:id/INTEGER,path_claim_id/INTEGER,blocking_claim_id/INTEGER,"
    "blocking_path_targets/TEXT,override_point/TEXT,conflict_reason/TEXT,"
    "integration_target/TEXT,actor_id/INTEGER,actor_reason/TEXT,item_id/INTEGER,"
    "project/TEXT,session_id/TEXT,created_at/TEXT"
    "|path_snapshots:id/INTEGER,project_id/TEXT,commit_sha/TEXT,built_at/TEXT"
    "|path_snapshot_entries:snapshot_id/INTEGER,target_id/INTEGER,line_count/INTEGER,"
    "language/TEXT,module_name/TEXT,area/TEXT,is_generated/INTEGER,dependency_edges/TEXT"
    "|path_context_values:id/INTEGER,target_id/INTEGER,context_family/TEXT,"
    "entry_key/TEXT,value/TEXT,recorded_event_id/TEXT,recorded_at/TEXT"
    "|path_moves:id/INTEGER,before_target_id/INTEGER,after_target_id/INTEGER,"
    "recorded_event_id/TEXT,recorded_at/TEXT"
    "|path_integrity_runs:id/INTEGER,project_id/TEXT,commit_sha/TEXT,status/TEXT,"
    "started_at/TEXT,completed_at/TEXT,skip_reason/TEXT,block_reason/TEXT,"
    "abort_reason/TEXT,failure_count/INTEGER,unrepaired_failure_count/INTEGER,"
    "verifier_version/TEXT"
    "|path_integrity_failures:id/INTEGER,run_id/INTEGER,invariant_kind/TEXT,"
    "target_id/INTEGER,details/TEXT,repair_status/TEXT,recorded_at/TEXT"
    "|path_integrity_repairs:id/INTEGER,failure_id/INTEGER,operation/TEXT,status/TEXT,"
    "requested_at/TEXT,applied_at/TEXT,error_text/TEXT,arguments/TEXT,"
    "recorded_event_id/TEXT,abandon_reason/TEXT"
    "|path_integrity_fixtures:id/INTEGER,name/TEXT,description/TEXT,seeded_at/TEXT,"
    "project_id/TEXT,expected_invariant_kind/TEXT"
    "|project_structure:id/INTEGER,project_id/TEXT,family/TEXT,attachment_value/TEXT,"
    "attachment_kind/TEXT,entry_key/TEXT,payload/TEXT,created_at/TEXT,updated_at/TEXT"
    "|strategize_landed_carry:item_id/INTEGER,project_id/INTEGER,state/TEXT,"
    "first_seen_at/TEXT,last_updated_at/TEXT,last_session_id/TEXT,reason/TEXT"
    "|item_status_transitions:id/INTEGER,item_id/INTEGER,task_num/INTEGER,"
    "from_status/TEXT,to_status/TEXT,source/TEXT,session_id/TEXT,"
    "actor_id/INTEGER,project_id/INTEGER,created_at/TEXT"
    "|item_activity_days:id/INTEGER,project_id/INTEGER,item_id/INTEGER,day/TEXT"
    "|strategy_checkpoints:id/INTEGER,project_id/INTEGER,kind/TEXT,created_at/TEXT"
    "|strategy_docs:id/INTEGER,slug/TEXT,content/TEXT,updated_at/TEXT,"
    "updated_by_actor_id/INTEGER"
    "|function_call_ledger:request_id/TEXT,function_id/TEXT,actor_id/TEXT,"
    "authorization_scope/TEXT,payload_checksum/TEXT,result/TEXT,created_at/TEXT"
    "|github_workflow_dispatch_intents:request_id/TEXT,attempt/INTEGER,"
    "actor_id/TEXT,authorization_scope/TEXT,payload_checksum/TEXT,repo/TEXT,"
    "workflow/TEXT,workflow_ref/TEXT,inputs/TEXT,correlation_id/TEXT,state/TEXT,"
    "workflow_run_id/TEXT,run_url/TEXT,html_url/TEXT,created_at/TEXT,updated_at/TEXT"
)


def parse_expected_schema() -> Dict[str, Dict[str, str]]:
    """Return ``{table: {column: type}}`` from the declared string.

    Pure parsing — no DB connection, no PRAGMA. The caller compares
    the result against the live schema and reports drift.
    """
    expected: Dict[str, Dict[str, str]] = {}
    for tbl_spec in _EXPECTED_SCHEMA_STR.split("|"):
        tbl_spec = tbl_spec.strip()
        if not tbl_spec or ":" not in tbl_spec:
            continue
        tbl_name, cols_str = tbl_spec.split(":", 1)
        expected[tbl_name] = {}
        for col_spec in cols_str.split(","):
            if "/" in col_spec:
                cname, ctype = col_spec.split("/", 1)
                expected[tbl_name][cname] = ctype
    return expected
