"""Client-side strategy render payload and local-edit apply."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from yoke_contracts.project_contract.strategy_docs_io import (
    LocalRenderFile,
    inspect_local_renders,
    local_render_known,
    relocate_generated_archive,
    write_rendered_files,
)

LOCAL_EDIT_CONFLICT_TEACHING = (
    "has local edits and the remote document changed. Write the edits "
    "back with `yoke strategy ingest {slug}` or move the file aside and "
    "re-render."
)

FetchDocs = Callable[[Sequence[str]], Iterable[Mapping[str, Any]]]


def build_render_payload(
    target_root: Path | str,
    *,
    slugs: Optional[Sequence[str]] = None,
    include_archives: bool = False,
) -> Dict[str, Any]:
    """Build ``strategy.render.run`` payload from the local rendered view.

    Empty slugs select the server's active corpus. ``known`` carries
    header identity from files that still parse, including locally
    edited bodies, so an unchanged remote omits ``file_text``.
    """
    payload: Dict[str, Any] = {}
    if slugs:
        payload["slugs"] = [str(slug) for slug in slugs]
    if include_archives:
        payload["include_archives"] = True
    known = local_render_known(Path(target_root))
    if known:
        payload["known"] = known
    return payload


def apply_rendered_docs(
    target_root: Path | str,
    docs: Iterable[Mapping[str, Any]],
) -> Tuple[Dict[str, str], List[str]]:
    """Write returned file texts, preserving dirty local edits.

    Returns ``(report, conflict_slugs)``. A conflict is a dirty local
    file whose remote row also changed (the response still carries
    ``file_text``). Unchanged remotes omit the body, so a dirty file
    stays on disk and reports ``local-edit``. A known-active→archived
    reply without ``file_text`` moves or removes only generated bytes.
    An ``unchanged`` reply whose local file vanished or drifted reports
    ``missing`` rather than claiming the file exists.
    """
    target_root = Path(target_root)
    inspected = inspect_local_renders(target_root)
    dirty = {item.slug: item for item in inspected if item.dirty}
    by_loc = {(item.slug, item.archived): item for item in inspected}
    conflicts: List[str] = []
    writable: List[Mapping[str, Any]] = []
    report: Dict[str, str] = {}
    for doc in docs:
        slug = str(doc.get("slug") or "")
        if not slug:
            continue
        if doc.get("file_text") and slug in dirty:
            conflicts.append(slug)
            continue
        if doc.get("file_text"):
            writable.append(doc)
            continue
        if doc.get("archived") and not doc.get("unchanged"):
            report[slug] = relocate_generated_archive(
                target_root, slug,
                updated_at=str(doc.get("updated_at") or ""),
                content_sha256=str(doc.get("content_sha256") or ""),
            )
            continue
        if doc.get("unchanged"):
            report[slug] = _unchanged_status(doc, by_loc.get(
                (slug, bool(doc.get("archived", False))),
            ))
    report.update(write_rendered_files(target_root, writable))
    return report, conflicts


def _unchanged_status(
    doc: Mapping[str, Any], local: Optional[LocalRenderFile],
) -> str:
    if local is None or not local.path.is_file():
        return "missing"
    if local.dirty:
        return "local-edit"
    if (
        str(local.updated_at or "") != str(doc.get("updated_at") or "")
        or str(local.content_sha256 or "") != str(doc.get("content_sha256") or "")
    ):
        return "missing"
    return "unchanged"


def apply_and_fill_missing(
    target_root: Path | str,
    docs: Iterable[Mapping[str, Any]],
    *,
    fetch_docs: Optional[FetchDocs] = None,
) -> Tuple[Dict[str, str], List[str]]:
    """Apply a render result, then fetch bodies for vanished local files."""
    report, conflicts = apply_rendered_docs(target_root, docs)
    missing = [slug for slug, status in report.items() if status == "missing"]
    if missing and fetch_docs is not None:
        extra, extra_conflicts = apply_rendered_docs(
            target_root, fetch_docs(missing) or (),
        )
        conflicts.extend(extra_conflicts)
        for slug in missing:
            if slug in extra:
                report.pop(slug, None)
        report.update(extra)
    return report, conflicts


def conflict_message(slugs: Sequence[str]) -> str:
    parts = [
        f"{slug} {LOCAL_EDIT_CONFLICT_TEACHING.format(slug=slug)}"
        for slug in slugs
    ]
    return "error (local_edit_conflict): " + " ".join(parts)


__all__ = [
    "LOCAL_EDIT_CONFLICT_TEACHING",
    "apply_and_fill_missing",
    "apply_rendered_docs",
    "build_render_payload",
    "conflict_message",
]
