"""Generated board block splicing helpers.

Pure text composition: merge freshly rendered board markdown into an existing
``BOARD.md`` between the ``YOKE:BOARD`` markers, stripping merge-conflict
debris. Ships in ``yoke_contracts`` so a client can write its board without
loading ``yoke_core``; the source-dev tier re-exports these names for its
existing importers.
"""

from __future__ import annotations

from typing import Iterable

MARKER_START = "<!-- YOKE:BOARD:START"
MARKER_END = "<!-- YOKE:BOARD:END"
CONFLICT_PREFIXES = ("<<<<<<< ", "=======", ">>>>>>> ")


def _marker_line(timestamp: str) -> str:
    return (
        "<!-- YOKE:BOARD:START — auto-generated by "
        "yoke_core.domain.rebuild_board, do not edit --> "
        f"last synced: {timestamp}"
    )


def _strip_conflict_markers(lines: Iterable[str]) -> list[str]:
    return [line for line in lines if not line.startswith(CONFLICT_PREFIXES)]


def _strip_generated_prefix_padding(lines: list[str]) -> list[str]:
    marker_index = 0
    while marker_index < len(lines) and not lines[marker_index].strip():
        marker_index += 1
    if marker_index and marker_index < len(lines) and MARKER_START in lines[marker_index]:
        return lines[marker_index:]
    return lines


def _fresh_board_text(board_content: str, timestamp: str) -> str:
    return (
        f"{_marker_line(timestamp)}\n"
        f"{board_content.rstrip()}\n"
        "<!-- YOKE:BOARD:END -->\n"
    )


def splice_board(existing_text: str, board_content: str, timestamp: str) -> str:
    clean_lines = _strip_generated_prefix_padding(
        _strip_conflict_markers(existing_text.splitlines())
    )
    board_lines = board_content.splitlines()
    found_markers = False
    in_board = False
    output: list[str] = []

    for line in clean_lines:
        if MARKER_START in line:
            if in_board:
                continue
            found_markers = True
            in_board = True
            output.append(_marker_line(timestamp))
            output.extend(board_lines)
            continue
        if MARKER_END in line:
            in_board = False
            output.append(line)
            continue
        if not in_board:
            output.append(line)

    if not found_markers:
        if output and output[-1] != "":
            output.append("")
        output.append(_marker_line(timestamp))
        output.extend(board_lines)
        output.append("<!-- YOKE:BOARD:END -->")

    rendered = "\n".join(output)
    if not rendered.endswith("\n"):
        rendered += "\n"

    if any(line.startswith(CONFLICT_PREFIXES) for line in rendered.splitlines()):
        return _fresh_board_text(board_content, timestamp)
    return rendered


__all__ = ["_fresh_board_text", "splice_board"]
