"""Shared time and byte ceilings for hosted JSON transports."""

from __future__ import annotations


DEFAULT_JSON_RESPONSE_LIMIT_BYTES = 4 * 1024 * 1024
BUNDLE_JSON_RESPONSE_LIMIT_BYTES = 16 * 1024 * 1024
SMALL_JSON_RESPONSE_LIMIT_BYTES = 64 * 1024
DEFAULT_JSON_REQUEST_TIMEOUT_SECONDS = 30.0
ONBOARD_JSON_REQUEST_TIMEOUT_SECONDS = 20.0


__all__ = [
    "BUNDLE_JSON_RESPONSE_LIMIT_BYTES",
    "DEFAULT_JSON_REQUEST_TIMEOUT_SECONDS",
    "DEFAULT_JSON_RESPONSE_LIMIT_BYTES",
    "ONBOARD_JSON_REQUEST_TIMEOUT_SECONDS",
    "SMALL_JSON_RESPONSE_LIMIT_BYTES",
]
