"""Closed vocabulary for requested and observed session presentation."""

from __future__ import annotations


CLAUDE_LOCAL_PRESENTATION = "local"
CLAUDE_REMOTE_CONTROL_SETTING = "disableRemoteControl"
PRESENTATION_SURFACE_REMOTE_CONTROL = "remote-control"
PRESENTATION_STATE_ATTACHED = "attached"
PRESENTATION_STATE_NOT_ATTACHED = "not-attached"
PRESENTATION_MODE_BIDIRECTIONAL = "bidirectional"
PRESENTATION_MODE_OUTBOUND_ONLY = "outbound-only"
PRESENTATION_SOURCE_CLAUDE_JOB_STATE = "claude-job-state"

PRESENTATION_STATES = frozenset(
    {PRESENTATION_STATE_ATTACHED, PRESENTATION_STATE_NOT_ATTACHED}
)
PRESENTATION_MODES = frozenset(
    {PRESENTATION_MODE_BIDIRECTIONAL, PRESENTATION_MODE_OUTBOUND_ONLY}
)


__all__ = [
    "CLAUDE_LOCAL_PRESENTATION",
    "CLAUDE_REMOTE_CONTROL_SETTING",
    "PRESENTATION_MODES",
    "PRESENTATION_MODE_BIDIRECTIONAL",
    "PRESENTATION_MODE_OUTBOUND_ONLY",
    "PRESENTATION_SOURCE_CLAUDE_JOB_STATE",
    "PRESENTATION_STATES",
    "PRESENTATION_STATE_ATTACHED",
    "PRESENTATION_STATE_NOT_ATTACHED",
    "PRESENTATION_SURFACE_REMOTE_CONTROL",
]
