"""Shared public constants for item-owned worktree lane operations."""

ITEM_WORKTREE_LANE_IMPLEMENTATION = "implementation"
ITEM_WORKTREE_LANE_WORKER = "worker"
ITEM_WORKTREE_LANE_INTEGRATION = "integration"
ADDITIONAL_ITEM_WORKTREE_LANE_ROLES = (
    ITEM_WORKTREE_LANE_WORKER,
    ITEM_WORKTREE_LANE_INTEGRATION,
)
EVIDENCE_ONLY_RECOVERY_REASON = "evidence-only-recovery"

__all__ = [
    "ADDITIONAL_ITEM_WORKTREE_LANE_ROLES",
    "EVIDENCE_ONLY_RECOVERY_REASON",
    "ITEM_WORKTREE_LANE_IMPLEMENTATION",
    "ITEM_WORKTREE_LANE_INTEGRATION",
    "ITEM_WORKTREE_LANE_WORKER",
]
