"""Wire constants for managed-project rendered artifact bundles."""

from __future__ import annotations


PROJECT_ARTIFACT_BUNDLE_SCHEMA = 2
PROJECT_ARTIFACT_MANIFEST_SCHEMA = 1
PROJECT_ARTIFACT_MANIFEST_REL = ".yoke/artifact-manifest.json"
PROJECT_ARTIFACT_TEMPLATE = "webapp"
PROJECT_ARTIFACT_PACKAGED_SOURCE = "packaged-template-mirror"
PROJECT_ARTIFACT_SOURCE_DEV_SOURCE = "source-dev-admin-template-tree"
PROJECT_ARTIFACT_GENERATED_REFERENCE_PREFIX = "docs/yoke-generated/deployment-reference/"
PROJECT_ARTIFACT_POLICY_CAPABILITY = "project-policy"
PROJECT_ARTIFACT_POLICY_SETTING = "artifact_refresh"
PROJECT_ARTIFACT_DEFAULT_APPLICABILITY_REASON = (
    "the generic webapp artifact contract applies"
)


__all__ = [
    "PROJECT_ARTIFACT_BUNDLE_SCHEMA",
    "PROJECT_ARTIFACT_DEFAULT_APPLICABILITY_REASON",
    "PROJECT_ARTIFACT_GENERATED_REFERENCE_PREFIX",
    "PROJECT_ARTIFACT_MANIFEST_REL",
    "PROJECT_ARTIFACT_MANIFEST_SCHEMA",
    "PROJECT_ARTIFACT_PACKAGED_SOURCE",
    "PROJECT_ARTIFACT_POLICY_CAPABILITY",
    "PROJECT_ARTIFACT_POLICY_SETTING",
    "PROJECT_ARTIFACT_SOURCE_DEV_SOURCE",
    "PROJECT_ARTIFACT_TEMPLATE",
]
