"""Shared wire contract for raw template bundles."""

from __future__ import annotations

TEMPLATE_BUNDLE_SCHEMA = 1
TEMPLATES_API_PATH = "/v1/templates"
TEMPLATE_PRODUCT_BOUNDARY_FIELD = "product_boundary"
TEMPLATE_PRODUCT_BOUNDARY_PRODUCT = "product"
TEMPLATE_PRODUCT_BOUNDARY_SOURCE_DEV_ADMIN = "source-dev/admin"
TEMPLATE_SOURCE_DEV_ADMIN_QUERY_PARAM = "include_source_dev_admin"

__all__ = [
    "TEMPLATE_BUNDLE_SCHEMA",
    "TEMPLATE_PRODUCT_BOUNDARY_FIELD",
    "TEMPLATE_PRODUCT_BOUNDARY_PRODUCT",
    "TEMPLATE_PRODUCT_BOUNDARY_SOURCE_DEV_ADMIN",
    "TEMPLATE_SOURCE_DEV_ADMIN_QUERY_PARAM",
    "TEMPLATES_API_PATH",
]
