"""Native PostgreSQL instant predicates and canonical UTC serialization.

Use now_sql for native indexed predicates, utc_now for Python DB parameters,
and instant_wire_sql only when projecting owned wire/document values. Fixed
window offsets count elapsed seconds; calendar buckets declare their timezone
at the owning query. Supplied modifier SQL remains caller-authored interval SQL.
"""

from __future__ import annotations

import json
from typing import Optional

INSTANT_WIRE_TEMPLATE = 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'


def instant_wire_sql(expression: str) -> str:
    """Project a native timestamptz to fixed-six UTC text, preserving SQL NULL.

    The expression is SQL authored by the caller, not untrusted input. This
    is a serialization boundary for owned JSON fields, never a predicate:
    compare indexed native instants before projecting their wire form.
    """
    return f"to_char(({expression}) AT TIME ZONE 'UTC', '{INSTANT_WIRE_TEMPLATE}')"


def instant_wire_typescript() -> str:
    """Emit the Node/browser SQL projector from the same canonical expression.

    This returns source without writing a checkout. The checked-in TypeScript
    contract is generated from it, so cross-language callers do not maintain
    a second timestamp template.
    """
    marker = "__instant_expression__"
    prefix, _, suffix = instant_wire_sql(marker).partition(marker)
    return (
        "/** Generated by yoke_contracts.time_sql.instant_wire_typescript. */\n"
        "/** Project caller-authored SQL instants to UTC wire text; NULL stays NULL. */\n"
        "export function instantWireSql(expression: string): string {\n"
        f"  return {json.dumps(prefix)} + expression + {json.dumps(suffix)};\n"
        "}\n"
    )


def now_sql(
    *,
    offset_days: Optional[int] = None,
    offset_hours: Optional[int] = None,
    offset_minutes: Optional[int] = None,
    offset_modifier: Optional[str] = None,
) -> str:
    """Return a native timestamptz clock with one elapsed offset.

    Fixed days/hours/minutes count 86400/3600/60 seconds, independent of the
    database session timezone. offset_modifier is trusted SQL cast to interval;
    its caller owns any calendar meaning and parameter binding.
    """
    fixed_offsets = (offset_days, offset_hours, offset_minutes)
    fixed_supplied = sum(1 for v in fixed_offsets if v is not None)
    if fixed_supplied > 1:
        raise ValueError(
            "now_sql: pass at most one of offset_days, offset_hours, offset_minutes"
        )
    if fixed_supplied and offset_modifier is not None:
        raise ValueError(
            "now_sql: offset_modifier is mutually exclusive with a fixed offset"
        )

    for offset, seconds in zip(fixed_offsets, (86400, 3600, 60)):
        if offset is not None:
            return f"(now() + make_interval(secs => {offset * seconds}))"
    if offset_modifier is not None:
        return f"(now() + ({offset_modifier})::interval)"
    return "now()"


__all__ = [
    "INSTANT_WIRE_TEMPLATE",
    "instant_wire_sql",
    "instant_wire_typescript",
    "now_sql",
]
