/** Generated by yoke_contracts.time_sql.instant_wire_typescript. */
/** Project caller-authored SQL instants to UTC wire text; NULL stays NULL. */
export function instantWireSql(expression) {
    return "to_char((" + expression + ") AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')";
}
