"""Level-store tables and writers for session-registration level tests.

Registration reads the levels a project sees from two stores: the
universe definition in ``universe_settings`` and a project override in the
project's ``session-routing`` capability. Fixtures that build a narrow
schema add both tables here so a registering session reads the same
stores a real universe carries, and tests write either store through the
helpers below.
"""

from __future__ import annotations

from typing import Any, Mapping, Optional

from yoke_contracts.project_contract.project_keys import SESSION_ROUTING_CAPABILITY
from yoke_core.domain import db_backend, json_helper
from yoke_core.domain.schema_init_apply import execute_schema_script
from yoke_core.domain.universe_levels import (
    create_universe_settings_table,
    write_universe_levels,
)

PROJECT_CAPABILITIES_DDL = """
CREATE TABLE IF NOT EXISTS project_capabilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    settings TEXT DEFAULT '{}',
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00Z',
    UNIQUE(project_id, type)
);
"""

# Distinct terminal-safe glyphs for levels a test declares.
_GLYPHS = ("\U0001f40e", "\U0001f680", "\U0001f6f8", "\U0001f453")


def create_level_store_tables(conn: Any) -> None:
    """Add both level stores to a fixture schema."""
    execute_schema_script(conn, PROJECT_CAPABILITIES_DDL)
    create_universe_settings_table(conn)
    conn.commit()


def option(
    surface: str,
    model: str,
    effort: str,
    context: Optional[int] = None,
) -> dict[str, Any]:
    """One launchable option in a levels document."""
    return {
        "surface": surface,
        "model": model,
        "reasoning_effort": effort,
        "context_window_tokens": context,
    }


def levels_doc(*levels: tuple[str, list[Mapping[str, Any]]]) -> list[dict]:
    """Build a levels document from ``(name, options)`` pairs, lowest first."""
    return [
        {"name": name, "glyph": _GLYPHS[index], "options": list(options)}
        for index, (name, options) in enumerate(levels)
    ]


def store_universe_levels(conn: Any, document: list[dict]) -> None:
    """Store the universe levels definition through its domain writer."""
    write_universe_levels(conn, document, actor_id=None)


def store_project_levels(conn: Any, project_id: int, document: list[dict]) -> None:
    """Store a project's ``session-routing`` levels override."""
    p = "%s" if db_backend.connection_is_postgres(conn) else "?"
    conn.execute(
        "INSERT INTO project_capabilities (project_id, type, settings) "
        f"VALUES ({p}, {p}, {p}) "
        "ON CONFLICT (project_id, type) DO UPDATE SET settings = excluded.settings",
        (
            int(project_id),
            SESSION_ROUTING_CAPABILITY,
            json_helper.dumps_compact({"levels": document}),
        ),
    )
    conn.commit()


__all__ = [
    "PROJECT_CAPABILITIES_DDL",
    "create_level_store_tables",
    "levels_doc",
    "option",
    "store_project_levels",
    "store_universe_levels",
]
