"""Fixture DDL — per-day activity and code rollup tables.

Native-Postgres mirrors of the canonical boot-converge definitions in
``yoke_core.domain.schema_init_tables``: the board/Overview momentum
readers (``yoke_contracts.board.momentum_series``) query both tables, so
disposable fixture databases must carry them.
"""

from __future__ import annotations

_ACTIVITY_ROLLUPS_DDL = """
-- board activity rollup: one row per (project, item, UTC day) of real
-- domain mutation (yoke_core.domain.item_activity).
CREATE TABLE IF NOT EXISTS item_activity_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    UNIQUE(project_id, item_id, day)
);
-- daily commit/line rollup shared by the board and Overview code meters
-- (yoke_core.domain.project_code_days).
CREATE TABLE IF NOT EXISTS project_code_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    commit_count INTEGER NOT NULL DEFAULT 0,
    lines_changed INTEGER NOT NULL DEFAULT 0,
    UNIQUE(project_id, day)
);
"""

__all__ = ("_ACTIVITY_ROLLUPS_DDL",)
