"""Test-fixture schema DDL — items table family.

Derives the items, item_dependencies, and release_entries DDL from
canonical schema initialization run against a disposable Postgres scratch
database, read back from the catalog. This is fixture derivation, not a
Yoke authority read: the fixture mirrors the canonical schema code's shape
so callers using ``SCHEMA_DDL`` see the same surface a freshly initialized
Yoke DB exposes — and so future column additions to ``items`` land in this
fixture automatically.

Derivation is lazy and cached per process: importing this module performs
no database work; the first ``_ITEMS_DDL`` / ``_ITEMS_RELAXED_DDL`` access
creates the scratch database (which requires the test-cluster DSN, present
whenever pytest's conftest has run) and derives both variants in one pass.

Like the rest of the fixture schema, the derived DDL carries no FOREIGN
KEY constraints, so tests can seed rows in any order.

Composed into ``SCHEMA_DDL`` by the assembler at
``runtime/api/fixtures/schema_ddl.py``. Read by the residue test at
``runtime/api/test_schema_fixture_derivation.py`` to keep the
migrated helper family from regressing back to copied long-form DDL.
"""

from __future__ import annotations

from typing import Any, Dict, Tuple


# Items-family tables the fixture exposes. Ordering matters for callers
# that apply the assembled DDL: parents first, dependents after.
# ``release_entries`` references ``items`` by ``item_id`` (no FK in the
# fixture but the ordering documents intent).
_ITEMS_FAMILY_TABLES: Tuple[str, ...] = (
    "items",
    "item_dependencies",
    "release_entries",
)


# Historical items columns (resolution*) and the full init sequence live in
# the shared apply helper (runtime.api.fixtures.schema_apply) so this fixture
# derivation and the Postgres disposable test database stay in lockstep.


_COLUMNS_SQL = """
SELECT a.attname,
       format_type(a.atttypid, a.atttypmod),
       a.attnotnull,
       pg_get_expr(d.adbin, d.adrelid),
       a.attidentity
FROM pg_attribute a
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = %s::regclass AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
"""

# FOREIGN KEY constraints (contype 'f') are deliberately excluded: fixture
# tables carry no FKs so tests can seed rows in any order.
_CONSTRAINTS_SQL = """
SELECT c.contype, pg_get_constraintdef(c.oid)
FROM pg_constraint c
WHERE c.conrelid = %s::regclass AND c.contype IN ('p', 'u', 'c')
ORDER BY c.contype, c.conname
"""


def _column_clause(
    name: str,
    data_type: str,
    not_null: bool,
    default: Any,
    identity: str,
    *,
    relaxed: bool,
) -> str:
    piece = f"{name} {data_type}"
    if identity == "a":
        piece += " GENERATED ALWAYS AS IDENTITY"
    elif identity == "d":
        piece += " GENERATED BY DEFAULT AS IDENTITY"
    if not_null and not relaxed and not identity:
        piece += " NOT NULL"
    if default is not None:
        piece += f" DEFAULT {default}"
    return piece


def _read_table_ddl(conn: Any, table_name: str, *, relaxed: bool = False) -> str:
    """Compose a table's CREATE statement from the Postgres catalog.

    The strict shape keeps NOT NULL plus the table's PRIMARY KEY, UNIQUE,
    and CHECK constraints. The relaxed shape keeps only columns, defaults,
    identity, and the PRIMARY KEY, so callers can seed slim or legacy rows.
    ``CREATE TABLE IF NOT EXISTS`` keeps repeated application from tripping
    on duplicate-table errors.
    """
    columns = conn.execute(_COLUMNS_SQL, (table_name,)).fetchall()
    if not columns:
        raise RuntimeError(
            f"derived items-family DDL missing table {table_name!r}"
        )
    parts = [
        _column_clause(name, data_type, not_null, default, identity, relaxed=relaxed)
        for name, data_type, not_null, default, identity in columns
    ]
    for contype, definition in conn.execute(_CONSTRAINTS_SQL, (table_name,)).fetchall():
        if relaxed and contype != "p":
            continue
        parts.append(definition)
    body = ",\n    ".join(parts)
    return f"CREATE TABLE IF NOT EXISTS {table_name} (\n    {body}\n)"


def _derive_ddl_variants() -> Dict[str, str]:
    """Apply canonical schema init to a scratch DB and derive both variants.

    The scratch database is disposable and local to this call — the
    canonical control-plane DB is never touched.
    """
    from runtime.api.fixtures import pg_testdb
    from runtime.api.fixtures.schema_apply import apply_canonical_schema

    name = pg_testdb.create_test_database()
    try:
        conn = pg_testdb.connect_test_database(name)
        try:
            apply_canonical_schema(conn)
            statements = [
                _read_table_ddl(conn, table) for table in _ITEMS_FAMILY_TABLES
            ]
            relaxed = _read_table_ddl(conn, "items", relaxed=True)
        finally:
            conn.close()
    finally:
        pg_testdb.drop_test_database(name)
    return {
        "_ITEMS_DDL": ";\n".join(statements) + ";\n",
        "_ITEMS_RELAXED_DDL": relaxed + ";\n",
    }


_DERIVED_DDL: Dict[str, str] = {}


def __getattr__(name: str) -> str:
    if name in ("_ITEMS_DDL", "_ITEMS_RELAXED_DDL"):
        if not _DERIVED_DDL:
            _DERIVED_DDL.update(_derive_ddl_variants())
        return _DERIVED_DDL[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = ("_ITEMS_DDL", "_ITEMS_RELAXED_DDL")  # noqa: F822
