"""Test-fixture schema DDL — merge lock tables."""

_MERGE_LOCKS_DDL = """
CREATE TABLE IF NOT EXISTS merge_locks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    branch TEXT NOT NULL,
    epic_id TEXT,
    acquired_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_merge_locks_expires_at
    ON merge_locks(expires_at);
"""

__all__ = ("_MERGE_LOCKS_DDL",)
