"""Test-fixture strategy-doc DDL (per-project rendered-view authority)."""

_STRATEGY_DDL = """
CREATE TABLE IF NOT EXISTS strategy_docs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    slug TEXT NOT NULL, content TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL,
    updated_by_actor_id INTEGER, archived_at TEXT, UNIQUE(project_id, slug));
"""
