"""Test-fixture schema DDL — epic + QA table family.

Owns CREATE TABLE statements for the epic and QA table family:
``epic_tasks``, ``epic_progress_notes``, ``epic_task_files``,
``epic_dispatch_chains``, ``qa_requirements``, ``qa_runs``,
``qa_artifacts``, ``deployment_run_qa``.

Native Postgres DDL. Mirrors production ``runtime/api/domain/schema.py``
for every column and CHECK constraint; fixture tables intentionally carry
no FOREIGN KEY constraints so tests can seed rows in any order. Composed
into ``SCHEMA_DDL`` by the assembler at
``runtime/api/fixtures/schema_ddl.py`` — any addition in production must
be reflected here in lockstep.
"""

_EPIC_QA_DDL = """
CREATE TABLE IF NOT EXISTS epic_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    title TEXT,
    worktree TEXT,
    context_estimate TEXT,
    dependencies TEXT,
    status TEXT DEFAULT 'planning'
        CHECK(status IN (
            'planning','plan-drafted','refining-plan','planned',
            'implementing','reviewing-implementation',
            'reviewed-implementation','polishing-implementation',
            'implemented','release','done','failed','blocked','stopped'
        )),
    dispatch_attempts INTEGER DEFAULT 0,
    body TEXT,
    github_issue TEXT,
    branch TEXT,
    worktree_path TEXT,
    blocked_by TEXT,
    max_attempts INTEGER DEFAULT 5,
    agent_id TEXT,
    last_heartbeat TEXT,
    last_activity_at TEXT,
    UNIQUE(epic_id, task_num)
);

CREATE TABLE IF NOT EXISTS epic_progress_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    note_num INTEGER NOT NULL,
    body TEXT,
    commit_hash TEXT,
    synced_to_github INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    UNIQUE(epic_id, task_num, note_num)
);

CREATE TABLE IF NOT EXISTS epic_task_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    task_num INTEGER NOT NULL,
    file_path TEXT NOT NULL,
    action TEXT,
    UNIQUE(epic_id, task_num, file_path)
);

CREATE TABLE IF NOT EXISTS epic_dispatch_chains (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epic_id INTEGER NOT NULL,
    worktree TEXT NOT NULL,
    worktree_path TEXT,
    queue TEXT,
    current_index INTEGER DEFAULT 0,
    current_task TEXT,
    current_attempt INTEGER DEFAULT 1,
    max_attempts INTEGER DEFAULT 5,
    no_chain INTEGER DEFAULT 0,
    started_at TEXT,
    last_updated TEXT,
    UNIQUE(epic_id, worktree)
);

CREATE TABLE IF NOT EXISTS qa_requirements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER,
    epic_id INTEGER,
    task_num INTEGER,
    deployment_run_id TEXT,
    qa_kind TEXT NOT NULL,
    qa_phase TEXT NOT NULL
        CHECK(qa_phase IN ('verification','post_deploy','manual_acceptance')),
    target_env TEXT,
    blocking_mode TEXT NOT NULL DEFAULT 'blocking'
        CHECK(blocking_mode IN ('blocking','non_blocking')),
    requirement_source TEXT NOT NULL DEFAULT 'explicit'
        CHECK(requirement_source IN ('explicit','seeded_default','ac_derived','flow_derived')),
    success_policy TEXT,
    capability_requirements TEXT,
    suite_id TEXT,
    waived_at TEXT,
    waiver_rationale TEXT,
    created_at TEXT NOT NULL,
    waiver_source TEXT,
    CHECK (
        (item_id IS NOT NULL AND epic_id IS NULL AND task_num IS NULL AND deployment_run_id IS NULL) OR
        (item_id IS NULL AND epic_id IS NOT NULL AND task_num IS NOT NULL AND deployment_run_id IS NULL) OR
        (item_id IS NULL AND epic_id IS NULL AND task_num IS NULL AND deployment_run_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS qa_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_requirement_id INTEGER NOT NULL,
    executor_type TEXT NOT NULL,
    qa_kind TEXT NOT NULL,
    verdict TEXT CHECK(verdict IN ('pass','fail','inconclusive','error')),
    execution_status TEXT CHECK(execution_status IN ('captured','capture_failed') OR execution_status IS NULL),
    score REAL,
    confidence REAL,
    raw_result TEXT,
    duration_ms INTEGER,
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS qa_artifacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_run_id INTEGER,
    artifact_type TEXT NOT NULL,
    content_type TEXT,
    artifact_handle TEXT,
    metadata TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS deployment_run_qa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL,
    check_name TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'flow_default',
    blocking INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','passed','failed','waived')),
    updated_at TEXT,
    UNIQUE(run_id, check_name)
);
"""

__all__ = ("_EPIC_QA_DDL",)
