"""Test-fixture runtime/event/deployment/registry DDL.

Native Postgres DDL; fixture tables intentionally carry no FOREIGN KEY
constraints so tests can seed rows in any order.
"""

from runtime.api.fixtures.schema_ddl_runtime_sessions import _SESSIONS_FAMILY_DDL

_RUNTIME_DDL = """
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    emoji TEXT DEFAULT '',
    default_branch TEXT DEFAULT 'main',
    github_repo TEXT,
    public_item_prefix TEXT NOT NULL DEFAULT 'YOK',
    org_id INTEGER DEFAULT 1,
    github_sync_mode TEXT,
    created_at TEXT NOT NULL
);
INSERT INTO projects (id, slug, name, github_repo, public_item_prefix, org_id, created_at)
VALUES (1, 'yoke', 'Yoke', 'upyoke/yoke', 'YOK', 1, '2026-01-01T00:00:00Z')
ON CONFLICT(id) DO NOTHING;
INSERT INTO projects (id, slug, name, github_repo, public_item_prefix, org_id, created_at)
VALUES (2, 'buzz', 'Buzz', 'example-org/buzz', 'BUZ', 1, '2026-01-01T00:00:00Z')
ON CONFLICT(id) DO NOTHING;
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_org_slug_unique
    ON projects(org_id, slug);

CREATE TABLE IF NOT EXISTS project_capabilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL, type TEXT NOT NULL,
    config TEXT, verified_at TEXT, created_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00Z', settings TEXT DEFAULT '{}',
    UNIQUE(project_id, type));
CREATE TABLE IF NOT EXISTS capability_secrets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL, type TEXT NOT NULL, key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'literal' CHECK(source = 'literal'),
    created_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00Z',
    UNIQUE(project_id, type, key));

CREATE TABLE IF NOT EXISTS deployment_flows (
    id TEXT PRIMARY KEY,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    stages TEXT NOT NULL,
    on_failure TEXT DEFAULT 'halt',
    created_at TEXT NOT NULL,
    target_env TEXT DEFAULT NULL,
    done_description TEXT DEFAULT NULL,
    UNIQUE(project_id, name)
);

CREATE TABLE IF NOT EXISTS deployment_runs (
    id TEXT PRIMARY KEY,
    project_id INTEGER NOT NULL,
    flow TEXT NOT NULL,
    target_env TEXT,
    release_lineage TEXT,
    status TEXT NOT NULL DEFAULT 'created'
        CHECK(status IN ('created','executing','succeeded','failed','cancelled')),
    current_stage TEXT,
    created_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    created_by TEXT DEFAULT 'operator'
);

CREATE TABLE IF NOT EXISTS deployment_run_items (
    run_id TEXT NOT NULL,
    item_id INTEGER NOT NULL,
    added_at TEXT NOT NULL,
    PRIMARY KEY (run_id, item_id)
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT UNIQUE NOT NULL,
    source_type TEXT NOT NULL
        CHECK(source_type IN ('agent','backend','frontend','system','script','hook','skill')),
    session_id TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'INFO',
    event_kind TEXT NOT NULL,
    event_type TEXT NOT NULL,
    event_name TEXT NOT NULL,
    event_outcome TEXT,
    user_id TEXT,
    org_id TEXT,
    actor_id INTEGER,
    environment TEXT,
    service TEXT NOT NULL DEFAULT 'cli',
    project_id INTEGER NOT NULL DEFAULT 1,
    item_id TEXT,
    task_num INTEGER,
    agent TEXT,
    tool_name TEXT,
    duration_ms INTEGER,
    exit_code INTEGER,
    trace_id TEXT,
    parent_id TEXT,
    anomaly_flags TEXT,
    tool_use_id TEXT,
    turn_id TEXT,
    hook_event_name TEXT,
    envelope TEXT CHECK(envelope IS NULL OR (envelope IS JSON)),
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS severity_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL DEFAULT '*',
    source_type TEXT NOT NULL DEFAULT '*',
    min_severity TEXT NOT NULL DEFAULT 'INFO'
        CHECK(min_severity IN ('DEBUG','INFO','STATUS','WARN','ERROR','FATAL')),
    created_at TEXT NOT NULL,
    UNIQUE(event_name, source_type)
);

CREATE TABLE IF NOT EXISTS event_registry (
    event_name      TEXT PRIMARY KEY,
    event_kind      TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    owner_service   TEXT NOT NULL,
    description     TEXT NOT NULL,
    context_schema  TEXT,
    severity_default TEXT NOT NULL DEFAULT 'INFO',
    added_in        TEXT,
    status          TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS shepherd_verdicts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item TEXT NOT NULL,
    transition TEXT NOT NULL,
    worker TEXT NOT NULL,
    verdict TEXT NOT NULL,
    caveats TEXT,
    attempt INTEGER DEFAULT 1,
    created_at TEXT NOT NULL
);

""" + _SESSIONS_FAMILY_DDL + """
CREATE TABLE IF NOT EXISTS caveat_dispositions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item TEXT NOT NULL,
    transition TEXT NOT NULL,
    attempt INTEGER NOT NULL DEFAULT 1,
    caveat_num INTEGER NOT NULL,
    caveat_text TEXT NOT NULL,
    disposition TEXT NOT NULL,
    resolution_details TEXT,
    verdict_id INTEGER,
    created_at TEXT NOT NULL,
    UNIQUE(item, transition, attempt, caveat_num)
);

CREATE TABLE IF NOT EXISTS ouroboros_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    agent TEXT NOT NULL,
    context TEXT,
    category TEXT NOT NULL,
    body TEXT NOT NULL,
    reviewed_at TEXT,
    archived_at TEXT,
    project_id INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wrapup_reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_timestamp TEXT NOT NULL UNIQUE,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ephemeral_environments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    branch TEXT NOT NULL,
    item TEXT,
    workflow_run_id TEXT,
    github_ref TEXT,
    port_api INTEGER,
    port_web INTEGER,
    url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    started_at TEXT,
    stopped_at TEXT,
    health_check_url TEXT,
    deployed_sha TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(project_id, branch)
);

CREATE TABLE IF NOT EXISTS path_targets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    kind TEXT NOT NULL,
    path_string TEXT NOT NULL,
    generation INTEGER NOT NULL,
    parent_target_id INTEGER,
    created_at TEXT NOT NULL,
    materialization_state TEXT NOT NULL DEFAULT 'observed'
        CHECK(materialization_state IN (
            'planned','observed','abandoned','tentative'
        )),
    materialization_updated_at TEXT,
    planned_by_item_id INTEGER,
    planned_by_claim_id INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_path_targets_generation
    ON path_targets(project_id, path_string, generation);
CREATE INDEX IF NOT EXISTS idx_path_targets_lookup
    ON path_targets(project_id, path_string);
CREATE INDEX IF NOT EXISTS idx_path_targets_materialization
    ON path_targets(project_id, materialization_state);
CREATE INDEX IF NOT EXISTS idx_path_targets_planned_item
    ON path_targets(planned_by_item_id)
    WHERE planned_by_item_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS path_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    commit_sha TEXT NOT NULL,
    built_at TEXT NOT NULL,
    UNIQUE(project_id, commit_sha)
);

CREATE TABLE IF NOT EXISTS actors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK(kind IN ('human','system')),
    system_component TEXT,
    created_at TEXT NOT NULL,
    CHECK (
        (kind = 'system' AND system_component IS NOT NULL)
        OR
        (kind = 'human' AND system_component IS NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_actors_system_component
    ON actors(system_component)
    WHERE system_component IS NOT NULL;

CREATE TABLE IF NOT EXISTS actor_labels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id INTEGER NOT NULL,
    surface TEXT NOT NULL,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(surface, label),
    UNIQUE(actor_id, surface)
);
CREATE INDEX IF NOT EXISTS idx_actor_labels_actor
    ON actor_labels(actor_id);

CREATE TABLE IF NOT EXISTS path_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state TEXT NOT NULL DEFAULT 'planned'
        CHECK(state IN ('planned','blocked','active','released','cancelled')),
    mode TEXT NOT NULL DEFAULT 'exclusive'
        CHECK(mode IN ('exclusive','parallel','exception')),
    actor_id INTEGER NOT NULL,
    session_id TEXT,
    item_id INTEGER,
    work_claim_id INTEGER,
    owner_kind TEXT CHECK(owner_kind IS NULL OR owner_kind IN ('item','session','process')),
    owner_item_id INTEGER,
    owner_session_id TEXT,
    owner_work_claim_id INTEGER,
    registered_by_actor_id INTEGER,
    registered_by_session_id TEXT,
    integration_target TEXT NOT NULL,
    base_commit_sha TEXT,
    registered_at TEXT NOT NULL,
    activated_at TEXT,
    released_at TEXT,
    cancelled_at TEXT,
    release_reason TEXT,
    cancel_reason TEXT,
    blocked_reason TEXT,
    exception_reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_path_claims_state ON path_claims(state);
CREATE INDEX IF NOT EXISTS idx_path_claims_actor ON path_claims(actor_id);
CREATE INDEX IF NOT EXISTS idx_path_claims_session ON path_claims(session_id);
CREATE INDEX IF NOT EXISTS idx_path_claims_item ON path_claims(item_id);
CREATE INDEX IF NOT EXISTS idx_path_claims_integration_target
    ON path_claims(integration_target, state);

CREATE TABLE IF NOT EXISTS path_claim_targets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER NOT NULL,
    target_id INTEGER NOT NULL,
    declared_at TEXT NOT NULL,
    UNIQUE(claim_id, target_id)
);
CREATE INDEX IF NOT EXISTS idx_path_claim_targets_target
    ON path_claim_targets(target_id);

CREATE TABLE IF NOT EXISTS path_claim_amendments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER NOT NULL,
    amended_at TEXT NOT NULL,
    amendment_kind TEXT NOT NULL,
    payload TEXT NOT NULL DEFAULT '{}',
    reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_path_claim_amendments_claim
    ON path_claim_amendments(claim_id);

CREATE TABLE IF NOT EXISTS path_claim_overrides (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_claim_id INTEGER NOT NULL,
    blocking_claim_id INTEGER,
    blocking_path_targets TEXT NOT NULL DEFAULT '[]',
    override_point TEXT NOT NULL,
    conflict_reason TEXT,
    integration_target TEXT,
    actor_id INTEGER,
    actor_reason TEXT NOT NULL,
    item_id INTEGER,
    project TEXT,
    session_id TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_path_claim_overrides_pair
    ON path_claim_overrides(path_claim_id, blocking_claim_id);
"""

__all__ = ("_RUNTIME_DDL",)
