"""Project site/environment rows shared by disposable Postgres fixtures."""

_PROJECT_ENVIRONMENT_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS sites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TEXT NOT NULL,
    settings TEXT DEFAULT '{}',
    UNIQUE(id, project_id),
    UNIQUE(project_id, name)
);
CREATE TABLE IF NOT EXISTS environments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    url TEXT,
    health_check_url TEXT,
    last_deployed_at TEXT,
    created_at TEXT NOT NULL,
    settings TEXT DEFAULT '{}',
    UNIQUE(project_id, name)
);
"""

_PROJECT_ENVIRONMENT_SEED_DDL = """
INSERT INTO sites(project_id,name,created_at)
VALUES (1,'Yoke API','2026-01-01T00:00:00Z')
ON CONFLICT(project_id,name) DO NOTHING;
INSERT INTO environments(site,project_id,name,created_at)
SELECT id,1,'development','2026-01-01T00:00:00Z'
FROM sites WHERE project_id=1 AND name='Yoke API'
ON CONFLICT(project_id,name) DO NOTHING;
INSERT INTO sites(project_id,name,created_at)
VALUES (2,'External webapp API','2026-01-01T00:00:00Z')
ON CONFLICT(project_id,name) DO NOTHING;
INSERT INTO environments(site,project_id,name,created_at)
SELECT id,2,'development','2026-01-01T00:00:00Z'
FROM sites WHERE project_id=2 AND name='External webapp API'
ON CONFLICT(project_id,name) DO NOTHING;
"""

_PROJECT_ENVIRONMENT_DDL = (
    _PROJECT_ENVIRONMENT_TABLE_DDL + _PROJECT_ENVIRONMENT_SEED_DDL
)

__all__ = [
    "_PROJECT_ENVIRONMENT_DDL",
    "_PROJECT_ENVIRONMENT_SEED_DDL",
    "_PROJECT_ENVIRONMENT_TABLE_DDL",
]
