"""Test-fixture sessions-family DDL (harness_sessions + tool calls + claims).

Split from :mod:`schema_ddl_runtime` to keep that module under the
authored-file budget; composed back into ``_RUNTIME_DDL`` at the same
position so table creation order is unchanged. Native Postgres DDL with
no FOREIGN KEY constraints, matching the rest of the fixture schema.
"""

from yoke_core.domain.session_turn_posture import (
    TURN_POSTURE_AT_COLUMN_DDL,
    TURN_POSTURE_COLUMN_DDL,
)
from yoke_core.domain.work_claim_target_sql import TARGET_KIND_CHECK_SQL


_SESSIONS_FAMILY_DDL = f"""
CREATE TABLE IF NOT EXISTS harness_sessions (
    session_id TEXT PRIMARY KEY,
    executor TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT,
    reasoning_effort TEXT DEFAULT NULL,
    context_window_tokens INTEGER DEFAULT NULL,
    requested_model TEXT DEFAULT NULL,
    requested_reasoning_effort TEXT DEFAULT NULL,
    requested_context_window_tokens INTEGER DEFAULT NULL,
    execution_lane TEXT NOT NULL DEFAULT 'primary',
    executor_version TEXT, machine_id TEXT,
    workspace TEXT NOT NULL,
    project_id INTEGER NOT NULL DEFAULT 1,
    mode TEXT DEFAULT 'wait',
    parked_reason TEXT DEFAULT NULL,
    keepalive_until TEXT DEFAULT NULL,
    keepalive_reason TEXT DEFAULT NULL,
    offered_at TEXT NOT NULL,
    last_heartbeat TEXT NOT NULL,
    ended_at TEXT,
    terminated_at TEXT,
    terminated_by_actor_id INTEGER,
    terminated_by_session_id TEXT,
    termination_reason TEXT,
    offer_envelope TEXT,
    current_item_id TEXT DEFAULT NULL,
    current_item_set_at TEXT DEFAULT NULL,
    recent_item_id TEXT DEFAULT NULL,
    recent_item_status TEXT DEFAULT NULL,
    recent_item_recorded_at TEXT DEFAULT NULL,
    actor_id INTEGER DEFAULT NULL,
    last_seen_main_sha TEXT DEFAULT NULL,
    last_drift_check_at TEXT DEFAULT NULL,
    executor_surface TEXT DEFAULT NULL,
    presentation_surface TEXT DEFAULT NULL,
    presentation_state TEXT DEFAULT NULL,
    presentation_mode TEXT DEFAULT NULL,
    presentation_source TEXT DEFAULT NULL,
    presentation_observed_at TEXT DEFAULT NULL,
    last_tool_call_at TEXT DEFAULT NULL,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    episode_started_at TEXT DEFAULT NULL,
    pending_resume_notice TEXT DEFAULT NULL,
    last_chain_step INTEGER DEFAULT NULL,
    last_checkpoint_at TEXT DEFAULT NULL,
    turn_posture {TURN_POSTURE_COLUMN_DDL},
    turn_posture_at {TURN_POSTURE_AT_COLUMN_DDL},
    native_thread_id TEXT DEFAULT NULL,
    last_steering_report_at TEXT DEFAULT NULL,
    last_steering_report_fingerprint TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS session_tool_calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    tool_use_id TEXT NOT NULL,
    tool_name TEXT,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    outcome TEXT,
    command_summary TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_session_tool_calls_dedup
    ON session_tool_calls(session_id, tool_use_id);

CREATE INDEX IF NOT EXISTS idx_session_tool_calls_session_started
    ON session_tool_calls(session_id, started_at);

CREATE TABLE IF NOT EXISTS work_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    target_kind TEXT NOT NULL CONSTRAINT work_claims_target_kind_check
      CHECK({TARGET_KIND_CHECK_SQL}),
    scope TEXT NOT NULL,
    claim_type TEXT NOT NULL DEFAULT 'exclusive' CHECK(claim_type='exclusive'),
    claimed_at TEXT NOT NULL,
    last_heartbeat TEXT NOT NULL,
    released_at TEXT,
    release_reason TEXT CHECK(release_reason IS NULL OR release_reason IN ('completed','released','reclaimed','handed_off','expired','session_ended')),
    reason TEXT DEFAULT NULL,
    reason_intent TEXT DEFAULT NULL,
    release_reason_intent TEXT DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_item
    ON work_claims(scope)
    WHERE released_at IS NULL AND target_kind='item';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_epic_task
    ON work_claims(scope)
    WHERE released_at IS NULL AND target_kind='epic_task';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_steering
    ON work_claims(scope)
    WHERE released_at IS NULL AND target_kind='steering';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_process_conflict
    ON work_claims(((scope::jsonb) ->> 'conflict_group'))
    WHERE released_at IS NULL AND target_kind='process';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_qa_admission
    ON work_claims(scope)
    WHERE released_at IS NULL AND target_kind='qa_admission';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_route_qualification
    ON work_claims(scope)
    WHERE released_at IS NULL AND target_kind='route_qualification';
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_claims_active_migration_serialization
    ON work_claims(
        ((scope::jsonb) ->> 'project_id'),
        ((scope::jsonb) ->> 'model')
    )
    WHERE released_at IS NULL AND target_kind='migration_serialization';

"""
