"""Fixture DDL — tables feeding the board/Overview momentum series.

Native-Postgres mirrors of the canonical boot-converge definitions in
``yoke_core.domain.schema_init_tables``: the shared momentum readers
(``yoke_contracts.board.momentum_series``) query all three tables, so
disposable fixture databases must carry them.
"""

from __future__ import annotations

_MOMENTUM_FEEDS_DDL = """
-- item/task status transition history, written at mutation time by
-- every status writer (yoke_core.domain.item_status_transitions).
CREATE TABLE IF NOT EXISTS item_status_transitions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    task_num INTEGER,
    from_status TEXT,
    to_status TEXT NOT NULL,
    source TEXT,
    session_id TEXT,
    actor_id INTEGER,
    project_id INTEGER,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_item_status_transitions_item_created
    ON item_status_transitions(item_id, created_at);
-- board activity rollup: one row per (project, item, UTC day) of real
-- domain mutation (yoke_core.domain.item_activity).
CREATE TABLE IF NOT EXISTS item_activity_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    UNIQUE(project_id, item_id, day)
);
-- daily commit/line rollup shared by the board and Overview code meters
-- (yoke_core.domain.project_code_days).
CREATE TABLE IF NOT EXISTS project_code_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    commit_count INTEGER NOT NULL DEFAULT 0,
    lines_changed INTEGER NOT NULL DEFAULT 0,
    UNIQUE(project_id, day)
);
"""

__all__ = ("_MOMENTUM_FEEDS_DDL",)
