"""Tests for per-worker reusable test databases with baseline reset."""

from __future__ import annotations

import uuid

import psycopg
import pytest

from runtime.api.fixtures import file_test_db, pg_reusable_db, pg_testdb


def _connect(name: str):
    return psycopg.connect(pg_testdb.dsn_for_test_database(name))


_SMALL_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE parent_rows (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        label TEXT NOT NULL,
        payload JSONB
    )
    """,
    """
    CREATE TABLE child_rows (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parent_id INTEGER NOT NULL REFERENCES parent_rows(id),
        note TEXT
    )
    """,
    """INSERT INTO parent_rows (label, payload) VALUES ('seed', '{"k": [1, 2]}')""",
    """INSERT INTO child_rows (parent_id, note) VALUES (1, 'seed-child')""",
]


def _build_small_db() -> str:
    name = pg_testdb.create_test_database()
    conn = _connect(name)
    try:
        for statement in _SMALL_SCHEMA_STATEMENTS:
            conn.execute(statement)
        conn.commit()
    finally:
        conn.close()
    return name


@pytest.fixture
def flavor():
    key = f"reusable_db_probe_{uuid.uuid4().hex[:8]}"
    yield key
    pg_reusable_db.discard(key)


def test_checkout_reuses_database_and_resets_to_baseline(flavor):
    with pg_reusable_db.checkout(flavor, _build_small_db) as first:
        assert first is not None
        conn = _connect(first)
        try:
            conn.execute("INSERT INTO parent_rows (label) VALUES ('extra')")
            conn.execute("UPDATE child_rows SET note = 'mutated'")
            conn.commit()
        finally:
            conn.close()

    with pg_reusable_db.checkout(flavor, _build_small_db) as second:
        assert second == first
        conn = _connect(second)
        try:
            labels = [
                row[0]
                for row in conn.execute("SELECT label FROM parent_rows").fetchall()
            ]
            assert labels == ["seed"]
            note, payload = conn.execute(
                "SELECT c.note, p.payload FROM child_rows c "
                "JOIN parent_rows p ON p.id = c.parent_id"
            ).fetchone()
            assert note == "seed-child"
            assert payload == {"k": [1, 2]}
            # Identity sequence restored: the next insert allocates the same
            # id a freshly built database would.
            (probe_id,) = conn.execute(
                "INSERT INTO parent_rows (label) VALUES ('probe') RETURNING id"
            ).fetchone()
            assert probe_id == 2
            conn.rollback()
        finally:
            conn.close()


def test_ddl_drift_discards_and_rebuilds(flavor):
    with pg_reusable_db.checkout(flavor, _build_small_db) as first:
        conn = _connect(first)
        try:
            conn.execute("CREATE TABLE drifted (id INTEGER PRIMARY KEY)")
            conn.commit()
        finally:
            conn.close()

    with pg_reusable_db.checkout(flavor, _build_small_db) as second:
        assert second != first
        conn = _connect(second)
        try:
            drifted_count = conn.execute(
                "SELECT count(*) FROM pg_class c "
                "JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE c.relname = 'drifted' AND n.nspname = current_schema()"
            ).fetchone()[0]
            assert drifted_count == 0
            dropped = conn.execute(
                "SELECT count(*) FROM pg_database WHERE datname = %s", (first,)
            ).fetchone()[0]
            assert dropped == 0
        finally:
            conn.close()


def test_nested_checkout_yields_none(flavor):
    with pg_reusable_db.checkout(flavor, _build_small_db) as outer:
        assert outer is not None
        with pg_reusable_db.checkout(flavor, _build_small_db) as inner:
            assert inner is None


def test_reset_terminates_leaked_connections(flavor):
    leaked = None
    try:
        with pg_reusable_db.checkout(flavor, _build_small_db) as name:
            leaked = _connect(name)
            # Open transaction holding a row lock; without termination the
            # baseline reset's DELETE would block behind it.
            leaked.execute(
                "INSERT INTO parent_rows (label) VALUES ('uncommitted')"
            )

        with pg_reusable_db.checkout(flavor, _build_small_db) as again:
            assert again == name
            conn = _connect(again)
            try:
                labels = [
                    row[0]
                    for row in conn.execute(
                        "SELECT label FROM parent_rows"
                    ).fetchall()
                ]
                assert labels == ["seed"]
            finally:
                conn.close()

        with pytest.raises(psycopg.OperationalError):
            leaked.execute("SELECT 1")
    finally:
        if leaked is not None:
            leaked.close()


def test_test_database_reuses_one_database_across_uses():
    with pg_testdb.test_database() as conn:
        first = conn.execute("SELECT current_database()").fetchone()[0]
    with pg_testdb.test_database() as conn:
        second = conn.execute("SELECT current_database()").fetchone()[0]
    assert second == first


def test_test_database_nested_contexts_use_distinct_databases():
    with pg_testdb.test_database() as outer:
        outer_db = outer.execute("SELECT current_database()").fetchone()[0]
        with pg_testdb.test_database() as inner:
            inner_db = inner.execute("SELECT current_database()").fetchone()[0]
            assert inner_db != outer_db
        assert outer.execute("SELECT 1").fetchone()[0] == 1


def test_init_test_db_default_strategy_reuses_database(tmp_path):
    from yoke_core.domain import db_backend

    with file_test_db.init_test_db(tmp_path):
        conn = db_backend.connect_psycopg()
        try:
            first = conn.execute("SELECT current_database()").fetchone()[0]
            baseline_projects = conn.execute(
                "SELECT count(*) FROM projects"
            ).fetchone()[0]
        finally:
            conn.close()

    with file_test_db.init_test_db(tmp_path):
        conn = db_backend.connect_psycopg()
        try:
            second = conn.execute("SELECT current_database()").fetchone()[0]
            again_projects = conn.execute(
                "SELECT count(*) FROM projects"
            ).fetchone()[0]
        finally:
            conn.close()

    assert second == first
    assert again_projects == baseline_projects


def test_init_test_db_fixture_strategy_shares_worker_fixture_database(tmp_path):
    from yoke_core.domain import db_backend

    with pg_testdb.test_database() as conn:
        fixture_db = conn.execute("SELECT current_database()").fetchone()[0]

    with file_test_db.init_test_db(
        tmp_path, apply_schema=file_test_db.apply_fixture_schema_ddl
    ):
        conn = db_backend.connect_psycopg()
        try:
            shared = conn.execute("SELECT current_database()").fetchone()[0]
        finally:
            conn.close()

    assert shared == fixture_db


def test_init_test_db_custom_strategy_uses_disposable_databases(tmp_path):
    from yoke_core.domain import db_backend

    names = []

    def custom() -> None:
        conn = db_backend.connect_psycopg()
        try:
            names.append(conn.execute("SELECT current_database()").fetchone()[0])
            conn.execute("CREATE TABLE only_here (id INTEGER)")
            conn.commit()
        finally:
            conn.close()

    with file_test_db.init_test_db(tmp_path, apply_schema=custom):
        pass
    with file_test_db.init_test_db(tmp_path, apply_schema=custom):
        pass

    assert len(names) == 2
    assert names[0] != names[1]
