"""The closed roster of packaged static assets the UI server may serve.

Split out of :mod:`yoke_core.ui.server` so the roster can grow one line
per new static module without crowding the server's routing and security
logic; the server re-exports both names for its callers.
"""

from __future__ import annotations

from typing import Dict

#: ``Cache-Control`` for the app shell and static assets: ``no-cache``
#: makes browsers revalidate on every load, so an upgraded server never
#: keeps stale modules running from cache.
ASSET_CACHE_CONTROL = "no-cache"

#: Packaged static assets the server may serve, with their content types.
#: A closed name→type map (no filesystem paths from the request) keeps
#: traversal structurally impossible.
ASSET_CONTENT_TYPES: Dict[str, str] = {
    "index.html": "text/html; charset=utf-8",
    # Developer page, not a product route: mounts the same app with sample
    # platform chrome shaped like the hosted shell's slots, so frame defects
    # that only show with occupied slots are visible on a laptop.
    "hosted-frame-harness.html": "text/html; charset=utf-8",
    "hosted_frame_workflows_fixture.js": "text/javascript; charset=utf-8",
    "hosted_frame_workflow_builders.js": "text/javascript; charset=utf-8",
    "hosted_frame_workflow_client.js": "text/javascript; charset=utf-8",
    "hosted_frame_workflow_epic_fixture.js": "text/javascript; charset=utf-8",
    "app.js": "text/javascript; charset=utf-8",
    "universe_app_shell_support.js": "text/javascript; charset=utf-8",
    "contract.js": "text/javascript; charset=utf-8",
    "contract-version.js": "text/javascript; charset=utf-8",
    "mount-options.js": "text/javascript; charset=utf-8",
    "universe_app_chrome.js": "text/javascript; charset=utf-8",
    "universe_shell_controls.js": "text/javascript; charset=utf-8",
    "universe_shell_footer.js": "text/javascript; charset=utf-8",
    "universe_destinations.js": "text/javascript; charset=utf-8",
    "universe_navigation.js": "text/javascript; charset=utf-8",
    "universe_state_pills.js": "text/javascript; charset=utf-8",
    "universe_view_support.js": "text/javascript; charset=utf-8",
    "universe_held_reads.js": "text/javascript; charset=utf-8",
    "universe_secondary_primitives.js": "text/javascript; charset=utf-8",
    "universe_views.js": "text/javascript; charset=utf-8",
    "universe_views_capabilities.js": "text/javascript; charset=utf-8",
    "universe_views_delivery.js": "text/javascript; charset=utf-8",
    "deployment_run_terminalization_dialog.js": "text/javascript; charset=utf-8",
    "universe_views_delivery_inventory.js": "text/javascript; charset=utf-8",
    "universe_views_doctor.js": "text/javascript; charset=utf-8",
    "universe_views_events.js": "text/javascript; charset=utf-8",
    "universe_views_frontier.js": "text/javascript; charset=utf-8",
    "universe_views_github.js": "text/javascript; charset=utf-8",
    "universe_views_items.js": "text/javascript; charset=utf-8",
    "item_detail_loader.js": "text/javascript; charset=utf-8",
    "universe_views_inbox.js": "text/javascript; charset=utf-8",
    "inbox_presentation.js": "text/javascript; charset=utf-8",
    "inbox_rows.js": "text/javascript; charset=utf-8",
    "universe_views_organization.js": "text/javascript; charset=utf-8",
    "universe_views_ouroboros.js": "text/javascript; charset=utf-8",
    "universe_views_overview.js": "text/javascript; charset=utf-8",
    "universe_overview_primitives.js": "text/javascript; charset=utf-8",
    "universe_overview_strategy.js": "text/javascript; charset=utf-8",
    "universe_overview_frontier.js": "text/javascript; charset=utf-8",
    "universe_overview_sessions.js": "text/javascript; charset=utf-8",
    "universe_overview_delivery.js": "text/javascript; charset=utf-8",
    "universe_overview_health.js": "text/javascript; charset=utf-8",
    "universe_views_overview_activation.js": "text/javascript; charset=utf-8",
    "universe_views_overview_activation_copy.js": "text/javascript; charset=utf-8",
    "universe_views_overview_signals.js": "text/javascript; charset=utf-8",
    "universe_views_packs.js": "text/javascript; charset=utf-8",
    "universe_views_projects.js": "text/javascript; charset=utf-8",
    "universe_views_qa.js": "text/javascript; charset=utf-8",
    "universe_views_sessions.js": "text/javascript; charset=utf-8",
    "universe_views_strategy.js": "text/javascript; charset=utf-8",
    "universe_views_blitz.js": "text/javascript; charset=utf-8",
    "execution_instruction_editor.js": "text/javascript; charset=utf-8",
    "universe_views_workflows.js": "text/javascript; charset=utf-8",
    "workflow_instructions_panel.js": "text/javascript; charset=utf-8",
    "universe_view_test_machine.js": "text/javascript; charset=utf-8",
    "test_machine_detail_panels.js": "text/javascript; charset=utf-8",
    "universe_time.js": "text/javascript; charset=utf-8",
    "markdown_view.js": "text/javascript; charset=utf-8",
    "test_machine_view_primitives.js": "text/javascript; charset=utf-8",
    "test_machine_settings_dialog.js": "text/javascript; charset=utf-8",
    "workflow_mechanics_data.js": "text/javascript; charset=utf-8",
    "workflow_mechanics_dialogs.js": "text/javascript; charset=utf-8",
    "workflow_accessibility.js": "text/javascript; charset=utf-8",
    "workflow_dialog_shell.js": "text/javascript; charset=utf-8",
    "workflow_path_posture_dialogs.js": "text/javascript; charset=utf-8",
    "workflow_view_lifecycle.js": "text/javascript; charset=utf-8",
    "workflow_view_mechanics.js": "text/javascript; charset=utf-8",
    "workflow_view_policy.js": "text/javascript; charset=utf-8",
    "workflow_view_canon_diff.js": "text/javascript; charset=utf-8",
    "workflow_view_primitives.js": "text/javascript; charset=utf-8",
    "workflow_view_versions.js": "text/javascript; charset=utf-8",
    "qa_view_activity.js": "text/javascript; charset=utf-8",
    "qa_view_evidence.js": "text/javascript; charset=utf-8",
    "qa_view_methods.js": "text/javascript; charset=utf-8",
    "qa_view_method_detail.js": "text/javascript; charset=utf-8",
    "qa_view_plans.js": "text/javascript; charset=utf-8",
    "qa_plan_actions.js": "text/javascript; charset=utf-8",
    "qa_execution_target_view.js": "text/javascript; charset=utf-8",
    "qa_case_output_view.js": "text/javascript; charset=utf-8",
    "qa_plan_detail_view.js": "text/javascript; charset=utf-8",
    "qa_review_explanation.js": "text/javascript; charset=utf-8",
    "qa_view_primitives.js": "text/javascript; charset=utf-8",
    "item_view_details.js": "text/javascript; charset=utf-8",
    "item_intake_controls.js": "text/javascript; charset=utf-8",
    "item_view_facts.js": "text/javascript; charset=utf-8",
    "item_view_new.js": "text/javascript; charset=utf-8",
    "item_view_primitives.js": "text/javascript; charset=utf-8",
    "item_view_shell.js": "text/javascript; charset=utf-8",
    "item_view_verification.js": "text/javascript; charset=utf-8",
    "strategy_view_primitives.js": "text/javascript; charset=utf-8",
    "strategy_view_summary.js": "text/javascript; charset=utf-8",
    "app.css": "text/css; charset=utf-8",
    "universe_chrome.css": "text/css; charset=utf-8",
    "universe_shell_controls.css": "text/css; charset=utf-8",
    "universe_content.css": "text/css; charset=utf-8",
    "universe_overview.css": "text/css; charset=utf-8",
    "universe_overview_foundations.css": "text/css; charset=utf-8",
    "universe_overview_tables.css": "text/css; charset=utf-8",
    "universe_overview_activity.css": "text/css; charset=utf-8",
    "universe_secondary_views.css": "text/css; charset=utf-8",
    "universe_secondary_activity.css": "text/css; charset=utf-8",
    "deployment_run_terminalization.css": "text/css; charset=utf-8",
    "universe_sessions.css": "text/css; charset=utf-8",
    "universe_overview_legacy.css": "text/css; charset=utf-8",
    "activation.css": "text/css; charset=utf-8",
    "shell.css": "text/css; charset=utf-8",
    "theme.css": "text/css; charset=utf-8",
    "workflows.css": "text/css; charset=utf-8",
    "workflow_posture.css": "text/css; charset=utf-8",
    "workflow_controls.css": "text/css; charset=utf-8",
    "workflow_canon_status.css": "text/css; charset=utf-8",
    "workflow_mechanics.css": "text/css; charset=utf-8",
    "test_machine.css": "text/css; charset=utf-8",
    "test_machine_support.css": "text/css; charset=utf-8",
    "qa.css": "text/css; charset=utf-8",
    "qa_catalog.css": "text/css; charset=utf-8",
    "qa_details.css": "text/css; charset=utf-8",
    "qa_results.css": "text/css; charset=utf-8",
    "inbox.css": "text/css; charset=utf-8",
    "items.css": "text/css; charset=utf-8",
    "item_foundations.css": "text/css; charset=utf-8",
    "item_roster.css": "text/css; charset=utf-8",
    "item_details.css": "text/css; charset=utf-8",
    "item_intake.css": "text/css; charset=utf-8",
    "strategy.css": "text/css; charset=utf-8",
    "workflow_instructions.css": "text/css; charset=utf-8",
    "yoke.svg": "image/svg+xml",
    "yoke-wordmark.svg": "image/svg+xml",
    "favicon.svg": "image/svg+xml",
    "favicon.ico": "image/x-icon",
    "apple-touch-icon.png": "image/png",
}
