"""Focused CLI tests for ``yoke claims work {acquire,release}`` — the
(epic_id, task_num) shape plus malformed-selector matrix conduct
fan-out depends on. Item-form dispatch lives in
``test_yoke_operations_cli_dispatch.py``.
"""

from __future__ import annotations

import io
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from unittest.mock import patch

import pytest

from runtime.api.engines._doctor_native_sql_test_helpers import (
    connect_disposable_test_db,
)
from yoke_cli.main import main as cli_main
from yoke_contracts.api.function_call import (
    FunctionCallRequest,
    FunctionCallResponse,
)


_CAPTURED: list[FunctionCallRequest] = []


def _stub_ok(request: FunctionCallRequest) -> FunctionCallResponse:
    _CAPTURED.append(request)
    return FunctionCallResponse(
        success=True,
        function=request.function,
        version=request.version,
        request_id=request.request_id,
        result={"echo": True},
    )


@pytest.fixture(autouse=True)
def _reset_captured() -> None:
    _CAPTURED.clear()


def _run(*argv: str, session_id: str = "test-session"):
    with patch.dict("os.environ", {"YOKE_SESSION_ID": session_id}):
        with (
            patch(
                "yoke_core.domain.yoke_function_dispatch.dispatch",
                side_effect=_stub_ok,
            ),
            patch(
                "yoke_cli.commands.adapters.claims.sync_local_snapshot_for_write",
            ),
        ):
            with patch("yoke_cli.commands._helpers.ensure_handlers_loaded"):
                buf, err = io.StringIO(), io.StringIO()
                with redirect_stdout(buf), redirect_stderr(err):
                    rc = cli_main(list(argv))
                return rc, buf.getvalue(), err.getvalue()


@pytest.fixture
def claims_conn():
    """Disposable Postgres claim-selector double."""
    c = connect_disposable_test_db()
    c.execute(
        "CREATE TABLE work_claims ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "session_id TEXT, target_kind TEXT, item_id INTEGER, "
        "epic_id INTEGER, task_num INTEGER, released_at TEXT)"
    )
    c.commit()
    yield c
    c.close()


def _run_db(claims_conn, *argv: str, session_id: str = "test-session"):
    @contextmanager
    def _conn_cm():
        yield claims_conn

    with patch.dict("os.environ", {"YOKE_SESSION_ID": session_id}):
        with (
            patch(
                "yoke_core.domain.yoke_function_dispatch.dispatch",
                side_effect=_stub_ok,
            ),
            patch("yoke_cli.commands._helpers.ensure_handlers_loaded"),
            patch(
                "yoke_core.domain.db_helpers.connect",
                side_effect=lambda *a, **kw: _conn_cm(),
            ),
            patch(
                "yoke_core.api.service_client_shared_session_resolver"
                "._resolve_session_id",
                side_effect=lambda explicit=None: explicit or session_id,
            ),
        ):
            buf, err = io.StringIO(), io.StringIO()
            with redirect_stdout(buf), redirect_stderr(err):
                rc = cli_main(list(argv))
            return rc, buf.getvalue(), err.getvalue()


# ---------------------------------------------------------------------------
# Acquire — epic_task target
# ---------------------------------------------------------------------------


class TestAcquireEpicTask:
    def test_acquire_epic_task_dispatches_typed_target(self) -> None:
        rc, _o, _e = _run(
            "claims",
            "work",
            "acquire",
            "--epic-id",
            "1872",
            "--task-num",
            "20",
            "--reason",
            "engineer dispatch",
        )
        assert rc == 0
        req = _CAPTURED[-1]
        assert req.function == "claims.work.acquire"
        assert req.target.kind == "epic_task"
        assert req.target.epic_id == 1872 and req.target.task_num == 20
        assert req.payload["target"] == {
            "kind": "epic_task",
            "epic_id": 1872,
            "task_num": 20,
        }
        assert req.payload["reason"] == "engineer dispatch"

    def test_acquire_epic_task_without_reason_omits_reason(self) -> None:
        rc, *_ = _run(
            "claims",
            "work",
            "acquire",
            "--epic-id",
            "100",
            "--task-num",
            "1",
        )
        assert rc == 0
        assert "reason" not in _CAPTURED[-1].payload

    def test_acquire_epic_task_requires_both_selectors(self) -> None:
        # --epic-id without --task-num falls through to "no target" usage.
        rc, *_ = _run(
            "claims",
            "work",
            "acquire",
            "--epic-id",
            "1872",
            "--reason",
            "missing task-num",
        )
        assert rc == 2 and _CAPTURED == []

    def test_acquire_epic_task_rejects_non_integer(self) -> None:
        rc, *_ = _run(
            "claims",
            "work",
            "acquire",
            "--epic-id",
            "abc",
            "--task-num",
            "5",
            "--reason",
            "bad",
        )
        assert rc == 2 and _CAPTURED == []


# ---------------------------------------------------------------------------
# Release — epic_task selector
# ---------------------------------------------------------------------------


class TestReleaseEpicTask:
    """Relay contract: the adapter ships the typed epic_task target and
    the dispatcher's self_only verification resolves the session's own
    claim server-side (covered in
    runtime/api/domain/test_yoke_function_dispatch_claims.py)."""

    def test_release_epic_task_dispatches_typed_target(self) -> None:
        rc, _o, err = _run(
            "claims",
            "work",
            "release",
            "--epic-id",
            "1872",
            "--task-num",
            "20",
            "--reason",
            "engineer return",
        )
        assert rc == 0, err
        req = _CAPTURED[-1]
        assert req.function == "claims.work.release"
        assert req.target.kind == "epic_task"
        assert req.target.epic_id == 1872 and req.target.task_num == 20
        assert req.target.claim_id is None
        assert req.payload == {"reason": "engineer return"}

    def test_release_item_dispatches_item_ref_target(self) -> None:
        rc, _o, err = _run(
            "claims",
            "work",
            "release",
            "--item",
            "YOK-1872",
            "--reason",
            "done here",
        )
        assert rc == 0, err
        req = _CAPTURED[-1]
        assert req.function == "claims.work.release"
        assert req.target.kind == "item"
        assert req.target.item_ref == "YOK-1872"
        assert req.target.claim_id is None
        assert req.payload == {"reason": "done here"}

    def test_release_process_dispatches_process_payload(self) -> None:
        rc, _o, err = _run(
            "claims",
            "work",
            "release",
            "--process",
            "STRATEGIZE",
            "--project",
            "yoke",
            "--reason",
            "era closeout",
        )
        assert rc == 0, err
        req = _CAPTURED[-1]
        assert req.function == "claims.work.release"
        assert req.target.kind == "global"
        assert req.payload == {
            "reason": "era closeout",
            "process_key": "STRATEGIZE",
            "project": "yoke",
        }


# ---------------------------------------------------------------------------
# Help — selector form documented
# ---------------------------------------------------------------------------


class TestReleaseHelp:
    def test_help_lists_epic_task_selector(self) -> None:
        with (
            patch.dict("os.environ", {"YOKE_SESSION_ID": "sid"}),
            patch("yoke_cli.commands._helpers.ensure_handlers_loaded"),
        ):
            buf, err = io.StringIO(), io.StringIO()
            with redirect_stdout(buf), redirect_stderr(err):
                rc = cli_main(["claims", "work", "release", "--help"])
        assert rc == 0
        out = buf.getvalue()
        assert "--epic-id" in out
        assert "--task-num" in out
        assert "epic_task" in out
        assert "--process" in out
        assert "STRATEGIZE" in out


class TestPathRegisterModes:
    def test_exception_mode_dispatches_without_paths(self) -> None:
        rc, _out, err = _run(
            "claims",
            "path",
            "register",
            "--item",
            "YOK-1872",
            "--mode",
            "exception",
            "--exception-reason",
            "evidence only",
        )
        assert rc == 0, err
        req = _CAPTURED[-1]
        assert req.function == "claims.path.register"
        assert req.target.item_ref == "YOK-1872"
        assert req.payload == {
            "paths": [],
            "mode": "exception",
            "allow_planned": False,
            "exception_reason": "evidence only",
        }

    @pytest.mark.parametrize(
        "extra, message",
        (
            ((), "--paths is required in exclusive mode"),
            (
                ("--mode", "exception"),
                "--exception-reason is required in exception mode",
            ),
            (
                (
                    "--mode",
                    "exception",
                    "--exception-reason",
                    "no files",
                    "--paths",
                    "runtime/api/foo.py",
                ),
                "--paths is not accepted in exception mode",
            ),
            (
                (
                    "--paths",
                    "runtime/api/foo.py",
                    "--exception-reason",
                    "wrong mode",
                ),
                "--exception-reason requires --mode exception",
            ),
        ),
    )
    def test_mode_specific_arguments_fail_closed(
        self,
        extra: tuple[str, ...],
        message: str,
    ) -> None:
        rc, _out, err = _run(
            "claims",
            "path",
            "register",
            "--item",
            "YOK-1872",
            *extra,
        )
        assert rc == 2
        assert message in err
        assert _CAPTURED == []
